GEN_FUNCS = \
gdk_pixbuf_xlib_get_from_drawable.o \
gdk_pixbuf_xlib_init.o \
gdk_pixbuf_xlib_init_with_depth.o \
gdk_pixbuf_xlib_render_pixmap_and_mask.o \
gdk_pixbuf_xlib_render_threshold_alpha.o \
gdk_pixbuf_xlib_render_to_drawable.o \
gdk_pixbuf_xlib_render_to_drawable_alpha.o \
xlib_draw_gray_image.o \
xlib_draw_indexed_image.o \
xlib_draw_rgb_32_image.o \
xlib_draw_rgb_image.o \
xlib_draw_rgb_image_dithalign.o \
xlib_rgb_cmap_free.o \
xlib_rgb_cmap_new.o \
xlib_rgb_ditherable.o \
xlib_rgb_gc_set_background.o \
xlib_rgb_gc_set_foreground.o \
xlib_rgb_get_cmap.o \
xlib_rgb_get_depth.o \
xlib_rgb_get_display.o \
xlib_rgb_get_screen.o \
xlib_rgb_get_visual.o \
xlib_rgb_get_visual_info.o \
xlib_rgb_init.o \
xlib_rgb_init_with_depth.o \
xlib_rgb_set_install.o \
xlib_rgb_set_min_colors.o \
xlib_rgb_set_verbose.o \
xlib_rgb_xpixel_from_rgb.o 