// Code generated by gen_tests.pl

#include <time.h>

void validate_struct_itimerspec(struct itimerspec * input)
{
	validate_struct_timespec(input->it_interval);
	validate_struct_timespec(input->it_value);
}

