// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <rpc/rpc_msg.h>

void validate_struct_accepted_reply(struct accepted_reply * input)
{
	validate_struct_opaque_auth(input->struct opaque_auth);
	validate_NULL_TYPETYPE(input->enum accept_stat);
	validate_NULL_TYPETYPE(input->ru.AR_versions.unsigned long);
	validate_NULL_TYPETYPE(input->ru.AR_versions.unsigned long);
	validate_NULL_TYPETYPE(input->ru.AR_results.caddr_t);
	validate_NULL_TYPETYPE(input->ru.AR_results.xdrproc_t);
}

