// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <unwind.h>

int validate_struct__Unwind_Context(struct _Unwind_Context  * input, char *name)
{
int failure = 0;
return failure;
}

