// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <utmpx.h>

void validate_struct_utmpx(struct utmpx * input)
{
	validate_NULL_TYPETYPE(input->short);
	validate_NULL_TYPETYPE(input->pid_t);
	validate_NULL_TYPETYPE(input->char);
	validate_NULL_TYPETYPE(input->char);
	validate_NULL_TYPETYPE(input->char);
	validate_NULL_TYPETYPE(input->char);
	validate_struct_exit_status(input->struct exit_status);
	validate_NULL_TYPETYPE(input->long);
	validate_struct_timeval(input->struct timeval);
	validate_NULL_TYPETYPE(input->int32_t);
	validate_NULL_TYPETYPE(input->char);
}

