// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <fcntl.h>

void validate_struct_flock(struct flock * input)
{
	validate_NULL_TYPETYPE(input->short);
	validate_NULL_TYPETYPE(input->short);
	validate_NULL_TYPETYPE(input->off_t);
	validate_NULL_TYPETYPE(input->off_t);
	validate_NULL_TYPETYPE(input->pid_t);
}

