// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <setjmp.h>

void validate_struct___jmp_buf_tag(struct __jmp_buf_tag * input)
{
	validate_NULL_TYPETYPE(input->__jmpbuf);
	validate_NULL_TYPETYPE(input->__mask_was_saved);
	validate_NULL_TYPETYPE(input->__saved_mask);
}

