// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <glib-2.0/gio/gdbusconnection.h>

int validate_struct__GDBusInterfaceVTable(struct _GDBusInterfaceVTable  * input, char *name)
{
int failure = 0;
	if(validate_NULL_TYPETYPE(input-> method_call,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> get_property,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> set_property,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> padding,name ))
		failure = 1;
return failure;
}

