// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <glib-2.0/gio/gasyncresult.h>

int validate_struct__GAsyncResultIface(struct _GAsyncResultIface  * input, char *name)
{
int failure = 0;
	if(validate_NULL_TYPETYPE(input-> g_iface,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> get_user_data,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> get_source_object,name ))
		failure = 1;
return failure;
}

