// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <netinet/ip_icmp.h>

int validate_struct_ih_idseq(struct ih_idseq  * input, char *name)
{
int failure = 0;
	if(validate_NULL_TYPETYPE(input-> icd_id,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> icd_seq,name ))
		failure = 1;
return failure;
}

