// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <glib-2.0/gio/gfilteroutputstream.h>

int validate_struct__GFilterOutputStreamClass(struct _GFilterOutputStreamClass  * input, char *name)
{
int failure = 0;
	if(validate_NULL_TYPETYPE(input-> parent_class,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> _g_reserved1,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> _g_reserved2,name ))
		failure = 1;
	if(validate_NULL_TYPETYPE(input-> _g_reserved3,name ))
		failure = 1;
return failure;
}

