// Code generated by gen_tests.pl

#include "../type_tests.h"
#include <netinet/in.h>

void validate_struct_ipv6_mreq(struct ipv6_mreq * input)
{
	validate_struct_in6_addr(input->struct in6_addr);
	validate_NULL_TYPETYPE(input->int);
}

