GEN_FUNCS = \
XRenderAddGlyphs.o \
XRenderAddTraps.o \
XRenderChangePicture.o \
XRenderComposite.o \
XRenderCompositeDoublePoly.o \
XRenderCompositeString16.o \
XRenderCompositeString32.o \
XRenderCompositeString8.o \
XRenderCompositeText16.o \
XRenderCompositeText32.o \
XRenderCompositeText8.o \
XRenderCompositeTrapezoids.o \
XRenderCompositeTriFan.o \
XRenderCompositeTriStrip.o \
XRenderCompositeTriangles.o \
XRenderCreateAnimCursor.o \
XRenderCreateConicalGradient.o \
XRenderCreateCursor.o \
XRenderCreateGlyphSet.o \
XRenderCreateLinearGradient.o \
XRenderCreatePicture.o \
XRenderCreateRadialGradient.o \
XRenderCreateSolidFill.o \
XRenderFillRectangle.o \
XRenderFillRectangles.o \
XRenderFindFormat.o \
XRenderFindStandardFormat.o \
XRenderFindVisualFormat.o \
XRenderFreeGlyphSet.o \
XRenderFreeGlyphs.o \
XRenderFreePicture.o \
XRenderParseColor.o \
XRenderQueryExtension.o \
XRenderQueryFilters.o \
XRenderQueryFormats.o \
XRenderQueryPictIndexValues.o \
XRenderQuerySubpixelOrder.o \
XRenderQueryVersion.o \
XRenderReferenceGlyphSet.o \
XRenderSetPictureClipRectangles.o \
XRenderSetPictureClipRegion.o \
XRenderSetPictureFilter.o \
XRenderSetPictureTransform.o \
XRenderSetSubpixelOrder.o 