// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/extensions/Xrender.h>
#undef XRenderAddGlyphs
static void(*funcptr) (Display * , GlyphSet , const Glyph * , const XGlyphInfo * , int , const char * , int ) = 0;

extern int __lsb_check_params;
void XRenderAddGlyphs (Display * arg0 , GlyphSet arg1 , const Glyph * arg2 , const XGlyphInfo * arg3 , int arg4 , const char * arg5 , int arg6 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for XRenderAddGlyphs()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XRenderAddGlyphs");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XRenderAddGlyphs. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XRenderAddGlyphs() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "XRenderAddGlyphs - arg0 (dpy)");
		}
		validate_NULL_TYPETYPE(  arg0, "XRenderAddGlyphs - arg0 (dpy)");
		validate_NULL_TYPETYPE(  arg1, "XRenderAddGlyphs - arg1 (glyphset)");
		if( arg2 ) {
		validate_Rdaddress( arg2, "XRenderAddGlyphs - arg2 (gids)");
		}
		validate_NULL_TYPETYPE(  arg2, "XRenderAddGlyphs - arg2 (gids)");
		if( arg3 ) {
		validate_Rdaddress( arg3, "XRenderAddGlyphs - arg3 (glyphs)");
		}
		validate_NULL_TYPETYPE(  arg3, "XRenderAddGlyphs - arg3 (glyphs)");
		validate_NULL_TYPETYPE(  arg4, "XRenderAddGlyphs - arg4 (nglyphs)");
		if( arg5 ) {
		validate_Rdaddress( arg5, "XRenderAddGlyphs - arg5 (images)");
		}
		validate_NULL_TYPETYPE(  arg5, "XRenderAddGlyphs - arg5 (images)");
		validate_NULL_TYPETYPE(  arg6, "XRenderAddGlyphs - arg6 (nbyte_images)");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
	__lsb_check_params = reset_flag;
}

