// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/extensions/render.h>
#include <X11/extensions/Xrender.h>
#undef XRenderCompositeString8
static void(*funcptr) (Display * , int , Picture , Picture , const XRenderPictFormat * , GlyphSet , int , int , int , int , const char * , int ) = 0;

extern int __lsb_check_params;
void XRenderCompositeString8 (Display * arg0 , int arg1 , Picture arg2 , Picture arg3 , const XRenderPictFormat * arg4 , GlyphSet arg5 , int arg6 , int arg7 , int arg8 , int arg9 , const char * arg10 , int arg11 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for XRenderCompositeString8()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XRenderCompositeString8");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XRenderCompositeString8. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XRenderCompositeString8() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "XRenderCompositeString8 - arg0 (dpy)");
		}
		validate_NULL_TYPETYPE(  arg0, "XRenderCompositeString8 - arg0 (dpy)");
		validate_NULL_TYPETYPE(  arg1, "XRenderCompositeString8 - arg1 (op)");
		validate_NULL_TYPETYPE(  arg2, "XRenderCompositeString8 - arg2 (src)");
		validate_NULL_TYPETYPE(  arg3, "XRenderCompositeString8 - arg3 (dst)");
		if( arg4 ) {
		validate_Rdaddress( arg4, "XRenderCompositeString8 - arg4 (maskFormat)");
		}
		validate_NULL_TYPETYPE(  arg4, "XRenderCompositeString8 - arg4 (maskFormat)");
		validate_NULL_TYPETYPE(  arg5, "XRenderCompositeString8 - arg5 (glyphset)");
		validate_NULL_TYPETYPE(  arg6, "XRenderCompositeString8 - arg6 (xSrc)");
		validate_NULL_TYPETYPE(  arg7, "XRenderCompositeString8 - arg7 (ySrc)");
		validate_NULL_TYPETYPE(  arg8, "XRenderCompositeString8 - arg8 (xDst)");
		validate_NULL_TYPETYPE(  arg9, "XRenderCompositeString8 - arg9 (yDst)");
		if( arg10 ) {
		validate_Rdaddress( arg10, "XRenderCompositeString8 - arg10 (string)");
		}
		validate_NULL_TYPETYPE(  arg10, "XRenderCompositeString8 - arg10 (string)");
		validate_NULL_TYPETYPE(  arg11, "XRenderCompositeString8 - arg11 (nchar)");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
	__lsb_check_params = reset_flag;
}

