GEN_FUNCS = \
PR_Abort.o \
PR_Accept.o \
PR_AtomicAdd.o \
PR_AtomicDecrement.o \
PR_AtomicIncrement.o \
PR_AtomicSet.o \
PR_Bind.o \
PR_Cleanup.o \
PR_ClearInterrupt.o \
PR_Close.o \
PR_Connect.o \
PR_ConnectContinue.o \
PR_ConvertIPv4AddrToIPv6.o \
PR_CreateIOLayerStub.o \
PR_CreatePipe.o \
PR_DestroyCondVar.o \
PR_DestroyLock.o \
PR_EnumerateAddrInfo.o \
PR_ExplodeTime.o \
PR_FormatTime.o \
PR_FreeAddrInfo.o \
PR_GMTParameters.o \
PR_GetAddrInfoByName.o \
PR_GetCanonNameFromAddrInfo.o \
PR_GetDefaultIOMethods.o \
PR_GetDescType.o \
PR_GetError.o \
PR_GetErrorText.o \
PR_GetErrorTextLength.o \
PR_GetLayersIdentity.o \
PR_GetOSError.o \
PR_GetSocketOption.o \
PR_GetThreadPrivate.o \
PR_GetThreadScope.o \
PR_GetThreadState.o \
PR_GetUniqueIdentity.o \
PR_ImplodeTime.o \
PR_ImportTCPSocket.o \
PR_Init.o \
PR_Initialize.o \
PR_InitializeNetAddr.o \
PR_Initialized.o \
PR_Interrupt.o \
PR_IntervalNow.o \
PR_IntervalToMicroseconds.o \
PR_IntervalToMilliseconds.o \
PR_IntervalToSeconds.o \
PR_Listen.o \
PR_LocalTimeParameters.o \
PR_Lock.o \
PR_MicrosecondsToInterval.o \
PR_MillisecondsToInterval.o \
PR_NetAddrToString.o \
PR_NewCondVar.o \
PR_NewLock.o \
PR_NewThreadPrivateIndex.o \
PR_NormalizeTime.o \
PR_NotifyAllCondVar.o \
PR_NotifyCondVar.o \
PR_Now.o \
PR_Open.o \
PR_OpenTCPSocket.o \
PR_OpenUDPSocket.o \
PR_ParseTimeString.o \
PR_ParseTimeStringToExplodedTime.o \
PR_Poll.o \
PR_PopIOLayer.o \
PR_ProcessExit.o \
PR_PushIOLayer.o \
PR_Read.o \
PR_Recv.o \
PR_RecvFrom.o \
PR_SecondsToInterval.o \
PR_Send.o \
PR_SendTo.o \
PR_SetError.o \
PR_SetErrorText.o \
PR_SetSocketOption.o \
PR_SetThreadPrivate.o \
PR_Shutdown.o \
PR_Sleep.o \
PR_StringToNetAddr.o \
PR_TicksPerSecond.o \
PR_Unlock.o \
PR_WaitCondVar.o \
PR_Write.o 