// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <nspr4/prnetdb.h>
#include <nspr4/prtypes.h>
#include <nspr4/prio.h>
#undef PR_InitializeNetAddr
static PRStatus(*funcptr) (PRNetAddrValue , PRUint16 , PRNetAddr * ) = 0;

extern int __lsb_check_params;
PRStatus PR_InitializeNetAddr (PRNetAddrValue arg0 , PRUint16 arg1 , PRNetAddr * arg2 )
{
	int reset_flag = __lsb_check_params;
	PRStatus ret_value  ;
	__lsb_output(4, "Invoking wrapper for PR_InitializeNetAddr()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "PR_InitializeNetAddr");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load PR_InitializeNetAddr. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "PR_InitializeNetAddr() - validating");
		validate_NULL_TYPETYPE(  arg0, "PR_InitializeNetAddr - arg0 (val)");
		validate_NULL_TYPETYPE(  arg1, "PR_InitializeNetAddr - arg1 (port)");
		if( arg2 ) {
		validate_RWaddress( arg2, "PR_InitializeNetAddr - arg2 (addr)");
		}
		validate_NULL_TYPETYPE(  arg2, "PR_InitializeNetAddr - arg2 (addr)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

