// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <pango-1.0/pango/pangoft2.h>
#undef pango_ft2_font_map_create_context
static PangoContext *(*funcptr) (PangoFT2FontMap * ) = 0;

extern int __lsb_check_params;
PangoContext * pango_ft2_font_map_create_context (PangoFT2FontMap * arg0 )
{
	int reset_flag = __lsb_check_params;
	PangoContext * ret_value  ;
	__lsb_output(4, "Invoking wrapper for pango_ft2_font_map_create_context()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pango_ft2_font_map_create_context");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load pango_ft2_font_map_create_context. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "pango_ft2_font_map_create_context() - validating");
		validate_RWaddress( arg0, "pango_ft2_font_map_create_context - arg0 (fontmap)");
		validate_NULL_TYPETYPE(  arg0, "pango_ft2_font_map_create_context - arg0 (fontmap)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

