GEN_FUNCS = \
png_benign_error.o \
png_build_grayscale_palette.o \
png_calloc.o \
png_chunk_benign_error.o \
png_chunk_error.o \
png_chunk_warning.o \
png_convert_to_rfc1123.o \
png_free_default.o \
png_get_cHRM_XYZ.o \
png_get_cHRM_XYZ_fixed.o \
png_get_cHRM_fixed.o \
png_get_chunk_cache_max.o \
png_get_chunk_malloc_max.o \
png_get_compression_buffer_size.o \
png_get_compression_type.o \
png_get_copyright.o \
png_get_current_pass_number.o \
png_get_current_row_number.o \
png_get_filter_type.o \
png_get_gAMA_fixed.o \
png_get_header_version.o \
png_get_int_32.o \
png_get_io_chunk_name.o \
png_get_io_chunk_type.o \
png_get_io_state.o \
png_get_mem_ptr.o \
png_get_pCAL.o \
png_get_pHYs_dpi.o \
png_get_pixel_aspect_ratio.o \
png_get_pixel_aspect_ratio_fixed.o \
png_get_pixels_per_inch.o \
png_get_pixels_per_meter.o \
png_get_rgb_to_gray_status.o \
png_get_sCAL.o \
png_get_sCAL_fixed.o \
png_get_sCAL_s.o \
png_get_sPLT.o \
png_get_signature.o \
png_get_uint_16.o \
png_get_uint_31.o \
png_get_uint_32.o \
png_get_user_height_max.o \
png_get_user_transform_ptr.o \
png_get_user_width_max.o \
png_get_x_offset_inches.o \
png_get_x_offset_inches_fixed.o \
png_get_x_offset_microns.o \
png_get_x_pixels_per_inch.o \
png_get_y_offset_inches.o \
png_get_y_offset_inches_fixed.o \
png_get_y_offset_microns.o \
png_get_y_pixels_per_inch.o \
png_handle_as_unknown.o \
png_longjmp.o \
png_malloc_default.o \
png_malloc_warn.o \
png_process_data_pause.o \
png_process_data_skip.o \
png_reset_zstream.o \
png_save_int_32.o \
png_save_uint_16.o \
png_save_uint_32.o \
png_set_add_alpha.o \
png_set_alpha_mode.o \
png_set_alpha_mode_fixed.o \
png_set_background_fixed.o \
png_set_benign_errors.o \
png_set_cHRM_XYZ.o \
png_set_cHRM_XYZ_fixed.o \
png_set_cHRM_fixed.o \
png_set_check_for_invalid_index.o \
png_set_chunk_cache_max.o \
png_set_chunk_malloc_max.o \
png_set_crc_action.o \
png_set_expand_16.o \
png_set_expand_gray_1_2_4_to_8.o \
png_set_filter_heuristics.o \
png_set_filter_heuristics_fixed.o \
png_set_flush.o \
png_set_gAMA_fixed.o \
png_set_gamma_fixed.o \
png_set_invalid.o \
png_set_longjmp_fn.o \
png_set_pCAL.o \
png_set_quantize.o \
png_set_read_status_fn.o \
png_set_rgb_to_gray_fixed.o \
png_set_sCAL.o \
png_set_sCAL_fixed.o \
png_set_sCAL_s.o \
png_set_sPLT.o \
png_set_scale_16.o \
png_set_text_compression_level.o \
png_set_text_compression_mem_level.o \
png_set_text_compression_method.o \
png_set_text_compression_strategy.o \
png_set_text_compression_window_bits.o \
png_set_user_limits.o \
png_set_user_transform_info.o \
png_write_chunk_data.o \
png_write_chunk_end.o \
png_write_chunk_start.o \
png_write_info_before_PLTE.o \
png_write_sig.o 