// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libpng15/png.h>
#undef png_longjmp
static void(*funcptr) (png_structp , int ) = 0;

extern int __lsb_check_params;
void png_longjmp (png_structp arg0 , int arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for png_longjmp()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "png_longjmp");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load png_longjmp. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "png_longjmp() - validating");
		validate_NULL_TYPETYPE(  arg0, "png_longjmp - arg0 (png_ptr)");
		validate_NULL_TYPETYPE(  arg1, "png_longjmp - arg1 (val)");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

