/* #define G_DISABLE_DEPRECATED */
#define G_ERRORCHECK_MUTEXES
#undef GOBJECT_COMPILATION
#undef GETTEXT_PACKAGE

struct _AtkText {
};

struct _AtkImage {
};

struct _AtkDocument {
};

struct _AtkTable {
};

struct _AtkEditableText {
};

struct _AtkHypertext {
};

struct _AtkSelection {
};

struct _AtkAction {
};

struct _AtkComponent {
};

struct _AtkValue {
};

struct _AtkStreamableContent {
};

struct _AtkImplementor {
};

