#!/bin/sh
#
# simulate how checkem used to run devchk, with twists

BLOG=make_cc.output
RLOG=hdrchk_cc.output
printf "*** Building devchk with cc\n"
make clean > /dev/null 2>&1
make -i > /dev/null 2>&1
if [ ! -f hdrchk ]
then
	# rerun for more targeted errors
	make -i > ${BLOG} 2>&1
	printf "*** ERROR: devchk cc build failed, log in ${BLOG}\n"
	# don't fool people with old output file
	if [ -f ${RLOG} ]
	then
		rm ${RLOG}
	fi
else
	# Execute devchk built with cc and save the output
	printf "*** Running devchk with cc, output in ${RLOG}\n"
	script -c ./hdrchk ${RLOG}
fi

# Clean out the devchk directory
make clean > /dev/null 2>&1

BLOG=make_lsbcc.output
RLOG=hdrchk_lsbcc.output
printf "*** Building devchk with lsbcc\n"
CC=lsbcc CXX=lsbc++ LSB_PRODUCT=desktop make -i > /dev/null 2>&1
if [ ! -f hdrchk ]
then
	CC=lsbcc CXX=lsbc++ LSB_PRODUCT=desktop make -i > ${BLOG} 2>&1
	printf "*** ERROR: devchk lsbcc build failed, log in ${BLOG}\n"
	# don't fool people with old output file
	if [ -f ${RLOG} ]
	then
		rm ${RLOG}
	fi
else
	# Execute devchk built with lsbcc and save the output
	printf "*** Running devchk with lsbcc, output in ${RLOG}\n"
	script -c ./hdrchk ${RLOG}
fi
