#include <stdio.h> 

struct _GHashTable {
	};

struct _GStringChunk {
	};

struct _GKeyFile {
	};

struct _GDir {
	};

struct _GCond {
	};

struct _GMainContext {
	};

struct _GMemChunk {
	};

struct _GRelation {
	};

struct _GData {
	};

struct _GOptionContext {
	};

struct _GOptionGroup {
	};

struct _GAllocator {
	};

struct _GRand {
	};

struct _GMarkupParseContext {
	};

struct _GCache {
	};

struct _GTree {
	};

struct _GMutex {
	};

struct _GAsyncQueue {
	};

struct _GTimer {
	};

struct _GPrivate {
	};

struct _GPatternSpec {
	};

struct _GMainLoop {
	};

