/* #define G_DISABLE_DEPRECATED */
#define G_ERRORCHECK_MUTEXES
#undef GOBJECT_COMPILATION
#undef GETTEXT_PACKAGE
/* #define PANGO_DISABLE_DEPRECATED */
struct _PangoFontFace { };
struct _PangoLayout { };
struct _PangoContext { };
struct _PangoContextClass { };
struct _PangoAttrList { };
struct _PangoFontDescription { };
struct _PangoTabArray { };
struct _PangoScriptIter { };
struct _PangoFont { };
struct _PangoLanguage { };
struct _PangoLayoutIter { };
struct _PangoRendererPrivate { };
struct _PangoFontFamily { };
struct _PangoFontMetrics { };
struct _PangoFontMap { };
struct _PangoAttrIterator { };
struct _PangoCoverage { };
struct _PangoFontsetSimple { };
struct _PangoFontset { };
struct _PangoLayoutClass { };
struct _PangoEngineLang { };
struct _PangoEngineShape { };
struct _PangoFcFont { };
