#include <stdio.h> 

struct _PangoFontFace {
};

struct _PangoLayout {
};

struct _PangoContext {
};

struct _PangoAttrList {
};

struct _PangoFontDescription {
};

struct _PangoTabArray {
};

struct _PangoScriptIter {
};

struct _ParenStackEntry {
};

struct _PangoFont {
};

struct _PangoGlyphItemIter {
};

struct _PangoEngineShape {
};

struct _PangoEngineLang {
};

struct _PangoLanguage {
};

struct _PangoLayoutIter {
};

struct _PangoRendererPrivate {
};

struct _LineState {
};

struct _PangoFontFamily {
};

struct _PangoFontMetrics {
};

struct _PangoFontMap {
};

struct _PangoAttrIterator {
};

struct _PangoCoverage {
};

struct _PangoBlockInfo {
};

struct _PangoFontsetSimple {
};

struct _PangoFontset {
};

struct _PangoEngineShapeClass {
};

struct _PangoEngineClass {
};

