// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#undef g_assert_warning
static void(*funcptr) (const char * , const char * , const int , const char * , const char * ) = 0;

extern int __lsb_check_params;
void g_assert_warning (const char * arg0 , const char * arg1 , const int arg2 , const char * arg3 , const char * arg4 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for g_assert_warning()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_assert_warning");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_assert_warning. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_assert_warning() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "g_assert_warning - arg0 (log_domain)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_assert_warning - arg0 (log_domain)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "g_assert_warning - arg1 (file)");
		}
		validate_NULL_TYPETYPE(  arg1, "g_assert_warning - arg1 (file)");
		validate_NULL_TYPETYPE(  arg2, "g_assert_warning - arg2 (line)");
		if( arg3 ) {
		validate_Rdaddress( arg3, "g_assert_warning - arg3 (pretty_function)");
		}
		validate_NULL_TYPETYPE(  arg3, "g_assert_warning - arg3 (pretty_function)");
		if( arg4 ) {
		validate_Rdaddress( arg4, "g_assert_warning - arg4 (expression)");
		}
		validate_NULL_TYPETYPE(  arg4, "g_assert_warning - arg4 (expression)");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
}

