// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#undef g_date_time_is_daylight_savings
static gboolean(*funcptr) (GDateTime * ) = 0;

extern int __lsb_check_params;
gboolean g_date_time_is_daylight_savings (GDateTime * arg0 )
{
	int reset_flag = __lsb_check_params;
	gboolean ret_value  ;
	__lsb_output(4, "Invoking wrapper for g_date_time_is_daylight_savings()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_date_time_is_daylight_savings");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_date_time_is_daylight_savings. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_date_time_is_daylight_savings() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "g_date_time_is_daylight_savings - arg0 (datetime)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_date_time_is_daylight_savings - arg0 (datetime)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

