// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#undef g_locale_to_utf8
static gchar *(*funcptr) (const gchar * , gssize , gsize * , gsize * , GError * * ) = 0;

extern int __lsb_check_params;
gchar * g_locale_to_utf8 (const gchar * arg0 , gssize arg1 , gsize * arg2 , gsize * arg3 , GError * * arg4 )
{
	int reset_flag = __lsb_check_params;
	gchar * ret_value  ;
	__lsb_output(4, "Invoking wrapper for g_locale_to_utf8()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_locale_to_utf8");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_locale_to_utf8. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_locale_to_utf8() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "g_locale_to_utf8 - arg0 (opsysstring)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_locale_to_utf8 - arg0 (opsysstring)");
		validate_NULL_TYPETYPE(  arg1, "g_locale_to_utf8 - arg1 (len)");
		if( arg2 ) {
		validate_RWaddress( arg2, "g_locale_to_utf8 - arg2 (bytes_read)");
		}
		validate_NULL_TYPETYPE(  arg2, "g_locale_to_utf8 - arg2 (bytes_read)");
		if( arg3 ) {
		validate_RWaddress( arg3, "g_locale_to_utf8 - arg3 (bytes_written)");
		}
		validate_NULL_TYPETYPE(  arg3, "g_locale_to_utf8 - arg3 (bytes_written)");
		if( arg4 ) {
		validate_RWaddress( arg4, "g_locale_to_utf8 - arg4 (error)");
		}
		validate_NULL_TYPETYPE(  arg4, "g_locale_to_utf8 - arg4 (error)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
	return ret_value;
}

