#!/usr/bin/perl
use strict;
use Getopt::Long;

sub usage()
{
print STDERR "Usage: mklsbver -v <lsbversion(s)>\n";
print STDERR "    LSB versions should be comma-separated.\n";
die;
}

my $lsbversion;
GetOptions("v=s" => \$lsbversion);
if( !$lsbversion ) { usage(); }

my @lsbversions = sort split(/,/, $lsbversion);
my @lsbversionsnumeric = @lsbversions;

for (@lsbversionsnumeric) {
	s/\.//;
};

print "char* LSB_Versions[] = {\"".join("\", \"", @lsbversions)."\"};\n";
print "int LSB_Versions_Numeric[] = {".join(", ", @lsbversionsnumeric)."};\n";
print "char* LSB_Versions_list = \"".join(", ", @lsbversions)."\";\n";
print "int num_LSB_Versions = sizeof(LSB_Versions)/sizeof(char *);\n\n";
print "int LSB_Version = -1;\n\n";
print "/* Default LSB version is 4.1 */\n";
print "int LSB_Version_default = 4;\n";
