GEN_FUNCS = \
COLOR_PAIR.o \
PAIR_NUMBER.o \
add_wch.o \
add_wchnstr.o \
add_wchstr.o \
addnwstr.o \
addwstr.o \
assume_default_colors.o \
bkgrnd.o \
bkgrndset.o \
border_set.o \
box_set.o \
curses_version.o \
define_key.o \
echo_wchar.o \
erasewchar.o \
get_wch.o \
get_wstr.o \
getbkgrnd.o \
getcchar.o \
getmouse.o \
getn_wstr.o \
has_key.o \
has_mouse.o \
hline_set.o \
in_wch.o \
in_wchnstr.o \
in_wchstr.o \
innwstr.o \
ins_nwstr.o \
ins_wch.o \
ins_wstr.o \
inwstr.o \
key_name.o \
keybound.o \
keyok.o \
killwchar.o \
mcprint.o \
mouse_trafo.o \
mouseinterval.o \
mousemask.o \
mvadd_wch.o \
mvadd_wchnstr.o \
mvadd_wchstr.o \
mvaddnwstr.o \
mvaddwstr.o \
mvget_wch.o \
mvget_wstr.o \
mvgetn_wstr.o \
mvhline_set.o \
mvin_wch.o \
mvin_wchnstr.o \
mvin_wchstr.o \
mvinnwstr.o \
mvins_nwstr.o \
mvins_wch.o \
mvins_wstr.o \
mvinwstr.o \
mvvline_set.o \
mvwadd_wch.o \
mvwadd_wchnstr.o \
mvwadd_wchstr.o \
mvwaddnwstr.o \
mvwaddwstr.o \
mvwget_wch.o \
mvwget_wstr.o \
mvwgetn_wstr.o \
mvwhline_set.o \
mvwin_wch.o \
mvwin_wchnstr.o \
mvwin_wchstr.o \
mvwinnwstr.o \
mvwins_nwstr.o \
mvwins_wch.o \
mvwins_wstr.o \
mvwinwstr.o \
mvwvline_set.o \
pecho_wchar.o \
resizeterm.o \
setcchar.o \
slk_attr.o \
slk_attr_off.o \
slk_attr_on.o \
slk_wset.o \
term_attrs.o \
unget_wch.o \
ungetmouse.o \
use_default_colors.o \
use_extended_names.o \
vid_attr.o \
vid_puts.o \
vline_set.o \
wadd_wch.o \
wadd_wchnstr.o \
wadd_wchstr.o \
waddnwstr.o \
waddwstr.o \
wbkgrnd.o \
wbkgrndset.o \
wborder_set.o \
wecho_wchar.o \
wenclose.o \
wget_wch.o \
wget_wstr.o \
wgetbkgrnd.o \
wgetn_wstr.o \
whline_set.o \
win_wch.o \
win_wchnstr.o \
win_wchstr.o \
winnwstr.o \
wins_nwstr.o \
wins_wch.o \
wins_wstr.o \
winwstr.o \
wmouse_trafo.o \
wresize.o \
wunctrl.o \
wvline_set.o 