// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <ncursesw/curses.h>
#undef wborder_set
static int(*funcptr) (WINDOW * , cchar_t * , cchar_t * , cchar_t * , cchar_t * , cchar_t * , cchar_t * , cchar_t * , cchar_t * ) = 0;

extern int __lsb_check_params;
int wborder_set (WINDOW * arg0 , cchar_t * arg1 , cchar_t * arg2 , cchar_t * arg3 , cchar_t * arg4 , cchar_t * arg5 , cchar_t * arg6 , cchar_t * arg7 , cchar_t * arg8 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for wborder_set()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "wborder_set");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load wborder_set. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "wborder_set() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "wborder_set - arg0");
		}
		validate_NULL_TYPETYPE(  arg0, "wborder_set - arg0");
		if( arg1 ) {
		validate_RWaddress( arg1, "wborder_set - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "wborder_set - arg1");
		if( arg2 ) {
		validate_RWaddress( arg2, "wborder_set - arg2");
		}
		validate_NULL_TYPETYPE(  arg2, "wborder_set - arg2");
		if( arg3 ) {
		validate_RWaddress( arg3, "wborder_set - arg3");
		}
		validate_NULL_TYPETYPE(  arg3, "wborder_set - arg3");
		if( arg4 ) {
		validate_RWaddress( arg4, "wborder_set - arg4");
		}
		validate_NULL_TYPETYPE(  arg4, "wborder_set - arg4");
		if( arg5 ) {
		validate_RWaddress( arg5, "wborder_set - arg5");
		}
		validate_NULL_TYPETYPE(  arg5, "wborder_set - arg5");
		if( arg6 ) {
		validate_RWaddress( arg6, "wborder_set - arg6");
		}
		validate_NULL_TYPETYPE(  arg6, "wborder_set - arg6");
		if( arg7 ) {
		validate_RWaddress( arg7, "wborder_set - arg7");
		}
		validate_NULL_TYPETYPE(  arg7, "wborder_set - arg7");
		if( arg8 ) {
		validate_RWaddress( arg8, "wborder_set - arg8");
		}
		validate_NULL_TYPETYPE(  arg8, "wborder_set - arg8");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
	__lsb_check_params = reset_flag;
	return ret_value;
}

