GEN_FUNCS = \
FT_Activate_Size.o \
FT_Add_Default_Modules.o \
FT_Add_Module.o \
FT_Angle_Diff.o \
FT_Atan2.o \
FT_Attach_File.o \
FT_Attach_Stream.o \
FT_Bitmap_Convert.o \
FT_Bitmap_Copy.o \
FT_Bitmap_Done.o \
FT_Bitmap_Embolden.o \
FT_Bitmap_New.o \
FT_CeilFix.o \
FT_Cos.o \
FT_DivFix.o \
FT_Done_Face.o \
FT_Done_FreeType.o \
FT_Done_Glyph.o \
FT_Done_Library.o \
FT_Done_Size.o \
FT_FloorFix.o \
FT_Get_BDF_Charset_ID.o \
FT_Get_BDF_Property.o \
FT_Get_CMap_Language_ID.o \
FT_Get_Char_Index.o \
FT_Get_Charmap_Index.o \
FT_Get_First_Char.o \
FT_Get_Glyph.o \
FT_Get_Glyph_Name.o \
FT_Get_Kerning.o \
FT_Get_MM_Var.o \
FT_Get_Module.o \
FT_Get_Multi_Master.o \
FT_Get_Name_Index.o \
FT_Get_Next_Char.o \
FT_Get_PFR_Advance.o \
FT_Get_PFR_Kerning.o \
FT_Get_PFR_Metrics.o \
FT_Get_PS_Font_Info.o \
FT_Get_PS_Font_Private.o \
FT_Get_Postscript_Name.o \
FT_Get_Renderer.o \
FT_Get_Sfnt_Name.o \
FT_Get_Sfnt_Name_Count.o \
FT_Get_Sfnt_Table.o \
FT_Get_X11_Font_Format.o \
FT_Glyph_Copy.o \
FT_Glyph_Get_CBox.o \
FT_Glyph_Stroke.o \
FT_Glyph_StrokeBorder.o \
FT_Glyph_To_Bitmap.o \
FT_Glyph_Transform.o \
FT_Has_PS_Glyph_Names.o \
FT_Init_FreeType.o \
FT_Library_Version.o \
FT_List_Add.o \
FT_List_Finalize.o \
FT_List_Find.o \
FT_List_Insert.o \
FT_List_Iterate.o \
FT_List_Remove.o \
FT_List_Up.o \
FT_Load_Char.o \
FT_Load_Glyph.o \
FT_Load_Sfnt_Table.o \
FT_Matrix_Invert.o \
FT_Matrix_Multiply.o \
FT_MulDiv.o \
FT_MulFix.o \
FT_New_Face.o \
FT_New_Library.o \
FT_New_Memory_Face.o \
FT_New_Size.o \
FT_OpenType_Validate.o \
FT_Open_Face.o \
FT_Outline_Check.o \
FT_Outline_Copy.o \
FT_Outline_Decompose.o \
FT_Outline_Done.o \
FT_Outline_GetInsideBorder.o \
FT_Outline_GetOutsideBorder.o \
FT_Outline_Get_BBox.o \
FT_Outline_Get_Bitmap.o \
FT_Outline_Get_CBox.o \
FT_Outline_Get_Orientation.o \
FT_Outline_New.o \
FT_Outline_Render.o \
FT_Outline_Reverse.o \
FT_Outline_Transform.o \
FT_Outline_Translate.o \
FT_Remove_Module.o \
FT_Render_Glyph.o \
FT_RoundFix.o \
FT_Select_Charmap.o \
FT_Set_Char_Size.o \
FT_Set_Charmap.o \
FT_Set_Debug_Hook.o \
FT_Set_MM_Blend_Coordinates.o \
FT_Set_MM_Design_Coordinates.o \
FT_Set_Pixel_Sizes.o \
FT_Set_Renderer.o \
FT_Set_Transform.o \
FT_Set_Var_Blend_Coordinates.o \
FT_Set_Var_Design_Coordinates.o \
FT_Sfnt_Table_Info.o \
FT_Sin.o \
FT_Stroker_BeginSubPath.o \
FT_Stroker_ConicTo.o \
FT_Stroker_CubicTo.o \
FT_Stroker_Done.o \
FT_Stroker_EndSubPath.o \
FT_Stroker_Export.o \
FT_Stroker_ExportBorder.o \
FT_Stroker_GetBorderCounts.o \
FT_Stroker_GetCounts.o \
FT_Stroker_LineTo.o \
FT_Stroker_New.o \
FT_Stroker_ParseOutline.o \
FT_Stroker_Rewind.o \
FT_Stroker_Set.o \
FT_Tan.o \
FT_Vector_From_Polar.o \
FT_Vector_Length.o \
FT_Vector_Polarize.o \
FT_Vector_Rotate.o \
FT_Vector_Transform.o \
FT_Vector_Unit.o 