// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gdk/gdk.h>
#include <gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h>
#include <glib-2.0/glib.h>
#undef gdk_cursor_new_from_pixbuf
static GdkCursor *(*funcptr) (GdkDisplay * , GdkPixbuf * , gint , gint ) = 0;

extern int __lsb_check_params;
GdkCursor * gdk_cursor_new_from_pixbuf (GdkDisplay * arg0 , GdkPixbuf * arg1 , gint arg2 , gint arg3 )
{
	int reset_flag = __lsb_check_params;
	GdkCursor * ret_value  ;
	__lsb_output(4, "Invoking wrapper for gdk_cursor_new_from_pixbuf()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gdk_cursor_new_from_pixbuf");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gdk_cursor_new_from_pixbuf. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gdk_cursor_new_from_pixbuf() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gdk_cursor_new_from_pixbuf - arg0 (display)");
		}
		validate_NULL_TYPETYPE(  arg0, "gdk_cursor_new_from_pixbuf - arg0 (display)");
		if( arg1 ) {
		validate_RWaddress( arg1, "gdk_cursor_new_from_pixbuf - arg1 (pixbuf)");
		}
		validate_NULL_TYPETYPE(  arg1, "gdk_cursor_new_from_pixbuf - arg1 (pixbuf)");
		validate_NULL_TYPETYPE(  arg2, "gdk_cursor_new_from_pixbuf - arg2 (x)");
		validate_NULL_TYPETYPE(  arg3, "gdk_cursor_new_from_pixbuf - arg3 (y)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

