// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gdk/gdk.h>
#include <glib-2.0/glib.h>
#undef gdk_device_set_axis_use
static void(*funcptr) (GdkDevice * , guint , GdkAxisUse ) = 0;

extern int __lsb_check_params;
void gdk_device_set_axis_use (GdkDevice * arg0 , guint arg1 , GdkAxisUse arg2 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gdk_device_set_axis_use()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gdk_device_set_axis_use");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gdk_device_set_axis_use. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gdk_device_set_axis_use() - validating");
		validate_RWaddress( arg0, "gdk_device_set_axis_use - arg0 (device)");
		validate_NULL_TYPETYPE(  arg0, "gdk_device_set_axis_use - arg0 (device)");
		validate_NULL_TYPETYPE(  arg1, "gdk_device_set_axis_use - arg1 (index_)");
		validate_NULL_TYPETYPE(  arg2, "gdk_device_set_axis_use - arg2 (use)");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

