GEN_FUNCS = \
DPMSCapable.o \
DPMSDisable.o \
DPMSEnable.o \
DPMSForceLevel.o \
DPMSGetTimeouts.o \
DPMSGetVersion.o \
DPMSInfo.o \
DPMSQueryExtension.o \
DPMSSetTimeouts.o \
XMissingExtension.o \
XSecurityAllocXauth.o \
XSecurityFreeXauth.o \
XSecurityGenerateAuthorization.o \
XSecurityQueryExtension.o \
XSecurityRevokeAuthorization.o \
XShapeCombineMask.o \
XShapeCombineRectangles.o \
XShapeCombineRegion.o \
XShapeCombineShape.o \
XShapeGetRectangles.o \
XShapeInputSelected.o \
XShapeOffsetShape.o \
XShapeQueryExtension.o \
XShapeQueryExtents.o \
XShapeQueryVersion.o \
XShapeSelectInput.o \
XShmAttach.o \
XShmCreateImage.o \
XShmCreatePixmap.o \
XShmDetach.o \
XShmGetEventBase.o \
XShmGetImage.o \
XShmPixmapFormat.o \
XShmPutImage.o \
XShmQueryExtension.o \
XShmQueryVersion.o \
XSyncAwait.o \
XSyncChangeAlarm.o \
XSyncChangeCounter.o \
XSyncCreateAlarm.o \
XSyncCreateCounter.o \
XSyncDestroyAlarm.o \
XSyncDestroyCounter.o \
XSyncFreeSystemCounterList.o \
XSyncGetPriority.o \
XSyncInitialize.o \
XSyncIntToValue.o \
XSyncIntsToValue.o \
XSyncListSystemCounters.o \
XSyncMaxValue.o \
XSyncMinValue.o \
XSyncQueryAlarm.o \
XSyncQueryCounter.o \
XSyncQueryExtension.o \
XSyncSetCounter.o \
XSyncSetPriority.o \
XSyncValueAdd.o \
XSyncValueEqual.o \
XSyncValueGreaterOrEqual.o \
XSyncValueGreaterThan.o \
XSyncValueHigh32.o \
XSyncValueIsNegative.o \
XSyncValueIsPositive.o \
XSyncValueIsZero.o \
XSyncValueLessOrEqual.o \
XSyncValueLessThan.o \
XSyncValueLow32.o \
XSyncValueSubtract.o \
XdbeAllocateBackBufferName.o \
XdbeBeginIdiom.o \
XdbeDeallocateBackBufferName.o \
XdbeEndIdiom.o \
XdbeFreeVisualInfo.o \
XdbeGetBackBufferAttributes.o \
XdbeGetVisualInfo.o \
XdbeQueryExtension.o \
XdbeSwapBuffers.o \
XeviGetVisualInfo.o \
XeviQueryExtension.o \
XeviQueryVersion.o \
XextAddDisplay.o \
XextCreateExtension.o \
XextDestroyExtension.o \
XextFindDisplay.o \
XextRemoveDisplay.o 