GEN_FUNCS = \
DPMSCapable.o \
DPMSDisable.o \
DPMSEnable.o \
DPMSForceLevel.o \
DPMSGetTimeouts.o \
DPMSGetVersion.o \
DPMSInfo.o \
DPMSQueryExtension.o \
DPMSSetTimeouts.o \
XSecurityAllocXauth.o \
XSecurityFreeXauth.o \
XSecurityGenerateAuthorization.o \
XSecurityQueryExtension.o \
XSecurityRevokeAuthorization.o \
XShapeCombineMask.o \
XShapeCombineRectangles.o \
XShapeCombineRegion.o \
XShapeCombineShape.o \
XShapeGetRectangles.o \
XShapeInputSelected.o \
XShapeOffsetShape.o \
XShapeQueryExtension.o \
XShapeQueryExtents.o \
XShapeQueryVersion.o \
XShapeSelectInput.o \
XShmAttach.o \
XShmCreateImage.o \
XShmCreatePixmap.o \
XShmDetach.o \
XShmGetEventBase.o \
XShmGetImage.o \
XShmPixmapFormat.o \
XShmPutImage.o \
XShmQueryExtension.o \
XShmQueryVersion.o 