GEN_FUNCS = \
XkbAllocGeomColors.o \
XkbAllocGeomDoodads.o \
XkbAllocGeomKeyAliases.o \
XkbAllocGeomKeys.o \
XkbAllocGeomOutlines.o \
XkbAllocGeomOverlayKeys.o \
XkbAllocGeomOverlayRows.o \
XkbAllocGeomOverlays.o \
XkbAllocGeomPoints.o \
XkbAllocGeomProps.o \
XkbAllocGeomRows.o \
XkbAllocGeomSectionDoodads.o \
XkbAllocGeomSections.o \
XkbAllocGeomShapes.o \
XkbAllocGeometry.o \
XkbComputeRowBounds.o \
XkbComputeSectionBounds.o \
XkbComputeShapeBounds.o \
XkbComputeShapeTop.o \
XkbFindOverlayForKey.o \
XkbFreeGeomColors.o \
XkbFreeGeomDoodads.o \
XkbFreeGeomKeyAliases.o \
XkbFreeGeomKeys.o \
XkbFreeGeomOutlines.o \
XkbFreeGeomOverlayKeys.o \
XkbFreeGeomOverlayRows.o \
XkbFreeGeomOverlays.o \
XkbFreeGeomPoints.o \
XkbFreeGeomProperties.o \
XkbFreeGeomRows.o \
XkbFreeGeomSections.o \
XkbFreeGeomShapes.o \
XkbFreeGeometry.o \
XkbGetGeometry.o \
XkbGetNamedGeometry.o \
XkbSetGeometry.o \
XShapeCombineMask.o \
XShapeCombineRectangles.o \
XShapeCombineRegion.o \
XShapeCombineShape.o \
XShapeGetRectangles.o \
XShapeInputSelected.o \
XShapeOffsetShape.o \
XShapeQueryExtension.o \
XShapeQueryExtents.o \
XShapeQueryVersion.o \
XShapeSelectInput.o \
XShmAttach.o \
XShmCreateImage.o \
XShmCreatePixmap.o \
XShmDetach.o \
XShmGetEventBase.o \
XShmGetImage.o \
XShmPixmapFormat.o \
XShmPutImage.o \
XShmQueryExtension.o \
XShmQueryVersion.o \
XSyncAwait.o \
XSyncChangeAlarm.o \
XSyncChangeCounter.o \
XSyncCreateAlarm.o \
XSyncCreateCounter.o \
XSyncDestroyAlarm.o \
XSyncDestroyCounter.o \
XSyncFreeSystemCounterList.o \
XSyncGetPriority.o \
XSyncInitialize.o \
XSyncIntToValue.o \
XSyncIntsToValue.o \
XSyncListSystemCounters.o \
XSyncMaxValue.o \
XSyncMinValue.o \
XSyncQueryAlarm.o \
XSyncQueryCounter.o \
XSyncQueryExtension.o \
XSyncSetCounter.o \
XSyncSetPriority.o \
XSyncValueAdd.o \
XSyncValueEqual.o \
XSyncValueGreaterOrEqual.o \
XSyncValueGreaterThan.o \
XSyncValueHigh32.o \
XSyncValueIsNegative.o \
XSyncValueIsPositive.o \
XSyncValueIsZero.o \
XSyncValueLessOrEqual.o \
XSyncValueLessThan.o \
XSyncValueLow32.o \
XSyncValueSubtract.o \
XdbeAllocateBackBufferName.o \
XdbeBeginIdiom.o \
XdbeDeallocateBackBufferName.o \
XdbeEndIdiom.o \
XdbeFreeVisualInfo.o \
XdbeGetBackBufferAttributes.o \
XdbeGetVisualInfo.o \
XdbeQueryExtension.o \
XdbeSwapBuffers.o \
DPMSCapable.o \
DPMSDisable.o \
DPMSEnable.o \
DPMSForceLevel.o \
DPMSGetTimeouts.o \
DPMSGetVersion.o \
DPMSInfo.o \
DPMSQueryExtension.o \
DPMSSetTimeouts.o \
XSecurityAllocXauth.o \
XSecurityFreeXauth.o \
XSecurityGenerateAuthorization.o \
XSecurityQueryExtension.o \
XSecurityRevokeAuthorization.o 