// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/extensions/XKBgeom.h>
static int(*funcptr)(XkbOverlayPtr, int, int, int) = 0;

void XkbFreeGeomOverlayRows(XkbOverlayPtr arg0, int arg1, int arg2, int arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XkbFreeGeomOverlayRows");
	validate_NULL_TYPETYPE(arg0, "XkbFreeGeomOverlayRows");
	validate_NULL_TYPETYPE(arg1, "XkbFreeGeomOverlayRows");
	validate_NULL_TYPETYPE(arg2, "XkbFreeGeomOverlayRows");
	validate_NULL_TYPETYPE(arg3, "XkbFreeGeomOverlayRows");
	return funcptr(arg0, arg1, arg2, arg3);
}

void lsb_XkbFreeGeomOverlayRows(XkbOverlayPtr arg0, int arg1, int arg2, int arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XkbFreeGeomOverlayRows");
	return funcptr(arg0, arg1, arg2, arg3);
}

