// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/extensions/sync.h>
#undef XSyncInitialize
static int(*funcptr) (Display * , int * , int * ) = 0;

extern int __lsb_check_params;
int XSyncInitialize (Display * arg0 , int * arg1 , int * arg2 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for XSyncInitialize()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSyncInitialize");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XSyncInitialize. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XSyncInitialize() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "XSyncInitialize - arg0");
		}
		validate_NULL_TYPETYPE(  arg0, "XSyncInitialize - arg0");
		if( arg1 ) {
		validate_RWaddress( arg1, "XSyncInitialize - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "XSyncInitialize - arg1");
		if( arg2 ) {
		validate_RWaddress( arg2, "XSyncInitialize - arg2");
		}
		validate_NULL_TYPETYPE(  arg2, "XSyncInitialize - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

