// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/extensions/sync.h>
#include <X11/extensions/sync.h>
static int(*funcptr)(XSyncValue, XSyncValue) = 0;

int XSyncValueGreaterThan(XSyncValue arg0, XSyncValue arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSyncValueGreaterThan");
	validate_NULL_TYPETYPE(arg0, "XSyncValueGreaterThan");
	validate_NULL_TYPETYPE(arg1, "XSyncValueGreaterThan");
	return funcptr(arg0, arg1);
}

int __lsb_XSyncValueGreaterThan(XSyncValue arg0, XSyncValue arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSyncValueGreaterThan");
	return funcptr(arg0, arg1);
}

