// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/extensions/sync.h>
#undef XSyncValueSubtract
static void(*funcptr) (XSyncValue * , XSyncValue , XSyncValue , int * ) = 0;

extern int __lsb_check_params;
void XSyncValueSubtract (XSyncValue * arg0 , XSyncValue arg1 , XSyncValue arg2 , int * arg3 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for XSyncValueSubtract()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSyncValueSubtract");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XSyncValueSubtract. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XSyncValueSubtract() - validating");
		validate_RWaddress( arg0, "XSyncValueSubtract - arg0");
		validate_NULL_TYPETYPE(  arg0, "XSyncValueSubtract - arg0");
		validate_NULL_TYPETYPE(  arg1, "XSyncValueSubtract - arg1");
		validate_NULL_TYPETYPE(  arg2, "XSyncValueSubtract - arg2");
		validate_RWaddress( arg3, "XSyncValueSubtract - arg3");
		validate_NULL_TYPETYPE(  arg3, "XSyncValueSubtract - arg3");
	}
	funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
}

