// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <zlib.h>
#undef compressBound
static uLong(*funcptr) (uLong ) = 0;

extern int __lsb_check_params;
uLong compressBound (uLong arg0 )
{
	int reset_flag = __lsb_check_params;
	uLong ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlsym(RTLD_NEXT, "compressBound");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "compressBound()");
		validate_NULL_TYPETYPE(  arg0, "compressBound - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

