// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <zlib.h>
#undef deflateParams
static int(*funcptr) (z_streamp , int , int ) = 0;

int deflateParams (z_streamp arg0 , int arg1 , int arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "deflateParams");
	validate_NULL_TYPETYPE(  arg0, "deflateParams - arg0");
	validate_NULL_TYPETYPE(  arg1, "deflateParams - arg1");
	validate_NULL_TYPETYPE(  arg2, "deflateParams - arg2");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_deflateParams (z_streamp arg0 , int arg1 , int arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "deflateParams");
	return funcptr(arg0, arg1, arg2);
}

