GEN_FUNCS = \
gzread.o \
gzclose.o \
gzopen.o \
gzdopen.o \
gzwrite.o \
gzflush.o \
gzerror.o \
adler32.o \
compress.o \
compress2.o \
crc32.o \
deflate.o \
deflateCopy.o \
deflateEnd.o \
deflateInit2_.o \
deflateInit_.o \
deflateParams.o \
deflateReset.o \
deflateSetDictionary.o \
get_crc_table.o \
gzeof.o \
gzgetc.o \
gzgets.o \
gzputc.o \
gzputs.o \
gzrewind.o \
gzseek.o \
gzsetparams.o \
gztell.o \
inflate.o \
inflateEnd.o \
inflateInit2_.o \
inflateInit_.o \
inflateReset.o \
inflateSetDictionary.o \
inflateSync.o \
inflateSyncPoint.o \
uncompress.o \
zError.o 