// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static double(*funcptr)() = 0;

double cabs()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cabs");
	return funcptr();
}

double lsb_cabs()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cabs");
	return funcptr();
}

