// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <complex.h>
#undef casinl
static long double complex(*funcptr) (long double complex ) = 0;

long double complex casinl (long double complex arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "casinl");
	validate_NULL_TYPETYPE(  arg0, "casinl");
	return funcptr(arg0);
}

long double complex __lsb_casinl (long double complex arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "casinl");
	return funcptr(arg0);
}

