// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <complex.h>
#undef catanhf
static float complex(*funcptr) (float complex ) = 0;

float complex catanhf (float complex arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "catanhf");
	validate_NULL_TYPETYPE(  arg0, "catanhf - arg0");
	return funcptr(arg0);
}

float complex __lsb_catanhf (float complex arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "catanhf");
	return funcptr(arg0);
}

