// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static double(*funcptr)() = 0;

double ccos()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ccos");
	return funcptr();
}

double lsb_ccos()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ccos");
	return funcptr();
}

