// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static float(*funcptr)(float) = 0;

float ctanhf(float arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ctanhf");
	validate_NULL_TYPETYPE(arg0, "ctanhf");
	return funcptr(arg0);
}

float lsb_ctanhf(float arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ctanhf");
	return funcptr(arg0);
}

