// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <math.h>
#undef finitef
static int(*funcptr) (float ) = 0;

int finitef (float arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "finitef");
	validate_NULL_TYPETYPE(  arg0, "finitef - arg0");
	return funcptr(arg0);
}

int __lsb_finitef (float arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "finitef");
	return funcptr(arg0);
}

