// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <math.h>
#undef floor
static double(*funcptr) (double ) = 0;

double floor (double arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "floor");
	validate_NULL_TYPETYPE(  arg0, "floor - arg0");
	return funcptr(arg0);
}

double __lsb_floor (double arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "floor");
	return funcptr(arg0);
}

