// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <math.h>
#undef hypot
static double(*funcptr) (double , double ) = 0;

double hypot (double arg0 , double arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "hypot");
	validate_NULL_TYPETYPE(  arg0, "hypot - arg0");
	validate_NULL_TYPETYPE(  arg1, "hypot - arg1");
	return funcptr(arg0, arg1);
}

double __lsb_hypot (double arg0 , double arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "hypot");
	return funcptr(arg0, arg1);
}

