// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#undef isnanl
static int(*funcptr) (long double ) = 0;

int isnanl (long double arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "isnanl");
	validate_NULL_TYPETYPE(arg0, "isnanl");
	return funcptr(arg0);
}

int lsb_isnanl (long double arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "isnanl");
	return funcptr(arg0);
}

