GEN_FUNCS = \
UTF8ToHtml.o \
UTF8Toisolat1.o \
__docbDefaultSAXHandler.o \
__htmlDefaultSAXHandler.o \
__oldXMLWDcompatibility.o \
__xmlBufferAllocScheme.o \
__xmlDefaultBufferSize.o \
__xmlDefaultSAXHandler.o \
__xmlDefaultSAXLocator.o \
__xmlDeregisterNodeDefaultValue.o \
__xmlDoValidityCheckingDefaultValue.o \
__xmlGenericError.o \
__xmlGenericErrorContext.o \
__xmlGetWarningsDefaultValue.o \
__xmlIndentTreeOutput.o \
__xmlKeepBlanksDefaultValue.o \
__xmlLastError.o \
__xmlLineNumbersDefaultValue.o \
__xmlLoadExtDtdDefaultValue.o \
__xmlOutputBufferCreateFilenameValue.o \
__xmlParserDebugEntities.o \
__xmlParserInputBufferCreateFilenameValue.o \
__xmlParserVersion.o \
__xmlPedanticParserDefaultValue.o \
__xmlRegisterNodeDefaultValue.o \
__xmlSaveNoEmptyTags.o \
__xmlStructuredError.o \
__xmlSubstituteEntitiesDefaultValue.o \
__xmlTreeIndentString.o \
docbDefaultSAXHandlerInit.o \
htmlAttrAllowed.o \
htmlAutoCloseTag.o \
htmlCreateFileParserCtxt.o \
htmlCreateMemoryParserCtxt.o \
htmlCreatePushParserCtxt.o \
htmlCtxtReadDoc.o \
htmlCtxtReadFd.o \
htmlCtxtReadFile.o \
htmlCtxtReadIO.o \
htmlCtxtReadMemory.o \
htmlCtxtReset.o \
htmlCtxtUseOptions.o \
htmlDefaultSAXHandlerInit.o \
htmlDocContentDumpFormatOutput.o \
htmlDocContentDumpOutput.o \
htmlDocDump.o \
htmlDocDumpMemory.o \
htmlElementAllowedHere.o \
htmlElementStatusHere.o \
htmlEncodeEntities.o \
htmlEntityLookup.o \
htmlEntityValueLookup.o \
htmlFreeParserCtxt.o \
htmlGetMetaEncoding.o \
htmlHandleOmittedElem.o \
htmlInitAutoClose.o \
htmlIsAutoClosed.o \
htmlIsBooleanAttr.o \
htmlIsScriptAttribute.o \
htmlNewDoc.o \
htmlNewDocNoDtD.o \
htmlNodeDump.o \
htmlNodeDumpFile.o \
htmlNodeDumpFileFormat.o \
htmlNodeDumpFormatOutput.o \
htmlNodeDumpOutput.o \
htmlParseCharRef.o \
htmlParseChunk.o \
htmlParseDoc.o \
htmlParseDocument.o \
htmlParseElement.o \
htmlParseEntityRef.o \
htmlParseFile.o \
htmlReadDoc.o \
htmlReadFd.o \
htmlReadFile.o \
htmlReadIO.o \
htmlReadMemory.o \
htmlSAXParseDoc.o \
htmlSAXParseFile.o \
htmlSaveFile.o \
htmlSaveFileEnc.o \
htmlSaveFileFormat.o \
htmlSetMetaEncoding.o \
htmlTagLookup.o \
initGenericErrorDefaultFunc.o \
inputPop.o \
inputPush.o \
isolat1ToUTF8.o \
namePop.o \
namePush.o \
nodePop.o \
nodePush.o \
valuePop.o \
valuePush.o \
xmlACatalogAdd.o \
xmlACatalogDump.o \
xmlACatalogRemove.o \
xmlACatalogResolve.o \
xmlACatalogResolvePublic.o \
xmlACatalogResolveSystem.o \
xmlACatalogResolveURI.o \
xmlAddAttributeDecl.o \
xmlAddChild.o \
xmlAddChildList.o \
xmlAddDocEntity.o \
xmlAddDtdEntity.o \
xmlAddElementDecl.o \
xmlAddEncodingAlias.o \
xmlAddID.o \
xmlAddNextSibling.o \
xmlAddNotationDecl.o \
xmlAddPrevSibling.o \
xmlAddRef.o \
xmlAddSibling.o \
xmlAllocOutputBuffer.o \
xmlAllocParserInputBuffer.o \
xmlAttrSerializeTxtContent.o \
xmlAutomataCompile.o \
xmlAutomataGetInitState.o \
xmlAutomataIsDeterminist.o \
xmlAutomataNewAllTrans.o \
xmlAutomataNewCountTrans.o \
xmlAutomataNewCountTrans2.o \
xmlAutomataNewCountedTrans.o \
xmlAutomataNewCounter.o \
xmlAutomataNewCounterTrans.o \
xmlAutomataNewEpsilon.o \
xmlAutomataNewNegTrans.o \
xmlAutomataNewOnceTrans.o \
xmlAutomataNewOnceTrans2.o \
xmlAutomataNewState.o \
xmlAutomataNewTransition.o \
xmlAutomataNewTransition2.o \
xmlAutomataSetFinalState.o \
xmlBoolToText.o \
xmlBufferAdd.o \
xmlBufferAddHead.o \
xmlBufferCCat.o \
xmlBufferCat.o \
xmlBufferContent.o \
xmlBufferCreate.o \
xmlBufferCreateSize.o \
xmlBufferCreateStatic.o \
xmlBufferDump.o \
xmlBufferEmpty.o \
xmlBufferFree.o \
xmlBufferGrow.o \
xmlBufferLength.o \
xmlBufferResize.o \
xmlBufferSetAllocationScheme.o \
xmlBufferShrink.o \
xmlBufferWriteCHAR.o \
xmlBufferWriteChar.o \
xmlBufferWriteQuotedString.o \
xmlBuildQName.o \
xmlBuildRelativeURI.o \
xmlBuildURI.o \
xmlByteConsumed.o \
xmlC14NDocDumpMemory.o \
xmlC14NDocSave.o \
xmlC14NDocSaveTo.o \
xmlC14NExecute.o \
xmlCanonicPath.o \
xmlCatalogAdd.o \
xmlCatalogAddLocal.o \
xmlCatalogCleanup.o \
xmlCatalogConvert.o \
xmlCatalogDump.o \
xmlCatalogFreeLocal.o \
xmlCatalogGetDefaults.o \
xmlCatalogIsEmpty.o \
xmlCatalogLocalResolve.o \
xmlCatalogLocalResolveURI.o \
xmlCatalogRemove.o \
xmlCatalogResolve.o \
xmlCatalogResolvePublic.o \
xmlCatalogResolveSystem.o \
xmlCatalogResolveURI.o \
xmlCatalogSetDebug.o \
xmlCatalogSetDefaultPrefer.o \
xmlCatalogSetDefaults.o \
xmlCharEncCloseFunc.o \
xmlCharEncFirstLine.o \
xmlCharEncInFunc.o \
xmlCharEncOutFunc.o \
xmlCharStrdup.o \
xmlCharStrndup.o \
xmlCheckFilename.o \
xmlCheckHTTPInput.o \
xmlCheckUTF8.o \
xmlCheckVersion.o \
xmlCleanupCharEncodingHandlers.o \
xmlCleanupEncodingAliases.o \
xmlCleanupGlobals.o \
xmlCleanupInputCallbacks.o \
xmlCleanupMemory.o \
xmlCleanupOutputCallbacks.o \
xmlCleanupParser.o \
xmlCleanupThreads.o \
xmlClearNodeInfoSeq.o \
xmlClearParserCtxt.o \
xmlConvertSGMLCatalog.o \
xmlCopyAttributeTable.o \
xmlCopyChar.o \
xmlCopyCharMultiByte.o \
xmlCopyDoc.o \
xmlCopyDocElementContent.o \
xmlCopyDtd.o \
xmlCopyElementTable.o \
xmlCopyEntitiesTable.o \
xmlCopyEnumeration.o \
xmlCopyError.o \
xmlCopyNamespace.o \
xmlCopyNamespaceList.o \
xmlCopyNode.o \
xmlCopyNodeList.o \
xmlCopyNotationTable.o \
xmlCopyProp.o \
xmlCopyPropList.o \
xmlCreateDocParserCtxt.o \
xmlCreateEntityParserCtxt.o \
xmlCreateEnumeration.o \
xmlCreateFileParserCtxt.o \
xmlCreateIOParserCtxt.o \
xmlCreateIntSubset.o \
xmlCreateMemoryParserCtxt.o \
xmlCreatePushParserCtxt.o \
xmlCreateURI.o \
xmlCreateURLParserCtxt.o \
xmlCtxtGetLastError.o \
xmlCtxtReadDoc.o \
xmlCtxtReadFd.o \
xmlCtxtReadFile.o \
xmlCtxtReadIO.o \
xmlCtxtReadMemory.o \
xmlCtxtReset.o \
xmlCtxtResetLastError.o \
xmlCtxtResetPush.o \
xmlCtxtUseOptions.o \
xmlCurrentChar.o \
xmlDOMWrapFreeCtxt.o \
xmlDOMWrapNewCtxt.o \
xmlDebugCheckDocument.o \
xmlDebugDumpAttr.o \
xmlDebugDumpAttrList.o \
xmlDebugDumpDTD.o \
xmlDebugDumpDocument.o \
xmlDebugDumpDocumentHead.o \
xmlDebugDumpEntities.o \
xmlDebugDumpNode.o \
xmlDebugDumpNodeList.o \
xmlDebugDumpOneNode.o \
xmlDebugDumpString.o \
xmlDefaultSAXHandlerInit.o \
xmlDelEncodingAlias.o \
xmlDeregisterNodeDefault.o \
xmlDetectCharEncoding.o \
xmlDictCleanup.o \
xmlDictCreate.o \
xmlDictCreateSub.o \
xmlDictExists.o \
xmlDictFree.o \
xmlDictLookup.o \
xmlDictOwns.o \
xmlDictQLookup.o \
xmlDictReference.o \
xmlDictSize.o \
xmlDocCopyNode.o \
xmlDocCopyNodeList.o \
xmlDocDump.o \
xmlDocDumpFormatMemory.o \
xmlDocDumpFormatMemoryEnc.o \
xmlDocDumpMemory.o \
xmlDocDumpMemoryEnc.o \
xmlDocFormatDump.o \
xmlDocGetRootElement.o \
xmlDocSetRootElement.o \
xmlDumpAttributeDecl.o \
xmlDumpAttributeTable.o \
xmlDumpElementDecl.o \
xmlDumpElementTable.o \
xmlDumpEntitiesTable.o \
xmlDumpEntityDecl.o \
xmlDumpNotationDecl.o \
xmlDumpNotationTable.o \
xmlElemDump.o \
xmlEncodeEntitiesReentrant.o \
xmlEncodeSpecialChars.o \
xmlExpCtxtNbCons.o \
xmlExpCtxtNbNodes.o \
xmlExpDump.o \
xmlExpExpDerive.o \
xmlExpFree.o \
xmlExpFreeCtxt.o \
xmlExpGetLanguage.o \
xmlExpGetStart.o \
xmlExpIsNillable.o \
xmlExpMaxToken.o \
xmlExpNewAtom.o \
xmlExpNewCtxt.o \
xmlExpNewOr.o \
xmlExpNewRange.o \
xmlExpNewSeq.o \
xmlExpParse.o \
xmlExpRef.o \
xmlExpStringDerive.o \
xmlExpSubsume.o \
xmlFileClose.o \
xmlFileMatch.o \
xmlFileOpen.o \
xmlFileRead.o \
xmlFindCharEncodingHandler.o \
xmlFreeAttributeTable.o \
xmlFreeAutomata.o \
xmlFreeCatalog.o \
xmlFreeDoc.o \
xmlFreeDocElementContent.o \
xmlFreeDtd.o \
xmlFreeElementTable.o \
xmlFreeEntitiesTable.o \
xmlFreeEnumeration.o \
xmlFreeIDTable.o \
xmlFreeInputStream.o \
xmlFreeMutex.o \
xmlFreeNode.o \
xmlFreeNodeList.o \
xmlFreeNotationTable.o \
xmlFreeNs.o \
xmlFreeNsList.o \
xmlFreeParserCtxt.o \
xmlFreeParserInputBuffer.o \
xmlFreePattern.o \
xmlFreePatternList.o \
xmlFreeProp.o \
xmlFreePropList.o \
xmlFreeRMutex.o \
xmlFreeRefTable.o \
xmlFreeStreamCtxt.o \
xmlFreeTextReader.o \
xmlFreeTextWriter.o \
xmlFreeURI.o \
xmlFreeValidCtxt.o \
xmlGcMemGet.o \
xmlGcMemSetup.o \
xmlGetBufferAllocationScheme.o \
xmlGetCharEncodingHandler.o \
xmlGetCharEncodingName.o \
xmlGetCompressMode.o \
xmlGetDocCompressMode.o \
xmlGetDocEntity.o \
xmlGetDtdAttrDesc.o \
xmlGetDtdElementDesc.o \
xmlGetDtdEntity.o \
xmlGetDtdNotationDesc.o \
xmlGetDtdQAttrDesc.o \
xmlGetDtdQElementDesc.o \
xmlGetEncodingAlias.o \
xmlGetExternalEntityLoader.o \
xmlGetGlobalState.o \
xmlGetID.o \
xmlGetIntSubset.o \
xmlGetLastChild.o \
xmlGetLastError.o \
xmlGetLineNo.o \
xmlGetNoNsProp.o \
xmlGetNodePath.o \
xmlGetNsList.o \
xmlGetNsProp.o \
xmlGetParameterEntity.o \
xmlGetPredefinedEntity.o \
xmlGetProp.o \
xmlGetRefs.o \
xmlGetThreadId.o \
xmlGetUTF8Char.o \
xmlHasFeature.o \
xmlHasNsProp.o \
xmlHasProp.o \
xmlHashAddEntry.o \
xmlHashAddEntry2.o \
xmlHashAddEntry3.o \
xmlHashCopy.o \
xmlHashCreate.o \
xmlHashCreateDict.o \
xmlHashFree.o \
xmlHashLookup.o \
xmlHashLookup2.o \
xmlHashLookup3.o \
xmlHashQLookup.o \
xmlHashQLookup2.o \
xmlHashQLookup3.o \
xmlHashRemoveEntry.o \
xmlHashRemoveEntry2.o \
xmlHashRemoveEntry3.o \
xmlHashScan.o \
xmlHashScan3.o \
xmlHashScanFull.o \
xmlHashScanFull3.o \
xmlHashSize.o \
xmlHashUpdateEntry.o \
xmlHashUpdateEntry2.o \
xmlHashUpdateEntry3.o \
xmlIOFTPClose.o \
xmlIOFTPMatch.o \
xmlIOFTPOpen.o \
xmlIOFTPRead.o \
xmlIOHTTPClose.o \
xmlIOHTTPMatch.o \
xmlIOHTTPOpen.o \
xmlIOHTTPOpenW.o \
xmlIOHTTPRead.o \
xmlIOParseDTD.o \
xmlInitCharEncodingHandlers.o \
xmlInitGlobals.o \
xmlInitMemory.o \
xmlInitNodeInfoSeq.o \
xmlInitParser.o \
xmlInitParserCtxt.o \
xmlInitThreads.o \
xmlInitializeCatalog.o \
xmlInitializeGlobalState.o \
xmlIsBlankNode.o \
xmlIsID.o \
xmlIsLetter.o \
xmlIsMainThread.o \
xmlIsMixedElement.o \
xmlIsRef.o \
xmlIsXHTML.o \
xmlKeepBlanksDefault.o \
xmlLineNumbersDefault.o \
xmlLinkGetData.o \
xmlListAppend.o \
xmlListClear.o \
xmlListCopy.o \
xmlListCreate.o \
xmlListDelete.o \
xmlListDup.o \
xmlListEmpty.o \
xmlListEnd.o \
xmlListFront.o \
xmlListInsert.o \
xmlListMerge.o \
xmlListPopBack.o \
xmlListPopFront.o \
xmlListPushBack.o \
xmlListPushFront.o \
xmlListRemoveAll.o \
xmlListRemoveFirst.o \
xmlListRemoveLast.o \
xmlListReverse.o \
xmlListReverseSearch.o \
xmlListReverseWalk.o \
xmlListSearch.o \
xmlListSize.o \
xmlListSort.o \
xmlListWalk.o \
xmlLoadACatalog.o \
xmlLoadCatalog.o \
xmlLoadCatalogs.o \
xmlLoadExternalEntity.o \
xmlLoadSGMLSuperCatalog.o \
xmlLockLibrary.o \
xmlLsCountNode.o \
xmlLsOneNode.o \
xmlMallocAtomicLoc.o \
xmlMallocLoc.o \
xmlMemBlocks.o \
xmlMemDisplay.o \
xmlMemFree.o \
xmlMemGet.o \
xmlMemMalloc.o \
xmlMemRealloc.o \
xmlMemSetup.o \
xmlMemShow.o \
xmlMemStrdupLoc.o \
xmlMemUsed.o \
xmlMemoryDump.o \
xmlMemoryStrdup.o \
xmlModuleClose.o \
xmlModuleFree.o \
xmlModuleOpen.o \
xmlModuleSymbol.o \
xmlMutexLock.o \
xmlMutexUnlock.o \
xmlNewAutomata.o \
xmlNewCDataBlock.o \
xmlNewCatalog.o \
xmlNewCharEncodingHandler.o \
xmlNewCharRef.o \
xmlNewChild.o \
xmlNewComment.o \
xmlNewDoc.o \
xmlNewDocComment.o \
xmlNewDocElementContent.o \
xmlNewDocFragment.o \
xmlNewDocNode.o \
xmlNewDocNodeEatName.o \
xmlNewDocPI.o \
xmlNewDocProp.o \
xmlNewDocRawNode.o \
xmlNewDocText.o \
xmlNewDocTextLen.o \
xmlNewDtd.o \
xmlNewEntityInputStream.o \
xmlNewIOInputStream.o \
xmlNewInputFromFile.o \
xmlNewInputStream.o \
xmlNewMutex.o \
xmlNewNode.o \
xmlNewNodeEatName.o \
xmlNewNs.o \
xmlNewNsProp.o \
xmlNewNsPropEatName.o \
xmlNewPI.o \
xmlNewParserCtxt.o \
xmlNewProp.o \
xmlNewRMutex.o \
xmlNewReference.o \
xmlNewStringInputStream.o \
xmlNewText.o \
xmlNewTextChild.o \
xmlNewTextLen.o \
xmlNewTextReader.o \
xmlNewTextReaderFilename.o \
xmlNewTextWriter.o \
xmlNewTextWriterDoc.o \
xmlNewTextWriterFilename.o \
xmlNewTextWriterMemory.o \
xmlNewTextWriterPushParser.o \
xmlNewTextWriterTree.o \
xmlNewValidCtxt.o \
xmlNextChar.o \
xmlNoNetExternalEntityLoader.o \
xmlNodeAddContent.o \
xmlNodeAddContentLen.o \
xmlNodeBufGetContent.o \
xmlNodeDump.o \
xmlNodeDumpOutput.o \
xmlNodeGetBase.o \
xmlNodeGetContent.o \
xmlNodeGetLang.o \
xmlNodeGetSpacePreserve.o \
xmlNodeIsText.o \
xmlNodeListGetRawString.o \
xmlNodeListGetString.o \
xmlNodeSetBase.o \
xmlNodeSetContent.o \
xmlNodeSetContentLen.o \
xmlNodeSetLang.o \
xmlNodeSetName.o \
xmlNodeSetSpacePreserve.o \
xmlNormalizeURIPath.o \
xmlNormalizeWindowsPath.o \
xmlOutputBufferClose.o \
xmlOutputBufferCreateFd.o \
xmlOutputBufferCreateFile.o \
xmlOutputBufferCreateFilename.o \
xmlOutputBufferCreateFilenameDefault.o \
xmlOutputBufferCreateIO.o \
xmlOutputBufferFlush.o \
xmlOutputBufferWrite.o \
xmlOutputBufferWriteEscape.o \
xmlOutputBufferWriteString.o \
xmlParseAttValue.o \
xmlParseAttribute.o \
xmlParseAttributeListDecl.o \
xmlParseAttributeType.o \
xmlParseBalancedChunkMemory.o \
xmlParseBalancedChunkMemoryRecover.o \
xmlParseCDSect.o \
xmlParseCatalogFile.o \
xmlParseCharData.o \
xmlParseCharEncoding.o \
xmlParseCharRef.o \
xmlParseChunk.o \
xmlParseComment.o \
xmlParseContent.o \
xmlParseCtxtExternalEntity.o \
xmlParseDTD.o \
xmlParseDefaultDecl.o \
xmlParseDoc.o \
xmlParseDocTypeDecl.o \
xmlParseDocument.o \
xmlParseElement.o \
xmlParseElementChildrenContentDecl.o \
xmlParseElementContentDecl.o \
xmlParseElementDecl.o \
xmlParseElementMixedContentDecl.o \
xmlParseEncName.o \
xmlParseEncodingDecl.o \
xmlParseEndTag.o \
xmlParseEntity.o \
xmlParseEntityDecl.o \
xmlParseEntityRef.o \
xmlParseEntityValue.o \
xmlParseEnumeratedType.o \
xmlParseEnumerationType.o \
xmlParseExtParsedEnt.o \
xmlParseExternalEntity.o \
xmlParseExternalID.o \
xmlParseExternalSubset.o \
xmlParseFile.o \
xmlParseInNodeContext.o \
xmlParseMarkupDecl.o \
xmlParseMemory.o \
xmlParseMisc.o \
xmlParseName.o \
xmlParseNmtoken.o \
xmlParseNotationDecl.o \
xmlParseNotationType.o \
xmlParsePEReference.o \
xmlParsePI.o \
xmlParsePITarget.o \
xmlParsePubidLiteral.o \
xmlParseReference.o \
xmlParseSDDecl.o \
xmlParseStartTag.o \
xmlParseSystemLiteral.o \
xmlParseTextDecl.o \
xmlParseURI.o \
xmlParseURIRaw.o \
xmlParseURIReference.o \
xmlParseVersionInfo.o \
xmlParseVersionNum.o \
xmlParseXMLDecl.o \
xmlParserAddNodeInfo.o \
xmlParserFindNodeInfo.o \
xmlParserFindNodeInfoIndex.o \
xmlParserGetDirectory.o \
xmlParserHandlePEReference.o \
xmlParserInputBufferCreateFd.o \
xmlParserInputBufferCreateFile.o \
xmlParserInputBufferCreateFilename.o \
xmlParserInputBufferCreateFilenameDefault.o \
xmlParserInputBufferCreateIO.o \
xmlParserInputBufferCreateMem.o \
xmlParserInputBufferCreateStatic.o \
xmlParserInputBufferGrow.o \
xmlParserInputBufferPush.o \
xmlParserInputBufferRead.o \
xmlParserInputGrow.o \
xmlParserInputRead.o \
xmlParserInputShrink.o \
xmlParserPrintFileContext.o \
xmlParserPrintFileInfo.o \
xmlPatternFromRoot.o \
xmlPatternGetStreamCtxt.o \
xmlPatternMatch.o \
xmlPatternMaxDepth.o \
xmlPatternMinDepth.o \
xmlPatternStreamable.o \
xmlPatterncompile.o \
xmlPedanticParserDefault.o \
xmlPopInput.o \
xmlPopInputCallbacks.o \
xmlPrintURI.o \
xmlPushInput.o \
xmlRMutexLock.o \
xmlRMutexUnlock.o \
xmlReadDoc.o \
xmlReadFd.o \
xmlReadFile.o \
xmlReadIO.o \
xmlReadMemory.o \
xmlReaderForDoc.o \
xmlReaderForFd.o \
xmlReaderForFile.o \
xmlReaderForIO.o \
xmlReaderForMemory.o \
xmlReaderNewDoc.o \
xmlReaderNewFd.o \
xmlReaderNewFile.o \
xmlReaderNewIO.o \
xmlReaderNewMemory.o \
xmlReaderNewWalker.o \
xmlReaderWalker.o \
xmlReallocLoc.o \
xmlReconciliateNs.o \
xmlRecoverDoc.o \
xmlRecoverFile.o \
xmlRecoverMemory.o \
xmlRegExecErrInfo.o \
xmlRegExecNextValues.o \
xmlRegExecPushString.o \
xmlRegExecPushString2.o \
xmlRegFreeExecCtxt.o \
xmlRegFreeRegexp.o \
xmlRegNewExecCtxt.o \
xmlRegexpCompile.o \
xmlRegexpExec.o \
xmlRegexpIsDeterminist.o \
xmlRegexpPrint.o \
xmlRegisterCharEncodingHandler.o \
xmlRegisterDefaultInputCallbacks.o \
xmlRegisterDefaultOutputCallbacks.o \
xmlRegisterHTTPPostCallbacks.o \
xmlRegisterInputCallbacks.o \
xmlRegisterNodeDefault.o \
xmlRegisterOutputCallbacks.o \
xmlRelaxNGCleanupTypes.o \
xmlRelaxNGDump.o \
xmlRelaxNGDumpTree.o \
xmlRelaxNGFree.o \
xmlRelaxNGFreeParserCtxt.o \
xmlRelaxNGFreeValidCtxt.o \
xmlRelaxNGGetParserErrors.o \
xmlRelaxNGGetValidErrors.o \
xmlRelaxNGInitTypes.o \
xmlRelaxNGNewDocParserCtxt.o \
xmlRelaxNGNewMemParserCtxt.o \
xmlRelaxNGNewParserCtxt.o \
xmlRelaxNGNewValidCtxt.o \
xmlRelaxNGParse.o \
xmlRelaxNGSetParserErrors.o \
xmlRelaxNGSetValidErrors.o \
xmlRelaxNGSetValidStructuredErrors.o \
xmlRelaxNGValidateDoc.o \
xmlRelaxNGValidateFullElement.o \
xmlRelaxNGValidatePopElement.o \
xmlRelaxNGValidatePushCData.o \
xmlRelaxNGValidatePushElement.o \
xmlRelaxParserSetFlag.o \
xmlRemoveID.o \
xmlRemoveProp.o \
xmlRemoveRef.o \
xmlReplaceNode.o \
xmlResetError.o \
xmlResetLastError.o \
xmlSAX2AttributeDecl.o \
xmlSAX2CDataBlock.o \
xmlSAX2Characters.o \
xmlSAX2Comment.o \
xmlSAX2ElementDecl.o \
xmlSAX2EndDocument.o \
xmlSAX2EndElement.o \
xmlSAX2EndElementNs.o \
xmlSAX2EntityDecl.o \
xmlSAX2ExternalSubset.o \
xmlSAX2GetColumnNumber.o \
xmlSAX2GetEntity.o \
xmlSAX2GetLineNumber.o \
xmlSAX2GetParameterEntity.o \
xmlSAX2GetPublicId.o \
xmlSAX2GetSystemId.o \
xmlSAX2HasExternalSubset.o \
xmlSAX2HasInternalSubset.o \
xmlSAX2IgnorableWhitespace.o \
xmlSAX2InitDefaultSAXHandler.o \
xmlSAX2InitDocbDefaultSAXHandler.o \
xmlSAX2InitHtmlDefaultSAXHandler.o \
xmlSAX2InternalSubset.o \
xmlSAX2IsStandalone.o \
xmlSAX2NotationDecl.o \
xmlSAX2ProcessingInstruction.o \
xmlSAX2Reference.o \
xmlSAX2ResolveEntity.o \
xmlSAX2SetDocumentLocator.o \
xmlSAX2StartDocument.o \
xmlSAX2StartElement.o \
xmlSAX2StartElementNs.o \
xmlSAX2UnparsedEntityDecl.o \
xmlSAXDefaultVersion.o \
xmlSAXParseDTD.o \
xmlSAXParseDoc.o \
xmlSAXParseEntity.o \
xmlSAXParseFile.o \
xmlSAXParseFileWithData.o \
xmlSAXParseMemory.o \
xmlSAXParseMemoryWithData.o \
xmlSAXUserParseFile.o \
xmlSAXUserParseMemory.o \
xmlSAXVersion.o \
xmlSaveClose.o \
xmlSaveDoc.o \
xmlSaveFile.o \
xmlSaveFileEnc.o \
xmlSaveFileTo.o \
xmlSaveFlush.o \
xmlSaveFormatFile.o \
xmlSaveFormatFileEnc.o \
xmlSaveFormatFileTo.o \
xmlSaveSetAttrEscape.o \
xmlSaveSetEscape.o \
xmlSaveToFd.o \
xmlSaveToFilename.o \
xmlSaveToIO.o \
xmlSaveTree.o \
xmlSaveUri.o \
xmlSchemaCleanupTypes.o \
xmlSchemaCollapseString.o \
xmlSchemaCompareValues.o \
xmlSchemaDump.o \
xmlSchemaFree.o \
xmlSchemaFreeParserCtxt.o \
xmlSchemaFreeValidCtxt.o \
xmlSchemaFreeValue.o \
xmlSchemaGetBuiltInType.o \
xmlSchemaGetCanonValue.o \
xmlSchemaGetParserErrors.o \
xmlSchemaGetValType.o \
xmlSchemaGetValidErrors.o \
xmlSchemaInitTypes.o \
xmlSchemaIsValid.o \
xmlSchemaNewDocParserCtxt.o \
xmlSchemaNewMemParserCtxt.o \
xmlSchemaNewParserCtxt.o \
xmlSchemaNewValidCtxt.o \
xmlSchemaParse.o \
xmlSchemaSAXPlug.o \
xmlSchemaSAXUnplug.o \
xmlSchemaSetParserErrors.o \
xmlSchemaSetValidErrors.o \
xmlSchemaSetValidOptions.o \
xmlSchemaSetValidStructuredErrors.o \
xmlSchemaValPredefTypeNode.o \
xmlSchemaValidCtxtGetOptions.o \
xmlSchemaValidateDoc.o \
xmlSchemaValidateFile.o \
xmlSchemaValidateOneElement.o \
xmlSchemaValidateStream.o \
xmlSchematronFree.o \
xmlSchematronFreeParserCtxt.o \
xmlSchematronFreeValidCtxt.o \
xmlSchematronNewDocParserCtxt.o \
xmlSchematronNewMemParserCtxt.o \
xmlSchematronNewParserCtxt.o \
xmlSchematronNewValidCtxt.o \
xmlSchematronParse.o \
xmlSchematronValidateDoc.o \
xmlSearchNs.o \
xmlSearchNsByHref.o \
xmlSetBufferAllocationScheme.o \
xmlSetCompressMode.o \
xmlSetDocCompressMode.o \
xmlSetEntityReferenceFunc.o \
xmlSetExternalEntityLoader.o \
xmlSetGenericErrorFunc.o \
xmlSetListDoc.o \
xmlSetNs.o \
xmlSetNsProp.o \
xmlSetProp.o \
xmlSetStructuredErrorFunc.o \
xmlSetTreeDoc.o \
xmlSetupParserForBuffer.o \
xmlShell.o \
xmlShellBase.o \
xmlShellCat.o \
xmlShellDir.o \
xmlShellDu.o \
xmlShellList.o \
xmlShellLoad.o \
xmlShellPrintNode.o \
xmlShellPrintXPathError.o \
xmlShellPrintXPathResult.o \
xmlShellPwd.o \
xmlShellSave.o \
xmlShellValidate.o \
xmlShellWrite.o \
xmlSkipBlankChars.o \
xmlSnprintfElementContent.o \
xmlSplitQName.o \
xmlSplitQName2.o \
xmlSplitQName3.o \
xmlStopParser.o \
xmlStrEqual.o \
xmlStrQEqual.o \
xmlStrVPrintf.o \
xmlStrcasecmp.o \
xmlStrcasestr.o \
xmlStrcat.o \
xmlStrchr.o \
xmlStrcmp.o \
xmlStrdup.o \
xmlStreamPop.o \
xmlStreamPush.o \
xmlStreamPushAttr.o \
xmlStringCurrentChar.o \
xmlStringDecodeEntities.o \
xmlStringGetNodeList.o \
xmlStringLenDecodeEntities.o \
xmlStringLenGetNodeList.o \
xmlStrlen.o \
xmlStrncasecmp.o \
xmlStrncat.o \
xmlStrncatNew.o \
xmlStrncmp.o \
xmlStrndup.o \
xmlStrstr.o \
xmlStrsub.o \
xmlSubstituteEntitiesDefault.o \
xmlSwitchEncoding.o \
xmlSwitchInputEncoding.o \
xmlSwitchToEncoding.o \
xmlTextConcat.o \
xmlTextMerge.o \
xmlTextReaderAttributeCount.o \
xmlTextReaderBaseUri.o \
xmlTextReaderByteConsumed.o \
xmlTextReaderClose.o \
xmlTextReaderConstBaseUri.o \
xmlTextReaderConstEncoding.o \
xmlTextReaderConstLocalName.o \
xmlTextReaderConstName.o \
xmlTextReaderConstNamespaceUri.o \
xmlTextReaderConstPrefix.o \
xmlTextReaderConstString.o \
xmlTextReaderConstValue.o \
xmlTextReaderConstXmlLang.o \
xmlTextReaderConstXmlVersion.o \
xmlTextReaderCurrentDoc.o \
xmlTextReaderCurrentNode.o \
xmlTextReaderDepth.o \
xmlTextReaderExpand.o \
xmlTextReaderGetAttribute.o \
xmlTextReaderGetAttributeNo.o \
xmlTextReaderGetAttributeNs.o \
xmlTextReaderGetErrorHandler.o \
xmlTextReaderGetParserColumnNumber.o \
xmlTextReaderGetParserLineNumber.o \
xmlTextReaderGetParserProp.o \
xmlTextReaderGetRemainder.o \
xmlTextReaderHasAttributes.o \
xmlTextReaderHasValue.o \
xmlTextReaderIsDefault.o \
xmlTextReaderIsEmptyElement.o \
xmlTextReaderIsNamespaceDecl.o \
xmlTextReaderIsValid.o \
xmlTextReaderLocalName.o \
xmlTextReaderLocatorBaseURI.o \
xmlTextReaderLocatorLineNumber.o \
xmlTextReaderLookupNamespace.o \
xmlTextReaderMoveToAttribute.o \
xmlTextReaderMoveToAttributeNo.o \
xmlTextReaderMoveToAttributeNs.o \
xmlTextReaderMoveToElement.o \
xmlTextReaderMoveToFirstAttribute.o \
xmlTextReaderMoveToNextAttribute.o \
xmlTextReaderName.o \
xmlTextReaderNamespaceUri.o \
xmlTextReaderNext.o \
xmlTextReaderNextSibling.o \
xmlTextReaderNodeType.o \
xmlTextReaderNormalization.o \
xmlTextReaderPrefix.o \
xmlTextReaderPreserve.o \
xmlTextReaderPreservePattern.o \
xmlTextReaderQuoteChar.o \
xmlTextReaderRead.o \
xmlTextReaderReadAttributeValue.o \
xmlTextReaderReadInnerXml.o \
xmlTextReaderReadOuterXml.o \
xmlTextReaderReadState.o \
xmlTextReaderReadString.o \
xmlTextReaderRelaxNGSetSchema.o \
xmlTextReaderRelaxNGValidate.o \
xmlTextReaderSchemaValidate.o \
xmlTextReaderSetErrorHandler.o \
xmlTextReaderSetParserProp.o \
xmlTextReaderSetSchema.o \
xmlTextReaderSetStructuredErrorHandler.o \
xmlTextReaderStandalone.o \
xmlTextReaderValue.o \
xmlTextReaderXmlLang.o \
xmlTextWriterEndAttribute.o \
xmlTextWriterEndCDATA.o \
xmlTextWriterEndComment.o \
xmlTextWriterEndDTD.o \
xmlTextWriterEndDTDAttlist.o \
xmlTextWriterEndDTDElement.o \
xmlTextWriterEndDTDEntity.o \
xmlTextWriterEndDocument.o \
xmlTextWriterEndElement.o \
xmlTextWriterEndPI.o \
xmlTextWriterFlush.o \
xmlTextWriterFullEndElement.o \
xmlTextWriterSetIndent.o \
xmlTextWriterSetIndentString.o \
xmlTextWriterStartAttribute.o \
xmlTextWriterStartAttributeNS.o \
xmlTextWriterStartCDATA.o \
xmlTextWriterStartComment.o \
xmlTextWriterStartDTD.o \
xmlTextWriterStartDTDAttlist.o \
xmlTextWriterStartDTDElement.o \
xmlTextWriterStartDTDEntity.o \
xmlTextWriterStartDocument.o \
xmlTextWriterStartElement.o \
xmlTextWriterStartElementNS.o \
xmlTextWriterStartPI.o \
xmlTextWriterWriteAttribute.o \
xmlTextWriterWriteAttributeNS.o \
xmlTextWriterWriteBase64.o \
xmlTextWriterWriteBinHex.o \
xmlTextWriterWriteCDATA.o \
xmlTextWriterWriteComment.o \
xmlTextWriterWriteDTD.o \
xmlTextWriterWriteDTDAttlist.o \
xmlTextWriterWriteDTDElement.o \
xmlTextWriterWriteDTDEntity.o \
xmlTextWriterWriteDTDExternalEntity.o \
xmlTextWriterWriteDTDExternalEntityContents.o \
xmlTextWriterWriteDTDInternalEntity.o \
xmlTextWriterWriteDTDNotation.o \
xmlTextWriterWriteElement.o \
xmlTextWriterWriteElementNS.o \
xmlTextWriterWritePI.o \
xmlTextWriterWriteRaw.o \
xmlTextWriterWriteRawLen.o \
xmlTextWriterWriteString.o \
xmlTextWriterWriteVFormatAttribute.o \
xmlTextWriterWriteVFormatAttributeNS.o \
xmlTextWriterWriteVFormatCDATA.o \
xmlTextWriterWriteVFormatComment.o \
xmlTextWriterWriteVFormatDTD.o \
xmlTextWriterWriteVFormatDTDAttlist.o \
xmlTextWriterWriteVFormatDTDElement.o \
xmlTextWriterWriteVFormatDTDInternalEntity.o \
xmlTextWriterWriteVFormatElement.o \
xmlTextWriterWriteVFormatElementNS.o \
xmlTextWriterWriteVFormatPI.o \
xmlTextWriterWriteVFormatRaw.o \
xmlTextWriterWriteVFormatString.o \
xmlThrDefBufferAllocScheme.o \
xmlThrDefDefaultBufferSize.o \
xmlThrDefDeregisterNodeDefault.o \
xmlThrDefDoValidityCheckingDefaultValue.o \
xmlThrDefGetWarningsDefaultValue.o \
xmlThrDefIndentTreeOutput.o \
xmlThrDefKeepBlanksDefaultValue.o \
xmlThrDefLineNumbersDefaultValue.o \
xmlThrDefLoadExtDtdDefaultValue.o \
xmlThrDefOutputBufferCreateFilenameDefault.o \
xmlThrDefParserDebugEntities.o \
xmlThrDefParserInputBufferCreateFilenameDefault.o \
xmlThrDefPedanticParserDefaultValue.o \
xmlThrDefRegisterNodeDefault.o \
xmlThrDefSaveNoEmptyTags.o \
xmlThrDefSetGenericErrorFunc.o \
xmlThrDefSetStructuredErrorFunc.o \
xmlThrDefSubstituteEntitiesDefaultValue.o \
xmlThrDefTreeIndentString.o \
xmlURIEscape.o \
xmlURIEscapeStr.o \
xmlURIUnescapeString.o \
xmlUTF8Charcmp.o \
xmlUTF8Size.o \
xmlUTF8Strlen.o \
xmlUTF8Strloc.o \
xmlUTF8Strndup.o \
xmlUTF8Strpos.o \
xmlUTF8Strsize.o \
xmlUTF8Strsub.o \
xmlUnlinkNode.o \
xmlUnlockLibrary.o \
xmlUnsetNsProp.o \
xmlUnsetProp.o \
xmlValidBuildContentModel.o \
xmlValidCtxtNormalizeAttributeValue.o \
xmlValidGetPotentialChildren.o \
xmlValidGetValidElements.o \
xmlValidNormalizeAttributeValue.o \
xmlValidateAttributeDecl.o \
xmlValidateAttributeValue.o \
xmlValidateDocument.o \
xmlValidateDocumentFinal.o \
xmlValidateDtd.o \
xmlValidateDtdFinal.o \
xmlValidateElement.o \
xmlValidateElementDecl.o \
xmlValidateNCName.o \
xmlValidateNMToken.o \
xmlValidateName.o \
xmlValidateNameValue.o \
xmlValidateNamesValue.o \
xmlValidateNmtokenValue.o \
xmlValidateNmtokensValue.o \
xmlValidateNotationDecl.o \
xmlValidateNotationUse.o \
xmlValidateOneAttribute.o \
xmlValidateOneElement.o \
xmlValidateOneNamespace.o \
xmlValidatePopElement.o \
xmlValidatePushCData.o \
xmlValidatePushElement.o \
xmlValidateQName.o \
xmlValidateRoot.o \
xmlXIncludeFreeContext.o \
xmlXIncludeNewContext.o \
xmlXIncludeProcess.o \
xmlXIncludeProcessFlags.o \
xmlXIncludeProcessNode.o \
xmlXIncludeProcessTree.o \
xmlXIncludeProcessTreeFlags.o \
xmlXIncludeSetFlags.o \
xmlXPathAddValues.o \
xmlXPathBooleanFunction.o \
xmlXPathCastBooleanToNumber.o \
xmlXPathCastBooleanToString.o \
xmlXPathCastNodeSetToBoolean.o \
xmlXPathCastNodeSetToNumber.o \
xmlXPathCastNodeSetToString.o \
xmlXPathCastNodeToNumber.o \
xmlXPathCastNodeToString.o \
xmlXPathCastNumberToBoolean.o \
xmlXPathCastNumberToString.o \
xmlXPathCastStringToBoolean.o \
xmlXPathCastStringToNumber.o \
xmlXPathCastToBoolean.o \
xmlXPathCastToNumber.o \
xmlXPathCastToString.o \
xmlXPathCeilingFunction.o \
xmlXPathCmpNodes.o \
xmlXPathCompareValues.o \
xmlXPathCompile.o \
xmlXPathCompiledEval.o \
xmlXPathConcatFunction.o \
xmlXPathContainsFunction.o \
xmlXPathConvertBoolean.o \
xmlXPathConvertNumber.o \
xmlXPathConvertString.o \
xmlXPathCountFunction.o \
xmlXPathCtxtCompile.o \
xmlXPathDebugDumpCompExpr.o \
xmlXPathDebugDumpObject.o \
xmlXPathDifference.o \
xmlXPathDistinct.o \
xmlXPathDistinctSorted.o \
xmlXPathDivValues.o \
xmlXPathEqualValues.o \
xmlXPathErr.o \
xmlXPathEval.o \
xmlXPathEvalExpr.o \
xmlXPathEvalExpression.o \
xmlXPathEvalPredicate.o \
xmlXPathEvaluatePredicateResult.o \
xmlXPathFalseFunction.o \
xmlXPathFloorFunction.o \
xmlXPathFreeCompExpr.o \
xmlXPathFreeContext.o \
xmlXPathFreeNodeSet.o \
xmlXPathFreeNodeSetList.o \
xmlXPathFreeObject.o \
xmlXPathFreeParserContext.o \
xmlXPathFunctionLookup.o \
xmlXPathFunctionLookupNS.o \
xmlXPathHasSameNodes.o \
xmlXPathIdFunction.o \
xmlXPathInit.o \
xmlXPathIntersection.o \
xmlXPathIsInf.o \
xmlXPathIsNaN.o \
xmlXPathIsNodeType.o \
xmlXPathLangFunction.o \
xmlXPathLastFunction.o \
xmlXPathLeading.o \
xmlXPathLeadingSorted.o \
xmlXPathLocalNameFunction.o \
xmlXPathModValues.o \
xmlXPathMultValues.o \
xmlXPathNamespaceURIFunction.o \
xmlXPathNewBoolean.o \
xmlXPathNewCString.o \
xmlXPathNewContext.o \
xmlXPathNewFloat.o \
xmlXPathNewNodeSet.o \
xmlXPathNewNodeSetList.o \
xmlXPathNewParserContext.o \
xmlXPathNewString.o \
xmlXPathNewValueTree.o \
xmlXPathNextAncestor.o \
xmlXPathNextAncestorOrSelf.o \
xmlXPathNextAttribute.o \
xmlXPathNextChild.o \
xmlXPathNextDescendant.o \
xmlXPathNextDescendantOrSelf.o \
xmlXPathNextFollowing.o \
xmlXPathNextFollowingSibling.o \
xmlXPathNextNamespace.o \
xmlXPathNextParent.o \
xmlXPathNextPreceding.o \
xmlXPathNextPrecedingSibling.o \
xmlXPathNextSelf.o \
xmlXPathNodeLeading.o \
xmlXPathNodeLeadingSorted.o \
xmlXPathNodeSetAdd.o \
xmlXPathNodeSetAddNs.o \
xmlXPathNodeSetAddUnique.o \
xmlXPathNodeSetContains.o \
xmlXPathNodeSetCreate.o \
xmlXPathNodeSetDel.o \
xmlXPathNodeSetFreeNs.o \
xmlXPathNodeSetMerge.o \
xmlXPathNodeSetRemove.o \
xmlXPathNodeSetSort.o \
xmlXPathNodeTrailing.o \
xmlXPathNodeTrailingSorted.o \
xmlXPathNormalizeFunction.o \
xmlXPathNotEqualValues.o \
xmlXPathNotFunction.o \
xmlXPathNsLookup.o \
xmlXPathNumberFunction.o \
xmlXPathObjectCopy.o \
xmlXPathOrderDocElems.o \
xmlXPathParseNCName.o \
xmlXPathParseName.o \
xmlXPathPopBoolean.o \
xmlXPathPopExternal.o \
xmlXPathPopNodeSet.o \
xmlXPathPopNumber.o \
xmlXPathPopString.o \
xmlXPathPositionFunction.o \
xmlXPathRegisterAllFunctions.o \
xmlXPathRegisterFunc.o \
xmlXPathRegisterFuncLookup.o \
xmlXPathRegisterFuncNS.o \
xmlXPathRegisterNs.o \
xmlXPathRegisterVariable.o \
xmlXPathRegisterVariableLookup.o \
xmlXPathRegisterVariableNS.o \
xmlXPathRegisteredFuncsCleanup.o \
xmlXPathRegisteredNsCleanup.o \
xmlXPathRegisteredVariablesCleanup.o \
xmlXPathRoot.o \
xmlXPathRoundFunction.o \
xmlXPathStartsWithFunction.o \
xmlXPathStringEvalNumber.o \
xmlXPathStringFunction.o \
xmlXPathStringLengthFunction.o \
xmlXPathSubValues.o \
xmlXPathSubstringAfterFunction.o \
xmlXPathSubstringBeforeFunction.o \
xmlXPathSubstringFunction.o \
xmlXPathSumFunction.o \
xmlXPathTrailing.o \
xmlXPathTrailingSorted.o \
xmlXPathTranslateFunction.o \
xmlXPathTrueFunction.o \
xmlXPathValueFlipSign.o \
xmlXPathVariableLookup.o \
xmlXPathVariableLookupNS.o \
xmlXPathWrapCString.o \
xmlXPathWrapExternal.o \
xmlXPathWrapNodeSet.o \
xmlXPathWrapString.o \
xmlXPatherror.o \
xmlXPtrBuildNodeList.o \
xmlXPtrEval.o \
xmlXPtrEvalRangePredicate.o \
xmlXPtrFreeLocationSet.o \
xmlXPtrLocationSetAdd.o \
xmlXPtrLocationSetCreate.o \
xmlXPtrLocationSetDel.o \
xmlXPtrLocationSetMerge.o \
xmlXPtrLocationSetRemove.o \
xmlXPtrNewCollapsedRange.o \
xmlXPtrNewContext.o \
xmlXPtrNewLocationSetNodeSet.o \
xmlXPtrNewLocationSetNodes.o \
xmlXPtrNewRange.o \
xmlXPtrNewRangeNodeObject.o \
xmlXPtrNewRangeNodePoint.o \
xmlXPtrNewRangeNodes.o \
xmlXPtrNewRangePointNode.o \
xmlXPtrNewRangePoints.o \
xmlXPtrRangeToFunction.o \
xmlXPtrWrapLocationSet.o 