// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/valid.h>
#include <libxml2/libxml/tree.h>
#include <libxml2/libxml/xmlstring.h>
#undef xmlAddRef
static xmlRefPtr(*funcptr) (xmlValidCtxtPtr , xmlDocPtr , const xmlChar * , xmlAttrPtr ) = 0;

extern int __lsb_check_params;
xmlRefPtr xmlAddRef (xmlValidCtxtPtr arg0 , xmlDocPtr arg1 , const xmlChar * arg2 , xmlAttrPtr arg3 )
{
	int reset_flag = __lsb_check_params;
	xmlRefPtr ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlAddRef()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlAddRef", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlAddRef. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlAddRef() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlAddRef - arg0");
		validate_NULL_TYPETYPE(  arg1, "xmlAddRef - arg1");
		validate_Rdaddress( arg2, "xmlAddRef - arg2");
		validate_NULL_TYPETYPE(  arg2, "xmlAddRef - arg2");
		validate_NULL_TYPETYPE(  arg3, "xmlAddRef - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

