// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xmlIO.h>
#include <libxml2/libxml/parser.h>
#undef xmlCtxtReadMemory
static xmlDocPtr(*funcptr) (xmlParserCtxtPtr , const char * , int , const char * , const char * , int ) = 0;

extern int __lsb_check_params;
xmlDocPtr xmlCtxtReadMemory (xmlParserCtxtPtr arg0 , const char * arg1 , int arg2 , const char * arg3 , const char * arg4 , int arg5 )
{
	int reset_flag = __lsb_check_params;
	xmlDocPtr ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlCtxtReadMemory()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlCtxtReadMemory", "LIBXML2_2.6.0");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlCtxtReadMemory. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlCtxtReadMemory() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlCtxtReadMemory - arg0 (ctxt)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "xmlCtxtReadMemory - arg1 (buffer)");
		}
		validate_NULL_TYPETYPE(  arg1, "xmlCtxtReadMemory - arg1 (buffer)");
		validate_NULL_TYPETYPE(  arg2, "xmlCtxtReadMemory - arg2 (size)");
		if( arg3 ) {
		validate_Rdaddress( arg3, "xmlCtxtReadMemory - arg3 (URL)");
		}
		validate_NULL_TYPETYPE(  arg3, "xmlCtxtReadMemory - arg3 (URL)");
		if( arg4 ) {
		validate_Rdaddress( arg4, "xmlCtxtReadMemory - arg4 (encoding)");
		}
		validate_NULL_TYPETYPE(  arg4, "xmlCtxtReadMemory - arg4 (encoding)");
		validate_NULL_TYPETYPE(  arg5, "xmlCtxtReadMemory - arg5 (options)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5);
	__lsb_check_params = reset_flag;
	return ret_value;
}

