// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/dict.h>
#include <libxml2/libxml/xmlstring.h>
#undef xmlDictExists
static const xmlChar *(*funcptr) (xmlDictPtr , const xmlChar * , int ) = 0;

extern int __lsb_check_params;
const xmlChar * xmlDictExists (xmlDictPtr arg0 , const xmlChar * arg1 , int arg2 )
{
	int reset_flag = __lsb_check_params;
	const xmlChar * ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlDictExists()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlDictExists", "LIBXML2_2.6.17");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlDictExists. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlDictExists() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlDictExists - arg0");
		if( arg1 ) {
		validate_Rdaddress( arg1, "xmlDictExists - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "xmlDictExists - arg1");
		validate_NULL_TYPETYPE(  arg2, "xmlDictExists - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

