// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xmlIO.h>
#undef xmlFileOpen
static void *(*funcptr) (const char * ) = 0;

extern int __lsb_check_params;
void * xmlFileOpen (const char * arg0 )
{
	int reset_flag = __lsb_check_params;
	void * ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlFileOpen()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlFileOpen", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlFileOpen. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlFileOpen() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "xmlFileOpen - arg0 (filename)");
		}
		validate_NULL_TYPETYPE(  arg0, "xmlFileOpen - arg0 (filename)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

