// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/uri.h>
#undef xmlParseURIReference
static int(*funcptr) (xmlURIPtr , const char * ) = 0;

extern int __lsb_check_params;
int xmlParseURIReference (xmlURIPtr arg0 , const char * arg1 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlParseURIReference()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlParseURIReference", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlParseURIReference. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlParseURIReference() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlParseURIReference - arg0 (uri)");
		validate_Rdaddress( arg1, "xmlParseURIReference - arg1 (str)");
		validate_NULL_TYPETYPE(  arg1, "xmlParseURIReference - arg1 (str)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

