// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xmlIO.h>
#include <libxml2/libxml/xmlerror.h>
#undef xmlRegisterInputCallbacks
static int(*funcptr) (xmlInputMatchCallback , xmlInputOpenCallback , xmlInputReadCallback , xmlInputCloseCallback ) = 0;

extern int __lsb_check_params;
int xmlRegisterInputCallbacks (xmlInputMatchCallback arg0 , xmlInputOpenCallback arg1 , xmlInputReadCallback arg2 , xmlInputCloseCallback arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlRegisterInputCallbacks()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlRegisterInputCallbacks", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlRegisterInputCallbacks. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlRegisterInputCallbacks() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlRegisterInputCallbacks - arg0 (matchFunc)");
		validate_NULL_TYPETYPE(  arg1, "xmlRegisterInputCallbacks - arg1 (openFunc)");
		validate_NULL_TYPETYPE(  arg2, "xmlRegisterInputCallbacks - arg2 (readFunc)");
		validate_NULL_TYPETYPE(  arg3, "xmlRegisterInputCallbacks - arg3 (closeFunc)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

