// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/SAX2.h>
#undef xmlSAX2IsStandalone
static int(*funcptr) (void * ) = 0;

extern int __lsb_check_params;
int xmlSAX2IsStandalone (void * arg0 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlSAX2IsStandalone()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlSAX2IsStandalone", "LIBXML2_2.6.0");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlSAX2IsStandalone. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlSAX2IsStandalone() - validating");
		validate_RWaddress( arg0, "xmlSAX2IsStandalone - arg0 (ctx)");
		validate_NULL_TYPETYPE(  arg0, "xmlSAX2IsStandalone - arg0 (ctx)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

