// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/debugXML.h>
#undef xmlShellPrintXPathError
static void(*funcptr) (int , const char * ) = 0;

extern int __lsb_check_params;
void xmlShellPrintXPathError (int arg0 , const char * arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for xmlShellPrintXPathError()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlShellPrintXPathError", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlShellPrintXPathError. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlShellPrintXPathError() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlShellPrintXPathError - arg0 (errorType)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "xmlShellPrintXPathError - arg1 (arg)");
		}
		validate_NULL_TYPETYPE(  arg1, "xmlShellPrintXPathError - arg1 (arg)");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

