// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/tree.h>
#undef xmlSaveFileEnc
static int(*funcptr) (const char * , xmlDocPtr , const char * ) = 0;

extern int __lsb_check_params;
int xmlSaveFileEnc (const char * arg0 , xmlDocPtr arg1 , const char * arg2 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlSaveFileEnc()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlSaveFileEnc", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlSaveFileEnc. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlSaveFileEnc() - validating");
		validate_Rdaddress( arg0, "xmlSaveFileEnc - arg0 (filename)");
		validate_NULL_TYPETYPE(  arg0, "xmlSaveFileEnc - arg0 (filename)");
		validate_NULL_TYPETYPE(  arg1, "xmlSaveFileEnc - arg1 (cur)");
		validate_Rdaddress( arg2, "xmlSaveFileEnc - arg2 (encoding)");
		validate_NULL_TYPETYPE(  arg2, "xmlSaveFileEnc - arg2 (encoding)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

