// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xmlreader.h>
#include <libxml2/libxml/relaxng.h>
#undef xmlTextReaderRelaxNGSetSchema
static int(*funcptr) (xmlTextReaderPtr , xmlRelaxNGPtr ) = 0;

extern int __lsb_check_params;
int xmlTextReaderRelaxNGSetSchema (xmlTextReaderPtr arg0 , xmlRelaxNGPtr arg1 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlTextReaderRelaxNGSetSchema()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlTextReaderRelaxNGSetSchema", "LIBXML2_2.5.7");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlTextReaderRelaxNGSetSchema. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlTextReaderRelaxNGSetSchema() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlTextReaderRelaxNGSetSchema - arg0 (reader)");
		validate_NULL_TYPETYPE(  arg1, "xmlTextReaderRelaxNGSetSchema - arg1 (schema)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

