// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xpath.h>
#undef xmlXPathCompiledEval
static xmlXPathObjectPtr(*funcptr) (xmlXPathCompExprPtr , xmlXPathContextPtr ) = 0;

extern int __lsb_check_params;
xmlXPathObjectPtr xmlXPathCompiledEval (xmlXPathCompExprPtr arg0 , xmlXPathContextPtr arg1 )
{
	int reset_flag = __lsb_check_params;
	xmlXPathObjectPtr ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlXPathCompiledEval()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlXPathCompiledEval", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlXPathCompiledEval. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlXPathCompiledEval() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlXPathCompiledEval - arg0 (comp)");
		validate_NULL_TYPETYPE(  arg1, "xmlXPathCompiledEval - arg1 (ctx)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

