// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xpath.h>
#include <libxml2/libxml/xpathInternals.h>
#undef xmlXPathRegisteredFuncsCleanup
static void(*funcptr) (xmlXPathContextPtr ) = 0;

extern int __lsb_check_params;
void xmlXPathRegisteredFuncsCleanup (xmlXPathContextPtr arg0 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for xmlXPathRegisteredFuncsCleanup()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlXPathRegisteredFuncsCleanup", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlXPathRegisteredFuncsCleanup. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlXPathRegisteredFuncsCleanup() - validating");
		validate_NULL_TYPETYPE(  arg0, "xmlXPathRegisteredFuncsCleanup - arg0 (ctxt)");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

