// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <libxml2/libxml/xmlstring.h>
#include <libxml2/libxml/xpath.h>
#undef xmlXPathEvalExpression
static xmlXPathObjectPtr(*funcptr) (const xmlChar * , xmlXPathContextPtr ) = 0;

extern int __lsb_check_params;
xmlXPathObjectPtr xmlXPathEvalExpression (const xmlChar * arg0 , xmlXPathContextPtr arg1 )
{
	int reset_flag = __lsb_check_params;
	xmlXPathObjectPtr ret_value  ;
	__lsb_output(4, "Invoking wrapper for xmlXPathEvalExpression()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "xmlXPathEvalExpression", "LIBXML2_2.4.30");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xmlXPathEvalExpression. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xmlXPathEvalExpression() - validating");
		validate_Rdaddress( arg0, "xmlXPathEvalExpression - arg0 (str)");
		validate_NULL_TYPETYPE(  arg0, "xmlXPathEvalExpression - arg0 (str)");
		validate_NULL_TYPETYPE(  arg1, "xmlXPathEvalExpression - arg1 (ctxt)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

