// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gdk-pixbuf/gdk-pixbuf.h>
#include <glib-2.0/glib.h>
#undef gdk_pixbuf_get_pixels_with_length
static guchar *(*funcptr) (const GdkPixbuf * , guint * ) = 0;

extern int __lsb_check_params;
guchar * gdk_pixbuf_get_pixels_with_length (const GdkPixbuf * arg0 , guint * arg1 )
{
	int reset_flag = __lsb_check_params;
	guchar * ret_value  ;
	__lsb_output(4, "Invoking wrapper for gdk_pixbuf_get_pixels_with_length()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gdk_pixbuf_get_pixels_with_length");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gdk_pixbuf_get_pixels_with_length. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gdk_pixbuf_get_pixels_with_length() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "gdk_pixbuf_get_pixels_with_length - arg0 (pixbuf)");
		}
		validate_NULL_TYPETYPE(  arg0, "gdk_pixbuf_get_pixels_with_length - arg0 (pixbuf)");
		if( arg1 ) {
		validate_RWaddress( arg1, "gdk_pixbuf_get_pixels_with_length - arg1 (length)");
		}
		validate_NULL_TYPETYPE(  arg1, "gdk_pixbuf_get_pixels_with_length - arg1 (length)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

