GEN_FUNCS = \
gdk_colorspace_get_type.o \
gdk_interp_type_get_type.o \
gdk_pixbuf_add_alpha.o \
gdk_pixbuf_alpha_mode_get_type.o \
gdk_pixbuf_animation_get_height.o \
gdk_pixbuf_animation_get_iter.o \
gdk_pixbuf_animation_get_static_image.o \
gdk_pixbuf_animation_get_type.o \
gdk_pixbuf_animation_get_width.o \
gdk_pixbuf_animation_is_static_image.o \
gdk_pixbuf_animation_iter_advance.o \
gdk_pixbuf_animation_iter_get_delay_time.o \
gdk_pixbuf_animation_iter_get_pixbuf.o \
gdk_pixbuf_animation_iter_get_type.o \
gdk_pixbuf_animation_iter_on_currently_loading_frame.o \
gdk_pixbuf_animation_new_from_file.o \
gdk_pixbuf_composite.o \
gdk_pixbuf_composite_color.o \
gdk_pixbuf_composite_color_simple.o \
gdk_pixbuf_copy.o \
gdk_pixbuf_copy_area.o \
gdk_pixbuf_error_get_type.o \
gdk_pixbuf_error_quark.o \
gdk_pixbuf_fill.o \
gdk_pixbuf_flip.o \
gdk_pixbuf_format_get_description.o \
gdk_pixbuf_format_get_extensions.o \
gdk_pixbuf_format_get_license.o \
gdk_pixbuf_format_get_mime_types.o \
gdk_pixbuf_format_get_name.o \
gdk_pixbuf_format_is_disabled.o \
gdk_pixbuf_format_is_scalable.o \
gdk_pixbuf_format_is_writable.o \
gdk_pixbuf_format_set_disabled.o \
gdk_pixbuf_from_pixdata.o \
gdk_pixbuf_get_bits_per_sample.o \
gdk_pixbuf_get_colorspace.o \
gdk_pixbuf_get_file_info.o \
gdk_pixbuf_get_formats.o \
gdk_pixbuf_get_has_alpha.o \
gdk_pixbuf_get_height.o \
gdk_pixbuf_get_n_channels.o \
gdk_pixbuf_get_option.o \
gdk_pixbuf_get_pixels.o \
gdk_pixbuf_get_rowstride.o \
gdk_pixbuf_get_type.o \
gdk_pixbuf_get_width.o \
gdk_pixbuf_loader_close.o \
gdk_pixbuf_loader_get_animation.o \
gdk_pixbuf_loader_get_format.o \
gdk_pixbuf_loader_get_pixbuf.o \
gdk_pixbuf_loader_get_type.o \
gdk_pixbuf_loader_new.o \
gdk_pixbuf_loader_new_with_mime_type.o \
gdk_pixbuf_loader_new_with_type.o \
gdk_pixbuf_loader_set_size.o \
gdk_pixbuf_loader_write.o \
gdk_pixbuf_new.o \
gdk_pixbuf_new_from_data.o \
gdk_pixbuf_new_from_file.o \
gdk_pixbuf_new_from_file_at_scale.o \
gdk_pixbuf_new_from_file_at_size.o \
gdk_pixbuf_new_from_inline.o \
gdk_pixbuf_new_from_xpm_data.o \
gdk_pixbuf_new_subpixbuf.o \
gdk_pixbuf_rotate_simple.o \
gdk_pixbuf_rotation_get_type.o \
gdk_pixbuf_saturate_and_pixelate.o \
gdk_pixbuf_save_to_bufferv.o \
gdk_pixbuf_save_to_callbackv.o \
gdk_pixbuf_savev.o \
gdk_pixbuf_scale.o \
gdk_pixbuf_scale_simple.o \
gdk_pixbuf_simple_anim_add_frame.o \
gdk_pixbuf_simple_anim_get_type.o \
gdk_pixbuf_simple_anim_iter_get_type.o \
gdk_pixbuf_simple_anim_new.o \
gdk_pixdata_deserialize.o \
gdk_pixdata_from_pixbuf.o \
gdk_pixdata_serialize.o \
gdk_pixdata_to_csource.o 