// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <cups/cups.h>
#undef cupsPrintFile
static int(*funcptr) (const char * , const char * , const char * , int , cups_option_t * ) = 0;

extern int __lsb_check_params;
int cupsPrintFile (const char * arg0 , const char * arg1 , const char * arg2 , int arg3 , cups_option_t * arg4 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for cupsPrintFile()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cupsPrintFile");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load cupsPrintFile. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "cupsPrintFile() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "cupsPrintFile - arg0 (printer)");
		}
		validate_NULL_TYPETYPE(  arg0, "cupsPrintFile - arg0 (printer)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "cupsPrintFile - arg1 (filename)");
		}
		validate_NULL_TYPETYPE(  arg1, "cupsPrintFile - arg1 (filename)");
		if( arg2 ) {
		validate_Rdaddress( arg2, "cupsPrintFile - arg2 (title)");
		}
		validate_NULL_TYPETYPE(  arg2, "cupsPrintFile - arg2 (title)");
		validate_NULL_TYPETYPE(  arg3, "cupsPrintFile - arg3 (num_options)");
		if( arg4 ) {
		validate_RWaddress( arg4, "cupsPrintFile - arg4 (options)");
		}
		validate_NULL_TYPETYPE(  arg4, "cupsPrintFile - arg4 (options)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
	return ret_value;
}

