// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <cups/cups.h>
#undef cupsAddDest
static int(*funcptr) (const char * , const char * , int , cups_dest_t * * ) = 0;

extern int __lsb_check_params;
int cupsAddDest (const char * arg0 , const char * arg1 , int arg2 , cups_dest_t * * arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for cupsAddDest()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cupsAddDest");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load cupsAddDest. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "cupsAddDest() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "cupsAddDest - arg0 (name)");
		}
		validate_NULL_TYPETYPE(  arg0, "cupsAddDest - arg0 (name)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "cupsAddDest - arg1 (instance)");
		}
		validate_NULL_TYPETYPE(  arg1, "cupsAddDest - arg1 (instance)");
		validate_NULL_TYPETYPE(  arg2, "cupsAddDest - arg2 (num_dests)");
		if( arg3 ) {
		validate_RWaddress( arg3, "cupsAddDest - arg3 (dests)");
		}
		validate_NULL_TYPETYPE(  arg3, "cupsAddDest - arg3 (dests)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

