GEN_FUNCS = \
cupsAddDest.o \
cupsAddOption.o \
cupsCancelJob.o \
cupsDoAuthentication.o \
cupsDoFileRequest.o \
cupsEncodeOptions.o \
cupsEncryption.o \
cupsFreeDests.o \
cupsFreeJobs.o \
cupsFreeOptions.o \
cupsGetDefault.o \
cupsGetDefault2.o \
cupsGetDest.o \
cupsGetDests.o \
cupsGetDests2.o \
cupsGetFd.o \
cupsGetFile.o \
cupsGetJobs.o \
cupsGetJobs2.o \
cupsGetOption.o \
cupsGetPPD.o \
cupsGetPPD2.o \
cupsGetPassword.o \
cupsLangEncoding.o \
cupsLangFlush.o \
cupsLangFree.o \
cupsLangGet.o \
cupsLastError.o \
cupsMarkOptions.o \
cupsParseOptions.o \
cupsPrintFile.o \
cupsPrintFile2.o \
cupsPrintFiles.o \
cupsPrintFiles2.o \
cupsPutFd.o \
cupsPutFile.o \
cupsServer.o \
cupsSetDests.o \
cupsSetDests2.o \
cupsSetEncryption.o \
cupsSetPasswordCB.o \
cupsSetServer.o \
cupsSetUser.o \
cupsTempFd.o \
cupsUser.o \
httpBlocking.o \
httpCheck.o \
httpClearCookie.o \
httpClearFields.o \
httpClose.o \
httpConnect.o \
httpConnectEncrypt.o \
httpDecode64_2.o \
httpDelete.o \
httpEncode64_2.o \
httpEncryption.o \
httpError.o \
httpFlush.o \
httpGet.o \
httpGetCookie.o \
httpGetDateString.o \
httpGetDateTime.o \
httpGetField.o \
httpGetHostByName.o \
httpGetSubField.o \
httpGets.o \
httpHead.o \
httpInitialize.o \
httpMD5.o \
httpMD5Final.o \
httpMD5String.o \
httpOptions.o \
httpPost.o \
httpPut.o \
httpReconnect.o \
httpSetCookie.o \
httpSetField.o \
httpStatus.o \
httpTrace.o \
httpUpdate.o \
httpWait.o \
ippAddBoolean.o \
ippAddBooleans.o \
ippAddCollection.o \
ippAddCollections.o \
ippAddDate.o \
ippAddInteger.o \
ippAddIntegers.o \
ippAddRange.o \
ippAddRanges.o \
ippAddResolution.o \
ippAddResolutions.o \
ippAddSeparator.o \
ippAddString.o \
ippAddStrings.o \
ippDateToTime.o \
ippDelete.o \
ippDeleteAttribute.o \
ippErrorString.o \
ippFindAttribute.o \
ippFindNextAttribute.o \
ippLength.o \
ippNew.o \
ippPort.o \
ippRead.o \
ippReadFile.o \
ippReadIO.o \
ippSetPort.o \
ippTimeToDate.o \
ippWrite.o \
ippWriteFile.o \
ippWriteIO.o \
ppdClose.o \
ppdCollect.o \
ppdConflicts.o \
ppdEmit.o \
ppdEmitFd.o \
ppdEmitJCL.o \
ppdErrorString.o \
ppdFindAttr.o \
ppdFindChoice.o \
ppdFindMarkedChoice.o \
ppdFindNextAttr.o \
ppdFindOption.o \
ppdIsMarked.o \
ppdLastError.o \
ppdMarkDefaults.o \
ppdMarkOption.o \
ppdOpen.o \
ppdOpenFd.o \
ppdOpenFile.o \
ppdPageLength.o \
ppdPageSize.o \
ppdPageWidth.o \
ppdSetConformance.o 