GEN_FUNCS = \
XtAddActions.o \
XtAddCallback.o \
XtAddCallbacks.o \
XtAddConverter.o \
XtAddEventHandler.o \
XtAddExposureToRegion.o \
XtAddGrab.o \
XtAddInput.o \
XtAddRawEventHandler.o \
XtAddTimeOut.o \
XtAddWorkProc.o \
XtAllocateGC.o \
XtAppAddActionHook.o \
XtAppAddActions.o \
XtAppAddBlockHook.o \
XtAppAddConverter.o \
XtAppAddInput.o \
XtAppAddSignal.o \
XtAppAddTimeOut.o \
XtAppAddWorkProc.o \
XtAppCreateShell.o \
XtAppError.o \
XtAppErrorMsg.o \
XtAppGetErrorDatabase.o \
XtAppGetErrorDatabaseText.o \
XtAppGetExitFlag.o \
XtAppGetSelectionTimeout.o \
XtAppInitialize.o \
XtAppLock.o \
XtAppMainLoop.o \
XtAppNextEvent.o \
XtAppPeekEvent.o \
XtAppPending.o \
XtAppProcessEvent.o \
XtAppReleaseCacheRefs.o \
XtAppSetErrorHandler.o \
XtAppSetErrorMsgHandler.o \
XtAppSetExitFlag.o \
XtAppSetFallbackResources.o \
XtAppSetSelectionTimeout.o \
XtAppSetTypeConverter.o \
XtAppSetWarningHandler.o \
XtAppSetWarningMsgHandler.o \
XtAppUnlock.o \
XtAppWarning.o \
XtAppWarningMsg.o \
XtAugmentTranslations.o \
XtBuildEventMask.o \
XtCallAcceptFocus.o \
XtCallActionProc.o \
XtCallCallbackList.o \
XtCallCallbacks.o \
XtCallConverter.o \
XtCallbackExclusive.o \
XtCallbackNone.o \
XtCallbackNonexclusive.o \
XtCallbackPopdown.o \
XtCallbackReleaseCacheRef.o \
XtCallbackReleaseCacheRefList.o \
XtCalloc.o \
XtCancelSelectionRequest.o \
XtChangeManagedSet.o \
XtClass.o \
XtCloseDisplay.o \
XtConfigureWidget.o \
XtConvert.o \
XtConvertAndStore.o \
XtConvertCase.o \
XtCreateApplicationContext.o \
XtCreateApplicationShell.o \
XtCreateManagedWidget.o \
XtCreatePopupShell.o \
XtCreateSelectionRequest.o \
XtCreateWidget.o \
XtCreateWindow.o \
XtCvtColorToPixel.o \
XtCvtIntToBool.o \
XtCvtIntToBoolean.o \
XtCvtIntToColor.o \
XtCvtIntToFloat.o \
XtCvtIntToFont.o \
XtCvtIntToPixel.o \
XtCvtIntToPixmap.o \
XtCvtIntToShort.o \
XtCvtIntToUnsignedChar.o \
XtCvtStringToAcceleratorTable.o \
XtCvtStringToAtom.o \
XtCvtStringToBool.o \
XtCvtStringToBoolean.o \
XtCvtStringToCommandArgArray.o \
XtCvtStringToCursor.o \
XtCvtStringToDimension.o \
XtCvtStringToDirectoryString.o \
XtCvtStringToDisplay.o \
XtCvtStringToFile.o \
XtCvtStringToFloat.o \
XtCvtStringToFont.o \
XtCvtStringToFontSet.o \
XtCvtStringToFontStruct.o \
XtCvtStringToGravity.o \
XtCvtStringToInitialState.o \
XtCvtStringToInt.o \
XtCvtStringToPixel.o \
XtCvtStringToRestartStyle.o \
XtCvtStringToShort.o \
XtCvtStringToTranslationTable.o \
XtCvtStringToUnsignedChar.o \
XtCvtStringToVisual.o \
XtDatabase.o \
XtDestroyApplicationContext.o \
XtDestroyGC.o \
XtDestroyWidget.o \
XtDirectConvert.o \
XtDisownSelection.o \
XtDispatchEvent.o \
XtDispatchEventToWidget.o \
XtDisplay.o \
XtDisplayInitialize.o \
XtDisplayOfObject.o \
XtDisplayStringConversionWarning.o \
XtDisplayToApplicationContext.o \
XtError.o \
XtErrorMsg.o \
XtFindFile.o \
XtFree.o \
XtGetActionKeysym.o \
XtGetActionList.o \
XtGetApplicationNameAndClass.o \
XtGetApplicationResources.o \
XtGetClassExtension.o \
XtGetConstraintResourceList.o \
XtGetDisplays.o \
XtGetErrorDatabase.o \
XtGetErrorDatabaseText.o \
XtGetGC.o \
XtGetKeyboardFocusWidget.o \
XtGetKeysymTable.o \
XtGetMultiClickTime.o \
XtGetResourceList.o \
XtGetSelectionParameters.o \
XtGetSelectionRequest.o \
XtGetSelectionTimeout.o \
XtGetSelectionValue.o \
XtGetSelectionValueIncremental.o \
XtGetSelectionValues.o \
XtGetSelectionValuesIncremental.o \
XtGetSubresources.o \
XtGetSubvalues.o \
XtGetValues.o \
XtGrabButton.o \
XtGrabKey.o \
XtGrabKeyboard.o \
XtGrabPointer.o \
XtHasCallbacks.o \
XtHooksOfDisplay.o \
XtInitialize.o \
XtInitializeWidgetClass.o \
XtInsertEventHandler.o \
XtInsertEventTypeHandler.o \
XtInsertRawEventHandler.o \
XtInstallAccelerators.o \
XtInstallAllAccelerators.o \
XtIsApplicationShell.o \
XtIsComposite.o \
XtIsConstraint.o \
XtIsManaged.o \
XtIsObject.o \
XtIsOverrideShell.o \
XtIsRealized.o \
XtIsRectObj.o \
XtIsSensitive.o \
XtIsSessionShell.o \
XtIsShell.o \
XtIsSubclass.o \
XtIsTopLevelShell.o \
XtIsTransientShell.o \
XtIsVendorShell.o \
XtIsWMShell.o \
XtIsWidget.o \
XtKeysymToKeycodeList.o \
XtLastEventProcessed.o \
XtLastTimestampProcessed.o \
XtMainLoop.o \
XtMakeGeometryRequest.o \
XtMakeResizeRequest.o \
XtMalloc.o \
XtManageChild.o \
XtManageChildren.o \
XtMapWidget.o \
XtMenuPopupAction.o \
XtMergeArgLists.o \
XtMoveWidget.o \
XtName.o \
XtNameToWidget.o \
XtNewString.o \
XtNextEvent.o \
XtNoticeSignal.o \
XtOpenApplication.o \
XtOpenDisplay.o \
XtOverrideTranslations.o \
XtOwnSelection.o \
XtOwnSelectionIncremental.o \
XtParent.o \
XtParseAcceleratorTable.o \
XtParseTranslationTable.o \
XtPeekEvent.o \
XtPending.o \
XtPopdown.o \
XtPopup.o \
XtPopupSpringLoaded.o \
XtProcessEvent.o \
XtProcessLock.o \
XtProcessUnlock.o \
XtQueryGeometry.o \
XtRealizeWidget.o \
XtRealloc.o \
XtRegisterCaseConverter.o \
XtRegisterDrawable.o \
XtRegisterExtensionSelector.o \
XtRegisterGrabAction.o \
XtReleaseGC.o \
XtReleasePropertyAtom.o \
XtRemoveActionHook.o \
XtRemoveAllCallbacks.o \
XtRemoveBlockHook.o \
XtRemoveCallback.o \
XtRemoveCallbacks.o \
XtRemoveEventHandler.o \
XtRemoveEventTypeHandler.o \
XtRemoveGrab.o \
XtRemoveInput.o \
XtRemoveRawEventHandler.o \
XtRemoveSignal.o \
XtRemoveTimeOut.o \
XtRemoveWorkProc.o \
XtReservePropertyAtom.o \
XtResizeWidget.o \
XtResizeWindow.o \
XtResolvePathname.o \
XtScreen.o \
XtScreenDatabase.o \
XtScreenOfObject.o \
XtSendSelectionRequest.o \
XtSessionGetToken.o \
XtSessionReturnToken.o \
XtSetErrorHandler.o \
XtSetErrorMsgHandler.o \
XtSetEventDispatcher.o \
XtSetKeyTranslator.o \
XtSetKeyboardFocus.o \
XtSetLanguageProc.o \
XtSetMappedWhenManaged.o \
XtSetMultiClickTime.o \
XtSetSelectionParameters.o \
XtSetSelectionTimeout.o \
XtSetSensitive.o \
XtSetSubvalues.o \
XtSetTypeConverter.o \
XtSetValues.o \
XtSetWMColormapWindows.o \
XtSetWarningHandler.o \
XtSetWarningMsgHandler.o \
XtStringConversionWarning.o \
XtSuperclass.o \
XtToolkitInitialize.o \
XtToolkitThreadInitialize.o \
XtTranslateCoords.o \
XtTranslateKey.o \
XtTranslateKeycode.o \
XtUngrabButton.o \
XtUngrabKey.o \
XtUngrabKeyboard.o \
XtUngrabPointer.o \
XtUninstallTranslations.o \
XtUnmanageChild.o \
XtUnmanageChildren.o \
XtUnmapWidget.o \
XtUnrealizeWidget.o \
XtUnregisterDrawable.o \
XtWarning.o \
XtWarningMsg.o \
XtWidgetToApplicationContext.o \
XtWindow.o \
XtWindowOfObject.o \
XtWindowToWidget.o \
_XtCheckSubclassFlag.o \
_XtInherit.o \
_XtIsSubclassOf.o 