// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#undef XtAddActions
static void(*funcptr) (XtActionList , Cardinal ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void XtAddActions (XtActionList arg0 , Cardinal arg1 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAddActions");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XtAddActions()");
		validate_NULL_TYPETYPE(  arg0, "XtAddActions - arg0");
		validate_NULL_TYPETYPE(  arg1, "XtAddActions - arg1");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

