// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(XtAppContext, XtActionList, Cardinal) = 0;

void XtAppAddActions(XtAppContext arg0, XtActionList arg1, Cardinal arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppAddActions");
	validate_NULL_TYPETYPE(arg0, "XtAppAddActions");
	validate_NULL_TYPETYPE(arg1, "XtAppAddActions");
	validate_NULL_TYPETYPE(arg2, "XtAppAddActions");
	return funcptr(arg0, arg1, arg2);
}

void lsb_XtAppAddActions(XtAppContext arg0, XtActionList arg1, Cardinal arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppAddActions");
	return funcptr(arg0, arg1, arg2);
}

