// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#undef XtAppSetTypeConverter
static void(*funcptr) (XtAppContext , char * , char * , XtTypeConverter , XtConvertArgList , Cardinal , XtCacheType , XtDestructor ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void XtAppSetTypeConverter (XtAppContext arg0 , char * arg1 , char * arg2 , XtTypeConverter arg3 , XtConvertArgList arg4 , Cardinal arg5 , XtCacheType arg6 , XtDestructor arg7 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppSetTypeConverter");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XtAppSetTypeConverter()");
		validate_NULL_TYPETYPE(  arg0, "XtAppSetTypeConverter - arg0");
	validate_RWaddress( arg1, "XtAppSetTypeConverter - arg1");
		validate_NULL_TYPETYPE(  arg1, "XtAppSetTypeConverter - arg1");
	validate_RWaddress( arg2, "XtAppSetTypeConverter - arg2");
		validate_NULL_TYPETYPE(  arg2, "XtAppSetTypeConverter - arg2");
		validate_NULL_TYPETYPE(  arg3, "XtAppSetTypeConverter - arg3");
		validate_NULL_TYPETYPE(  arg4, "XtAppSetTypeConverter - arg4");
		validate_NULL_TYPETYPE(  arg5, "XtAppSetTypeConverter - arg5");
		validate_NULL_TYPETYPE(  arg6, "XtAppSetTypeConverter - arg6");
		validate_NULL_TYPETYPE(  arg7, "XtAppSetTypeConverter - arg7");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
	__lsb_check_params = reset_flag;
}

