// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(XtAppContext) = 0;

void XtAppSetExitFlag(XtAppContext arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppSetExitFlag");
	validate_NULL_TYPETYPE(arg0, "XtAppSetExitFlag");
	return funcptr(arg0);
}

void __lsb_XtAppSetExitFlag(XtAppContext arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppSetExitFlag");
	return funcptr(arg0);
}

