// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(XtAppContext) = 0;

XtInputMask XtAppPending(XtAppContext arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppPending");
	validate_NULL_TYPETYPE(arg0, "XtAppPending");
	return funcptr(arg0);
}

XtInputMask __lsb_XtAppPending(XtAppContext arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppPending");
	return funcptr(arg0);
}

