// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(XtAppContext, XtActionHookProc, XtPointer) = 0;

XtActionHookId XtAppAddActionHook(XtAppContext arg0, XtActionHookProc arg1, XtPointer arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppAddActionHook");
	validate_NULL_TYPETYPE(arg0, "XtAppAddActionHook");
	validate_NULL_TYPETYPE(arg1, "XtAppAddActionHook");
	validate_NULL_TYPETYPE(arg2, "XtAppAddActionHook");
	return funcptr(arg0, arg1, arg2);
}

XtActionHookId __lsb_XtAppAddActionHook(XtAppContext arg0, XtActionHookProc arg1, XtPointer arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtAppAddActionHook");
	return funcptr(arg0, arg1, arg2);
}

