// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/X.h>
static int(*funcptr)(Widget, Atom) = 0;

void XtCreateSelectionRequest(Widget arg0, Atom arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtCreateSelectionRequest");
	validate_NULL_TYPETYPE(arg0, "XtCreateSelectionRequest");
	validate_NULL_TYPETYPE(arg1, "XtCreateSelectionRequest");
	return funcptr(arg0, arg1);
}

void __lsb_XtCreateSelectionRequest(Widget arg0, Atom arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtCreateSelectionRequest");
	return funcptr(arg0, arg1);
}

