// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(Widget) = 0;

void XtDestroyWidget(Widget arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtDestroyWidget");
	validate_NULL_TYPETYPE(arg0, "XtDestroyWidget");
	return funcptr(arg0);
}

void __lsb_XtDestroyWidget(Widget arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtDestroyWidget");
	return funcptr(arg0);
}

