// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/X.h>
#include <X11/X.h>
static int(*funcptr)(Widget, Atom, Time) = 0;

void XtDisownSelection(Widget arg0, Atom arg1, Time arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtDisownSelection");
	validate_NULL_TYPETYPE(arg0, "XtDisownSelection");
	validate_NULL_TYPETYPE(arg1, "XtDisownSelection");
	validate_NULL_TYPETYPE(arg2, "XtDisownSelection");
	return funcptr(arg0, arg1, arg2);
}

void lsb_XtDisownSelection(Widget arg0, Atom arg1, Time arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtDisownSelection");
	return funcptr(arg0, arg1, arg2);
}

