// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(WidgetClass, XtResourceList *, Cardinal *) = 0;

void XtGetConstraintResourceList(WidgetClass arg0, XtResourceList * arg1, Cardinal * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetConstraintResourceList");
	validate_NULL_TYPETYPE(arg0, "XtGetConstraintResourceList");
	validate_NULL_TYPETYPE(arg1, "XtGetConstraintResourceList");
	validate_NULL_TYPETYPE(arg2, "XtGetConstraintResourceList");
	return funcptr(arg0, arg1, arg2);
}

void lsb_XtGetConstraintResourceList(WidgetClass arg0, XtResourceList * arg1, Cardinal * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetConstraintResourceList");
	return funcptr(arg0, arg1, arg2);
}

