// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#undef XtGetActionList
static void(*funcptr) (WidgetClass , XtActionList * , Cardinal * ) = 0;

extern int __lsb_check_params;
void XtGetActionList (WidgetClass arg0 , XtActionList * arg1 , Cardinal * arg2 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " XtGetActionList ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "XtGetActionList()");
		validate_NULL_TYPETYPE(  arg0, "XtGetActionList - arg0");
		validate_RWaddress( arg1, "XtGetActionList - arg1");
		validate_NULL_TYPETYPE(  arg1, "XtGetActionList - arg1");
		validate_RWaddress( arg2, "XtGetActionList - arg2");
		validate_NULL_TYPETYPE(  arg2, "XtGetActionList - arg2");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

