// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/X.h>
#include <X11/Intrinsic.h>
#include <X11/X.h>
static int(*funcptr)(Widget, Atom, Atom *, int, XtSelectionCallbackProc, XtPointer *, Time) = 0;

void XtGetSelectionValuesIncremental(Widget arg0, Atom arg1, Atom * arg2, int arg3, XtSelectionCallbackProc arg4, XtPointer * arg5, Time arg6)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg0, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg1, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg2, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg3, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg4, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg5, "XtGetSelectionValuesIncremental");
	validate_NULL_TYPETYPE(arg6, "XtGetSelectionValuesIncremental");
	return funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}

void lsb_XtGetSelectionValuesIncremental(Widget arg0, Atom arg1, Atom * arg2, int arg3, XtSelectionCallbackProc arg4, XtPointer * arg5, Time arg6)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetSelectionValuesIncremental");
	return funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
}

