// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/Xlib.h>
#undef XtGetGC
static GC(*funcptr) (Widget , XtGCMask , XGCValues * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
GC XtGetGC (Widget arg0 , XtGCMask arg1 , XGCValues * arg2 )
{
	int reset_flag = __lsb_check_params;
	GC ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetGC");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XtGetGC()");
		validate_NULL_TYPETYPE(  arg0, "XtGetGC - arg0");
		validate_NULL_TYPETYPE(  arg1, "XtGetGC - arg1");
	validate_RWaddress( arg2, "XtGetGC - arg2");
		validate_NULL_TYPETYPE(  arg2, "XtGetGC - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

