// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(XtPointer, XtResourceList, Cardinal, ArgList, Cardinal) = 0;

void XtGetSubvalues(XtPointer arg0, XtResourceList arg1, Cardinal arg2, ArgList arg3, Cardinal arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetSubvalues");
	validate_NULL_TYPETYPE(arg0, "XtGetSubvalues");
	validate_NULL_TYPETYPE(arg1, "XtGetSubvalues");
	validate_NULL_TYPETYPE(arg2, "XtGetSubvalues");
	validate_NULL_TYPETYPE(arg3, "XtGetSubvalues");
	validate_NULL_TYPETYPE(arg4, "XtGetSubvalues");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

void lsb_XtGetSubvalues(XtPointer arg0, XtResourceList arg1, Cardinal arg2, ArgList arg3, Cardinal arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtGetSubvalues");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

