// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#undef XtInsertRawEventHandler
static void(*funcptr) (Widget , EventMask , int , XtEventHandler , XtPointer , XtListPosition ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void XtInsertRawEventHandler (Widget arg0 , EventMask arg1 , int arg2 , XtEventHandler arg3 , XtPointer arg4 , XtListPosition arg5 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtInsertRawEventHandler");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XtInsertRawEventHandler()");
		validate_NULL_TYPETYPE(  arg0, "XtInsertRawEventHandler - arg0");
		validate_NULL_TYPETYPE(  arg1, "XtInsertRawEventHandler - arg1");
		validate_NULL_TYPETYPE(  arg2, "XtInsertRawEventHandler - arg2");
		validate_NULL_TYPETYPE(  arg3, "XtInsertRawEventHandler - arg3");
		validate_NULL_TYPETYPE(  arg4, "XtInsertRawEventHandler - arg4");
		validate_NULL_TYPETYPE(  arg5, "XtInsertRawEventHandler - arg5");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4, arg5);
	__lsb_check_params = reset_flag;
}

