// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)() = 0;

Boolean XtIsWidget()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtIsWidget");
	return funcptr();
}

Boolean __lsb_XtIsWidget()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtIsWidget");
	return funcptr();
}

