// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
#undef XtIsSubclass
static Boolean(*funcptr) (Widget , WidgetClass ) = 0;

extern int __lsb_check_params;
Boolean XtIsSubclass (Widget arg0 , WidgetClass arg1 )
{
	int reset_flag = __lsb_check_params;
	Boolean ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " XtIsSubclass ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "XtIsSubclass()");
		validate_NULL_TYPETYPE(  arg0, "XtIsSubclass - arg0");
		validate_NULL_TYPETYPE(  arg1, "XtIsSubclass - arg1");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

