// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(Widget, unsigned int, unsigned int, Dimension *, Dimension *) = 0;

XtGeometryResult XtMakeResizeRequest(Widget arg0, unsigned int arg1, unsigned int arg2, Dimension * arg3, Dimension * arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtMakeResizeRequest");
	validate_NULL_TYPETYPE(arg0, "XtMakeResizeRequest");
	validate_NULL_TYPETYPE(arg1, "XtMakeResizeRequest");
	validate_NULL_TYPETYPE(arg2, "XtMakeResizeRequest");
	validate_NULL_TYPETYPE(arg3, "XtMakeResizeRequest");
	validate_NULL_TYPETYPE(arg4, "XtMakeResizeRequest");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

XtGeometryResult __lsb_XtMakeResizeRequest(Widget arg0, unsigned int arg1, unsigned int arg2, Dimension * arg3, Dimension * arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtMakeResizeRequest");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

