// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(char *) = 0;

XtAccelerators XtParseAcceleratorTable(char * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtParseAcceleratorTable");
	validate_NULL_TYPETYPE(arg0, "XtParseAcceleratorTable");
	return funcptr(arg0);
}

XtAccelerators __lsb_XtParseAcceleratorTable(char * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtParseAcceleratorTable");
	return funcptr(arg0);
}

