// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Intrinsic.h>
static int(*funcptr)(XtActionProc, int, unsigned int, int, int) = 0;

void XtRegisterGrabAction(XtActionProc arg0, int arg1, unsigned int arg2, int arg3, int arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtRegisterGrabAction");
	validate_NULL_TYPETYPE(arg0, "XtRegisterGrabAction");
	validate_NULL_TYPETYPE(arg1, "XtRegisterGrabAction");
	validate_NULL_TYPETYPE(arg2, "XtRegisterGrabAction");
	validate_NULL_TYPETYPE(arg3, "XtRegisterGrabAction");
	validate_NULL_TYPETYPE(arg4, "XtRegisterGrabAction");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

void lsb_XtRegisterGrabAction(XtActionProc arg0, int arg1, unsigned int arg2, int arg3, int arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XtRegisterGrabAction");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

