GEN_FUNCS = \
xslAddCall.o \
xslDropCall.o \
xslHandleDebugger.o \
xsltAddKey.o \
xsltAddStackElemList.o \
xsltAddTemplate.o \
xsltAllocateExtra.o \
xsltAllocateExtraCtxt.o \
xsltApplyAttributeSet.o \
xsltApplyImports.o \
xsltApplyOneTemplate.o \
xsltApplyStripSpaces.o \
xsltApplyStylesheet.o \
xsltApplyStylesheetUser.o \
xsltApplyTemplates.o \
xsltAttrListTemplateProcess.o \
xsltAttrTemplateProcess.o \
xsltAttrTemplateValueProcess.o \
xsltAttrTemplateValueProcessNode.o \
xsltAttribute.o \
xsltCalibrateAdjust.o \
xsltCallTemplate.o \
xsltCheckExtPrefix.o \
xsltCheckExtURI.o \
xsltCheckRead.o \
xsltCheckWrite.o \
xsltChoose.o \
xsltCleanupGlobals.o \
xsltCleanupTemplates.o \
xsltComment.o \
xsltCompileAttr.o \
xsltCompilePattern.o \
xsltComputeSortResult.o \
xsltCopy.o \
xsltCopyNamespace.o \
xsltCopyNamespaceList.o \
xsltCopyOf.o \
xsltCopyTextString.o \
xsltCreateRVT.o \
xsltDebug.o \
xsltDebugDumpExtensions.o \
xsltDebugGetDefaultTrace.o \
xsltDebugSetDefaultTrace.o \
xsltDecimalFormatGetByName.o \
xsltDefaultSortFunction.o \
xsltDoSortFunction.o \
xsltDocumentComp.o \
xsltDocumentElem.o \
xsltDocumentFunction.o \
xsltDocumentSortFunction.o \
xsltElement.o \
xsltElementAvailableFunction.o \
xsltEvalAVT.o \
xsltEvalAttrValueTemplate.o \
xsltEvalGlobalVariables.o \
xsltEvalOneUserParam.o \
xsltEvalStaticAttrValueTemplate.o \
xsltEvalTemplateString.o \
xsltEvalUserParams.o \
xsltEvalXPathPredicate.o \
xsltEvalXPathString.o \
xsltEvalXPathStringNs.o \
xsltExtElementLookup.o \
xsltExtModuleElementLookup.o \
xsltExtModuleElementPreComputeLookup.o \
xsltExtModuleFunctionLookup.o \
xsltExtModuleTopLevelLookup.o \
xsltExtensionInstructionResultFinalize.o \
xsltExtensionInstructionResultRegister.o \
xsltFindDocument.o \
xsltFindElemSpaceHandling.o \
xsltFindTemplate.o \
xsltForEach.o \
xsltFormatNumberConversion.o \
xsltFormatNumberFunction.o \
xsltFreeAVTList.o \
xsltFreeAttributeSetsHashes.o \
xsltFreeCompMatchList.o \
xsltFreeCtxtExts.o \
xsltFreeDocumentKeys.o \
xsltFreeDocuments.o \
xsltFreeExts.o \
xsltFreeGlobalVariables.o \
xsltFreeKeys.o \
xsltFreeLocale.o \
xsltFreeNamespaceAliasHashes.o \
xsltFreeRVTs.o \
xsltFreeSecurityPrefs.o \
xsltFreeStackElemList.o \
xsltFreeStyleDocuments.o \
xsltFreeStylePreComps.o \
xsltFreeStylesheet.o \
xsltFreeTemplateHashes.o \
xsltFreeTransformContext.o \
xsltFunctionAvailableFunction.o \
xsltFunctionNodeSet.o \
xsltGenerateIdFunction.o \
xsltGetCNsProp.o \
xsltGetDebuggerStatus.o \
xsltGetDefaultSecurityPrefs.o \
xsltGetExtData.o \
xsltGetExtInfo.o \
xsltGetKey.o \
xsltGetNamespace.o \
xsltGetNsProp.o \
xsltGetPlainNamespace.o \
xsltGetProfileInformation.o \
xsltGetQNameURI.o \
xsltGetQNameURI2.o \
xsltGetSecurityPrefs.o \
xsltGetSpecialNamespace.o \
xsltGetTemplate.o \
xsltGetUTF8Char.o \
xsltGetXIncludeDefault.o \
xsltIf.o \
xsltInit.o \
xsltInitAllDocKeys.o \
xsltInitCtxtExts.o \
xsltInitCtxtKey.o \
xsltInitCtxtKeys.o \
xsltInitElemPreComp.o \
xsltInitGlobals.o \
xsltIsBlank.o \
xsltKeyFunction.o \
xsltLoadDocument.o \
xsltLoadStyleDocument.o \
xsltLoadStylesheetPI.o \
xsltLocalVariablePop.o \
xsltLocalVariablePush.o \
xsltLocaleStrcmp.o \
xsltMessage.o \
xsltNamespaceAlias.o \
xsltNeedElemSpaceHandling.o \
xsltNewDocument.o \
xsltNewElemPreComp.o \
xsltNewLocale.o \
xsltNewSecurityPrefs.o \
xsltNewStyleDocument.o \
xsltNewStylesheet.o \
xsltNewTransformContext.o \
xsltNextImport.o \
xsltNormalizeCompSteps.o \
xsltNumber.o \
xsltNumberFormat.o \
xsltParseGlobalParam.o \
xsltParseGlobalVariable.o \
xsltParseStylesheetAttributeSet.o \
xsltParseStylesheetCallerParam.o \
xsltParseStylesheetDoc.o \
xsltParseStylesheetFile.o \
xsltParseStylesheetImport.o \
xsltParseStylesheetImportedDoc.o \
xsltParseStylesheetInclude.o \
xsltParseStylesheetOutput.o \
xsltParseStylesheetParam.o \
xsltParseStylesheetProcess.o \
xsltParseStylesheetVariable.o \
xsltParseTemplateContent.o \
xsltPreComputeExtModuleElement.o \
xsltPrintErrorContext.o \
xsltProcessOneNode.o \
xsltProcessingInstruction.o \
xsltProfileStylesheet.o \
xsltQuoteOneUserParam.o \
xsltQuoteUserParams.o \
xsltRegisterAllElement.o \
xsltRegisterAllExtras.o \
xsltRegisterAllFunctions.o \
xsltRegisterExtElement.o \
xsltRegisterExtFunction.o \
xsltRegisterExtModule.o \
xsltRegisterExtModuleElement.o \
xsltRegisterExtModuleFull.o \
xsltRegisterExtModuleFunction.o \
xsltRegisterExtModuleTopLevel.o \
xsltRegisterExtPrefix.o \
xsltRegisterExtras.o \
xsltRegisterLocalRVT.o \
xsltRegisterPersistRVT.o \
xsltRegisterTestModule.o \
xsltRegisterTmpRVT.o \
xsltReleaseRVT.o \
xsltResolveStylesheetAttributeSet.o \
xsltRunStylesheet.o \
xsltRunStylesheetUser.o \
xsltSaveProfiling.o \
xsltSaveResultTo.o \
xsltSaveResultToFd.o \
xsltSaveResultToFile.o \
xsltSaveResultToFilename.o \
xsltSaveResultToString.o \
xsltSecurityAllow.o \
xsltSecurityForbid.o \
xsltSetCtxtParseOptions.o \
xsltSetCtxtSecurityPrefs.o \
xsltSetCtxtSortFunc.o \
xsltSetDebuggerCallbacks.o \
xsltSetDebuggerStatus.o \
xsltSetDefaultSecurityPrefs.o \
xsltSetGenericDebugFunc.o \
xsltSetGenericErrorFunc.o \
xsltSetLoaderFunc.o \
xsltSetSecurityPrefs.o \
xsltSetSortFunc.o \
xsltSetTransformErrorFunc.o \
xsltSetXIncludeDefault.o \
xsltShutdownCtxtExts.o \
xsltShutdownExts.o \
xsltSort.o \
xsltSplitQName.o \
xsltStrxfrm.o \
xsltStyleGetExtData.o \
xsltStylePreCompute.o \
xsltSystemPropertyFunction.o \
xsltTemplateProcess.o \
xsltTestCompMatchList.o \
xsltText.o \
xsltTimestamp.o \
xsltUninit.o \
xsltUnparsedEntityURIFunction.o \
xsltUnregisterExtModule.o \
xsltUnregisterExtModuleElement.o \
xsltUnregisterExtModuleFunction.o \
xsltUnregisterExtModuleTopLevel.o \
xsltValueOf.o \
xsltVariableLookup.o \
xsltXPathCompile.o \
xsltXPathFunctionLookup.o \
xsltXPathGetTransformContext.o \
xsltXPathVariableLookup.o 