GEN_FUNCS = \
_pthread_cleanup_pop.o \
_pthread_cleanup_push.o \
pthread_atfork.o \
pthread_attr_destroy.o \
pthread_attr_getdetachstate.o \
pthread_attr_getinheritsched.o \
pthread_attr_getschedparam.o \
pthread_attr_getschedpolicy.o \
pthread_attr_getscope.o \
pthread_attr_init.o \
pthread_attr_setdetachstate.o \
pthread_attr_setinheritsched.o \
pthread_attr_setschedparam.o \
pthread_attr_setschedpolicy.o \
pthread_attr_setscope.o \
pthread_cancel.o \
pthread_cond_broadcast.o \
pthread_cond_destroy.o \
pthread_cond_init.o \
pthread_cond_signal.o \
pthread_cond_timedwait.o \
pthread_cond_wait.o \
pthread_condattr_destroy.o \
pthread_condattr_init.o \
pthread_create.o \
pthread_detach.o \
pthread_equal.o \
pthread_exit.o \
pthread_getschedparam.o \
pthread_getspecific.o \
pthread_join.o \
pthread_key_create.o \
pthread_key_delete.o \
pthread_mutex_destroy.o \
pthread_mutex_init.o \
pthread_mutex_trylock.o \
pthread_mutex_unlock.o \
pthread_mutexattr_destroy.o \
pthread_mutexattr_init.o \
pthread_once.o \
pthread_rwlock_destroy.o \
pthread_rwlock_init.o \
pthread_rwlock_rdlock.o \
pthread_rwlock_tryrdlock.o \
pthread_rwlock_trywrlock.o \
pthread_rwlock_unlock.o \
pthread_rwlock_wrlock.o \
pthread_rwlockattr_destroy.o \
pthread_rwlockattr_getpshared.o \
pthread_rwlockattr_init.o \
pthread_rwlockattr_setpshared.o \
pthread_self.o \
pthread_setcancelstate.o \
pthread_setcanceltype.o \
pthread_setschedparam.o \
pthread_setspecific.o \
pthread_testcancel.o \
sem_close.o \
sem_destroy.o \
sem_getvalue.o \
sem_init.o \
sem_post.o \
sem_trywait.o \
sem_unlink.o \
sem_wait.o \
pthread_attr_getguardsize.o \
pthread_attr_setguardsize.o \
pthread_attr_setstackaddr.o \
pthread_attr_getstackaddr.o \
pthread_attr_setstacksize.o \
pthread_attr_getstacksize.o \
pthread_mutexattr_gettype.o \
pthread_mutexattr_settype.o \
pthread_setconcurrency.o \
pthread_condattr_getpshared.o \
pthread_condattr_setpshared.o \
pthread_mutexattr_getpshared.o \
pthread_mutexattr_setpshared.o \
pthread_rwlock_timedrdlock.o \
pthread_rwlock_timedwrlock.o \
sem_timedwait.o 