GEN_FUNCS = \
_pthread_cleanup_pop.o \
_pthread_cleanup_push.o \
pthread_atfork.o \
pthread_attr_destroy.o \
pthread_attr_getdetachstate.o \
pthread_attr_getinheritsched.o \
pthread_attr_getschedparam.o \
pthread_attr_getschedpolicy.o \
pthread_attr_getscope.o \
pthread_attr_init.o \
pthread_attr_setdetachstate.o \
pthread_attr_setinheritsched.o \
pthread_attr_setschedparam.o \
pthread_attr_setschedpolicy.o \
pthread_attr_setscope.o \
pthread_cancel.o \
pthread_cond_broadcast.o \
pthread_cond_destroy.o \
pthread_cond_init.o \
pthread_cond_signal.o \
pthread_cond_timedwait.o \
pthread_cond_wait.o \
pthread_condattr_destroy.o \
pthread_condattr_init.o \
pthread_create.o \
pthread_detach.o \
pthread_equal.o \
pthread_exit.o \
pthread_getschedparam.o \
pthread_getspecific.o \
pthread_join.o \
pthread_key_create.o \
pthread_key_delete.o \
pthread_mutex_destroy.o \
pthread_mutex_init.o \
pthread_mutex_trylock.o \
pthread_mutex_unlock.o \
pthread_mutexattr_destroy.o \
pthread_mutexattr_init.o \
pthread_once.o \
pthread_rwlock_destroy.o \
pthread_rwlock_init.o \
pthread_rwlock_rdlock.o 