// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <pthread.h>
#include <sys/time.h>
#undef pthread_rwlock_timedwrlock
static int(*funcptr) (pthread_rwlock_t * , const struct timespec * ) = 0;

int pthread_rwlock_timedwrlock (pthread_rwlock_t * arg0 , const struct timespec * arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pthread_rwlock_timedwrlock");
	validate_Rdaddress( arg0, "pthread_rwlock_timedwrlock - arg0");
	validate_NULL_TYPETYPE(  arg0, "pthread_rwlock_timedwrlock - arg0");
	validate_Rdaddress( arg1, "pthread_rwlock_timedwrlock - arg1");
	validate_NULL_TYPETYPE(  arg1, "pthread_rwlock_timedwrlock - arg1");
	return funcptr(arg0, arg1);
}

int __lsb_pthread_rwlock_timedwrlock (pthread_rwlock_t * arg0 , const struct timespec * arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pthread_rwlock_timedwrlock");
	return funcptr(arg0, arg1);
}

