// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <pthread.h>
#undef pthread_barrier_init
static int(*funcptr) (pthread_barrier_t * , const pthread_barrierattr_t * , unsigned int ) = 0;

extern int __lsb_check_params;
int pthread_barrier_init (pthread_barrier_t * arg0 , const pthread_barrierattr_t * arg1 , unsigned int arg2 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for pthread_barrier_init()");
	if(!funcptr)
		#if defined __i386__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.2");
		#endif
		#if defined __ia64__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.2");
		#endif
		#if defined __powerpc__ && !defined __powerpc64__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.2");
		#endif
		#if defined __s390__ && !defined __s390x__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.2");
		#endif
		#if defined __s390x__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.2");
		#endif
		#if defined __x86_64__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.2.5");
		#endif
		#if defined __powerpc64__
			funcptr = dlvsym(RTLD_NEXT, "pthread_barrier_init", "GLIBC_2.3");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load pthread_barrier_init. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "pthread_barrier_init() - validating");
		validate_RWaddress( arg0, "pthread_barrier_init - arg0 (__barrier)");
		validate_NULL_TYPETYPE(  arg0, "pthread_barrier_init - arg0 (__barrier)");
		validate_Rdaddress( arg1, "pthread_barrier_init - arg1 (__attr)");
		validate_NULL_TYPETYPE(  arg1, "pthread_barrier_init - arg1 (__attr)");
		validate_NULL_TYPETYPE(  arg2, "pthread_barrier_init - arg2 (__count)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

