// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <pthread.h>
#undef pthread_condattr_getpshared
static int(*funcptr) (const pthread_condattr_t * , int * ) = 0;

int pthread_condattr_getpshared (const pthread_condattr_t * arg0 , int * arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pthread_condattr_getpshared");
	validate_NULL_TYPETYPE(arg0, "pthread_condattr_getpshared");
	validate_NULL_TYPETYPE(arg1, "pthread_condattr_getpshared");
	return funcptr(arg0, arg1);
}

int lsb_pthread_condattr_getpshared (const pthread_condattr_t * arg0 , int * arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pthread_condattr_getpshared");
	return funcptr(arg0, arg1);
}

