// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <semaphore.h>
#undef sem_post
static int(*funcptr) (sem_t * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
int sem_post (sem_t * arg0 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sem_post");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "sem_post()");
	validate_Rdaddress( arg0, "sem_post - arg0");
		validate_NULL_TYPETYPE(  arg0, "sem_post - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

