// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#undef gtk_icon_factory_remove_default
static void(*funcptr) (GtkIconFactory * ) = 0;

extern int __lsb_check_params;
void gtk_icon_factory_remove_default (GtkIconFactory * arg0 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gtk_icon_factory_remove_default()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_icon_factory_remove_default");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_icon_factory_remove_default. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_icon_factory_remove_default() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gtk_icon_factory_remove_default - arg0 (factory)");
		}
		validate_NULL_TYPETYPE(  arg0, "gtk_icon_factory_remove_default - arg0 (factory)");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

