// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#include <gtk-2.0/gdk/gdk.h>
#undef gtk_style_attach
static GtkStyle *(*funcptr) (GtkStyle * , GdkWindow * ) = 0;

extern int __lsb_check_params;
GtkStyle * gtk_style_attach (GtkStyle * arg0 , GdkWindow * arg1 )
{
	int reset_flag = __lsb_check_params;
	GtkStyle * ret_value  ;
	__lsb_output(4, "Invoking wrapper for gtk_style_attach()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_style_attach");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_style_attach. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_style_attach() - validating");
		validate_RWaddress( arg0, "gtk_style_attach - arg0 (style)");
		validate_NULL_TYPETYPE(  arg0, "gtk_style_attach - arg0 (style)");
		validate_RWaddress( arg1, "gtk_style_attach - arg1 (window)");
		validate_NULL_TYPETYPE(  arg1, "gtk_style_attach - arg1 (window)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

