// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#include <gtk-2.0/gtk/gtkenums.h>
#undef gtk_range_set_upper_stepper_sensitivity
static void(*funcptr) (GtkRange * , GtkSensitivityType ) = 0;

extern int __lsb_check_params;
void gtk_range_set_upper_stepper_sensitivity (GtkRange * arg0 , GtkSensitivityType arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gtk_range_set_upper_stepper_sensitivity()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_range_set_upper_stepper_sensitivity");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_range_set_upper_stepper_sensitivity. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_range_set_upper_stepper_sensitivity() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gtk_range_set_upper_stepper_sensitivity - arg0 (range)");
		}
		validate_NULL_TYPETYPE(  arg0, "gtk_range_set_upper_stepper_sensitivity - arg0 (range)");
		validate_NULL_TYPETYPE(  arg1, "gtk_range_set_upper_stepper_sensitivity - arg1 (sensitivity)");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

