// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#include <gtk-2.0/gdk/gdk.h>
#undef gtk_widget_intersect
static gboolean(*funcptr) (GtkWidget * , const GdkRectangle * , GdkRectangle * ) = 0;

extern int __lsb_check_params;
gboolean gtk_widget_intersect (GtkWidget * arg0 , const GdkRectangle * arg1 , GdkRectangle * arg2 )
{
	int reset_flag = __lsb_check_params;
	gboolean ret_value  ;
	__lsb_output(4, "Invoking wrapper for gtk_widget_intersect()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_widget_intersect");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_widget_intersect. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_widget_intersect() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gtk_widget_intersect - arg0 (widget)");
		}
		validate_NULL_TYPETYPE(  arg0, "gtk_widget_intersect - arg0 (widget)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "gtk_widget_intersect - arg1 (area)");
		}
		validate_NULL_TYPETYPE(  arg1, "gtk_widget_intersect - arg1 (area)");
		if( arg2 ) {
		validate_RWaddress( arg2, "gtk_widget_intersect - arg2 (intersection)");
		}
		validate_NULL_TYPETYPE(  arg2, "gtk_widget_intersect - arg2 (intersection)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

