// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#include <glib-2.0/glib.h>
#include <gtk-2.0/gtk/gtkenums.h>
#undef gtk_page_setup_set_left_margin
static void(*funcptr) (GtkPageSetup * , gdouble , GtkUnit ) = 0;

extern int __lsb_check_params;
void gtk_page_setup_set_left_margin (GtkPageSetup * arg0 , gdouble arg1 , GtkUnit arg2 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gtk_page_setup_set_left_margin()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_page_setup_set_left_margin");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_page_setup_set_left_margin. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_page_setup_set_left_margin() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gtk_page_setup_set_left_margin - arg0 (setup)");
		}
		validate_NULL_TYPETYPE(  arg0, "gtk_page_setup_set_left_margin - arg0 (setup)");
		validate_NULL_TYPETYPE(  arg1, "gtk_page_setup_set_left_margin - arg1 (margin)");
		validate_NULL_TYPETYPE(  arg2, "gtk_page_setup_set_left_margin - arg2 (unit)");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

