// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtkenums.h>
#include <gtk-2.0/gtk/gtk.h>
#undef gtk_icon_size_get_name
static const gchar *(*funcptr) (GtkIconSize ) = 0;

extern int __lsb_check_params;
const gchar * gtk_icon_size_get_name (GtkIconSize arg0 )
{
	int reset_flag = __lsb_check_params;
	const gchar * ret_value  ;
	__lsb_output(4, "Invoking wrapper for gtk_icon_size_get_name()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_icon_size_get_name");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_icon_size_get_name. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_icon_size_get_name() - validating");
		validate_NULL_TYPETYPE(  arg0, "gtk_icon_size_get_name - arg0 (size)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

