// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#include <glib-2.0/glib.h>
#undef gtk_link_button_set_uri_hook
static GtkLinkButtonUriFunc(*funcptr) (GtkLinkButtonUriFunc , gpointer , GDestroyNotify ) = 0;

extern int __lsb_check_params;
GtkLinkButtonUriFunc gtk_link_button_set_uri_hook (GtkLinkButtonUriFunc arg0 , gpointer arg1 , GDestroyNotify arg2 )
{
	int reset_flag = __lsb_check_params;
	GtkLinkButtonUriFunc ret_value  ;
	__lsb_output(4, "Invoking wrapper for gtk_link_button_set_uri_hook()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_link_button_set_uri_hook");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_link_button_set_uri_hook. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_link_button_set_uri_hook() - validating");
		validate_NULL_TYPETYPE(  arg0, "gtk_link_button_set_uri_hook - arg0 (func)");
		validate_NULL_TYPETYPE(  arg1, "gtk_link_button_set_uri_hook - arg1 (data)");
		validate_NULL_TYPETYPE(  arg2, "gtk_link_button_set_uri_hook - arg2 (destroy)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

