// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-2.0/gtk/gtk.h>
#include <glib-2.0/glib.h>
#undef gtk_icon_theme_lookup_icon
static GtkIconInfo *(*funcptr) (GtkIconTheme * , const gchar * , gint , GtkIconLookupFlags ) = 0;

extern int __lsb_check_params;
GtkIconInfo * gtk_icon_theme_lookup_icon (GtkIconTheme * arg0 , const gchar * arg1 , gint arg2 , GtkIconLookupFlags arg3 )
{
	int reset_flag = __lsb_check_params;
	GtkIconInfo * ret_value  ;
	__lsb_output(4, "Invoking wrapper for gtk_icon_theme_lookup_icon()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_icon_theme_lookup_icon");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_icon_theme_lookup_icon. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_icon_theme_lookup_icon() - validating");
		validate_RWaddress( arg0, "gtk_icon_theme_lookup_icon - arg0 (icon_theme)");
		validate_NULL_TYPETYPE(  arg0, "gtk_icon_theme_lookup_icon - arg0 (icon_theme)");
		validate_Rdaddress( arg1, "gtk_icon_theme_lookup_icon - arg1 (icon_name)");
		validate_NULL_TYPETYPE(  arg1, "gtk_icon_theme_lookup_icon - arg1 (icon_name)");
		validate_NULL_TYPETYPE(  arg2, "gtk_icon_theme_lookup_icon - arg2 (size)");
		validate_NULL_TYPETYPE(  arg3, "gtk_icon_theme_lookup_icon - arg3 (flags)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

