// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <cairo/cairo.h>
#undef cairo_mesh_pattern_get_corner_color_rgba
static cairo_status_t(*funcptr) (cairo_pattern_t * , unsigned int , unsigned int , double * , double * , double * , double * ) = 0;

extern int __lsb_check_params;
cairo_status_t cairo_mesh_pattern_get_corner_color_rgba (cairo_pattern_t * arg0 , unsigned int arg1 , unsigned int arg2 , double * arg3 , double * arg4 , double * arg5 , double * arg6 )
{
	int reset_flag = __lsb_check_params;
	cairo_status_t ret_value  ;
	__lsb_output(4, "Invoking wrapper for cairo_mesh_pattern_get_corner_color_rgba()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cairo_mesh_pattern_get_corner_color_rgba");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load cairo_mesh_pattern_get_corner_color_rgba. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "cairo_mesh_pattern_get_corner_color_rgba() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "cairo_mesh_pattern_get_corner_color_rgba - arg0 (pattern)");
		}
		validate_NULL_TYPETYPE(  arg0, "cairo_mesh_pattern_get_corner_color_rgba - arg0 (pattern)");
		validate_NULL_TYPETYPE(  arg1, "cairo_mesh_pattern_get_corner_color_rgba - arg1 (patch_num)");
		validate_NULL_TYPETYPE(  arg2, "cairo_mesh_pattern_get_corner_color_rgba - arg2 (corner_num)");
		if( arg3 ) {
		validate_RWaddress( arg3, "cairo_mesh_pattern_get_corner_color_rgba - arg3 (red)");
		}
		validate_NULL_TYPETYPE(  arg3, "cairo_mesh_pattern_get_corner_color_rgba - arg3 (red)");
		if( arg4 ) {
		validate_RWaddress( arg4, "cairo_mesh_pattern_get_corner_color_rgba - arg4 (green)");
		}
		validate_NULL_TYPETYPE(  arg4, "cairo_mesh_pattern_get_corner_color_rgba - arg4 (green)");
		if( arg5 ) {
		validate_RWaddress( arg5, "cairo_mesh_pattern_get_corner_color_rgba - arg5 (blue)");
		}
		validate_NULL_TYPETYPE(  arg5, "cairo_mesh_pattern_get_corner_color_rgba - arg5 (blue)");
		if( arg6 ) {
		validate_RWaddress( arg6, "cairo_mesh_pattern_get_corner_color_rgba - arg6 (alpha)");
		}
		validate_NULL_TYPETYPE(  arg6, "cairo_mesh_pattern_get_corner_color_rgba - arg6 (alpha)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
	__lsb_check_params = reset_flag;
	return ret_value;
}

