// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <cairo/cairo.h>
#undef cairo_surface_set_device_offset
static void(*funcptr) (cairo_surface_t * , double , double ) = 0;

extern int __lsb_check_params;
void cairo_surface_set_device_offset (cairo_surface_t * arg0 , double arg1 , double arg2 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for cairo_surface_set_device_offset()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cairo_surface_set_device_offset");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load cairo_surface_set_device_offset. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "cairo_surface_set_device_offset() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "cairo_surface_set_device_offset - arg0 (surface)");
		}
		validate_NULL_TYPETYPE(  arg0, "cairo_surface_set_device_offset - arg0 (surface)");
		validate_NULL_TYPETYPE(  arg1, "cairo_surface_set_device_offset - arg1 (x_offset)");
		validate_NULL_TYPETYPE(  arg2, "cairo_surface_set_device_offset - arg2 (y_offset)");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

