GEN_FUNCS = \
cairo_append_path.o \
cairo_arc.o \
cairo_arc_negative.o \
cairo_clip.o \
cairo_clip_preserve.o \
cairo_close_path.o \
cairo_copy_page.o \
cairo_copy_path.o \
cairo_copy_path_flat.o \
cairo_create.o \
cairo_curve_to.o \
cairo_destroy.o \
cairo_device_to_user.o \
cairo_device_to_user_distance.o \
cairo_fill.o \
cairo_fill_extents.o \
cairo_fill_preserve.o \
cairo_font_extents.o \
cairo_font_face_destroy.o \
cairo_font_face_get_type.o \
cairo_font_face_get_user_data.o \
cairo_font_face_reference.o \
cairo_font_face_set_user_data.o \
cairo_font_face_status.o \
cairo_font_options_copy.o \
cairo_font_options_create.o \
cairo_font_options_destroy.o \
cairo_font_options_equal.o \
cairo_font_options_get_antialias.o \
cairo_font_options_get_hint_metrics.o \
cairo_font_options_get_hint_style.o \
cairo_font_options_get_subpixel_order.o \
cairo_font_options_hash.o \
cairo_font_options_merge.o \
cairo_font_options_set_antialias.o \
cairo_font_options_set_hint_metrics.o \
cairo_font_options_set_hint_style.o \
cairo_font_options_set_subpixel_order.o \
cairo_font_options_status.o \
cairo_ft_font_face_create_for_ft_face.o \
cairo_ft_font_face_create_for_pattern.o \
cairo_ft_font_options_substitute.o \
cairo_ft_scaled_font_lock_face.o \
cairo_ft_scaled_font_unlock_face.o \
cairo_get_antialias.o \
cairo_get_current_point.o \
cairo_get_fill_rule.o \
cairo_get_font_face.o \
cairo_get_font_matrix.o \
cairo_get_font_options.o \
cairo_get_group_target.o \
cairo_get_line_cap.o \
cairo_get_line_join.o \
cairo_get_line_width.o \
cairo_get_matrix.o \
cairo_get_miter_limit.o \
cairo_get_operator.o \
cairo_get_source.o \
cairo_get_target.o \
cairo_get_tolerance.o \
cairo_glyph_extents.o \
cairo_glyph_path.o \
cairo_identity_matrix.o \
cairo_image_surface_create.o \
cairo_image_surface_create_for_data.o \
cairo_image_surface_create_from_png.o \
cairo_image_surface_create_from_png_stream.o \
cairo_image_surface_get_data.o \
cairo_image_surface_get_format.o \
cairo_image_surface_get_height.o \
cairo_image_surface_get_stride.o \
cairo_image_surface_get_width.o \
cairo_in_fill.o \
cairo_in_stroke.o \
cairo_line_to.o \
cairo_mask.o \
cairo_mask_surface.o \
cairo_matrix_init.o \
cairo_matrix_init_identity.o \
cairo_matrix_init_rotate.o \
cairo_matrix_init_scale.o \
cairo_matrix_init_translate.o \
cairo_matrix_invert.o \
cairo_matrix_multiply.o \
cairo_matrix_rotate.o \
cairo_matrix_scale.o \
cairo_matrix_transform_distance.o \
cairo_matrix_transform_point.o \
cairo_matrix_translate.o \
cairo_move_to.o \
cairo_new_path.o \
cairo_new_sub_path.o \
cairo_paint.o \
cairo_paint_with_alpha.o \
cairo_path_destroy.o \
cairo_pattern_add_color_stop_rgb.o \
cairo_pattern_add_color_stop_rgba.o \
cairo_pattern_create_for_surface.o \
cairo_pattern_create_linear.o \
cairo_pattern_create_radial.o \
cairo_pattern_create_rgb.o \
cairo_pattern_create_rgba.o \
cairo_pattern_destroy.o \
cairo_pattern_get_extend.o \
cairo_pattern_get_filter.o \
cairo_pattern_get_matrix.o \
cairo_pattern_get_type.o \
cairo_pattern_reference.o \
cairo_pattern_set_extend.o \
cairo_pattern_set_filter.o \
cairo_pattern_set_matrix.o \
cairo_pattern_status.o \
cairo_pdf_surface_create.o \
cairo_pdf_surface_create_for_stream.o \
cairo_pdf_surface_set_size.o \
cairo_pop_group.o \
cairo_pop_group_to_source.o \
cairo_ps_surface_create.o \
cairo_ps_surface_create_for_stream.o \
cairo_ps_surface_dsc_begin_page_setup.o \
cairo_ps_surface_dsc_begin_setup.o \
cairo_ps_surface_dsc_comment.o \
cairo_ps_surface_set_size.o \
cairo_push_group.o \
cairo_push_group_with_content.o \
cairo_rectangle.o \
cairo_reference.o \
cairo_rel_curve_to.o \
cairo_rel_line_to.o \
cairo_rel_move_to.o \
cairo_reset_clip.o \
cairo_restore.o \
cairo_rotate.o \
cairo_save.o \
cairo_scale.o \
cairo_scaled_font_create.o \
cairo_scaled_font_destroy.o \
cairo_scaled_font_extents.o \
cairo_scaled_font_get_ctm.o \
cairo_scaled_font_get_font_face.o \
cairo_scaled_font_get_font_matrix.o \
cairo_scaled_font_get_font_options.o \
cairo_scaled_font_get_type.o \
cairo_scaled_font_glyph_extents.o \
cairo_scaled_font_reference.o \
cairo_scaled_font_status.o \
cairo_scaled_font_text_extents.o \
cairo_select_font_face.o \
cairo_set_antialias.o \
cairo_set_dash.o \
cairo_set_fill_rule.o \
cairo_set_font_face.o \
cairo_set_font_matrix.o \
cairo_set_font_options.o \
cairo_set_font_size.o \
cairo_set_line_cap.o \
cairo_set_line_join.o \
cairo_set_line_width.o \
cairo_set_matrix.o \
cairo_set_miter_limit.o \
cairo_set_operator.o \
cairo_set_scaled_font.o \
cairo_set_source.o \
cairo_set_source_rgb.o \
cairo_set_source_rgba.o \
cairo_set_source_surface.o \
cairo_set_tolerance.o \
cairo_show_glyphs.o \
cairo_show_page.o \
cairo_show_text.o \
cairo_status.o \
cairo_status_to_string.o \
cairo_stroke.o \
cairo_stroke_extents.o \
cairo_stroke_preserve.o \
cairo_surface_create_similar.o \
cairo_surface_destroy.o \
cairo_surface_finish.o \
cairo_surface_flush.o \
cairo_surface_get_content.o \
cairo_surface_get_device_offset.o \
cairo_surface_get_font_options.o \
cairo_surface_get_type.o \
cairo_surface_get_user_data.o \
cairo_surface_mark_dirty.o \
cairo_surface_mark_dirty_rectangle.o \
cairo_surface_reference.o \
cairo_surface_set_device_offset.o \
cairo_surface_set_fallback_resolution.o \
cairo_surface_set_user_data.o \
cairo_surface_status.o \
cairo_surface_write_to_png.o \
cairo_surface_write_to_png_stream.o \
cairo_svg_get_versions.o \
cairo_svg_surface_create.o \
cairo_svg_surface_create_for_stream.o \
cairo_svg_surface_restrict_to_version.o \
cairo_svg_version_to_string.o \
cairo_text_extents.o \
cairo_text_path.o \
cairo_transform.o \
cairo_translate.o \
cairo_user_to_device.o \
cairo_user_to_device_distance.o \
cairo_version.o \
cairo_version_string.o \
cairo_xlib_surface_create.o \
cairo_xlib_surface_create_for_bitmap.o \
cairo_xlib_surface_create_with_xrender_format.o \
cairo_xlib_surface_get_depth.o \
cairo_xlib_surface_get_display.o \
cairo_xlib_surface_get_drawable.o \
cairo_xlib_surface_get_height.o \
cairo_xlib_surface_get_screen.o \
cairo_xlib_surface_get_visual.o \
cairo_xlib_surface_get_width.o \
cairo_xlib_surface_set_drawable.o \
cairo_xlib_surface_set_size.o 