GEN_FUNCS = \
gluBeginCurve.o \
gluBeginPolygon.o \
gluBeginSurface.o \
gluBeginTrim.o \
gluBuild1DMipmapLevels.o \
gluBuild1DMipmaps.o \
gluBuild2DMipmapLevels.o \
gluBuild2DMipmaps.o \
gluBuild3DMipmapLevels.o \
gluBuild3DMipmaps.o \
gluCheckExtension.o \
gluCylinder.o \
gluDeleteNurbsRenderer.o \
gluDeleteQuadric.o \
gluDeleteTess.o \
gluDisk.o \
gluEndCurve.o \
gluEndPolygon.o \
gluEndSurface.o \
gluEndTrim.o \
gluErrorString.o \
gluGetNurbsProperty.o \
gluGetString.o \
gluGetTessProperty.o \
gluLoadSamplingMatrices.o \
gluLookAt.o \
gluNewNurbsRenderer.o \
gluNewQuadric.o \
gluNewTess.o \
gluNextContour.o \
gluNurbsCallback.o \
gluNurbsCallbackData.o \
gluNurbsCallbackDataEXT.o \
gluNurbsCurve.o \
gluNurbsProperty.o \
gluNurbsSurface.o \
gluOrtho2D.o \
gluPartialDisk.o \
gluPerspective.o \
gluPickMatrix.o \
gluProject.o \
gluPwlCurve.o \
gluQuadricCallback.o \
gluQuadricDrawStyle.o \
gluQuadricNormals.o \
gluQuadricOrientation.o \
gluQuadricTexture.o \
gluScaleImage.o \
gluSphere.o \
gluTessBeginContour.o \
gluTessBeginPolygon.o \
gluTessCallback.o \
gluTessEndContour.o \
gluTessEndPolygon.o \
gluTessNormal.o \
gluTessProperty.o \
gluTessVertex.o \
gluUnProject.o \
gluUnProject4.o 