// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#include <GL/glu.h>
#undef gluGetString
static const GLubyte *(*funcptr) (GLenum ) = 0;

extern int __lsb_check_params;
const GLubyte * gluGetString (GLenum arg0 )
{
	int reset_flag = __lsb_check_params;
	const GLubyte * ret_value  ;
	__lsb_output(4, "Invoking wrapper for gluGetString()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gluGetString");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gluGetString. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gluGetString() - validating");
		validate_NULL_TYPETYPE(  arg0, "gluGetString - arg0 (name)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

