GEN_FUNCS = \
glAccum.o \
glAlphaFunc.o \
glAreTexturesResident.o \
glArrayElement.o \
glBegin.o \
glBindTexture.o \
glBitmap.o \
glBlendFunc.o \
glCallList.o \
glCallLists.o \
glClear.o \
glClearAccum.o \
glClearColor.o \
glClearDepth.o \
glClearIndex.o \
glClearStencil.o \
glClipPlane.o \
glColor3b.o \
glColor3bv.o \
glColor3d.o \
glColor3dv.o \
glColor3f.o \
glColor3fv.o \
glColor3i.o \
glColor3iv.o \
glColor3s.o \
glColor3sv.o \
glColor3ub.o \
glColor3ubv.o \
glColor3ui.o \
glColor3uiv.o \
glColor3us.o \
glColor3usv.o \
glColor4b.o \
glColor4bv.o \
glColor4d.o \
glColor4dv.o \
glColor4f.o \
glColor4fv.o \
glColor4i.o \
glColor4iv.o \
glColor4s.o \
glColor4sv.o \
glColor4ub.o \
glColor4ubv.o \
glColor4ui.o \
glColor4uiv.o \
glColor4us.o \
glColor4usv.o \
glColorMask.o \
glColorMaterial.o \
glColorPointer.o \
glCopyPixels.o \
glCopyTexImage1D.o \
glCopyTexImage2D.o \
glCopyTexSubImage1D.o \
glCopyTexSubImage2D.o \
glCullFace.o \
glDeleteLists.o \
glDeleteTextures.o \
glDepthFunc.o \
glDepthMask.o \
glDepthRange.o \
glDisable.o \
glDisableClientState.o \
glDrawArrays.o \
glDrawBuffer.o \
glDrawElements.o \
glDrawPixels.o \
glEdgeFlag.o \
glEdgeFlagPointer.o \
glEdgeFlagv.o \
glEnable.o \
glEnableClientState.o \
glEnd.o \
glEndList.o \
glEvalCoord1d.o \
glEvalCoord1dv.o \
glEvalCoord1f.o \
glEvalCoord1fv.o \
glEvalCoord2d.o \
glEvalCoord2dv.o \
glEvalCoord2f.o \
glEvalCoord2fv.o \
glEvalMesh1.o \
glEvalMesh2.o \
glEvalPoint1.o \
glEvalPoint2.o \
glFeedbackBuffer.o \
glFinish.o \
glFlush.o \
glFogf.o \
glFogfv.o \
glFogi.o \
glFogiv.o \
glFrontFace.o \
glFrustum.o \
glGenLists.o \
glGenTextures.o \
glGetBooleanv.o \
glGetClipPlane.o \
glGetDoublev.o \
glGetError.o \
glGetFloatv.o \
glGetIntegerv.o \
glGetLightfv.o \
glGetLightiv.o \
glGetMapdv.o \
glGetMapfv.o \
glGetMapiv.o \
glGetMaterialfv.o \
glGetMaterialiv.o \
glGetPixelMapfv.o \
glGetPixelMapuiv.o \
glGetPixelMapusv.o \
glGetPointerv.o \
glGetPolygonStipple.o \
glGetString.o \
glGetTexEnvfv.o \
glGetTexEnviv.o \
glGetTexGendv.o \
glGetTexGenfv.o \
glGetTexGeniv.o \
glGetTexImage.o \
glGetTexLevelParameterfv.o \
glGetTexLevelParameteriv.o \
glGetTexParameterfv.o \
glGetTexParameteriv.o \
glHint.o \
glIndexMask.o \
glIndexPointer.o \
glIndexd.o \
glIndexdv.o \
glIndexf.o \
glIndexfv.o \
glIndexi.o \
glIndexiv.o \
glIndexs.o \
glIndexsv.o \
glIndexub.o \
glIndexubv.o \
glInitNames.o \
glInterleavedArrays.o \
glIsEnabled.o \
glIsList.o \
glIsTexture.o \
glLightModelf.o \
glLightModelfv.o \
glLightModeli.o \
glLightModeliv.o \
glLightf.o \
glLightfv.o \
glLighti.o \
glLightiv.o \
glLineStipple.o \
glLineWidth.o \
glListBase.o \
glLoadIdentity.o \
glLoadMatrixd.o \
glLoadMatrixf.o \
glLoadName.o \
glLogicOp.o \
glMap1d.o \
glMap1f.o \
glMap2d.o \
glMap2f.o \
glMapGrid1d.o \
glMapGrid1f.o \
glMapGrid2d.o \
glMapGrid2f.o \
glMaterialf.o \
glMaterialfv.o \
glMateriali.o \
glMaterialiv.o \
glMatrixMode.o \
glMultMatrixd.o \
glMultMatrixf.o \
glNewList.o \
glNormal3b.o \
glNormal3bv.o \
glNormal3d.o \
glNormal3dv.o \
glNormal3f.o \
glNormal3fv.o \
glNormal3i.o \
glNormal3iv.o \
glNormal3s.o \
glNormal3sv.o \
glNormalPointer.o \
glOrtho.o \
glPassThrough.o \
glPixelMapfv.o \
glPixelMapuiv.o \
glPixelMapusv.o \
glPixelStoref.o \
glPixelStorei.o \
glPixelTransferf.o \
glPixelTransferi.o \
glPixelZoom.o \
glPointSize.o \
glPolygonMode.o \
glPolygonOffset.o \
glPolygonStipple.o \
glPopAttrib.o \
glPopClientAttrib.o \
glPopMatrix.o \
glPopName.o \
glPrioritizeTextures.o \
glPushAttrib.o \
glPushClientAttrib.o \
glPushMatrix.o \
glPushName.o \
glRasterPos2d.o \
glRasterPos2dv.o \
glRasterPos2f.o \
glRasterPos2fv.o \
glRasterPos2i.o \
glRasterPos2iv.o \
glRasterPos2s.o \
glRasterPos2sv.o \
glRasterPos3d.o \
glRasterPos3dv.o \
glRasterPos3f.o \
glRasterPos3fv.o \
glRasterPos3i.o \
glRasterPos3iv.o \
glRasterPos3s.o \
glRasterPos3sv.o \
glRasterPos4d.o \
glRasterPos4dv.o \
glRasterPos4f.o \
glRasterPos4fv.o \
glRasterPos4i.o \
glRasterPos4iv.o \
glRasterPos4s.o \
glRasterPos4sv.o \
glReadBuffer.o \
glReadPixels.o \
glRectd.o \
glRectdv.o \
glRectf.o \
glRectfv.o \
glRecti.o \
glRectiv.o \
glRects.o \
glRectsv.o \
glRenderMode.o \
glRotated.o \
glRotatef.o \
glScaled.o \
glScalef.o \
glScissor.o \
glSelectBuffer.o \
glShadeModel.o \
glStencilFunc.o \
glStencilMask.o \
glStencilOp.o \
glTexCoord1d.o \
glTexCoord1dv.o \
glTexCoord1f.o \
glTexCoord1fv.o \
glTexCoord1i.o \
glTexCoord1iv.o \
glTexCoord1s.o \
glTexCoord1sv.o \
glTexCoord2d.o \
glTexCoord2dv.o \
glTexCoord2f.o \
glTexCoord2fv.o \
glTexCoord2i.o \
glTexCoord2iv.o \
glTexCoord2s.o \
glTexCoord2sv.o \
glTexCoord3d.o \
glTexCoord3dv.o \
glTexCoord3f.o \
glTexCoord3fv.o \
glTexCoord3i.o \
glTexCoord3iv.o \
glTexCoord3s.o \
glTexCoord3sv.o \
glTexCoord4d.o \
glTexCoord4dv.o \
glTexCoord4f.o \
glTexCoord4fv.o \
glTexCoord4i.o \
glTexCoord4iv.o \
glTexCoord4s.o \
glTexCoord4sv.o \
glTexCoordPointer.o \
glTexEnvf.o \
glTexEnvfv.o \
glTexEnvi.o \
glTexEnviv.o \
glTexGend.o \
glTexGendv.o \
glTexGenf.o \
glTexGenfv.o \
glTexGeni.o \
glTexGeniv.o \
glTexImage1D.o \
glTexImage2D.o \
glTexParameterf.o \
glTexParameterfv.o \
glTexParameteri.o \
glTexParameteriv.o \
glTexSubImage1D.o \
glTexSubImage2D.o \
glTranslated.o \
glTranslatef.o \
glVertex2d.o \
glVertex2dv.o \
glVertex2f.o \
glVertex2fv.o \
glVertex2i.o \
glVertex2iv.o \
glVertex2s.o \
glVertex2sv.o \
glVertex3d.o \
glVertex3dv.o \
glVertex3f.o \
glVertex3fv.o \
glVertex3i.o \
glVertex3iv.o \
glVertex3s.o \
glVertex3sv.o \
glVertex4d.o \
glVertex4dv.o \
glVertex4f.o \
glVertex4fv.o \
glVertex4i.o \
glVertex4iv.o \
glVertex4s.o \
glVertex4sv.o \
glVertexPointer.o \
glViewport.o \
glXChooseVisual.o \
glXCopyContext.o \
glXCreateContext.o \
glXCreateGLXPixmap.o \
glXDestroyContext.o \
glXDestroyGLXPixmap.o \
glXFreeContextEXT.o \
glXGetClientString.o \
glXGetConfig.o \
glXGetContextIDEXT.o \
glXGetCurrentContext.o \
glXGetCurrentDisplay.o \
glXGetCurrentDrawable.o \
glXImportContextEXT.o \
glXIsDirect.o \
glXMakeCurrent.o \
glXQueryContextInfoEXT.o \
glXQueryExtension.o \
glXQueryExtensionsString.o \
glXQueryServerString.o \
glXQueryVersion.o \
glXSwapBuffers.o \
glXUseXFont.o \
glXWaitGL.o \
glXWaitX.o \
glDrawRangeElements.o \
glTexImage3D.o \
glTexSubImage3D.o \
glCopyTexSubImage3D.o \
glColorTable.o \
glColorSubTable.o \
glColorTableParameteriv.o \
glColorTableParameterfv.o \
glCopyColorSubTable.o \
glCopyColorTable.o \
glGetColorTable.o \
glGetColorTableParameterfv.o \
glGetColorTableParameteriv.o \
glBlendEquation.o \
glBlendColor.o \
glHistogram.o \
glResetHistogram.o \
glGetHistogram.o \
glGetHistogramParameterfv.o \
glGetHistogramParameteriv.o \
glMinmax.o \
glResetMinmax.o \
glGetMinmax.o \
glGetMinmaxParameterfv.o \
glGetMinmaxParameteriv.o \
glConvolutionFilter1D.o \
glConvolutionFilter2D.o \
glConvolutionParameterf.o \
glConvolutionParameterfv.o \
glConvolutionParameteri.o \
glConvolutionParameteriv.o \
glCopyConvolutionFilter1D.o \
glCopyConvolutionFilter2D.o \
glGetConvolutionFilter.o \
glGetConvolutionParameterfv.o \
glGetConvolutionParameteriv.o \
glSeparableFilter2D.o \
glGetSeparableFilter.o \
glActiveTextureARB.o \
glClientActiveTextureARB.o \
glMultiTexCoord1dARB.o \
glMultiTexCoord1dvARB.o \
glMultiTexCoord1fARB.o \
glMultiTexCoord1fvARB.o \
glMultiTexCoord1iARB.o \
glMultiTexCoord1ivARB.o \
glMultiTexCoord1sARB.o \
glMultiTexCoord1svARB.o \
glMultiTexCoord2dARB.o \
glMultiTexCoord2dvARB.o \
glMultiTexCoord2fARB.o \
glMultiTexCoord2fvARB.o \
glMultiTexCoord2iARB.o \
glMultiTexCoord2ivARB.o \
glMultiTexCoord2sARB.o \
glMultiTexCoord2svARB.o \
glMultiTexCoord3dARB.o \
glMultiTexCoord3dvARB.o \
glMultiTexCoord3fARB.o \
glMultiTexCoord3fvARB.o \
glMultiTexCoord3iARB.o \
glMultiTexCoord3ivARB.o \
glMultiTexCoord3sARB.o \
glMultiTexCoord3svARB.o \
glMultiTexCoord4dARB.o \
glMultiTexCoord4dvARB.o \
glMultiTexCoord4fARB.o \
glMultiTexCoord4fvARB.o \
glMultiTexCoord4iARB.o \
glMultiTexCoord4ivARB.o \
glMultiTexCoord4sARB.o \
glMultiTexCoord4svARB.o \
glXChooseFBConfig.o \
glXGetFBConfigAttrib.o \
glXGetVisualFromFBConfig.o \
glXCreateWindow.o \
glXDestroyWindow.o \
glXCreatePixmap.o \
glXDestroyPixmap.o \
glXCreatePbuffer.o \
glXDestroyPbuffer.o \
glXQueryDrawable.o \
glXCreateNewContext.o \
glXMakeContextCurrent.o \
glXGetCurrentReadDrawable.o \
glXQueryContext.o \
glXSelectEvent.o \
glXGetSelectedEvent.o \
glXGetProcAddressARB.o 