// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
static int(*funcptr)(GLenum) = 0;

void glActiveTextureARB(GLenum arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glActiveTextureARB");
	validate_NULL_TYPETYPE(arg0, "glActiveTextureARB");
	return funcptr(arg0);
}

void lsb_glActiveTextureARB(GLenum arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glActiveTextureARB");
	return funcptr(arg0);
}

