// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#undef glBlendColor
static void(*funcptr) (GLclampf , GLclampf , GLclampf , GLclampf ) = 0;

extern int __lsb_check_params;
void glBlendColor (GLclampf arg0 , GLclampf arg1 , GLclampf arg2 , GLclampf arg3 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glBlendColor()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glBlendColor");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glBlendColor. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glBlendColor() - validating");
		validate_NULL_TYPETYPE(  arg0, "glBlendColor - arg0 (red)");
		validate_NULL_TYPETYPE(  arg1, "glBlendColor - arg1 (green)");
		validate_NULL_TYPETYPE(  arg2, "glBlendColor - arg2 (blue)");
		validate_NULL_TYPETYPE(  arg3, "glBlendColor - arg3 (alpha)");
	}
	funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
}

