// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#undef glCopyColorSubTable
static void(*funcptr) (GLenum , GLsizei , GLint , GLint , GLsizei ) = 0;

extern int __lsb_check_params;
void glCopyColorSubTable (GLenum arg0 , GLsizei arg1 , GLint arg2 , GLint arg3 , GLsizei arg4 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glCopyColorSubTable()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glCopyColorSubTable");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glCopyColorSubTable. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glCopyColorSubTable() - validating");
		validate_NULL_TYPETYPE(  arg0, "glCopyColorSubTable - arg0 (target)");
		validate_NULL_TYPETYPE(  arg1, "glCopyColorSubTable - arg1 (start)");
		validate_NULL_TYPETYPE(  arg2, "glCopyColorSubTable - arg2 (x)");
		validate_NULL_TYPETYPE(  arg3, "glCopyColorSubTable - arg3 (y)");
		validate_NULL_TYPETYPE(  arg4, "glCopyColorSubTable - arg4 (width)");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
}

