// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#undef glCopyConvolutionFilter1D
static void(*funcptr) (GLenum , GLenum , GLint , GLint , GLsizei ) = 0;

extern int __lsb_check_params;
void glCopyConvolutionFilter1D (GLenum arg0 , GLenum arg1 , GLint arg2 , GLint arg3 , GLsizei arg4 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glCopyConvolutionFilter1D()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glCopyConvolutionFilter1D");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glCopyConvolutionFilter1D. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glCopyConvolutionFilter1D() - validating");
		validate_NULL_TYPETYPE(  arg0, "glCopyConvolutionFilter1D - arg0 (target)");
		validate_NULL_TYPETYPE(  arg1, "glCopyConvolutionFilter1D - arg1 (internalformat)");
		validate_NULL_TYPETYPE(  arg2, "glCopyConvolutionFilter1D - arg2 (x)");
		validate_NULL_TYPETYPE(  arg3, "glCopyConvolutionFilter1D - arg3 (y)");
		validate_NULL_TYPETYPE(  arg4, "glCopyConvolutionFilter1D - arg4 (width)");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
}

