// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#undef glColorMask
static void(*funcptr) (GLboolean , GLboolean , GLboolean , GLboolean ) = 0;

extern int __lsb_check_params;
void glColorMask (GLboolean arg0 , GLboolean arg1 , GLboolean arg2 , GLboolean arg3 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glColorMask()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glColorMask");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glColorMask. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glColorMask() - validating");
		validate_NULL_TYPETYPE(  arg0, "glColorMask - arg0 (red)");
		validate_NULL_TYPETYPE(  arg1, "glColorMask - arg1 (green)");
		validate_NULL_TYPETYPE(  arg2, "glColorMask - arg2 (blue)");
		validate_NULL_TYPETYPE(  arg3, "glColorMask - arg3 (alpha)");
	}
	funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
}

