// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <GL/gl.h>
#undef glDisableClientState
static void(*funcptr) (GLenum ) = 0;

extern int __lsb_check_params;
void glDisableClientState (GLenum arg0 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " glDisableClientState ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "glDisableClientState()");
		validate_NULL_TYPETYPE(  arg0, "glDisableClientState - arg0");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

