// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
#undef glGetMinmaxParameterfv
static void(*funcptr) (GLenum , GLenum , GLfloat * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void glGetMinmaxParameterfv (GLenum arg0 , GLenum arg1 , GLfloat * arg2 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glGetMinmaxParameterfv");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "glGetMinmaxParameterfv()");
		validate_NULL_TYPETYPE(  arg0, "glGetMinmaxParameterfv - arg0");
		validate_NULL_TYPETYPE(  arg1, "glGetMinmaxParameterfv - arg1");
	validate_RWaddress( arg2, "glGetMinmaxParameterfv - arg2");
		validate_NULL_TYPETYPE(  arg2, "glGetMinmaxParameterfv - arg2");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

