// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#undef glInterleavedArrays
static void(*funcptr) (GLenum , GLsizei , const GLvoid * ) = 0;

extern int __lsb_check_params;
void glInterleavedArrays (GLenum arg0 , GLsizei arg1 , const GLvoid * arg2 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glInterleavedArrays()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glInterleavedArrays");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glInterleavedArrays. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glInterleavedArrays() - validating");
		validate_NULL_TYPETYPE(  arg0, "glInterleavedArrays - arg0 (format)");
		validate_NULL_TYPETYPE(  arg1, "glInterleavedArrays - arg1 (stride)");
		validate_Rdaddress( arg2, "glInterleavedArrays - arg2 (pointer)");
		validate_NULL_TYPETYPE(  arg2, "glInterleavedArrays - arg2 (pointer)");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

