// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
#undef glLightModelf
static void(*funcptr) (GLenum , GLfloat ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void glLightModelf (GLenum arg0 , GLfloat arg1 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glLightModelf");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "glLightModelf()");
		validate_NULL_TYPETYPE(  arg0, "glLightModelf - arg0");
		validate_NULL_TYPETYPE(  arg1, "glLightModelf - arg1");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

