// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
static int(*funcptr)(GLenum, GLfloat *) = 0;

void glMultiTexCoord3fvARB(GLenum arg0, GLfloat * arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glMultiTexCoord3fvARB");
	validate_NULL_TYPETYPE(arg0, "glMultiTexCoord3fvARB");
	validate_NULL_TYPETYPE(arg1, "glMultiTexCoord3fvARB");
	return funcptr(arg0, arg1);
}

void __lsb_glMultiTexCoord3fvARB(GLenum arg0, GLfloat * arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glMultiTexCoord3fvARB");
	return funcptr(arg0, arg1);
}

