// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#undef glMultiTexCoord2d
static void(*funcptr) (GLenum , GLdouble , GLdouble ) = 0;

extern int __lsb_check_params;
void glMultiTexCoord2d (GLenum arg0 , GLdouble arg1 , GLdouble arg2 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glMultiTexCoord2d()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glMultiTexCoord2d");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glMultiTexCoord2d. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glMultiTexCoord2d() - validating");
		validate_NULL_TYPETYPE(  arg0, "glMultiTexCoord2d - arg0 (target)");
		validate_NULL_TYPETYPE(  arg1, "glMultiTexCoord2d - arg1 (s)");
		validate_NULL_TYPETYPE(  arg2, "glMultiTexCoord2d - arg2 (t)");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

