// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
#include <GL/gl.h>
static int(*funcptr)(GLenum, GLsizei, GLvoid *) = 0;

void glNormalPointer(GLenum arg0, GLsizei arg1, GLvoid * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glNormalPointer");
	validate_NULL_TYPETYPE(arg0, "glNormalPointer");
	validate_NULL_TYPETYPE(arg1, "glNormalPointer");
	validate_NULL_TYPETYPE(arg2, "glNormalPointer");
	return funcptr(arg0, arg1, arg2);
}

void lsb_glNormalPointer(GLenum arg0, GLsizei arg1, GLvoid * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glNormalPointer");
	return funcptr(arg0, arg1, arg2);
}

