// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(GLdouble *) = 0;

void glRasterPos4dv(GLdouble * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glRasterPos4dv");
	validate_NULL_TYPETYPE(arg0, "glRasterPos4dv");
	return funcptr(arg0);
}

void lsb_glRasterPos4dv(GLdouble * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glRasterPos4dv");
	return funcptr(arg0);
}

