// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
#include <GL/gl.h>
#include <GL/gl.h>
#include <GL/gl.h>
static int(*funcptr)(GLint, GLint, GLsizei, GLsizei) = 0;

void glScissor(GLint arg0, GLint arg1, GLsizei arg2, GLsizei arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glScissor");
	validate_NULL_TYPETYPE(arg0, "glScissor");
	validate_NULL_TYPETYPE(arg1, "glScissor");
	validate_NULL_TYPETYPE(arg2, "glScissor");
	validate_NULL_TYPETYPE(arg3, "glScissor");
	return funcptr(arg0, arg1, arg2, arg3);
}

void lsb_glScissor(GLint arg0, GLint arg1, GLsizei arg2, GLsizei arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glScissor");
	return funcptr(arg0, arg1, arg2, arg3);
}

