// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <GL/gl.h>
#include <GL/glext.h>
#undef glSecondaryColor3usv
static void(*funcptr) (const GLushort * ) = 0;

extern int __lsb_check_params;
void glSecondaryColor3usv (const GLushort * arg0 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for glSecondaryColor3usv()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glSecondaryColor3usv");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glSecondaryColor3usv. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glSecondaryColor3usv() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "glSecondaryColor3usv - arg0");
		}
		validate_NULL_TYPETYPE(  arg0, "glSecondaryColor3usv - arg0");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

