// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <GL/gl.h>
#undef glTexCoord2fv
static void(*funcptr) (GLfloat * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void glTexCoord2fv (GLfloat * arg0 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glTexCoord2fv");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "glTexCoord2fv()");
	validate_RWaddress( arg0, "glTexCoord2fv - arg0");
		validate_NULL_TYPETYPE(  arg0, "glTexCoord2fv - arg0");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

