// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, XVisualInfo *, Pixmap) = 0;

GLXPixmap glXCreateGLXPixmap(Display * arg0, XVisualInfo * arg1, Pixmap arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXCreateGLXPixmap");
	validate_NULL_TYPETYPE(arg0, "glXCreateGLXPixmap");
	validate_NULL_TYPETYPE(arg1, "glXCreateGLXPixmap");
	validate_NULL_TYPETYPE(arg2, "glXCreateGLXPixmap");
	return funcptr(arg0, arg1, arg2);
}

GLXPixmap lsb_glXCreateGLXPixmap(Display * arg0, XVisualInfo * arg1, Pixmap arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXCreateGLXPixmap");
	return funcptr(arg0, arg1, arg2);
}

