// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <GL/glx.h>
static int(*funcptr)(Display *, GLXPixmap) = 0;

void glXDestroyPixmap(Display * arg0, GLXPixmap arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXDestroyPixmap");
	validate_NULL_TYPETYPE(arg0, "glXDestroyPixmap");
	validate_NULL_TYPETYPE(arg1, "glXDestroyPixmap");
	return funcptr(arg0, arg1);
}

void lsb_glXDestroyPixmap(Display * arg0, GLXPixmap arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXDestroyPixmap");
	return funcptr(arg0, arg1);
}

