// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(void) = 0;

GLXDrawable glXGetCurrentReadDrawable(void arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXGetCurrentReadDrawable");
	validate_NULL_TYPETYPE(arg0, "glXGetCurrentReadDrawable");
	return funcptr(arg0);
}

GLXDrawable lsb_glXGetCurrentReadDrawable(void arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXGetCurrentReadDrawable");
	return funcptr(arg0);
}

