// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <GL/glx.h>
#undef glXQueryContext
static int(*funcptr) (Display * , GLXContext , int , int * ) = 0;

extern int __lsb_check_params;
int glXQueryContext (Display * arg0 , GLXContext arg1 , int arg2 , int * arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for glXQueryContext()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "glXQueryContext");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load glXQueryContext. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "glXQueryContext() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "glXQueryContext - arg0 (dpy)");
		}
		validate_NULL_TYPETYPE(  arg0, "glXQueryContext - arg0 (dpy)");
		validate_NULL_TYPETYPE(  arg1, "glXQueryContext - arg1 (ctx)");
		validate_NULL_TYPETYPE(  arg2, "glXQueryContext - arg2 (attribute)");
		if( arg3 ) {
		validate_RWaddress( arg3, "glXQueryContext - arg3 (value)");
		}
		validate_NULL_TYPETYPE(  arg3, "glXQueryContext - arg3 (value)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

