GEN_FUNCS = \
jpeg_CreateCompress.o \
jpeg_CreateDecompress.o \
jpeg_abort.o \
jpeg_abort_compress.o \
jpeg_abort_decompress.o \
jpeg_add_quant_table.o \
jpeg_alloc_huff_table.o \
jpeg_alloc_quant_table.o \
jpeg_calc_output_dimensions.o \
jpeg_consume_input.o \
jpeg_copy_critical_parameters.o \
jpeg_default_colorspace.o \
jpeg_destroy.o \
jpeg_destroy_compress.o \
jpeg_destroy_decompress.o \
jpeg_finish_compress.o \
jpeg_finish_decompress.o \
jpeg_finish_output.o \
jpeg_has_multiple_scans.o \
jpeg_input_complete.o \
jpeg_new_colormap.o \
jpeg_quality_scaling.o \
jpeg_read_coefficients.o \
jpeg_read_header.o \
jpeg_read_raw_data.o \
jpeg_read_scanlines.o \
jpeg_resync_to_restart.o \
jpeg_save_markers.o \
jpeg_set_colorspace.o \
jpeg_set_defaults.o \
jpeg_set_linear_quality.o \
jpeg_set_marker_processor.o \
jpeg_set_quality.o \
jpeg_simple_progression.o \
jpeg_start_compress.o \
jpeg_start_decompress.o \
jpeg_start_output.o \
jpeg_std_error.o \
jpeg_stdio_dest.o \
jpeg_stdio_src.o \
jpeg_suppress_tables.o \
jpeg_write_coefficients.o \
jpeg_write_m_byte.o \
jpeg_write_m_header.o \
jpeg_write_marker.o \
jpeg_write_raw_data.o \
jpeg_write_scanlines.o \
jpeg_write_tables.o 