GEN_FUNCS = \
LogL10fromY.o \
LogL10toY.o \
LogL16fromY.o \
LogL16toY.o \
LogLuv24fromXYZ.o \
LogLuv24toXYZ.o \
LogLuv32fromXYZ.o \
LogLuv32toXYZ.o \
TIFFAccessTagMethods.o \
TIFFCIELabToRGBInit.o \
TIFFCIELabToXYZ.o \
TIFFCheckTile.o \
TIFFCheckpointDirectory.o \
TIFFCleanup.o \
TIFFClientOpen.o \
TIFFClientdata.o \
TIFFClose.o \
TIFFComputeStrip.o \
TIFFComputeTile.o \
TIFFCreateCustomDirectory.o \
TIFFCreateDirectory.o \
TIFFCreateEXIFDirectory.o \
TIFFCurrentDirOffset.o \
TIFFCurrentDirectory.o \
TIFFCurrentRow.o \
TIFFCurrentStrip.o \
TIFFCurrentTile.o \
TIFFDataWidth.o \
TIFFDefaultStripSize.o \
TIFFDefaultTileSize.o \
TIFFFdOpen.o \
TIFFFieldWithName.o \
TIFFFieldWithTag.o \
TIFFFileName.o \
TIFFFileno.o \
TIFFFindCODEC.o \
TIFFFindField.o \
TIFFFlush.o \
TIFFFlushData.o \
TIFFFreeDirectory.o \
TIFFGetBitRevTable.o \
TIFFGetClientInfo.o \
TIFFGetCloseProc.o \
TIFFGetConfiguredCODECs.o \
TIFFGetMapFileProc.o \
TIFFGetMode.o \
TIFFGetReadProc.o \
TIFFGetSeekProc.o \
TIFFGetSizeProc.o \
TIFFGetTagListCount.o \
TIFFGetTagListEntry.o \
TIFFGetUnmapFileProc.o \
TIFFGetVersion.o \
TIFFGetWriteProc.o \
TIFFIsBigEndian.o \
TIFFIsByteSwapped.o \
TIFFIsCODECConfigured.o \
TIFFIsMSB2LSB.o \
TIFFIsTiled.o \
TIFFIsUpSampled.o \
TIFFLastDirectory.o \
TIFFNumberOfDirectories.o \
TIFFNumberOfStrips.o \
TIFFNumberOfTiles.o \
TIFFOpen.o \
TIFFPrintDirectory.o \
TIFFRGBAImageBegin.o \
TIFFRGBAImageEnd.o \
TIFFRGBAImageGet.o \
TIFFRGBAImageOK.o \
TIFFRasterScanlineSize.o \
TIFFRasterScanlineSize64.o \
TIFFRawStripSize.o \
TIFFRawStripSize64.o \
TIFFReadBufferSetup.o \
TIFFReadCustomDirectory.o \
TIFFReadDirectory.o \
TIFFReadEXIFDirectory.o \
TIFFReadEncodedStrip.o \
TIFFReadEncodedTile.o \
TIFFReadRGBAImage.o \
TIFFReadRGBAImageOriented.o \
TIFFReadRGBAStrip.o \
TIFFReadRGBATile.o \
TIFFReadRawStrip.o \
TIFFReadRawTile.o \
TIFFReadScanline.o \
TIFFReadTile.o \
TIFFRegisterCODEC.o \
TIFFReverseBits.o \
TIFFRewriteDirectory.o \
TIFFScanlineSize.o \
TIFFScanlineSize64.o \
TIFFSetClientInfo.o \
TIFFSetClientdata.o \
TIFFSetDirectory.o \
TIFFSetErrorHandler.o \
TIFFSetErrorHandlerExt.o \
TIFFSetFileName.o \
TIFFSetFileno.o \
TIFFSetMode.o \
TIFFSetSubDirectory.o \
TIFFSetTagExtender.o \
TIFFSetWarningHandler.o \
TIFFSetWarningHandlerExt.o \
TIFFSetWriteOffset.o \
TIFFSetupStrips.o \
TIFFStripSize.o \
TIFFStripSize64.o \
TIFFSwabArrayOfDouble.o \
TIFFSwabArrayOfFloat.o \
TIFFSwabArrayOfLong.o \
TIFFSwabArrayOfLong8.o \
TIFFSwabArrayOfShort.o \
TIFFSwabArrayOfTriples.o \
TIFFSwabDouble.o \
TIFFSwabFloat.o \
TIFFSwabLong.o \
TIFFSwabLong8.o \
TIFFSwabShort.o \
TIFFTileRowSize.o \
TIFFTileRowSize64.o \
TIFFTileSize.o \
TIFFTileSize64.o \
TIFFUnRegisterCODEC.o \
TIFFUnlinkDirectory.o \
TIFFUnsetField.o \
TIFFVGetField.o \
TIFFVGetFieldDefaulted.o \
TIFFVSetField.o \
TIFFVStripSize.o \
TIFFVStripSize64.o \
TIFFVTileSize.o \
TIFFVTileSize64.o \
TIFFWriteBufferSetup.o \
TIFFWriteCheck.o \
TIFFWriteCustomDirectory.o \
TIFFWriteDirectory.o \
TIFFWriteEncodedStrip.o \
TIFFWriteEncodedTile.o \
TIFFWriteRawStrip.o \
TIFFWriteRawTile.o \
TIFFWriteScanline.o \
TIFFWriteTile.o \
TIFFXYZToRGB.o \
TIFFYCbCrToRGBInit.o \
TIFFYCbCrtoRGB.o \
XYZtoRGB24.o \
_TIFFfree.o \
_TIFFmalloc.o \
_TIFFmemcmp.o \
_TIFFmemcpy.o \
_TIFFmemset.o \
_TIFFrealloc.o \
uv_decode.o \
uv_encode.o 