// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <tiffio.h>
#undef TIFFFdOpen
static TIFF *(*funcptr) (int , const char * , const char * ) = 0;

extern int __lsb_check_params;
TIFF * TIFFFdOpen (int arg0 , const char * arg1 , const char * arg2 )
{
	int reset_flag = __lsb_check_params;
	TIFF * ret_value  ;
	__lsb_output(4, "Invoking wrapper for TIFFFdOpen()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "TIFFFdOpen");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load TIFFFdOpen. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "TIFFFdOpen() - validating");
		validate_NULL_TYPETYPE(  arg0, "TIFFFdOpen - arg0");
		if( arg1 ) {
		validate_Rdaddress( arg1, "TIFFFdOpen - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "TIFFFdOpen - arg1");
		if( arg2 ) {
		validate_Rdaddress( arg2, "TIFFFdOpen - arg2");
		}
		validate_NULL_TYPETYPE(  arg2, "TIFFFdOpen - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

