// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <tiffio.h>
#include <tiff.h>
#undef TIFFWriteRawStrip
static tmsize_t(*funcptr) (TIFF * , uint32 , void * , tmsize_t ) = 0;

extern int __lsb_check_params;
tmsize_t TIFFWriteRawStrip (TIFF * arg0 , uint32 arg1 , void * arg2 , tmsize_t arg3 )
{
	int reset_flag = __lsb_check_params;
	tmsize_t ret_value  ;
	__lsb_output(4, "Invoking wrapper for TIFFWriteRawStrip()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "TIFFWriteRawStrip", "LIBTIFF_4.0");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load TIFFWriteRawStrip. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "TIFFWriteRawStrip() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "TIFFWriteRawStrip - arg0 (tif)");
		}
		validate_NULL_TYPETYPE(  arg0, "TIFFWriteRawStrip - arg0 (tif)");
		validate_NULL_TYPETYPE(  arg1, "TIFFWriteRawStrip - arg1 (strip)");
		if( arg2 ) {
		validate_RWaddress( arg2, "TIFFWriteRawStrip - arg2 (data)");
		}
		validate_NULL_TYPETYPE(  arg2, "TIFFWriteRawStrip - arg2 (data)");
		validate_NULL_TYPETYPE(  arg3, "TIFFWriteRawStrip - arg3 (cc)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

