char *DtNeeded[] = {
	"/lib/ld-lsb-ia64.so.1",
	"/lib/ld-lsb.so.1",
	"libGL.so.1",
	"libICE.so.6",
	"libSM.so.6",
	"libX11.so.6",
	"libXext.so.6",
	"libXt.so.6",
	"libc.so.6",
	"libc.so.6.1",
	"libcrypt.so.1",
	"libdl.so.2",
	"libm.so.6",
	"libncurses.so.5",
	"libpthread.so.0",
	"librt.so.1",
	"libutil.so.1",
	"libz.so.1",
	};
int numDtNeeded = sizeof(DtNeeded)/sizeof(char *);
