#!/usr/bin/perl

use CGI;
use Mysql;

use Env qw(LSBUSER LSBDBPASSWD LSBDB LSBDBHOST);

$Dbh = Mysql->connect($LSBDBHOST,$LSBDB,$LSBUSER, $LSBDBPASSWD) || die $Mysql::db_errstr;

$select = "SELECT DISTINCT Lrunname FROM Library ";
$select.= "WHERE Library.Lstd='Yes' ";
$select.= "ORDER BY Lrunname ";

#print $select;

$sth = $Dbh->query($select) || die $Dbh->errmsg();

print "char *DtNeeded[] = {\n";
for(1..$sth->numrows) {
	%entry=$sth->fetchhash;
	printf "\t\"%s\",\n",$entry{'Lrunname'};
}
print "\t};\n";
print "int numDtNeeded = sizeof(DtNeeded)/sizeof(char *);\n";

