// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-3.0/gtk/gtk.h>
#undef _gtk_action_emit_activate
static void(*funcptr) (GtkAction * ) = 0;

extern int __lsb_check_params;
void _gtk_action_emit_activate (GtkAction * arg0 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for _gtk_action_emit_activate()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "_gtk_action_emit_activate");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load _gtk_action_emit_activate. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "_gtk_action_emit_activate() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "_gtk_action_emit_activate - arg0 (action)");
		}
		validate_NULL_TYPETYPE(  arg0, "_gtk_action_emit_activate - arg0 (action)");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

