// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-3.0/gtk/gtk.h>
#undef gtk_target_entry_free
static void(*funcptr) (GtkTargetEntry * ) = 0;

extern int __lsb_check_params;
void gtk_target_entry_free (GtkTargetEntry * arg0 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gtk_target_entry_free()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_target_entry_free");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_target_entry_free. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_target_entry_free() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gtk_target_entry_free - arg0 (data)");
		}
		validate_NULL_TYPETYPE(  arg0, "gtk_target_entry_free - arg0 (data)");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

