// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#include <gtk-3.0/gtk/gtk.h>
#undef gtk_hsv_to_rgb
static void(*funcptr) (gdouble , gdouble , gdouble , gdouble * , gdouble * , gdouble * ) = 0;

extern int __lsb_check_params;
void gtk_hsv_to_rgb (gdouble arg0 , gdouble arg1 , gdouble arg2 , gdouble * arg3 , gdouble * arg4 , gdouble * arg5 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gtk_hsv_to_rgb()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_hsv_to_rgb");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_hsv_to_rgb. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_hsv_to_rgb() - validating");
		validate_NULL_TYPETYPE(  arg0, "gtk_hsv_to_rgb - arg0 (h)");
		validate_NULL_TYPETYPE(  arg1, "gtk_hsv_to_rgb - arg1");
		validate_NULL_TYPETYPE(  arg2, "gtk_hsv_to_rgb - arg2");
		if( arg3 ) {
		validate_RWaddress( arg3, "gtk_hsv_to_rgb - arg3");
		}
		validate_NULL_TYPETYPE(  arg3, "gtk_hsv_to_rgb - arg3");
		if( arg4 ) {
		validate_RWaddress( arg4, "gtk_hsv_to_rgb - arg4");
		}
		validate_NULL_TYPETYPE(  arg4, "gtk_hsv_to_rgb - arg4");
		if( arg5 ) {
		validate_RWaddress( arg5, "gtk_hsv_to_rgb - arg5");
		}
		validate_NULL_TYPETYPE(  arg5, "gtk_hsv_to_rgb - arg5");
	}
	funcptr(arg0, arg1, arg2, arg3, arg4, arg5);
	__lsb_check_params = reset_flag;
}

