// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-3.0/gtk/gtk.h>
#undef gtk_app_chooser_button_set_active_custom_item
static void(*funcptr) (GtkAppChooserButton * , const char * ) = 0;

extern int __lsb_check_params;
void gtk_app_chooser_button_set_active_custom_item (GtkAppChooserButton * arg0 , const char * arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for gtk_app_chooser_button_set_active_custom_item()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gtk_app_chooser_button_set_active_custom_item");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gtk_app_chooser_button_set_active_custom_item. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gtk_app_chooser_button_set_active_custom_item() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gtk_app_chooser_button_set_active_custom_item - arg0 (self)");
		}
		validate_NULL_TYPETYPE(  arg0, "gtk_app_chooser_button_set_active_custom_item - arg0 (self)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "gtk_app_chooser_button_set_active_custom_item - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "gtk_app_chooser_button_set_active_custom_item - arg1");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

