GEN_FUNCS = \
png_access_version_number.o \
png_check_sig.o \
png_convert_from_struct_tm.o \
png_convert_from_time_t.o \
png_create_info_struct.o \
png_create_read_struct.o \
png_create_read_struct_2.o \
png_create_write_struct.o \
png_create_write_struct_2.o \
png_data_freer.o \
png_destroy_info_struct.o \
png_destroy_read_struct.o \
png_destroy_write_struct.o \
png_error.o \
png_free.o \
png_free_data.o \
png_get_IHDR.o \
png_get_PLTE.o \
png_get_bKGD.o \
png_get_bit_depth.o \
png_get_cHRM.o \
png_get_channels.o \
png_get_color_type.o \
png_get_error_ptr.o \
png_get_gAMA.o \
png_get_hIST.o \
png_get_header_ver.o \
png_get_iCCP.o \
png_get_image_height.o \
png_get_image_width.o \
png_get_interlace_type.o \
png_get_io_ptr.o \
png_get_libpng_ver.o \
png_get_oFFs.o \
png_get_pHYs.o \
png_get_progressive_ptr.o \
png_get_rowbytes.o \
png_get_rows.o \
png_get_sBIT.o \
png_get_sRGB.o \
png_get_tIME.o \
png_get_tRNS.o \
png_get_text.o \
png_get_unknown_chunks.o \
png_get_user_chunk_ptr.o \
png_get_valid.o \
png_get_x_offset_pixels.o \
png_get_x_pixels_per_meter.o \
png_get_y_offset_pixels.o \
png_get_y_pixels_per_meter.o \
png_info_init_3.o \
png_init_io.o \
png_malloc.o \
png_permit_mng_features.o \
png_process_data.o \
png_progressive_combine_row.o \
png_read_end.o \
png_read_image.o \
png_read_info.o \
png_read_png.o \
png_read_row.o \
png_read_rows.o \
png_read_update_info.o \
png_set_IHDR.o \
png_set_PLTE.o \
png_set_bKGD.o \
png_set_background.o \
png_set_bgr.o \
png_set_cHRM.o \
png_set_compression_buffer_size.o \
png_set_compression_level.o \
png_set_compression_mem_level.o \
png_set_compression_method.o \
png_set_compression_strategy.o \
png_set_compression_window_bits.o \
png_set_dither.o \
png_set_error_fn.o \
png_set_expand.o \
png_set_filler.o \
png_set_filter.o \
png_set_gAMA.o \
png_set_gamma.o \
png_set_gray_1_2_4_to_8.o \
png_set_gray_to_rgb.o \
png_set_hIST.o \
png_set_iCCP.o \
png_set_interlace_handling.o \
png_set_invert_alpha.o \
png_set_invert_mono.o \
png_set_keep_unknown_chunks.o \
png_set_mem_fn.o \
png_set_oFFs.o \
png_set_pHYs.o \
png_set_packing.o \
png_set_packswap.o \
png_set_palette_to_rgb.o \
png_set_progressive_read_fn.o \
png_set_read_fn.o \
png_set_read_user_chunk_fn.o \
png_set_read_user_transform_fn.o \
png_set_rgb_to_gray.o \
png_set_rows.o \
png_set_sBIT.o \
png_set_sRGB.o \
png_set_sRGB_gAMA_and_cHRM.o \
png_set_shift.o \
png_set_sig_bytes.o \
png_set_strip_16.o \
png_set_strip_alpha.o \
png_set_swap.o \
png_set_swap_alpha.o \
png_set_tIME.o \
png_set_tRNS.o \
png_set_tRNS_to_alpha.o \
png_set_text.o \
png_set_unknown_chunk_location.o \
png_set_unknown_chunks.o \
png_set_write_fn.o \
png_set_write_status_fn.o \
png_set_write_user_transform_fn.o \
png_sig_cmp.o \
png_start_read_image.o \
png_warning.o \
png_write_chunk.o \
png_write_end.o \
png_write_flush.o \
png_write_image.o \
png_write_info.o \
png_write_png.o \
png_write_row.o \
png_write_rows.o 