// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <png.h>
#undef png_set_unknown_chunks
static void(*funcptr) (png_structp , png_infop , png_unknown_chunkp , int ) = 0;

extern int __lsb_check_params;
void png_set_unknown_chunks (png_structp arg0 , png_infop arg1 , png_unknown_chunkp arg2 , int arg3 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for png_set_unknown_chunks()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "png_set_unknown_chunks", "PNG12_0");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load png_set_unknown_chunks. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "png_set_unknown_chunks() - validating");
		validate_NULL_TYPETYPE(  arg0, "png_set_unknown_chunks - arg0 (png_ptr)");
		validate_NULL_TYPETYPE(  arg1, "png_set_unknown_chunks - arg1 (info_ptr)");
		validate_NULL_TYPETYPE(  arg2, "png_set_unknown_chunks - arg2 (unknowns)");
		validate_NULL_TYPETYPE(  arg3, "png_set_unknown_chunks - arg3 (num_unknowns)");
	}
	funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
}

