// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/extensions/XInput.h>
#include <X11/extensions/XTest.h>
#undef XTestFakeDeviceKeyEvent
static int(*funcptr) (Display * , XDevice * , unsigned int , int , int * , int , unsigned long int ) = 0;

extern int __lsb_check_params;
int XTestFakeDeviceKeyEvent (Display * arg0 , XDevice * arg1 , unsigned int arg2 , int arg3 , int * arg4 , int arg5 , unsigned long int arg6 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for XTestFakeDeviceKeyEvent()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XTestFakeDeviceKeyEvent");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XTestFakeDeviceKeyEvent. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XTestFakeDeviceKeyEvent() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "XTestFakeDeviceKeyEvent - arg0");
		}
		validate_NULL_TYPETYPE(  arg0, "XTestFakeDeviceKeyEvent - arg0");
		if( arg1 ) {
		validate_RWaddress( arg1, "XTestFakeDeviceKeyEvent - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "XTestFakeDeviceKeyEvent - arg1");
		validate_NULL_TYPETYPE(  arg2, "XTestFakeDeviceKeyEvent - arg2");
		validate_NULL_TYPETYPE(  arg3, "XTestFakeDeviceKeyEvent - arg3");
		if( arg4 ) {
		validate_RWaddress( arg4, "XTestFakeDeviceKeyEvent - arg4");
		}
		validate_NULL_TYPETYPE(  arg4, "XTestFakeDeviceKeyEvent - arg4");
		validate_NULL_TYPETYPE(  arg5, "XTestFakeDeviceKeyEvent - arg5");
		validate_NULL_TYPETYPE(  arg6, "XTestFakeDeviceKeyEvent - arg6");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
	__lsb_check_params = reset_flag;
	return ret_value;
}

