// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <nss3/certt.h>
#include <nss3/cert.h>
#undef CERT_DestroyCertificate
static void(*funcptr) (CERTCertificate * ) = 0;

extern int __lsb_check_params;
void CERT_DestroyCertificate (CERTCertificate * arg0 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for CERT_DestroyCertificate()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "CERT_DestroyCertificate", "NSS_3.2");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load CERT_DestroyCertificate. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "CERT_DestroyCertificate() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "CERT_DestroyCertificate - arg0 (cert)");
		}
		validate_NULL_TYPETYPE(  arg0, "CERT_DestroyCertificate - arg0 (cert)");
	}
	funcptr(arg0);
	__lsb_check_params = reset_flag;
}

