GEN_FUNCS = \
IceAcceptConnection.o \
IceAddConnectionWatch.o \
IceAllocScratch.o \
IceAppLockConn.o \
IceAppUnlockConn.o \
IceAuthFileName.o \
IceCheckShutdownNegotiation.o \
IceCloseConnection.o \
IceComposeNetworkIdList.o \
IceConnectionNumber.o \
IceConnectionStatus.o \
IceConnectionString.o \
IceFlush.o \
IceFreeAuthFileEntry.o \
IceFreeListenObjs.o \
IceGenerateMagicCookie.o \
IceGetAuthFileEntry.o \
IceGetConnectionContext.o \
IceGetInBufSize.o \
IceGetListenConnectionNumber.o \
IceGetListenConnectionString.o \
IceGetOutBufSize.o \
IceInitThreads.o \
IceLastReceivedSequenceNumber.o \
IceLastSentSequenceNumber.o \
IceListenForConnections.o \
IceListenForWellKnownConnections.o \
IceLockAuthFile.o \
IceOpenConnection.o \
IcePing.o \
IceProcessMessages.o \
IceProtocolRevision.o \
IceProtocolSetup.o \
IceProtocolShutdown.o \
IceProtocolVersion.o \
IceReadAuthFileEntry.o \
IceRegisterForProtocolReply.o \
IceRegisterForProtocolSetup.o \
IceRelease.o \
IceRemoveConnectionWatch.o \
IceSetErrorHandler.o \
IceSetHostBasedAuthProc.o \
IceSetIOErrorHandler.o \
IceSetPaAuthData.o \
IceSetShutdownNegotiation.o \
IceSwapping.o \
IceUnlockAuthFile.o \
IceVendor.o \
IceWriteAuthFileEntry.o 