// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <X11/ICE/ICElib.h>
#undef IceRemoveConnectionWatch
static void(*funcptr) (IceWatchProc , IcePointer ) = 0;

extern int __lsb_check_params;
void IceRemoveConnectionWatch (IceWatchProc arg0 , IcePointer arg1 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " IceRemoveConnectionWatch ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "IceRemoveConnectionWatch()");
		validate_NULL_TYPETYPE(  arg0, "IceRemoveConnectionWatch - arg0");
		validate_NULL_TYPETYPE(  arg1, "IceRemoveConnectionWatch - arg1");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

