// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <fontconfig/fontconfig.h>
#undef FcPatternHash
static FcChar32(*funcptr) (const FcPattern * ) = 0;

extern int __lsb_check_params;
FcChar32 FcPatternHash (const FcPattern * arg0 )
{
	int reset_flag = __lsb_check_params;
	FcChar32 ret_value  ;
	__lsb_output(4, "Invoking wrapper for FcPatternHash()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "FcPatternHash");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load FcPatternHash. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "FcPatternHash() - validating");
		validate_Rdaddress( arg0, "FcPatternHash - arg0 (p)");
		validate_NULL_TYPETYPE(  arg0, "FcPatternHash - arg0 (p)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

