GEN_FUNCS = \
FcAtomicCreate.o \
FcAtomicDeleteNew.o \
FcAtomicDestroy.o \
FcAtomicLock.o \
FcAtomicNewFile.o \
FcAtomicOrigFile.o \
FcAtomicReplaceOrig.o \
FcAtomicUnlock.o \
FcBlanksAdd.o \
FcBlanksCreate.o \
FcBlanksDestroy.o \
FcBlanksIsMember.o \
FcCharSetAddChar.o \
FcCharSetCopy.o \
FcCharSetCount.o \
FcCharSetCreate.o \
FcCharSetDestroy.o \
FcCharSetEqual.o \
FcCharSetFirstPage.o \
FcCharSetHasChar.o \
FcCharSetIntersect.o \
FcCharSetIntersectCount.o \
FcCharSetIsSubset.o \
FcCharSetNextPage.o \
FcCharSetSubtract.o \
FcCharSetSubtractCount.o \
FcCharSetUnion.o \
FcConfigAppFontAddDir.o \
FcConfigAppFontAddFile.o \
FcConfigAppFontClear.o \
FcConfigBuildFonts.o \
FcConfigDestroy.o \
FcConfigEnableHome.o \
FcConfigFilename.o \
FcConfigGetBlanks.o \
FcConfigGetCache.o \
FcConfigGetConfigDirs.o \
FcConfigGetConfigFiles.o \
FcConfigGetCurrent.o \
FcConfigGetFontDirs.o \
FcConfigGetFonts.o \
FcConfigGetRescanInterval.o \
FcConfigGetRescanInverval.o \
FcConfigHome.o \
FcConfigParseAndLoad.o \
FcConfigSetCurrent.o \
FcConfigSetRescanInterval.o \
FcConfigSetRescanInverval.o \
FcConfigSubstitute.o \
FcConfigSubstituteWithPat.o \
FcConfigUptoDate.o \
FcDefaultSubstitute.o \
FcDirCacheValid.o \
FcDirSave.o \
FcDirScan.o \
FcFileScan.o \
FcFini.o \
FcFontList.o \
FcFontMatch.o \
FcFontRenderPrepare.o \
FcFontSetAdd.o \
FcFontSetCreate.o \
FcFontSetDestroy.o \
FcFontSetList.o \
FcFontSetMatch.o \
FcFontSetPrint.o \
FcFontSetSort.o \
FcFontSetSortDestroy.o \
FcFontSort.o \
FcFreeTypeCharIndex.o \
FcFreeTypeCharSet.o \
FcFreeTypeCharSetAndSpacing.o \
FcFreeTypeQuery.o \
FcGetVersion.o \
FcInit.o \
FcInitBringUptoDate.o \
FcInitLoadConfig.o \
FcInitLoadConfigAndFonts.o \
FcInitReinitialize.o \
FcLangSetAdd.o \
FcLangSetCompare.o \
FcLangSetContains.o \
FcLangSetCopy.o \
FcLangSetCreate.o \
FcLangSetDestroy.o \
FcLangSetEqual.o \
FcLangSetHasLang.o \
FcLangSetHash.o \
FcMatrixCopy.o \
FcMatrixEqual.o \
FcMatrixMultiply.o \
FcMatrixRotate.o \
FcMatrixScale.o \
FcMatrixShear.o \
FcNameConstant.o \
FcNameGetConstant.o \
FcNameGetObjectType.o \
FcNameParse.o \
FcNameRegisterConstants.o \
FcNameRegisterObjectTypes.o \
FcNameUnparse.o \
FcNameUnregisterConstants.o \
FcNameUnregisterObjectTypes.o \
FcObjectSetAdd.o \
FcObjectSetCreate.o \
FcObjectSetDestroy.o \
FcObjectSetVaBuild.o \
FcPatternAdd.o \
FcPatternAddBool.o \
FcPatternAddCharSet.o \
FcPatternAddDouble.o \
FcPatternAddFTFace.o \
FcPatternAddInteger.o \
FcPatternAddLangSet.o \
FcPatternAddMatrix.o \
FcPatternAddString.o \
FcPatternAddWeak.o \
FcPatternCreate.o \
FcPatternDel.o \
FcPatternDestroy.o \
FcPatternDuplicate.o \
FcPatternEqual.o \
FcPatternEqualSubset.o \
FcPatternGet.o \
FcPatternGetBool.o \
FcPatternGetCharSet.o \
FcPatternGetDouble.o \
FcPatternGetFTFace.o \
FcPatternGetInteger.o \
FcPatternGetLangSet.o \
FcPatternGetMatrix.o \
FcPatternGetString.o \
FcPatternHash.o \
FcPatternPrint.o \
FcPatternReference.o \
FcPatternVaBuild.o \
FcStrBasename.o \
FcStrCmp.o \
FcStrCmpIgnoreCase.o \
FcStrCopy.o \
FcStrCopyFilename.o \
FcStrDirname.o \
FcStrListCreate.o \
FcStrListDone.o \
FcStrListNext.o \
FcStrSetAdd.o \
FcStrSetAddFilename.o \
FcStrSetCreate.o \
FcStrSetDel.o \
FcStrSetDestroy.o \
FcStrSetEqual.o \
FcStrSetMember.o \
FcUcs4ToUtf8.o \
FcUtf16Len.o \
FcUtf16ToUcs4.o \
FcUtf8Len.o \
FcUtf8ToUcs4.o \
FcValueDestroy.o \
FcValueEqual.o \
FcValuePrint.o \
FcValueSave.o 