GEN_FUNCS = \
xcb_alloc_color.o \
xcb_alloc_color_cells.o \
xcb_alloc_color_cells_masks.o \
xcb_alloc_color_cells_masks_end.o \
xcb_alloc_color_cells_masks_length.o \
xcb_alloc_color_cells_pixels.o \
xcb_alloc_color_cells_pixels_end.o \
xcb_alloc_color_cells_pixels_length.o \
xcb_alloc_color_cells_reply.o \
xcb_alloc_color_cells_unchecked.o \
xcb_alloc_color_planes.o \
xcb_alloc_color_planes_pixels.o \
xcb_alloc_color_planes_pixels_end.o \
xcb_alloc_color_planes_pixels_length.o \
xcb_alloc_color_planes_reply.o \
xcb_alloc_color_planes_unchecked.o \
xcb_alloc_color_reply.o \
xcb_alloc_color_unchecked.o \
xcb_alloc_named_color.o \
xcb_alloc_named_color_reply.o \
xcb_alloc_named_color_unchecked.o \
xcb_allow_events.o \
xcb_allow_events_checked.o \
xcb_arc_end.o \
xcb_arc_next.o \
xcb_atom_end.o \
xcb_atom_next.o \
xcb_bell.o \
xcb_bell_checked.o \
xcb_big_requests_enable.o \
xcb_big_requests_enable_reply.o \
xcb_big_requests_enable_unchecked.o \
xcb_button_end.o \
xcb_button_next.o \
xcb_change_active_pointer_grab.o \
xcb_change_active_pointer_grab_checked.o \
xcb_change_gc.o \
xcb_change_gc_checked.o \
xcb_change_hosts.o \
xcb_change_hosts_checked.o \
xcb_change_keyboard_control.o \
xcb_change_keyboard_control_checked.o \
xcb_change_keyboard_mapping.o \
xcb_change_keyboard_mapping_checked.o \
xcb_change_pointer_control.o \
xcb_change_pointer_control_checked.o \
xcb_change_property.o \
xcb_change_property_checked.o \
xcb_change_save_set.o \
xcb_change_save_set_checked.o \
xcb_change_window_attributes.o \
xcb_change_window_attributes_checked.o \
xcb_char2b_end.o \
xcb_char2b_next.o \
xcb_charinfo_end.o \
xcb_charinfo_next.o \
xcb_circulate_window.o \
xcb_circulate_window_checked.o \
xcb_clear_area.o \
xcb_clear_area_checked.o \
xcb_client_message_data_end.o \
xcb_client_message_data_next.o \
xcb_close_font.o \
xcb_close_font_checked.o \
xcb_coloritem_end.o \
xcb_coloritem_next.o \
xcb_colormap_end.o \
xcb_colormap_next.o \
xcb_configure_window.o \
xcb_configure_window_checked.o \
xcb_connect.o \
xcb_connect_to_display_with_auth_info.o \
xcb_connect_to_fd.o \
xcb_connection_has_error.o \
xcb_convert_selection.o \
xcb_convert_selection_checked.o \
xcb_copy_area.o \
xcb_copy_area_checked.o \
xcb_copy_colormap_and_free.o \
xcb_copy_colormap_and_free_checked.o \
xcb_copy_gc.o \
xcb_copy_gc_checked.o \
xcb_copy_plane.o \
xcb_copy_plane_checked.o \
xcb_create_colormap.o \
xcb_create_colormap_checked.o \
xcb_create_cursor.o \
xcb_create_cursor_checked.o \
xcb_create_gc.o \
xcb_create_gc_checked.o \
xcb_create_glyph_cursor.o \
xcb_create_glyph_cursor_checked.o \
xcb_create_pixmap.o \
xcb_create_pixmap_checked.o \
xcb_create_window.o \
xcb_create_window_checked.o \
xcb_cursor_end.o \
xcb_cursor_next.o \
xcb_delete_property.o \
xcb_delete_property_checked.o \
xcb_depth_end.o \
xcb_depth_next.o \
xcb_depth_visuals.o \
xcb_depth_visuals_iterator.o \
xcb_depth_visuals_length.o \
xcb_destroy_subwindows.o \
xcb_destroy_subwindows_checked.o \
xcb_destroy_window.o \
xcb_destroy_window_checked.o \
xcb_discard_reply.o \
xcb_disconnect.o \
xcb_drawable_end.o \
xcb_drawable_next.o \
xcb_fill_poly.o \
xcb_fill_poly_checked.o \
xcb_flush.o \
xcb_font_end.o \
xcb_font_next.o \
xcb_fontable_end.o \
xcb_fontable_next.o \
xcb_fontprop_end.o \
xcb_fontprop_next.o \
xcb_force_screen_saver.o \
xcb_force_screen_saver_checked.o \
xcb_format_end.o \
xcb_format_next.o \
xcb_free_colormap.o \
xcb_free_colormap_checked.o \
xcb_free_colors.o \
xcb_free_colors_checked.o \
xcb_free_cursor.o \
xcb_free_cursor_checked.o \
xcb_free_gc.o \
xcb_free_gc_checked.o \
xcb_free_pixmap.o \
xcb_free_pixmap_checked.o \
xcb_gcontext_end.o \
xcb_gcontext_next.o \
xcb_generate_id.o \
xcb_get_atom_name.o \
xcb_get_atom_name_name.o \
xcb_get_atom_name_name_end.o \
xcb_get_atom_name_name_length.o \
xcb_get_atom_name_reply.o \
xcb_get_atom_name_unchecked.o \
xcb_get_extension_data.o \
xcb_get_file_descriptor.o \
xcb_get_font_path.o \
xcb_get_font_path_path_iterator.o \
xcb_get_font_path_path_length.o \
xcb_get_font_path_reply.o \
xcb_get_font_path_unchecked.o \
xcb_get_geometry.o \
xcb_get_geometry_reply.o \
xcb_get_geometry_unchecked.o \
xcb_get_image.o \
xcb_get_image_data.o \
xcb_get_image_data_end.o \
xcb_get_image_data_length.o \
xcb_get_image_reply.o \
xcb_get_image_unchecked.o \
xcb_get_input_focus.o \
xcb_get_input_focus_reply.o \
xcb_get_input_focus_unchecked.o \
xcb_get_keyboard_control.o \
xcb_get_keyboard_control_reply.o \
xcb_get_keyboard_control_unchecked.o \
xcb_get_keyboard_mapping.o \
xcb_get_keyboard_mapping_keysyms.o \
xcb_get_keyboard_mapping_keysyms_end.o \
xcb_get_keyboard_mapping_keysyms_length.o \
xcb_get_keyboard_mapping_reply.o \
xcb_get_keyboard_mapping_unchecked.o \
xcb_get_maximum_request_length.o \
xcb_get_modifier_mapping.o \
xcb_get_modifier_mapping_keycodes.o \
xcb_get_modifier_mapping_keycodes_end.o \
xcb_get_modifier_mapping_keycodes_length.o \
xcb_get_modifier_mapping_reply.o \
xcb_get_modifier_mapping_unchecked.o \
xcb_get_motion_events.o \
xcb_get_motion_events_events.o \
xcb_get_motion_events_events_iterator.o \
xcb_get_motion_events_events_length.o \
xcb_get_motion_events_reply.o \
xcb_get_motion_events_unchecked.o \
xcb_get_pointer_control.o \
xcb_get_pointer_control_reply.o \
xcb_get_pointer_control_unchecked.o \
xcb_get_pointer_mapping.o \
xcb_get_pointer_mapping_map.o \
xcb_get_pointer_mapping_map_end.o \
xcb_get_pointer_mapping_map_length.o \
xcb_get_pointer_mapping_reply.o \
xcb_get_pointer_mapping_unchecked.o \
xcb_get_property.o \
xcb_get_property_reply.o \
xcb_get_property_unchecked.o \
xcb_get_property_value.o \
xcb_get_property_value_end.o \
xcb_get_property_value_length.o \
xcb_get_screen_saver.o \
xcb_get_screen_saver_reply.o \
xcb_get_screen_saver_unchecked.o \
xcb_get_selection_owner.o \
xcb_get_selection_owner_reply.o \
xcb_get_selection_owner_unchecked.o \
xcb_get_setup.o \
xcb_get_window_attributes.o \
xcb_get_window_attributes_reply.o \
xcb_get_window_attributes_unchecked.o \
xcb_grab_button.o \
xcb_grab_button_checked.o \
xcb_grab_key.o \
xcb_grab_key_checked.o \
xcb_grab_keyboard.o \
xcb_grab_keyboard_reply.o \
xcb_grab_keyboard_unchecked.o \
xcb_grab_pointer.o \
xcb_grab_pointer_reply.o \
xcb_grab_pointer_unchecked.o \
xcb_grab_server.o \
xcb_grab_server_checked.o \
xcb_host_address.o \
xcb_host_address_end.o \
xcb_host_address_length.o \
xcb_host_end.o \
xcb_host_next.o \
xcb_image_text_16.o \
xcb_image_text_16_checked.o \
xcb_image_text_8.o \
xcb_image_text_8_checked.o \
xcb_install_colormap.o \
xcb_install_colormap_checked.o \
xcb_intern_atom.o \
xcb_intern_atom_reply.o \
xcb_intern_atom_unchecked.o \
xcb_keycode_end.o \
xcb_keycode_next.o \
xcb_keysym_end.o \
xcb_keysym_next.o \
xcb_kill_client.o \
xcb_kill_client_checked.o \
xcb_list_extensions.o \
xcb_list_extensions_names_iterator.o \
xcb_list_extensions_names_length.o \
xcb_list_extensions_reply.o \
xcb_list_extensions_unchecked.o \
xcb_list_fonts.o \
xcb_list_fonts_names_iterator.o \
xcb_list_fonts_names_length.o \
xcb_list_fonts_reply.o \
xcb_list_fonts_unchecked.o \
xcb_list_fonts_with_info.o \
xcb_list_fonts_with_info_name.o \
xcb_list_fonts_with_info_name_end.o \
xcb_list_fonts_with_info_name_length.o \
xcb_list_fonts_with_info_properties.o \
xcb_list_fonts_with_info_properties_iterator.o \
xcb_list_fonts_with_info_properties_length.o \
xcb_list_fonts_with_info_reply.o \
xcb_list_fonts_with_info_unchecked.o \
xcb_list_hosts.o \
xcb_list_hosts_hosts_iterator.o \
xcb_list_hosts_hosts_length.o \
xcb_list_hosts_reply.o \
xcb_list_hosts_unchecked.o \
xcb_list_installed_colormaps.o \
xcb_list_installed_colormaps_cmaps.o \
xcb_list_installed_colormaps_cmaps_end.o \
xcb_list_installed_colormaps_cmaps_length.o \
xcb_list_installed_colormaps_reply.o \
xcb_list_installed_colormaps_unchecked.o \
xcb_list_properties.o \
xcb_list_properties_atoms.o \
xcb_list_properties_atoms_end.o \
xcb_list_properties_atoms_length.o \
xcb_list_properties_reply.o \
xcb_list_properties_unchecked.o \
xcb_lookup_color.o \
xcb_lookup_color_reply.o \
xcb_lookup_color_unchecked.o \
xcb_map_subwindows.o \
xcb_map_subwindows_checked.o \
xcb_map_window.o \
xcb_map_window_checked.o \
xcb_no_operation.o \
xcb_no_operation_checked.o \
xcb_open_font.o \
xcb_open_font_checked.o \
xcb_parse_display.o \
xcb_pixmap_end.o \
xcb_pixmap_next.o \
xcb_point_end.o \
xcb_point_next.o \
xcb_poll_for_event.o \
xcb_poll_for_reply.o \
xcb_poly_arc.o \
xcb_poly_arc_checked.o \
xcb_poly_fill_arc.o \
xcb_poly_fill_arc_checked.o \
xcb_poly_fill_rectangle.o \
xcb_poly_fill_rectangle_checked.o \
xcb_poly_line.o \
xcb_poly_line_checked.o \
xcb_poly_point.o \
xcb_poly_point_checked.o \
xcb_poly_rectangle.o \
xcb_poly_rectangle_checked.o \
xcb_poly_segment.o \
xcb_poly_segment_checked.o \
xcb_poly_text_16.o \
xcb_poly_text_16_checked.o \
xcb_poly_text_8.o \
xcb_poly_text_8_checked.o \
xcb_popcount.o \
xcb_prefetch_extension_data.o \
xcb_prefetch_maximum_request_length.o \
xcb_put_image.o \
xcb_put_image_checked.o \
xcb_query_best_size.o \
xcb_query_best_size_reply.o \
xcb_query_best_size_unchecked.o \
xcb_query_colors.o \
xcb_query_colors_colors.o \
xcb_query_colors_colors_iterator.o \
xcb_query_colors_colors_length.o \
xcb_query_colors_reply.o \
xcb_query_colors_unchecked.o \
xcb_query_extension.o \
xcb_query_extension_reply.o \
xcb_query_extension_unchecked.o \
xcb_query_font.o \
xcb_query_font_char_infos.o \
xcb_query_font_char_infos_iterator.o \
xcb_query_font_char_infos_length.o \
xcb_query_font_properties.o \
xcb_query_font_properties_iterator.o \
xcb_query_font_properties_length.o \
xcb_query_font_reply.o \
xcb_query_font_unchecked.o \
xcb_query_keymap.o \
xcb_query_keymap_reply.o \
xcb_query_keymap_unchecked.o \
xcb_query_pointer.o \
xcb_query_pointer_reply.o \
xcb_query_pointer_unchecked.o \
xcb_query_text_extents.o \
xcb_query_text_extents_reply.o \
xcb_query_text_extents_unchecked.o \
xcb_query_tree.o \
xcb_query_tree_children.o \
xcb_query_tree_children_end.o \
xcb_query_tree_children_length.o \
xcb_query_tree_reply.o \
xcb_query_tree_unchecked.o \
xcb_recolor_cursor.o \
xcb_recolor_cursor_checked.o \
xcb_rectangle_end.o \
xcb_rectangle_next.o \
xcb_reparent_window.o \
xcb_reparent_window_checked.o \
xcb_request_check.o \
xcb_rgb_end.o \
xcb_rgb_next.o \
xcb_rotate_properties.o \
xcb_rotate_properties_checked.o \
xcb_screen_allowed_depths_iterator.o \
xcb_screen_allowed_depths_length.o \
xcb_screen_end.o \
xcb_screen_next.o \
xcb_segment_end.o \
xcb_segment_next.o \
xcb_send_event.o \
xcb_send_event_checked.o \
xcb_send_request.o \
xcb_set_access_control.o \
xcb_set_access_control_checked.o \
xcb_set_clip_rectangles.o \
xcb_set_clip_rectangles_checked.o \
xcb_set_close_down_mode.o \
xcb_set_close_down_mode_checked.o \
xcb_set_dashes.o \
xcb_set_dashes_checked.o \
xcb_set_font_path.o \
xcb_set_font_path_checked.o \
xcb_set_input_focus.o \
xcb_set_input_focus_checked.o \
xcb_set_modifier_mapping.o \
xcb_set_modifier_mapping_reply.o \
xcb_set_modifier_mapping_unchecked.o \
xcb_set_pointer_mapping.o \
xcb_set_pointer_mapping_reply.o \
xcb_set_pointer_mapping_unchecked.o \
xcb_set_screen_saver.o \
xcb_set_screen_saver_checked.o \
xcb_set_selection_owner.o \
xcb_set_selection_owner_checked.o \
xcb_setup_authenticate_end.o \
xcb_setup_authenticate_next.o \
xcb_setup_authenticate_reason.o \
xcb_setup_authenticate_reason_end.o \
xcb_setup_authenticate_reason_length.o \
xcb_setup_end.o \
xcb_setup_failed_end.o \
xcb_setup_failed_next.o \
xcb_setup_failed_reason.o \
xcb_setup_failed_reason_end.o \
xcb_setup_failed_reason_length.o \
xcb_setup_next.o \
xcb_setup_pixmap_formats.o \
xcb_setup_pixmap_formats_iterator.o \
xcb_setup_pixmap_formats_length.o \
xcb_setup_request_authorization_protocol_data.o \
xcb_setup_request_authorization_protocol_data_end.o \
xcb_setup_request_authorization_protocol_data_length.o \
xcb_setup_request_authorization_protocol_name.o \
xcb_setup_request_authorization_protocol_name_end.o \
xcb_setup_request_authorization_protocol_name_length.o \
xcb_setup_request_end.o \
xcb_setup_request_next.o \
xcb_setup_roots_iterator.o \
xcb_setup_roots_length.o \
xcb_setup_vendor.o \
xcb_setup_vendor_end.o \
xcb_setup_vendor_length.o \
xcb_store_colors.o \
xcb_store_colors_checked.o \
xcb_store_named_color.o \
xcb_store_named_color_checked.o \
xcb_str_end.o \
xcb_str_name.o \
xcb_str_name_end.o \
xcb_str_name_length.o \
xcb_str_next.o \
xcb_take_socket.o \
xcb_timecoord_end.o \
xcb_timecoord_next.o \
xcb_timestamp_end.o \
xcb_timestamp_next.o \
xcb_translate_coordinates.o \
xcb_translate_coordinates_reply.o \
xcb_translate_coordinates_unchecked.o \
xcb_ungrab_button.o \
xcb_ungrab_button_checked.o \
xcb_ungrab_key.o \
xcb_ungrab_key_checked.o \
xcb_ungrab_keyboard.o \
xcb_ungrab_keyboard_checked.o \
xcb_ungrab_pointer.o \
xcb_ungrab_pointer_checked.o \
xcb_ungrab_server.o \
xcb_ungrab_server_checked.o \
xcb_uninstall_colormap.o \
xcb_uninstall_colormap_checked.o \
xcb_unmap_subwindows.o \
xcb_unmap_subwindows_checked.o \
xcb_unmap_window.o \
xcb_unmap_window_checked.o \
xcb_visualid_end.o \
xcb_visualid_next.o \
xcb_visualtype_end.o \
xcb_visualtype_next.o \
xcb_wait_for_event.o \
xcb_wait_for_reply.o \
xcb_warp_pointer.o \
xcb_warp_pointer_checked.o \
xcb_window_end.o \
xcb_window_next.o \
xcb_writev.o \
xcb_xc_misc_get_version.o \
xcb_xc_misc_get_version_reply.o \
xcb_xc_misc_get_version_unchecked.o \
xcb_xc_misc_get_xid_list.o \
xcb_xc_misc_get_xid_list_ids.o \
xcb_xc_misc_get_xid_list_ids_end.o \
xcb_xc_misc_get_xid_list_ids_length.o \
xcb_xc_misc_get_xid_list_reply.o \
xcb_xc_misc_get_xid_list_unchecked.o \
xcb_xc_misc_get_xid_range.o \
xcb_xc_misc_get_xid_range_reply.o \
xcb_xc_misc_get_xid_range_unchecked.o 