// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <xcb/xcb.h>
#include <xcb/xproto.h>
#include <stdint.h>
#undef xcb_copy_plane
static xcb_void_cookie_t(*funcptr) (xcb_connection_t * , xcb_drawable_t , xcb_drawable_t , xcb_gcontext_t , int16_t , int16_t , int16_t , int16_t , uint16_t , uint16_t , uint32_t ) = 0;

extern int __lsb_check_params;
xcb_void_cookie_t xcb_copy_plane (xcb_connection_t * arg0 , xcb_drawable_t arg1 , xcb_drawable_t arg2 , xcb_gcontext_t arg3 , int16_t arg4 , int16_t arg5 , int16_t arg6 , int16_t arg7 , uint16_t arg8 , uint16_t arg9 , uint32_t arg10 )
{
	int reset_flag = __lsb_check_params;
	xcb_void_cookie_t ret_value  ;
	__lsb_output(4, "Invoking wrapper for xcb_copy_plane()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "xcb_copy_plane");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load xcb_copy_plane. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "xcb_copy_plane() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "xcb_copy_plane - arg0 (c)");
		}
		validate_NULL_TYPETYPE(  arg0, "xcb_copy_plane - arg0 (c)");
		validate_NULL_TYPETYPE(  arg1, "xcb_copy_plane - arg1 (src_drawable)");
		validate_NULL_TYPETYPE(  arg2, "xcb_copy_plane - arg2 (dst_drawable)");
		validate_NULL_TYPETYPE(  arg3, "xcb_copy_plane - arg3 (gc)");
		validate_NULL_TYPETYPE(  arg4, "xcb_copy_plane - arg4 (src_x)");
		validate_NULL_TYPETYPE(  arg5, "xcb_copy_plane - arg5 (src_y)");
		validate_NULL_TYPETYPE(  arg6, "xcb_copy_plane - arg6 (dst_x)");
		validate_NULL_TYPETYPE(  arg7, "xcb_copy_plane - arg7 (dst_y)");
		validate_NULL_TYPETYPE(  arg8, "xcb_copy_plane - arg8 (width)");
		validate_NULL_TYPETYPE(  arg9, "xcb_copy_plane - arg9 (height)");
		validate_NULL_TYPETYPE(  arg10, "xcb_copy_plane - arg10 (bit_plane)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
	__lsb_check_params = reset_flag;
	return ret_value;
}

