// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <atk-1.0/atk/atk.h>
#undef atk_add_focus_tracker
static guint(*funcptr) (AtkEventListener ) = 0;

extern int __lsb_check_params;
guint atk_add_focus_tracker (AtkEventListener arg0 )
{
	int reset_flag = __lsb_check_params;
	guint ret_value  ;
	__lsb_output(4, "Invoking wrapper for atk_add_focus_tracker()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "atk_add_focus_tracker");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load atk_add_focus_tracker. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "atk_add_focus_tracker() - validating");
		validate_NULL_TYPETYPE(  arg0, "atk_add_focus_tracker - arg0 (focus_tracker)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

