GEN_FUNCS = \
atk_action_do_action.o \
atk_action_get_description.o \
atk_action_get_keybinding.o \
atk_action_get_localized_name.o \
atk_action_get_n_actions.o \
atk_action_get_name.o \
atk_action_get_type.o \
atk_action_set_description.o \
atk_add_focus_tracker.o \
atk_add_global_event_listener.o \
atk_add_key_event_listener.o \
atk_attribute_set_free.o \
atk_component_add_focus_handler.o \
atk_component_contains.o \
atk_component_get_extents.o \
atk_component_get_layer.o \
atk_component_get_mdi_zorder.o \
atk_component_get_position.o \
atk_component_get_size.o \
atk_component_get_type.o \
atk_component_grab_focus.o \
atk_component_ref_accessible_at_point.o \
atk_component_remove_focus_handler.o \
atk_component_set_extents.o \
atk_component_set_position.o \
atk_component_set_size.o \
atk_coord_type_get_type.o \
atk_document_get_document.o \
atk_document_get_document_type.o \
atk_document_get_type.o \
atk_editable_text_copy_text.o \
atk_editable_text_cut_text.o \
atk_editable_text_delete_text.o \
atk_editable_text_get_type.o \
atk_editable_text_insert_text.o \
atk_editable_text_paste_text.o \
atk_editable_text_set_run_attributes.o \
atk_editable_text_set_text_contents.o \
atk_focus_tracker_init.o \
atk_focus_tracker_notify.o \
atk_get_default_registry.o \
atk_get_focus_object.o \
atk_get_root.o \
atk_get_toolkit_name.o \
atk_get_toolkit_version.o \
atk_gobject_accessible_for_object.o \
atk_gobject_accessible_get_object.o \
atk_gobject_accessible_get_type.o \
atk_hyperlink_get_end_index.o \
atk_hyperlink_get_n_anchors.o \
atk_hyperlink_get_object.o \
atk_hyperlink_get_start_index.o \
atk_hyperlink_get_type.o \
atk_hyperlink_get_uri.o \
atk_hyperlink_is_inline.o \
atk_hyperlink_is_selected_link.o \
atk_hyperlink_is_valid.o \
atk_hyperlink_state_flags_get_type.o \
atk_hypertext_get_link.o \
atk_hypertext_get_link_index.o \
atk_hypertext_get_n_links.o \
atk_hypertext_get_type.o \
atk_image_get_image_description.o \
atk_image_get_image_position.o \
atk_image_get_image_size.o \
atk_image_get_type.o \
atk_image_set_image_description.o \
atk_implementor_get_type.o \
atk_implementor_ref_accessible.o \
atk_key_event_type_get_type.o \
atk_layer_get_type.o \
atk_no_op_object_factory_get_type.o \
atk_no_op_object_factory_new.o \
atk_no_op_object_get_type.o \
atk_no_op_object_new.o \
atk_object_add_relationship.o \
atk_object_connect_property_change_handler.o \
atk_object_factory_create_accessible.o \
atk_object_factory_get_accessible_type.o \
atk_object_factory_get_type.o \
atk_object_factory_invalidate.o \
atk_object_get_description.o \
atk_object_get_index_in_parent.o \
atk_object_get_n_accessible_children.o \
atk_object_get_name.o \
atk_object_get_parent.o \
atk_object_get_role.o \
atk_object_get_type.o \
atk_object_initialize.o \
atk_object_notify_state_change.o \
atk_object_ref_accessible_child.o \
atk_object_ref_relation_set.o \
atk_object_ref_state_set.o \
atk_object_remove_property_change_handler.o \
atk_object_remove_relationship.o \
atk_object_set_description.o \
atk_object_set_name.o \
atk_object_set_parent.o \
atk_object_set_role.o \
atk_rectangle_get_type.o \
atk_registry_get_factory.o \
atk_registry_get_factory_type.o \
atk_registry_get_type.o \
atk_registry_set_factory_type.o \
atk_relation_add_target.o \
atk_relation_get_relation_type.o \
atk_relation_get_target.o \
atk_relation_get_type.o \
atk_relation_new.o \
atk_relation_set_add.o \
atk_relation_set_add_relation_by_type.o \
atk_relation_set_contains.o \
atk_relation_set_get_n_relations.o \
atk_relation_set_get_relation.o \
atk_relation_set_get_relation_by_type.o \
atk_relation_set_get_type.o \
atk_relation_set_new.o \
atk_relation_set_remove.o \
atk_relation_type_for_name.o \
atk_relation_type_get_name.o \
atk_relation_type_get_type.o \
atk_relation_type_register.o \
atk_remove_focus_tracker.o \
atk_remove_global_event_listener.o \
atk_remove_key_event_listener.o \
atk_role_for_name.o \
atk_role_get_localized_name.o \
atk_role_get_name.o \
atk_role_get_type.o \
atk_role_register.o \
atk_selection_add_selection.o \
atk_selection_clear_selection.o \
atk_selection_get_selection_count.o \
atk_selection_get_type.o \
atk_selection_is_child_selected.o \
atk_selection_ref_selection.o \
atk_selection_remove_selection.o \
atk_selection_select_all_selection.o \
atk_state_set_add_state.o \
atk_state_set_add_states.o \
atk_state_set_and_sets.o \
atk_state_set_clear_states.o \
atk_state_set_contains_state.o \
atk_state_set_contains_states.o \
atk_state_set_get_type.o \
atk_state_set_is_empty.o \
atk_state_set_new.o \
atk_state_set_or_sets.o \
atk_state_set_remove_state.o \
atk_state_set_xor_sets.o \
atk_state_type_for_name.o \
atk_state_type_get_name.o \
atk_state_type_get_type.o \
atk_state_type_register.o \
atk_streamable_content_get_mime_type.o \
atk_streamable_content_get_n_mime_types.o \
atk_streamable_content_get_stream.o \
atk_streamable_content_get_type.o \
atk_table_add_column_selection.o \
atk_table_add_row_selection.o \
atk_table_get_caption.o \
atk_table_get_column_at_index.o \
atk_table_get_column_description.o \
atk_table_get_column_extent_at.o \
atk_table_get_column_header.o \
atk_table_get_index_at.o \
atk_table_get_n_columns.o \
atk_table_get_n_rows.o \
atk_table_get_row_at_index.o \
atk_table_get_row_description.o \
atk_table_get_row_extent_at.o \
atk_table_get_row_header.o \
atk_table_get_selected_columns.o \
atk_table_get_selected_rows.o \
atk_table_get_summary.o \
atk_table_get_type.o \
atk_table_is_column_selected.o \
atk_table_is_row_selected.o \
atk_table_is_selected.o \
atk_table_ref_at.o \
atk_table_remove_column_selection.o \
atk_table_remove_row_selection.o \
atk_table_set_caption.o \
atk_table_set_column_description.o \
atk_table_set_column_header.o \
atk_table_set_row_description.o \
atk_table_set_row_header.o \
atk_table_set_summary.o \
atk_text_add_selection.o \
atk_text_attribute_for_name.o \
atk_text_attribute_get_name.o \
atk_text_attribute_get_type.o \
atk_text_attribute_get_value.o \
atk_text_attribute_register.o \
atk_text_boundary_get_type.o \
atk_text_clip_type_get_type.o \
atk_text_free_ranges.o \
atk_text_get_bounded_ranges.o \
atk_text_get_caret_offset.o \
atk_text_get_character_at_offset.o \
atk_text_get_character_count.o \
atk_text_get_character_extents.o \
atk_text_get_default_attributes.o \
atk_text_get_n_selections.o \
atk_text_get_offset_at_point.o \
atk_text_get_range_extents.o \
atk_text_get_run_attributes.o \
atk_text_get_selection.o \
atk_text_get_text.o \
atk_text_get_text_after_offset.o \
atk_text_get_text_at_offset.o \
atk_text_get_text_before_offset.o \
atk_text_get_type.o \
atk_text_remove_selection.o \
atk_text_set_caret_offset.o \
atk_text_set_selection.o \
atk_util_get_type.o \
atk_value_get_current_value.o \
atk_value_get_maximum_value.o \
atk_value_get_minimum_value.o \
atk_value_get_type.o \
atk_value_set_current_value.o 