GEN_FUNCS = \
pango_cairo_context_get_font_options.o \
pango_cairo_context_get_resolution.o \
pango_cairo_context_get_shape_renderer.o \
pango_cairo_context_set_font_options.o \
pango_cairo_context_set_resolution.o \
pango_cairo_context_set_shape_renderer.o \
pango_cairo_create_context.o \
pango_cairo_create_layout.o \
pango_cairo_error_underline_path.o \
pango_cairo_font_get_scaled_font.o \
pango_cairo_font_get_type.o \
pango_cairo_font_map_create_context.o \
pango_cairo_font_map_get_default.o \
pango_cairo_font_map_get_font_type.o \
pango_cairo_font_map_get_resolution.o \
pango_cairo_font_map_get_type.o \
pango_cairo_font_map_new.o \
pango_cairo_font_map_new_for_font_type.o \
pango_cairo_font_map_set_default.o \
pango_cairo_font_map_set_resolution.o \
pango_cairo_glyph_string_path.o \
pango_cairo_layout_line_path.o \
pango_cairo_layout_path.o \
pango_cairo_show_error_underline.o \
pango_cairo_show_glyph_item.o \
pango_cairo_show_glyph_string.o \
pango_cairo_show_layout.o \
pango_cairo_show_layout_line.o \
pango_cairo_update_context.o \
pango_cairo_update_layout.o 