STRUCTTESTS = 	\
struct/validate_struct_CERTDistNamesStr.o	\
struct/validate_struct_CERTVerifyLogNodeStr.o	\
struct/validate_struct_CLIENT.o	\
struct/validate_struct_FTW.o	\
struct/validate_struct_FT_BBox_.o	\
struct/validate_struct_FT_BitmapGlyphRec_.o	\
struct/validate_struct_FT_Bitmap_Size_.o	\
struct/validate_struct_FT_CharMapRec_.o	\
struct/validate_struct_FT_Generic_.o	\
struct/validate_struct_FT_GlyphRec_.o	\
struct/validate_struct_FT_GlyphSlotRec_.o	\
struct/validate_struct_FT_Glyph_Class_.o	\
struct/validate_struct_FT_Glyph_Metrics_.o	\
struct/validate_struct_FT_ListNodeRec_.o	\
struct/validate_struct_FT_ListRec_.o	\
struct/validate_struct_FT_Matrix_.o	\
struct/validate_struct_FT_MemoryRec_.o	\
struct/validate_struct_FT_Module_Class_.o	\
struct/validate_struct_FT_OutlineGlyphRec_.o	\
struct/validate_struct_FT_Parameter_.o	\
struct/validate_struct_FT_SizeRec_.o	\
struct/validate_struct_FT_Size_Metrics_.o	\
struct/validate_struct_FT_StreamRec_.o	\
struct/validate_struct_FT_Vector_.o	\
struct/validate_struct_PLArena.o	\
struct/validate_struct_PLHashEntry.o	\
struct/validate_struct_PLHashTable.o	\
struct/validate_struct_PRIOMethods.o	\
struct/validate_struct_SECKEYPrivateKeyStr.o	\
struct/validate_struct__GHashTableIter.o	\
struct/validate_struct__GRWLock.o	\
struct/validate_struct__GRecMutex.o	\
struct/validate_struct__GVariantBuilder.o	\
struct/validate_struct__GVariantIter.o	\
struct/validate_struct__IO_FILE.o	\
struct/validate_struct__Unwind_Exception.o	\
struct/validate_struct___jmp_buf_tag.o	\
struct/validate_struct___locale_struct.o	\
struct/validate_struct___pthread_internal_list.o	\
struct/validate_struct___pthread_mutex_s.o	\
struct/validate_struct__fpstate.o	\
struct/validate_struct__fpxreg.o	\
struct/validate_struct__libc_fpstate.o	\
struct/validate_struct__libc_fpxreg.o	\
struct/validate_struct__libc_xmmreg.o	\
struct/validate_struct__pthread_cleanup_buffer.o	\
struct/validate_struct__win_st.o	\
struct/validate_struct__xmmreg.o	\
struct/validate_struct__xsltDecimalFormat.o	\
struct/validate_struct__xsltDocument.o	\
struct/validate_struct__xsltElemPreComp.o	\
struct/validate_struct__xsltFormatNumberInfo.o	\
struct/validate_struct__xsltKeyDef.o	\
struct/validate_struct__xsltKeyTable.o	\
struct/validate_struct__xsltNumberData.o	\
struct/validate_struct__xsltRuntimeExtra.o	\
struct/validate_struct__xsltStackElem.o	\
struct/validate_struct__xsltStylePreComp.o	\
struct/validate_struct__xsltStylesheet.o	\
struct/validate_struct__xsltTemplate.o	\
struct/validate_struct__xsltTransformCache.o	\
struct/validate_struct__xsltTransformContext.o	\
struct/validate_struct_accepted_reply.o	\
struct/validate_struct_addrinfo.o	\
struct/validate_struct_auth_ops.o	\
struct/validate_struct_call_body.o	\
struct/validate_struct_clnt_ops.o	\
struct/validate_struct_cmsghdr.o	\
struct/validate_struct_cups_page_header2_s.o	\
struct/validate_struct_dirent.o	\
struct/validate_struct_dirent64.o	\
struct/validate_struct_dl_phdr_info.o	\
struct/validate_struct_drand48_data.o	\
struct/validate_struct_epoll_event.o	\
struct/validate_struct_exit_status.o	\
struct/validate_struct_flock.o	\
struct/validate_struct_flock64.o	\
struct/validate_struct_group.o	\
struct/validate_struct_hostent.o	\
struct/validate_struct_hsearch_data.o	\
struct/validate_struct_icmp.o	\
struct/validate_struct_icmp6_filter.o	\
struct/validate_struct_icmp6_hdr.o	\
struct/validate_struct_icmp6_router_renum.o	\
struct/validate_struct_icmp_ra_addr.o	\
struct/validate_struct_icmphdr.o	\
struct/validate_struct_if_nameindex.o	\
struct/validate_struct_ifaddr.o	\
struct/validate_struct_ifconf.o	\
struct/validate_struct_ifmap.o	\
struct/validate_struct_ifreq.o	\
struct/validate_struct_igmp.o	\
struct/validate_struct_ih_idseq.o	\
struct/validate_struct_ih_pmtu.o	\
struct/validate_struct_ih_rtradv.o	\
struct/validate_struct_in6_addr.o	\
struct/validate_struct_in_addr.o	\
struct/validate_struct_inotify_event.o	\
struct/validate_struct_internal_state.o	\
struct/validate_struct_iovec.o	\
struct/validate_struct_ip.o	\
struct/validate_struct_ip6_dest.o	\
struct/validate_struct_ip6_ext.o	\
struct/validate_struct_ip6_frag.o	\
struct/validate_struct_ip6_hbh.o	\
struct/validate_struct_ip6_hdr.o	\
struct/validate_struct_ip6_hdrctl.o	\
struct/validate_struct_ip6_opt.o	\
struct/validate_struct_ip6_opt_jumbo.o	\
struct/validate_struct_ip6_opt_nsap.o	\
struct/validate_struct_ip6_opt_router.o	\
struct/validate_struct_ip6_opt_tunnel.o	\
struct/validate_struct_ip6_rthdr.o	\
struct/validate_struct_ip_mreq.o	\
struct/validate_struct_ip_timestamp.o	\
struct/validate_struct_ipc_perm.o	\
struct/validate_struct_iphdr.o	\
struct/validate_struct_ipv6_mreq.o	\
struct/validate_struct_itimerspec.o	\
struct/validate_struct_itimerval.o	\
struct/validate_struct_lastlog.o	\
struct/validate_struct_lconv.o	\
struct/validate_struct_linger.o	\
struct/validate_struct_mld_hdr.o	\
struct/validate_struct_mq_attr.o	\
struct/validate_struct_msghdr.o	\
struct/validate_struct_msqid_ds.o	\
struct/validate_struct_nd_neighbor_advert.o	\
struct/validate_struct_nd_neighbor_solicit.o	\
struct/validate_struct_nd_opt_adv_interval.o	\
struct/validate_struct_nd_opt_hdr.o	\
struct/validate_struct_nd_opt_home_agent_info.o	\
struct/validate_struct_nd_opt_mtu.o	\
struct/validate_struct_nd_opt_prefix_info.o	\
struct/validate_struct_nd_opt_rd_hdr.o	\
struct/validate_struct_nd_redirect.o	\
struct/validate_struct_nd_router_advert.o	\
struct/validate_struct_nd_router_solicit.o	\
struct/validate_struct_netent.o	\
struct/validate_struct_opaque_auth.o	\
struct/validate_struct_option.o	\
struct/validate_struct_pam_conv.o	\
struct/validate_struct_pam_message.o	\
struct/validate_struct_pam_response.o	\
struct/validate_struct_passwd.o	\
struct/validate_struct_pdat.o	\
struct/validate_struct_png_color_16_struct.o	\
struct/validate_struct_png_color_8_struct.o	\
struct/validate_struct_png_row_info_struct.o	\
struct/validate_struct_png_sPLT_entry_struct.o	\
struct/validate_struct_png_sPLT_struct.o	\
struct/validate_struct_png_time_struct.o	\
struct/validate_struct_png_unknown_chunk_t.o	\
struct/validate_struct_pollfd.o	\
struct/validate_struct_protoent.o	\
struct/validate_struct_random_data.o	\
struct/validate_struct_rejected_reply.o	\
struct/validate_struct_reply_body.o	\
struct/validate_struct_rlimit.o	\
struct/validate_struct_rlimit64.o	\
struct/validate_struct_rpc_err.o	\
struct/validate_struct_rpc_msg.o	\
struct/validate_struct_rr_pco_match.o	\
struct/validate_struct_rr_pco_use.o	\
struct/validate_struct_rr_result.o	\
struct/validate_struct_rusage.o	\
struct/validate_struct_sched_param.o	\
struct/validate_struct_sembuf.o	\
struct/validate_struct_semid_ds.o	\
struct/validate_struct_servent.o	\
struct/validate_struct_shmid_ds.o	\
struct/validate_struct_sigaction.o	\
struct/validate_struct_sigcontext.o	\
struct/validate_struct_snd_mixer_selem_regopt.o	\
struct/validate_struct_snd_seq_queue_skew.o	\
struct/validate_struct_snd_seq_real_time.o	\
struct/validate_struct_snd_seq_result.o	\
struct/validate_struct_sockaddr.o	\
struct/validate_struct_sockaddr_in.o	\
struct/validate_struct_sockaddr_in6.o	\
struct/validate_struct_sockaddr_storage.o	\
struct/validate_struct_sockaddr_un.o	\
struct/validate_struct_stat.o	\
struct/validate_struct_stat64.o	\
struct/validate_struct_statfs.o	\
struct/validate_struct_statfs64.o	\
struct/validate_struct_statvfs.o	\
struct/validate_struct_statvfs64.o	\
struct/validate_struct_svc_req.o	\
struct/validate_struct_sysinfo.o	\
struct/validate_struct_tcp_info.o	\
struct/validate_struct_tcphdr.o	\
struct/validate_struct_termios.o	\
struct/validate_struct_timeb.o	\
struct/validate_struct_timespec.o	\
struct/validate_struct_timestamp.o	\
struct/validate_struct_timeval.o	\
struct/validate_struct_timezone.o	\
struct/validate_struct_tm.o	\
struct/validate_struct_tms.o	\
struct/validate_struct_udphdr.o	\
struct/validate_struct_utimbuf.o	\
struct/validate_struct_utmp.o	\
struct/validate_struct_utmpx.o	\
struct/validate_struct_utsname.o	\
struct/validate_struct_winsize.o	\
struct/validate_struct_xcb_extension_t.o	\
struct/validate_struct_xdr_discrim.o	\
struct/validate_struct_xdr_ops.o	\
struct/validate_struct_xp_ops.o
