STRUCTTESTS = 	\
struct/validate_struct_FTW.o	\
struct/validate_struct__IO_FILE.o	\
struct/validate_struct___jmp_buf_tag.o	\
struct/validate_struct__fpreg.o	\
struct/validate_struct__fpstate.o	\
struct/validate_struct__fpxreg.o	\
struct/validate_struct__libc_fpreg.o	\
struct/validate_struct__libc_fpstate.o	\
struct/validate_struct__pthread_cleanup_buffer.o	\
struct/validate_struct__pthread_fastlock.o	\
struct/validate_struct__win_st.o	\
struct/validate_struct__xmmreg.o	\
struct/validate_struct_accepted_reply.o	\
struct/validate_struct_addrinfo.o	\
struct/validate_struct_auth_ops.o	\
struct/validate_struct_call_body.o	\
struct/validate_struct_clnt_ops.o	\
struct/validate_struct_cmsghdr.o	\
struct/validate_struct_dirent.o	\
struct/validate_struct_dirent64.o	\
struct/validate_struct_exception.o	\
struct/validate_struct_exit_status.o	\
struct/validate_struct_flock.o	\
struct/validate_struct_flock64.o	\
struct/validate_struct_group.o	\
struct/validate_struct_hostent.o	\
struct/validate_struct_ifaddr.o	\
struct/validate_struct_ifconf.o	\
struct/validate_struct_ifmap.o	\
struct/validate_struct_ifreq.o	\
struct/validate_struct_in6_addr.o	\
struct/validate_struct_in_addr.o	\
struct/validate_struct_internal_state.o	\
struct/validate_struct_iovec.o	\
struct/validate_struct_ip_mreq.o	\
struct/validate_struct_ipc_perm.o	\
struct/validate_struct_ipv6_mreq.o	\
struct/validate_struct_itimerspec.o	\
struct/validate_struct_itimerval.o	\
struct/validate_struct_lastlog.o	\
struct/validate_struct_lconv.o	\
struct/validate_struct_ldat.o	\
struct/validate_struct_linger.o	\
struct/validate_struct_msghdr.o	\
struct/validate_struct_msqid_ds.o	\
struct/validate_struct_netent.o	\
struct/validate_struct_opaque_auth.o	\
struct/validate_struct_option.o	\
struct/validate_struct_pam_conv.o	\
struct/validate_struct_pam_handle.o	\
struct/validate_struct_pam_message.o	\
struct/validate_struct_pam_response.o	\
struct/validate_struct_passwd.o	\
struct/validate_struct_pdat.o	\
struct/validate_struct_pollfd.o	\
struct/validate_struct_protoent.o	\
struct/validate_struct_random_data.o	\
struct/validate_struct_rejected_reply.o	\
struct/validate_struct_reply_body.o	\
struct/validate_struct_rlimit.o	\
struct/validate_struct_rlimit64.o	\
struct/validate_struct_rpc_err.o	\
struct/validate_struct_rpc_msg.o	\
struct/validate_struct_rusage.o	\
struct/validate_struct_sched_param.o	\
struct/validate_struct_sembuf.o	\
struct/validate_struct_semid_ds.o	\
struct/validate_struct_servent.o	\
struct/validate_struct_shmid_ds.o	\
struct/validate_struct_sigaction.o	\
struct/validate_struct_sigcontext.o	\
struct/validate_struct_sigstack.o	\
struct/validate_struct_sockaddr.o	\
struct/validate_struct_sockaddr_in.o	\
struct/validate_struct_sockaddr_in6.o	\
struct/validate_struct_sockaddr_storage.o	\
struct/validate_struct_sockaddr_un.o	\
struct/validate_struct_stat.o	\
struct/validate_struct_stat64.o	\
struct/validate_struct_statvfs.o	\
struct/validate_struct_statvfs64.o	\
struct/validate_struct_svc_req.o	\
struct/validate_struct_term.o	\
struct/validate_struct_termios.o	\
struct/validate_struct_timeb.o	\
struct/validate_struct_timespec.o	\
struct/validate_struct_timeval.o	\
struct/validate_struct_timezone.o	\
struct/validate_struct_tm.o	\
struct/validate_struct_tms.o	\
struct/validate_struct_utimbuf.o	\
struct/validate_struct_utmp.o	\
struct/validate_struct_utmpx.o	\
struct/validate_struct_utsname.o	\
struct/validate_struct_winsize.o	\
struct/validate_struct_xdr_discrim.o	\
struct/validate_struct_xdr_ops.o	\
struct/validate_struct_xp_ops.o
