// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static int(*funcptr)() = 0;

int flushinp()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "flushinp");
	return funcptr();
}

int lsb_flushinp()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "flushinp");
	return funcptr();
}

