// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#undef halfdelay
static int(*funcptr) (int ) = 0;

int halfdelay (int arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "halfdelay");
	validate_NULL_TYPETYPE(arg0, "halfdelay");
	return funcptr(arg0);
}

int lsb_halfdelay (int arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "halfdelay");
	return funcptr(arg0);
}

