// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <curses.h>
#undef insnstr
static int(*funcptr) (const char * , int ) = 0;

int insnstr (const char * arg0 , int arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "insnstr");
	validate_NULL_TYPETYPE(arg0, "insnstr");
	validate_NULL_TYPETYPE(arg1, "insnstr");
	return funcptr(arg0, arg1);
}

int lsb_insnstr (const char * arg0 , int arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "insnstr");
	return funcptr(arg0, arg1);
}

