// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <curses.h>
#undef killchar
static char(*funcptr) () = 0;

extern int __lsb_check_params;
char killchar ()
{
	int reset_flag = __lsb_check_params;
	char ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlsym(RTLD_NEXT, "killchar");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "killchar()");
	}
	ret_value = funcptr();
	__lsb_check_params = reset_flag;
	return ret_value;
}

