// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <curses.h>
#undef mvinsstr
static int(*funcptr) (int , int , const char * ) = 0;

extern int __lsb_check_params;
int mvinsstr (int arg0 , int arg1 , const char * arg2 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlsym(RTLD_NEXT, "mvinsstr");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "mvinsstr()");
		validate_NULL_TYPETYPE(  arg0, "mvinsstr - arg0");
		validate_NULL_TYPETYPE(  arg1, "mvinsstr - arg1");
		validate_Rdaddress( arg2, "mvinsstr - arg2");
		validate_NULL_TYPETYPE(  arg2, "mvinsstr - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

