// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <curses.h>
#undef newpad
static WINDOW *(*funcptr) (int , int ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
WINDOW * newpad (int arg0 , int arg1 )
{
	int reset_flag = __lsb_check_params;
	WINDOW * ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "newpad");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "newpad()");
		validate_NULL_TYPETYPE(  arg0, "newpad - arg0");
		validate_NULL_TYPETYPE(  arg1, "newpad - arg1");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

