// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <term.h>
#undef putp
static int(*funcptr) (const char * ) = 0;

int putp (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "putp");
	validate_Rdaddress( arg0, "putp - arg0");
	validate_NULL_TYPETYPE(  arg0, "putp - arg0");
	return funcptr(arg0);
}

int __lsb_putp (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "putp");
	return funcptr(arg0);
}

