// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <term.h>
#undef tgetstr
static char *(*funcptr) (char * , char * * ) = 0;

char * tgetstr (char * arg0 , char * * arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "tgetstr");
	validate_Rdaddress( arg0, "tgetstr - arg0");
	validate_NULL_TYPETYPE(  arg0, "tgetstr - arg0");
	validate_Rdaddress( arg1, "tgetstr - arg1");
	validate_Rdaddress(* arg1, "tgetstr - arg1");
	validate_NULL_TYPETYPE(  arg1, "tgetstr - arg1");
	return funcptr(arg0, arg1);
}

char * __lsb_tgetstr (char * arg0 , char * * arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "tgetstr");
	return funcptr(arg0, arg1);
}

