// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <curses.h>
#undef wattr_get
static int(*funcptr) (WINDOW * , attr_t * , short * , void * ) = 0;

extern int __lsb_check_params;
int wattr_get (WINDOW * arg0 , attr_t * arg1 , short * arg2 , void * arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "wattr_get");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "wattr_get()");
		validate_RWaddress( arg0, "wattr_get - arg0");
		validate_NULL_TYPETYPE(  arg0, "wattr_get - arg0");
		validate_RWaddress( arg1, "wattr_get - arg1");
		validate_NULL_TYPETYPE(  arg1, "wattr_get - arg1");
		validate_RWaddress( arg2, "wattr_get - arg2");
		validate_NULL_TYPETYPE(  arg2, "wattr_get - arg2");
		validate_RWaddress( arg3, "wattr_get - arg3");
		validate_NULL_TYPETYPE(  arg3, "wattr_get - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

