// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(WINDOW *) = 0;

int wclrtoeol(WINDOW * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "wclrtoeol");
	validate_NULL_TYPETYPE(arg0, "wclrtoeol");
	return funcptr(arg0);
}

int lsb_wclrtoeol(WINDOW * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "wclrtoeol");
	return funcptr(arg0);
}

