// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <curses.h>
#undef wdelch
static int(*funcptr) (WINDOW * ) = 0;

int wdelch (WINDOW * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "wdelch");
	validate_Rdaddress( arg0, "wdelch");
	validate_NULL_TYPETYPE(  arg0, "wdelch");
	return funcptr(arg0);
}

int __lsb_wdelch (WINDOW * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "wdelch");
	return funcptr(arg0);
}

