// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static void(*funcptr)(char *, char *, unsigned int, char *) = 0;

void __assert_fail(char * arg0, char * arg1, unsigned int arg2, char * arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "__assert_fail");
	validate_NULL_TYPETYPE(arg0, "__assert_fail");
	validate_NULL_TYPETYPE(arg1, "__assert_fail");
	validate_NULL_TYPETYPE(arg2, "__assert_fail");
	validate_NULL_TYPETYPE(arg3, "__assert_fail");
	funcptr(arg0, arg1, arg2, arg3);
}

void lsb___assert_fail(char * arg0, char * arg1, unsigned int arg2, char * arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "__assert_fail");
	funcptr(arg0, arg1, arg2, arg3);
}

