// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <stddef.h>
#include <unistd.h>
#undef __confstr_chk
static size_t(*funcptr) (int , char * , size_t , size_t ) = 0;

extern int __lsb_check_params;
size_t __confstr_chk (int arg0 , char * arg1 , size_t arg2 , size_t arg3 )
{
	int reset_flag = __lsb_check_params;
	size_t ret_value  ;
	__lsb_output(4, "Invoking wrapper for __confstr_chk()");
	if(!funcptr)
		#if 1
			funcptr = dlvsym(RTLD_NEXT, "__confstr_chk", "GLIBC_2.4");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load __confstr_chk. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "__confstr_chk() - validating");
		validate_NULL_TYPETYPE(  arg0, "__confstr_chk - arg0");
		if( arg1 ) {
		validate_RWaddress( arg1, "__confstr_chk - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "__confstr_chk - arg1");
		validate_NULL_TYPETYPE(  arg2, "__confstr_chk - arg2");
		validate_NULL_TYPETYPE(  arg3, "__confstr_chk - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

