// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <sys/types.h>
#include <unistd.h>
#undef __getpgid
static pid_t(*funcptr) (pid_t ) = 0;

extern int __lsb_check_params;
pid_t __getpgid (pid_t arg0 )
{
	int reset_flag = __lsb_check_params;
	pid_t ret_value  ;
	if(!funcptr)
		funcptr = dlvsym(RTLD_NEXT, "__getpgid", "GLIBC_2.0");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "__getpgid()");
		validate_NULL_TYPETYPE(  arg0, "__getpgid - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

