// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stddef.h>
#include <string.h>
#undef bcopy
static void(*funcptr) (const void * , void * , size_t ) = 0;

void bcopy (const void * arg0 , void * arg1 , size_t arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "bcopy");
	validate_NULL_TYPETYPE(arg0, "bcopy");
	validate_NULL_TYPETYPE(arg1, "bcopy");
	validate_NULL_TYPETYPE(arg2, "bcopy");
	funcptr(arg0, arg1, arg2);
}

void lsb_bcopy (const void * arg0 , void * arg1 , size_t arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "bcopy");
	funcptr(arg0, arg1, arg2);
}

