// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <unistd.h>
#undef chroot
static int(*funcptr) (const char * ) = 0;

int chroot (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "chroot");
	validate_Rdaddress( arg0, "chroot");
	validate_NULL_TYPETYPE(  arg0, "chroot");
	return funcptr(arg0);
}

int __lsb_chroot (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "chroot");
	return funcptr(arg0);
}

