// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#undef ecvt
static char *(*funcptr) (double , int , int * , int * ) = 0;

char * ecvt (double arg0 , int arg1 , int * arg2 , int * arg3 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ecvt");
	validate_NULL_TYPETYPE(arg0, "ecvt");
	validate_NULL_TYPETYPE(arg1, "ecvt");
	validate_NULL_TYPETYPE(arg2, "ecvt");
	validate_NULL_TYPETYPE(arg3, "ecvt");
	return funcptr(arg0, arg1, arg2, arg3);
}

char * lsb_ecvt (double arg0 , int arg1 , int * arg2 , int * arg3 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ecvt");
	return funcptr(arg0, arg1, arg2, arg3);
}

