// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <stdio.h>
#undef ferror
static int(*funcptr) (FILE * ) = 0;

extern int __lsb_check_params;
int ferror (FILE * arg0 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlvsym(RTLD_NEXT, "ferror", "GLIBC_2.0");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "ferror()");
		validate_RWaddress( arg0, "ferror - arg0");
		validate_NULL_TYPETYPE(  arg0, "ferror - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

