// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <fnmatch.h>
#undef fnmatch
static int(*funcptr) (const char * , const char * , int ) = 0;

int fnmatch (const char * arg0 , const char * arg1 , int arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "fnmatch");
	validate_Rdaddress( arg0, "fnmatch - arg0");
	validate_NULL_TYPETYPE(  arg0, "fnmatch - arg0");
	validate_Rdaddress( arg1, "fnmatch - arg1");
	validate_NULL_TYPETYPE(  arg1, "fnmatch - arg1");
	validate_NULL_TYPETYPE(  arg2, "fnmatch - arg2");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_fnmatch (const char * arg0 , const char * arg1 , int arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "fnmatch");
	return funcptr(arg0, arg1, arg2);
}

