// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <stddef.h>
#include <stdio.h>
#undef fread_unlocked
static size_t(*funcptr) (void * , size_t , size_t , FILE * ) = 0;

extern int __lsb_check_params;
size_t fread_unlocked (void * arg0 , size_t arg1 , size_t arg2 , FILE * arg3 )
{
	int reset_flag = __lsb_check_params;
	size_t ret_value  ;
	__lsb_output(4, "Invoking wrapper for fread_unlocked()");
	if(!funcptr)
		#if defined __i386__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.1");
		#endif
		#if defined __powerpc__ && !defined __powerpc64__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.1");
		#endif
		#if defined __s390__ && !defined __s390x__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.1");
		#endif
		#if defined __ia64__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.2");
		#endif
		#if defined __s390x__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.2");
		#endif
		#if defined __x86_64__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.2.5");
		#endif
		#if defined __powerpc64__
			funcptr = dlvsym(RTLD_NEXT, "fread_unlocked", "GLIBC_2.3");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load fread_unlocked. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "fread_unlocked() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "fread_unlocked - arg0 (__ptr)");
		}
		validate_NULL_TYPETYPE(  arg0, "fread_unlocked - arg0 (__ptr)");
		validate_NULL_TYPETYPE(  arg1, "fread_unlocked - arg1 (__size)");
		validate_NULL_TYPETYPE(  arg2, "fread_unlocked - arg2 (__n)");
		if( arg3 ) {
		validate_RWaddress( arg3, "fread_unlocked - arg3 (__stream)");
		}
		validate_NULL_TYPETYPE(  arg3, "fread_unlocked - arg3 (__stream)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

