// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stdio.h>
#undef freopen64
static FILE *(*funcptr) (const char * , const char * , FILE * ) = 0;

FILE * freopen64 (const char * arg0 , const char * arg1 , FILE * arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "freopen64");
	validate_NULL_TYPETYPE(arg0, "freopen64");
	validate_NULL_TYPETYPE(arg1, "freopen64");
	validate_NULL_TYPETYPE(arg2, "freopen64");
	return funcptr(arg0, arg1, arg2);
}

FILE * lsb_freopen64 (const char * arg0 , const char * arg1 , FILE * arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "freopen64");
	return funcptr(arg0, arg1, arg2);
}

