// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stdio.h>
#undef ftrylockfile
static int(*funcptr) (FILE * ) = 0;

int ftrylockfile (FILE * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ftrylockfile");
	validate_Rdaddress( arg0, "ftrylockfile - arg0");
	validate_NULL_TYPETYPE(  arg0, "ftrylockfile - arg0");
	return funcptr(arg0);
}

int __lsb_ftrylockfile (FILE * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "ftrylockfile");
	return funcptr(arg0);
}

