GEN_FUNCS = \
_Exit.o \
__assert_fail.o \
__confstr_chk.o \
__ctype_b_loc.o \
__ctype_get_mb_cur_max.o \
__ctype_tolower_loc.o \
__ctype_toupper_loc.o \
__errno_location.o \
__fgets_chk.o \
__fgets_unlocked_chk.o \
__fgetws_chk.o \
__fgetws_unlocked_chk.o \
__fpending.o \
__fxstat.o \
__fxstat64.o \
__fxstatat.o \
__fxstatat64.o \
__getcwd_chk.o \
__getgroups_chk.o \
__gethostname_chk.o \
__getlogin_r_chk.o \
__getpagesize.o \
__getpgid.o \
__h_errno_location.o \
__isinf.o \
__isinff.o \
__isinfl.o \
__isnan.o \
__isnanf.o \
__isnanl.o \
__libc_current_sigrtmax.o \
__libc_current_sigrtmin.o \
__lxstat.o \
__lxstat64.o \
__mbsnrtowcs_chk.o \
__mbsrtowcs_chk.o \
__mbstowcs_chk.o \
__memcpy_chk.o \
__memmove_chk.o \
__mempcpy.o \
__mempcpy_chk.o \
__memset_chk.o \
__pread64_chk.o \
__pread_chk.o \
__read_chk.o \
__readlink_chk.o \
__realpath_chk.o \
__recv_chk.o \
__recvfrom_chk.o \
__register_atfork.o \
__stpcpy.o \
__stpcpy_chk.o \
__stpncpy_chk.o \
__strcat_chk.o \
__strcpy_chk.o \
__strncat_chk.o \
__strncpy_chk.o \
__strtod_internal.o \
__strtof_internal.o \
__strtok_r.o \
__strtol_internal.o \
__strtold_internal.o \
__strtoll_internal.o \
__strtoul_internal.o \
__strtoull_internal.o \
__sysv_signal.o \
__ttyname_r_chk.o \
__vfprintf_chk.o \
__vsyslog_chk.o \
__wcpcpy_chk.o \
__wcpncpy_chk.o \
__wcrtomb_chk.o \
__wcscat_chk.o \
__wcscpy_chk.o \
__wcsncat_chk.o \
__wcsncpy_chk.o \
__wcsnrtombs_chk.o \
__wcsrtombs_chk.o \
__wcstod_internal.o \
__wcstof_internal.o \
__wcstol_internal.o \
__wcstold_internal.o \
__wcstombs_chk.o \
__wcstoul_internal.o \
__wctomb_chk.o \
__wmemcpy_chk.o \
__wmemmove_chk.o \
__wmempcpy_chk.o \
__wmemset_chk.o \
__xmknod.o \
__xmknodat.o \
__xstat.o \
__xstat64.o \
_exit.o \
_longjmp.o \
_setjmp.o \
_tolower.o \
_toupper.o \
a64l.o \
abort.o \
abs.o \
accept.o \
access.o \
acct.o \
adjtime.o \
alarm.o \
alphasort.o \
alphasort64.o \
argz_add.o \
argz_add_sep.o \
argz_append.o \
argz_count.o \
argz_create.o \
argz_create_sep.o \
argz_delete.o \
argz_extract.o \
argz_insert.o \
argz_next.o \
argz_replace.o \
argz_stringify.o \
asctime.o \
asctime_r.o \
atof.o \
atoi.o \
atol.o \
atoll.o \
authnone_create.o \
backtrace.o \
backtrace_symbols.o \
backtrace_symbols_fd.o \
bcmp.o \
bcopy.o \
bind.o \
bind_textdomain_codeset.o \
bindresvport.o \
bindtextdomain.o \
brk.o \
bsd_signal.o \
bsearch.o \
btowc.o \
bzero.o \
callrpc.o \
catclose.o \
catgets.o \
catopen.o \
cfgetispeed.o \
cfgetospeed.o \
cfmakeraw.o \
cfsetispeed.o \
cfsetospeed.o \
cfsetspeed.o \
chdir.o \
chmod.o \
chown.o \
chroot.o \
clearerr.o \
clearerr_unlocked.o \
clnt_create.o \
clnt_pcreateerror.o \
clnt_perrno.o \
clnt_perror.o \
clnt_spcreateerror.o \
clnt_sperrno.o \
clnt_sperror.o \
clntraw_create.o \
clnttcp_create.o \
clntudp_bufcreate.o \
clntudp_create.o \
clock.o \
close.o \
closedir.o \
closelog.o \
confstr.o \
connect.o \
creat.o \
creat64.o \
ctermid.o \
ctime.o \
ctime_r.o \
cuserid.o \
daemon.o \
dcgettext.o \
dcngettext.o \
dgettext.o \
difftime.o \
dirfd.o \
dirname.o \
div.o \
dl_iterate_phdr.o \
dngettext.o \
drand48.o \
drand48_r.o \
dup.o \
dup2.o \
duplocale.o \
ecvt.o \
endgrent.o \
endprotoent.o \
endpwent.o \
endservent.o \
endutent.o \
endutxent.o \
envz_add.o \
envz_entry.o \
envz_get.o \
envz_merge.o \
envz_remove.o \
envz_strip.o \
epoll_create.o \
epoll_ctl.o \
epoll_wait.o \
erand48.o \
erand48_r.o \
execv.o \
execve.o \
execvp.o \
exit.o \
faccessat.o \
fchdir.o \
fchmod.o \
fchmodat.o \
fchown.o \
fchownat.o \
fclose.o \
fcvt.o \
fdatasync.o \
fdopen.o \
fdopendir.o \
feof.o \
feof_unlocked.o \
ferror.o \
ferror_unlocked.o \
fexecve.o \
ffs.o \
fgetc.o \
fgetc_unlocked.o \
fgetpos.o \
fgetpos64.o \
fgets.o \
fgets_unlocked.o \
fgetwc.o \
fgetwc_unlocked.o \
fgetws.o \
fgetws_unlocked.o \
fileno.o \
fileno_unlocked.o \
flock.o \
flockfile.o \
fmemopen.o \
fmtmsg.o \
fnmatch.o \
fopen.o \
fopen64.o \
fork.o \
fpathconf.o \
fputs.o \
fputs_unlocked.o \
fputwc.o \
fputwc_unlocked.o \
fputws.o \
fputws_unlocked.o \
fread.o \
fread_unlocked.o \
freeaddrinfo.o \
freeifaddrs.o \
freelocale.o \
freopen.o \
freopen64.o \
fseek.o \
fseeko.o \
fseeko64.o \
fsetpos.o \
fsetpos64.o \
fstatfs.o \
fstatfs64.o \
fstatvfs.o \
fstatvfs64.o \
fsync.o \
ftell.o \
ftello.o \
ftello64.o \
ftime.o \
ftok.o \
ftruncate.o \
ftruncate64.o \
ftrylockfile.o \
ftw.o \
ftw64.o \
funlockfile.o \
futimens.o \
futimes.o \
fwide.o \
fwrite.o \
fwrite_unlocked.o \
gai_strerror.o \
gcvt.o \
getaddrinfo.o \
getc.o \
getc_unlocked.o \
getchar.o \
getchar_unlocked.o \
getcontext.o \
getcwd.o \
getdate.o \
getdelim.o \
getdomainname.o \
getdtablesize.o \
getegid.o \
geteuid.o \
getgid.o \
getgrent.o \
getgrent_r.o \
getgrgid.o \
getgrgid_r.o \
getgrnam.o \
getgrnam_r.o \
getgrouplist.o \
getgroups.o \
gethostbyaddr.o \
gethostbyaddr_r.o \
gethostbyname.o \
gethostbyname2.o \
gethostbyname2_r.o \
gethostbyname_r.o \
gethostid.o \
gethostname.o \
getifaddrs.o \
getitimer.o \
getline.o \
getloadavg.o \
getlogin.o \
getlogin_r.o \
getnameinfo.o \
getopt.o \
getopt_long.o \
getopt_long_only.o \
getpagesize.o \
getpeername.o \
getpgid.o \
getpgrp.o \
getpid.o \
getppid.o \
getpriority.o \
getprotobyname.o \
getprotobyname_r.o \
getprotobynumber.o \
getprotobynumber_r.o \
getprotoent.o \
getprotoent_r.o \
getpwent.o \
getpwent_r.o \
getpwnam.o \
getpwnam_r.o \
getpwuid.o \
getpwuid_r.o \
getrlimit.o \
getrlimit64.o \
getrusage.o \
getservbyname.o \
getservbyname_r.o \
getservbyport.o \
getservbyport_r.o \
getservent.o \
getservent_r.o \
getsid.o \
getsockname.o \
getsockopt.o \
getsubopt.o \
gettext.o \
gettimeofday.o \
getuid.o \
getutent.o \
getutent_r.o \
getutxent.o \
getutxid.o \
getutxline.o \
getw.o \
getwc.o \
getwc_unlocked.o \
getwchar.o \
getwchar_unlocked.o \
getwd.o \
glob.o \
glob64.o \
globfree.o \
globfree64.o \
gmtime.o \
gmtime_r.o \
gnu_get_libc_release.o \
gnu_get_libc_version.o \
grantpt.o \
hcreate.o \
hcreate_r.o \
hdestroy.o \
hdestroy_r.o \
hsearch.o \
hsearch_r.o \
htonl.o \
htons.o \
iconv.o \
iconv_close.o \
iconv_open.o \
if_freenameindex.o \
if_indextoname.o \
if_nameindex.o \
if_nametoindex.o \
imaxabs.o \
imaxdiv.o \
index.o \
inet_addr.o \
inet_aton.o \
inet_ntoa.o \
inet_ntop.o \
inet_pton.o \
initgroups.o \
initstate.o \
initstate_r.o \
inotify_add_watch.o \
inotify_init.o \
inotify_rm_watch.o \
insque.o \
isalnum.o \
isalnum_l.o \
isalpha.o \
isalpha_l.o \
isascii.o \
isatty.o \
isblank.o \
isblank_l.o \
iscntrl.o \
iscntrl_l.o \
isdigit.o \
isdigit_l.o \
isgraph.o \
isgraph_l.o \
islower.o \
islower_l.o \
isprint.o \
isprint_l.o \
ispunct.o \
ispunct_l.o \
isspace.o \
isspace_l.o \
isupper.o \
isupper_l.o \
iswalnum.o \
iswalnum_l.o \
iswalpha.o \
iswalpha_l.o \
iswblank.o \
iswblank_l.o \
iswcntrl.o \
iswcntrl_l.o \
iswctype.o \
iswctype_l.o \
iswdigit.o \
iswdigit_l.o \
iswgraph.o \
iswgraph_l.o \
iswlower.o \
iswlower_l.o \
iswprint.o \
iswprint_l.o \
iswpunct.o \
iswpunct_l.o \
iswspace.o \
iswspace_l.o \
iswupper.o \
iswupper_l.o \
iswxdigit.o \
iswxdigit_l.o \
isxdigit.o \
isxdigit_l.o \
jrand48.o \
jrand48_r.o \
key_decryptsession.o \
kill.o \
killpg.o \
l64a.o \
labs.o \
lchown.o \
lcong48.o \
lcong48_r.o \
ldiv.o \
lfind.o \
link.o \
linkat.o \
listen.o \
llabs.o \
lldiv.o \
localeconv.o \
localtime.o \
localtime_r.o \
lockf.o \
lockf64.o \
longjmp.o \
lrand48.o \
lrand48_r.o \
lsearch.o \
lseek.o \
lseek64.o \
lutimes.o \
mblen.o \
mbrlen.o \
mbrtowc.o \
mbsinit.o \
mbsnrtowcs.o \
mbsrtowcs.o \
mbstowcs.o \
mbtowc.o \
memccpy.o \
memchr.o \
memcmp.o \
memcpy.o \
memmem.o \
memmove.o \
memrchr.o \
memset.o \
mkdir.o \
mkdirat.o \
mkdtemp.o \
mkfifo.o \
mkfifoat.o \
mkstemp.o \
mkstemp64.o \
mktemp.o \
mktime.o \
mlock.o \
mlockall.o \
mmap64.o \
mprotect.o \
mrand48.o \
mrand48_r.o \
msgctl.o \
msgget.o \
msgrcv.o \
msgsnd.o \
msync.o \
munlock.o \
munlockall.o \
nanosleep.o \
newlocale.o \
nftw.o \
nftw64.o \
ngettext.o \
nice.o \
nl_langinfo.o \
nrand48.o \
nrand48_r.o \
ntohl.o \
ntohs.o \
open_memstream.o \
open_wmemstream.o \
opendir.o \
openlog.o \
pathconf.o \
pause.o \
pclose.o \
perror.o \
pipe.o \
pmap_getport.o \
pmap_set.o \
pmap_unset.o \
poll.o \
popen.o \
posix_fadvise.o \
posix_fadvise64.o \
posix_fallocate.o \
posix_fallocate64.o \
posix_madvise.o \
posix_memalign.o \
posix_openpt.o \
posix_spawn.o \
posix_spawn_file_actions_addclose.o \
posix_spawn_file_actions_adddup2.o \
posix_spawn_file_actions_addopen.o \
posix_spawn_file_actions_destroy.o \
posix_spawn_file_actions_init.o \
posix_spawnattr_destroy.o \
posix_spawnattr_getflags.o \
posix_spawnattr_getpgroup.o \
posix_spawnattr_getschedparam.o \
posix_spawnattr_getschedpolicy.o \
posix_spawnattr_getsigdefault.o \
posix_spawnattr_getsigmask.o \
posix_spawnattr_init.o \
posix_spawnattr_setflags.o \
posix_spawnattr_setpgroup.o \
posix_spawnattr_setschedparam.o \
posix_spawnattr_setschedpolicy.o \
posix_spawnattr_setsigdefault.o \
posix_spawnattr_setsigmask.o \
posix_spawnp.o \
pread.o \
pread64.o \
pselect.o \
psiginfo.o \
psignal.o \
ptsname.o \
putchar.o \
putchar_unlocked.o \
putenv.o \
puts.o \
pututxline.o \
putw.o \
putwc.o \
putwc_unlocked.o \
putwchar.o \
putwchar_unlocked.o \
pwrite.o \
pwrite64.o \
qsort.o \
raise.o \
rand.o \
rand_r.o \
random.o \
random_r.o \
read.o \
readdir.o \
readdir64.o \
readdir64_r.o \
readdir_r.o \
readlink.o \
readlinkat.o \
readv.o \
realpath.o \
recv.o \
recvfrom.o \
recvmsg.o \
regcomp.o \
regerror.o \
regexec.o \
regfree.o \
remove.o \
remque.o \
rename.o \
renameat.o \
rewind.o \
rewinddir.o \
rindex.o \
rmdir.o \
sbrk.o \
scandir.o \
scandir64.o \
sched_get_priority_max.o \
sched_get_priority_min.o \
sched_getaffinity.o \
sched_getparam.o \
sched_getscheduler.o \
sched_rr_get_interval.o \
sched_setaffinity.o \
sched_setparam.o \
sched_setscheduler.o \
sched_yield.o \
seed48.o \
seed48_r.o \
seekdir.o \
select.o \
semget.o \
semop.o \
send.o \
sendfile.o \
sendfile64.o \
sendmsg.o \
sendto.o \
setbuf.o \
setbuffer.o \
setcontext.o \
setegid.o \
setenv.o \
seteuid.o \
setgid.o \
setgrent.o \
setgroups.o \
sethostname.o \
setitimer.o \
setlocale.o \
setlogmask.o \
setpgid.o \
setpgrp.o \
setpriority.o \
setprotoent.o \
setpwent.o \
setregid.o \
setreuid.o \
setrlimit.o \
setrlimit64.o \
setservent.o \
setsid.o \
setsockopt.o \
setstate.o \
setstate_r.o \
setuid.o \
setutent.o \
setutxent.o \
setvbuf.o \
shmat.o \
shmctl.o \
shmdt.o \
shmget.o \
shutdown.o \
sigaction.o \
sigaddset.o \
sigaltstack.o \
sigandset.o \
sigdelset.o \
sigemptyset.o \
sigfillset.o \
sighold.o \
sigignore.o \
siginterrupt.o \
sigisemptyset.o \
sigismember.o \
siglongjmp.o \
signal.o \
sigorset.o \
sigpending.o \
sigprocmask.o \
sigqueue.o \
sigrelse.o \
sigreturn.o \
sigset.o \
sigsuspend.o \
sigtimedwait.o \
sigwait.o \
sigwaitinfo.o \
sleep.o \
sockatmark.o \
socket.o \
socketpair.o \
srand.o \
srand48.o \
srand48_r.o \
srandom.o \
srandom_r.o \
statfs.o \
statfs64.o \
statvfs.o \
statvfs64.o \
stime.o \
stpcpy.o \
stpncpy.o \
strcasecmp.o \
strcasecmp_l.o \
strcasestr.o \
strcat.o \
strchr.o \
strcmp.o \
strcoll.o \
strcoll_l.o \
strcpy.o \
strcspn.o \
strdup.o \
strerror.o \
strerror_l.o \
strftime.o \
strftime_l.o \
strncasecmp.o \
strncasecmp_l.o \
strncat.o \
strncmp.o \
strncpy.o \
strndup.o \
strnlen.o \
strpbrk.o \
strptime.o \
strrchr.o \
strsep.o \
strsignal.o \
strspn.o \
strstr.o \
strtod.o \
strtof.o \
strtoimax.o \
strtok.o \
strtok_r.o \
strtol.o \
strtold.o \
strtoll.o \
strtoq.o \
strtoul.o \
strtoull.o \
strtoumax.o \
strtouq.o \
strxfrm.o \
strxfrm_l.o \
svc_getreqset.o \
svc_register.o \
svc_run.o \
svc_sendreply.o \
svcerr_auth.o \
svcerr_decode.o \
svcerr_noproc.o \
svcerr_noprog.o \
svcerr_progvers.o \
svcerr_systemerr.o \
svcerr_weakauth.o \
svcfd_create.o \
svcraw_create.o \
svctcp_create.o \
svcudp_create.o \
swab.o \
swapcontext.o \
symlink.o \
symlinkat.o \
sync.o \
sysconf.o \
sysinfo.o \
system.o \
tcdrain.o \
tcflow.o \
tcflush.o \
tcgetattr.o \
tcgetpgrp.o \
tcgetsid.o \
tcsendbreak.o \
tcsetattr.o \
tcsetpgrp.o \
tdelete.o \
telldir.o \
tempnam.o \
textdomain.o \
tfind.o \
time.o \
times.o \
tmpfile.o \
tmpfile64.o \
tmpnam.o \
toascii.o \
tolower.o \
tolower_l.o \
toupper.o \
toupper_l.o \
towctrans.o \
towctrans_l.o \
towlower.o \
towlower_l.o \
towupper.o \
towupper_l.o \
truncate.o \
truncate64.o \
tsearch.o \
ttyname.o \
ttyname_r.o \
twalk.o \
tzset.o \
ualarm.o \
umask.o \
uname.o \
ungetc.o \
ungetwc.o \
unlink.o \
unlinkat.o \
unlockpt.o \
unsetenv.o \
uselocale.o \
usleep.o \
utime.o \
utimensat.o \
utimes.o \
utmpname.o \
verrx.o \
vfork.o \
vsyslog.o \
wait.o \
wait4.o \
waitid.o \
waitpid.o \
wcpcpy.o \
wcpncpy.o \
wcrtomb.o \
wcscasecmp.o \
wcscasecmp_l.o \
wcscat.o \
wcschr.o \
wcscmp.o \
wcscoll.o \
wcscoll_l.o \
wcscpy.o \
wcscspn.o \
wcsdup.o \
wcsftime.o \
wcslen.o \
wcsncasecmp.o \
wcsncasecmp_l.o \
wcsncat.o \
wcsncmp.o \
wcsncpy.o \
wcsnlen.o \
wcsnrtombs.o \
wcspbrk.o \
wcsrchr.o \
wcsrtombs.o \
wcsspn.o \
wcsstr.o \
wcstod.o \
wcstof.o \
wcstoimax.o \
wcstok.o \
wcstol.o \
wcstold.o \
wcstoll.o \
wcstombs.o \
wcstoq.o \
wcstoul.o \
wcstoull.o \
wcstoumax.o \
wcstouq.o \
wcswcs.o \
wcswidth.o \
wcsxfrm.o \
wcsxfrm_l.o \
wctob.o \
wctomb.o \
wctrans.o \
wctrans_l.o \
wctype.o \
wctype_l.o \
wcwidth.o \
wmemchr.o \
wmemcmp.o \
wmemcpy.o \
wmemmove.o \
wmemset.o \
wordexp.o \
wordfree.o \
write.o \
writev.o \
xdr_accepted_reply.o \
xdr_array.o \
xdr_bool.o \
xdr_bytes.o \
xdr_callhdr.o \
xdr_callmsg.o \
xdr_char.o \
xdr_double.o \
xdr_enum.o \
xdr_float.o \
xdr_free.o \
xdr_int.o \
xdr_long.o \
xdr_opaque.o \
xdr_opaque_auth.o \
xdr_pointer.o \
xdr_reference.o \
xdr_rejected_reply.o \
xdr_replymsg.o \
xdr_short.o \
xdr_string.o \
xdr_u_char.o \
xdr_u_int.o \
xdr_u_long.o \
xdr_u_short.o \
xdr_union.o \
xdr_vector.o \
xdr_void.o \
xdr_wrapstring.o \
xdrmem_create.o \
xdrrec_create.o \
xdrrec_endofrecord.o \
xdrrec_eof.o \
xdrrec_skiprecord.o \
xdrstdio_create.o 