// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stdio.h>
#undef getchar
static int(*funcptr) () = 0;

int getchar ()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "getchar");
	return funcptr();
}

int __lsb_getchar ()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "getchar");
	return funcptr();
}

