// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <sys/types.h>
#include <grp.h>
#undef getgrgid
static struct group *(*funcptr) (gid_t ) = 0;

extern int __lsb_check_params;
struct group * getgrgid (gid_t arg0 )
{
	int reset_flag = __lsb_check_params;
	struct group * ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "getgrgid");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		validate_NULL_TYPETYPE(  arg0, "getgrgid - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

