// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <netdb.h>
#undef gethostbyname
static struct hostent *(*funcptr) (const char * ) = 0;

struct hostent * gethostbyname (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gethostbyname");
	validate_Rdaddress( arg0, "gethostbyname");
	validate_NULL_TYPETYPE(  arg0, "gethostbyname");
	return funcptr(arg0);
}

struct hostent * __lsb_gethostbyname (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gethostbyname");
	return funcptr(arg0);
}

