// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <pwd.h>
#undef getpwent
static struct passwd *(*funcptr) () = 0;

struct passwd * getpwent ()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "getpwent");
	return funcptr();
}

struct passwd * __lsb_getpwent ()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "getpwent");
	return funcptr();
}

