// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <utmpx.h>
#undef getutxent
static struct utmpx *(*funcptr) () = 0;

extern int __lsb_check_params;
struct utmpx * getutxent ()
{
	int reset_flag = __lsb_check_params;
	struct utmpx * ret_value  ;
	if(!funcptr)
		funcptr = dlvsym(RTLD_NEXT, "getutxent", "GLIBC_2.1");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "getutxent()");
	}
	ret_value = funcptr();
	__lsb_check_params = reset_flag;
	return ret_value;
}

