// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <utmpx.h>
#undef getutxline
static struct utmpx *(*funcptr) (const struct utmpx * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
struct utmpx * getutxline (const struct utmpx * arg0 )
{
	int reset_flag = __lsb_check_params;
	struct utmpx * ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "getutxline");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "getutxline()");
	validate_Rdaddress( arg0, "getutxline - arg0");
		validate_NULL_TYPETYPE(  arg0, "getutxline - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

