// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <sys/types.h>
#include <time.h>
#undef gmtime
static struct tm *(*funcptr) (const time_t * ) = 0;

struct tm * gmtime (const time_t * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gmtime");
	validate_NULL_TYPETYPE(arg0, "gmtime");
	return funcptr(arg0);
}

struct tm * lsb_gmtime (const time_t * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gmtime");
	return funcptr(arg0);
}

