// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <inttypes.h>
#undef htons
static uint16_t(*funcptr) (uint16_t ) = 0;

uint16_t htons (uint16_t arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "htons");
	validate_NULL_TYPETYPE(arg0, "htons");
	return funcptr(arg0);
}

uint16_t lsb_htons (uint16_t arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "htons");
	return funcptr(arg0);
}

