// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <net/if.h>
#undef if_freenameindex
static void(*funcptr) () = 0;

extern int __lsb_check_params;
void if_freenameindex ()
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "if_freenameindex");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "if_freenameindex()");
	}
	funcptr();
	__lsb_check_params = reset_flag;
}

