// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(const char *) = 0;

int logout(const char * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "logout");
	validate_NULL_TYPETYPE(arg0, "logout");
	return funcptr(arg0);
}

int lsb_logout(const char * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "logout");
	return funcptr(arg0);
}

