// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <stdlib.h>
#undef lrand48_r
static int(*funcptr) (struct drand48_data * , long int * ) = 0;

extern int __lsb_check_params;
int lrand48_r (struct drand48_data * arg0 , long int * arg1 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for lrand48_r()");
	if(!funcptr)
		#if defined __i386__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.0");
		#endif
		#if defined __ia64__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.2");
		#endif
		#if defined __powerpc__ && !defined __powerpc64__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.0");
		#endif
		#if defined __powerpc64__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.3");
		#endif
		#if defined __s390__ && !defined __s390x__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.0");
		#endif
		#if defined __x86_64__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.2.5");
		#endif
		#if defined __s390x__
			funcptr = dlvsym(RTLD_NEXT, "lrand48_r", "GLIBC_2.2");
		#endif
	if(!funcptr) {
		__lsb_output(-1, "Failed to load lrand48_r. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "lrand48_r() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "lrand48_r - arg0 (__buffer)");
		}
		validate_NULL_TYPETYPE(  arg0, "lrand48_r - arg0 (__buffer)");
		if( arg1 ) {
		validate_RWaddress( arg1, "lrand48_r - arg1 (__result)");
		}
		validate_NULL_TYPETYPE(  arg1, "lrand48_r - arg1 (__result)");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

