// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <unistd.h>
#undef mkstemp
static int(*funcptr) (char * ) = 0;

int mkstemp (char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "mkstemp");
	validate_Rdaddress( arg0, "mkstemp - arg0");
	validate_NULL_TYPETYPE(  arg0, "mkstemp - arg0");
	return funcptr(arg0);
}

int __lsb_mkstemp (char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "mkstemp");
	return funcptr(arg0);
}

