// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <unistd.h>
#undef pathconf
static long(*funcptr) (const char * , int ) = 0;

long pathconf (const char * arg0 , int arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pathconf");
	validate_Rdaddress( arg0, "pathconf - arg0");
	validate_NULL_TYPETYPE(  arg0, "pathconf - arg0");
	validate_NULL_TYPETYPE(  arg1, "pathconf - arg1");
	return funcptr(arg0, arg1);
}

long __lsb_pathconf (const char * arg0 , int arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pathconf");
	return funcptr(arg0, arg1);
}

