// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stdio.h>
#undef pclose
static int(*funcptr) (FILE * ) = 0;

int pclose (FILE * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pclose");
	validate_NULL_TYPETYPE(arg0, "pclose");
	return funcptr(arg0);
}

int lsb_pclose (FILE * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pclose");
	return funcptr(arg0);
}

