// Generated by gen_lib.pl

#include "../tests/type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(void) = 0;

int rand(void arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "rand");
	validate_NULL_TYPETYPE(arg0, "rand");
	return funcptr(arg0);
}

int lsb_rand(void arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "rand");
	return funcptr(arg0);
}

