// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <dirent.h>
#undef readdir64
static struct dirent64 *(*funcptr) (DIR * ) = 0;

extern int __lsb_check_params;
struct dirent64 * readdir64 (DIR * arg0 )
{
	int reset_flag = __lsb_check_params;
	struct dirent64 * ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "readdir64");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	validate_Rdaddress( arg0, "readdir64 - arg0");
		validate_NULL_TYPETYPE(  arg0, "readdir64 - arg0");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

