// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <sys/types.h>
#include <sched.h>
#undef sched_getparam
static int(*funcptr) (pid_t , struct sched_param * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
int sched_getparam (pid_t arg0 , struct sched_param * arg1 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sched_getparam");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "sched_getparam()");
		validate_NULL_TYPETYPE(  arg0, "sched_getparam - arg0");
	validate_RWaddress( arg1, "sched_getparam - arg1");
		validate_NULL_TYPETYPE(  arg1, "sched_getparam - arg1");
	}
	ret_value = funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
	return ret_value;
}

