// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <signal.h>
#undef sigaction
static int(*funcptr) (int , const struct sigaction * , struct sigaction * ) = 0;

int sigaction (int arg0 , const struct sigaction * arg1 , struct sigaction * arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sigaction");
	validate_NULL_TYPETYPE(  arg0, "sigaction - arg0");
	validate_Rdaddress( arg1, "sigaction - arg1");
	validate_NULL_TYPETYPE(  arg1, "sigaction - arg1");
	validate_Rdaddress( arg2, "sigaction - arg2");
	validate_NULL_TYPETYPE(  arg2, "sigaction - arg2");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_sigaction (int arg0 , const struct sigaction * arg1 , struct sigaction * arg2 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sigaction");
	return funcptr(arg0, arg1, arg2);
}

