// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <signal.h>
#undef sigisemptyset
static int(*funcptr) (const sigset_t * ) = 0;

int sigisemptyset (const sigset_t * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sigisemptyset");
	validate_NULL_TYPETYPE(arg0, "sigisemptyset");
	return funcptr(arg0);
}

int lsb_sigisemptyset (const sigset_t * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sigisemptyset");
	return funcptr(arg0);
}

