// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <sys/socket.h>
#undef socket
static int(*funcptr) (int , int , int ) = 0;

extern int __lsb_check_params;
int socket (int arg0 , int arg1 , int arg2 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlvsym(RTLD_NEXT, "socket", "GLIBC_2.0");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "socket()");
		validate_NULL_TYPETYPE(  arg0, "socket - arg0");
		validate_NULL_TYPETYPE(  arg1, "socket - arg1");
		validate_NULL_TYPETYPE(  arg2, "socket - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

