// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
static void(*funcptr)(SVCXPRT *) = 0;

void svcerr_systemerr(SVCXPRT * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "svcerr_systemerr");
	validate_NULL_TYPETYPE(arg0, "svcerr_systemerr");
	funcptr(arg0);
}

void lsb_svcerr_systemerr(SVCXPRT * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "svcerr_systemerr");
	funcptr(arg0);
}

