// Generated by gen_lib.pl

#include "../tests/type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(void) = 0;

int sync(void arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sync");
	validate_NULL_TYPETYPE(arg0, "sync");
	return funcptr(arg0);
}

int lsb_sync(void arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "sync");
	return funcptr(arg0);
}

