// Generated by gen_lib.pl

#include "../tests/type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(tms *) = 0;

clock_t times(tms * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "times");
	validate_NULL_TYPETYPE(arg0, "times");
	return funcptr(arg0);
}

clock_t lsb_times(tms * arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "times");
	return funcptr(arg0);
}

