// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <time.h>
#undef tzset
static void(*funcptr) () = 0;

void tzset ()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "tzset");
	funcptr();
}

void __lsb_tzset ()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "tzset");
	funcptr();
}

