// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stdlib.h>
#undef unsetenv
static int(*funcptr) (const char * ) = 0;

int unsetenv (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "unsetenv");
	validate_NULL_TYPETYPE(arg0, "unsetenv");
	return funcptr(arg0);
}

int lsb_unsetenv (const char * arg0 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "unsetenv");
	return funcptr(arg0);
}

