// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <stdarg.h>
#include <stdio.h>
#undef vprintf
static int(*funcptr) (const char * , va_list ) = 0;

int vprintf (const char * arg0 , va_list arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "vprintf");
	validate_Rdaddress( arg0, "vprintf - arg0");
	validate_NULL_TYPETYPE(  arg0, "vprintf - arg0");
	validate_NULL_TYPETYPE(  arg1, "vprintf - arg1");
	return funcptr(arg0, arg1);
}

int __lsb_vprintf (const char * arg0 , va_list arg1 )
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "vprintf");
	return funcptr(arg0, arg1);
}

