// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <stddef.h>
#include <wchar.h>
#undef wmemmove
static wchar_t *(*funcptr) (wchar_t * , const wchar_t * , size_t ) = 0;

extern int __lsb_check_params;
wchar_t * wmemmove (wchar_t * arg0 , const wchar_t * arg1 , size_t arg2 )
{
	int reset_flag = __lsb_check_params;
	wchar_t * ret_value  ;
	if(!funcptr)
		funcptr = dlvsym(RTLD_NEXT, "wmemmove", "GLIBC_2.0");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "wmemmove()");
		validate_RWaddress( arg0, "wmemmove - arg0");
		validate_NULL_TYPETYPE(  arg0, "wmemmove - arg0");
		validate_Rdaddress( arg1, "wmemmove - arg1");
		validate_NULL_TYPETYPE(  arg1, "wmemmove - arg1");
		validate_NULL_TYPETYPE(  arg2, "wmemmove - arg2");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

