GEN_FUNCS = \
NSS_CmpCertChainWCANames.o \
NSS_FindCertKEAType.o \
NSS_GetClientAuthData.o \
SSL_AuthCertificate.o \
SSL_AuthCertificateHook.o \
SSL_BadCertHook.o \
SSL_CipherPolicyGet.o \
SSL_CipherPolicySet.o \
SSL_CipherPrefGet.o \
SSL_CipherPrefGetDefault.o \
SSL_CipherPrefSet.o \
SSL_CipherPrefSetDefault.o \
SSL_ClearSessionCache.o \
SSL_ConfigMPServerSIDCache.o \
SSL_ConfigSecureServer.o \
SSL_ConfigServerSessionIDCache.o \
SSL_DataPending.o \
SSL_ForceHandshake.o \
SSL_GetClientAuthDataHook.o \
SSL_GetSessionID.o \
SSL_HandshakeCallback.o \
SSL_ImportFD.o \
SSL_InheritMPServerSIDCache.o \
SSL_InvalidateSession.o \
SSL_OptionGet.o \
SSL_OptionGetDefault.o \
SSL_OptionSet.o \
SSL_OptionSetDefault.o \
SSL_PeerCertificate.o \
SSL_ReHandshake.o \
SSL_ResetHandshake.o \
SSL_RevealPinArg.o \
SSL_RevealURL.o \
SSL_SecurityStatus.o \
SSL_SetPKCS11PinArg.o \
SSL_SetSockPeerID.o \
SSL_SetURL.o 