GEN_FUNCS = \
XActivateScreenSaver.o \
XAddConnectionWatch.o \
XAddExtension.o \
XAddHost.o \
XAddHosts.o \
XAddPixel.o \
XAddToExtensionList.o \
XAddToSaveSet.o \
XAllPlanes.o \
XAllocClassHint.o \
XAllocColor.o \
XAllocColorCells.o \
XAllocColorPlanes.o \
XAllocIconSize.o \
XAllocNamedColor.o \
XAllocSizeHints.o \
XAllocStandardColormap.o \
XAllocWMHints.o \
XAllowEvents.o \
XAutoRepeatOff.o \
XAutoRepeatOn.o \
XBaseFontNameListOfFontSet.o \
XBell.o \
XBitmapBitOrder.o \
XBitmapPad.o \
XBitmapUnit.o \
XBlackPixel.o \
XBlackPixelOfScreen.o \
XCellsOfScreen.o \
XChangeActivePointerGrab.o \
XChangeGC.o \
XChangeKeyboardControl.o \
XChangeKeyboardMapping.o \
XChangePointerControl.o \
XChangeProperty.o \
XChangeSaveSet.o \
XChangeWindowAttributes.o \
XCheckIfEvent.o \
XCheckMaskEvent.o \
XCheckTypedEvent.o \
XCheckTypedWindowEvent.o \
XCheckWindowEvent.o \
XCirculateSubwindows.o \
XCirculateSubwindowsDown.o \
XCirculateSubwindowsUp.o \
XClearArea.o \
XClearWindow.o \
XClipBox.o \
XCloseDisplay.o \
XCloseIM.o \
XCloseOM.o \
XConfigureWindow.o \
XConnectionNumber.o \
XContextDependentDrawing.o \
XContextualDrawing.o \
XConvertCase.o \
XConvertSelection.o \
XCopyArea.o \
XCopyColormapAndFree.o \
XCopyGC.o \
XCopyPlane.o \
XCreateBitmapFromData.o \
XCreateColormap.o \
XCreateFontCursor.o \
XCreateFontSet.o \
XCreateGC.o \
XCreateGlyphCursor.o \
XCreateImage.o \
XCreatePixmap.o \
XCreatePixmapCursor.o \
XCreatePixmapFromBitmapData.o \
XCreateRegion.o \
XCreateSimpleWindow.o \
XCreateWindow.o \
XDefaultColormap.o \
XDefaultColormapOfScreen.o \
XDefaultDepth.o \
XDefaultDepthOfScreen.o \
XDefaultGC.o \
XDefaultGCOfScreen.o \
XDefaultRootWindow.o \
XDefaultScreen.o \
XDefaultScreenOfDisplay.o \
XDefaultString.o \
XDefaultVisual.o \
XDefaultVisualOfScreen.o \
XDefineCursor.o \
XDeleteContext.o \
XDeleteModifiermapEntry.o \
XDeleteProperty.o \
XDestroyIC.o \
XDestroyImage.o \
XDestroyOC.o \
XDestroyRegion.o \
XDestroySubwindows.o \
XDestroyWindow.o \
XDirectionalDependentDrawing.o \
XDisableAccessControl.o \
XDisplayCells.o \
XDisplayHeight.o \
XDisplayHeightMM.o \
XDisplayKeycodes.o \
XDisplayMotionBufferSize.o \
XDisplayName.o \
XDisplayOfIM.o \
XDisplayOfOM.o \
XDisplayOfScreen.o \
XDisplayPlanes.o \
XDisplayString.o \
XDisplayWidth.o \
XDisplayWidthMM.o \
XDoesBackingStore.o \
XDoesSaveUnders.o \
XDrawArc.o \
XDrawArcs.o \
XDrawImageString.o \
XDrawImageString16.o \
XDrawLine.o \
XDrawLines.o \
XDrawPoint.o \
XDrawPoints.o \
XDrawRectangle.o \
XDrawRectangles.o \
XDrawSegments.o \
XDrawString.o \
XDrawString16.o \
XDrawText.o \
XDrawText16.o \
XEHeadOfExtensionList.o \
XESetBeforeFlush.o \
XESetCloseDisplay.o \
XESetCopyGC.o \
XESetCreateFont.o \
XESetCreateGC.o \
XESetError.o \
XESetErrorString.o \
XESetEventToWire.o \
XESetFlushGC.o \
XESetFreeFont.o \
XESetFreeGC.o \
XESetPrintErrorValues.o \
XESetWireToError.o \
XESetWireToEvent.o \
XEmptyRegion.o \
XEnableAccessControl.o \
XEqualRegion.o \
XEventMaskOfScreen.o \
XEventsQueued.o \
XExtendedMaxRequestSize.o \
XExtentsOfFontSet.o \
XFetchBuffer.o \
XFetchBytes.o \
XFetchName.o \
XFillArc.o \
XFillArcs.o \
XFillPolygon.o \
XFillRectangle.o \
XFillRectangles.o \
XFilterEvent.o \
XFindContext.o \
XFindOnExtensionList.o \
XFlush.o \
XFlushGC.o \
XFontsOfFontSet.o \
XForceScreenSaver.o \
XFree.o \
XFreeColormap.o \
XFreeColors.o \
XFreeCursor.o \
XFreeExtensionList.o \
XFreeFont.o \
XFreeFontInfo.o \
XFreeFontNames.o \
XFreeFontPath.o \
XFreeFontSet.o \
XFreeGC.o \
XFreeModifiermap.o \
XFreePixmap.o \
XFreeStringList.o \
XGContextFromGC.o \
XGeometry.o \
XGetAtomName.o \
XGetAtomNames.o \
XGetClassHint.o \
XGetCommand.o \
XGetDefault.o \
XGetErrorDatabaseText.o \
XGetErrorText.o \
XGetFontPath.o \
XGetFontProperty.o \
XGetGCValues.o \
XGetGeometry.o \
XGetIconName.o \
XGetIconSizes.o \
XGetImage.o \
XGetInputFocus.o \
XGetKeyboardControl.o \
XGetKeyboardMapping.o \
XGetModifierMapping.o \
XGetMotionEvents.o \
XGetNormalHints.o \
XGetPixel.o \
XGetPointerControl.o \
XGetPointerMapping.o \
XGetRGBColormaps.o \
XGetScreenSaver.o \
XGetSelectionOwner.o \
XGetSizeHints.o \
XGetStandardColormap.o \
XGetSubImage.o \
XGetTextProperty.o \
XGetTransientForHint.o \
XGetVisualInfo.o \
XGetWMClientMachine.o \
XGetWMColormapWindows.o \
XGetWMHints.o \
XGetWMIconName.o \
XGetWMName.o \
XGetWMNormalHints.o \
XGetWMProtocols.o \
XGetWMSizeHints.o \
XGetWindowAttributes.o \
XGetWindowProperty.o \
XGetZoomHints.o \
XGrabButton.o \
XGrabKey.o \
XGrabKeyboard.o \
XGrabPointer.o \
XGrabServer.o \
XHeightMMOfScreen.o \
XHeightOfScreen.o \
XIMOfIC.o \
XIconifyWindow.o \
XIfEvent.o \
XImageByteOrder.o \
XInitExtension.o \
XInitImage.o \
XInitThreads.o \
XInsertModifiermapEntry.o \
XInstallColormap.o \
XInternAtom.o \
XInternAtoms.o \
XInternalConnectionNumbers.o \
XIntersectRegion.o \
XKeycodeToKeysym.o \
XKeysymToKeycode.o \
XKeysymToString.o \
XKillClient.o \
XLastKnownRequestProcessed.o \
XListDepths.o \
XListExtensions.o \
XListFonts.o \
XListFontsWithInfo.o \
XListHosts.o \
XListInstalledColormaps.o \
XListPixmapFormats.o \
XListProperties.o \
XLoadFont.o \
XLoadQueryFont.o \
XLocaleOfFontSet.o \
XLocaleOfIM.o \
XLocaleOfOM.o \
XLockDisplay.o \
XLookupColor.o \
XLookupKeysym.o \
XLookupString.o \
XLowerWindow.o \
XMapRaised.o \
XMapSubwindows.o \
XMapWindow.o \
XMaskEvent.o \
XMatchVisualInfo.o \
XMaxCmapsOfScreen.o \
XMaxRequestSize.o \
XMinCmapsOfScreen.o \
XMoveResizeWindow.o \
XMoveWindow.o \
XNewModifiermap.o \
XNextEvent.o \
XNextRequest.o \
XNoOp.o \
XOMOfOC.o \
XOffsetRegion.o \
XOpenDisplay.o \
XOpenIM.o \
XOpenOM.o \
XParseColor.o \
XParseGeometry.o \
XPeekEvent.o \
XPeekIfEvent.o \
XPending.o \
XPlanesOfScreen.o \
XPointInRegion.o \
XPolygonRegion.o \
XProcessInternalConnection.o \
XProtocolRevision.o \
XProtocolVersion.o \
XPutBackEvent.o \
XPutImage.o \
XPutPixel.o \
XQLength.o \
XQueryBestCursor.o \
XQueryBestSize.o \
XQueryBestStipple.o \
XQueryBestTile.o \
XQueryColor.o \
XQueryColors.o \
XQueryExtension.o \
XQueryFont.o \
XQueryKeymap.o \
XQueryPointer.o \
XQueryTextExtents.o \
XQueryTextExtents16.o \
XQueryTree.o \
XRaiseWindow.o \
XReadBitmapFile.o \
XReadBitmapFileData.o \
XRebindKeysym.o \
XRecolorCursor.o \
XReconfigureWMWindow.o \
XRectInRegion.o \
XRefreshKeyboardMapping.o \
XRegisterIMInstantiateCallback.o \
XRemoveConnectionWatch.o \
XRemoveFromSaveSet.o \
XRemoveHost.o \
XRemoveHosts.o \
XReparentWindow.o \
XResetScreenSaver.o \
XResizeWindow.o \
XResourceManagerString.o \
XRestackWindows.o \
XRootWindow.o \
XRootWindowOfScreen.o \
XRotateBuffers.o \
XRotateWindowProperties.o \
XSaveContext.o \
XScreenCount.o \
XScreenNumberOfScreen.o \
XScreenOfDisplay.o \
XScreenResourceString.o \
XSelectInput.o \
XSendEvent.o \
XServerVendor.o \
XSetAccessControl.o \
XSetArcMode.o \
XSetAuthorization.o \
XSetBackground.o \
XSetClassHint.o \
XSetClipMask.o \
XSetClipOrigin.o \
XSetClipRectangles.o \
XSetCloseDownMode.o \
XSetCommand.o \
XSetDashes.o \
XSetErrorHandler.o \
XSetFillRule.o \
XSetFillStyle.o \
XSetFont.o \
XSetFontPath.o \
XSetForeground.o \
XSetFunction.o \
XSetGraphicsExposures.o \
XSetICFocus.o \
XSetIOErrorHandler.o \
XSetIconName.o \
XSetIconSizes.o \
XSetInputFocus.o \
XSetLineAttributes.o \
XSetLocaleModifiers.o \
XSetModifierMapping.o \
XSetNormalHints.o \
XSetPlaneMask.o \
XSetPointerMapping.o \
XSetRGBColormaps.o \
XSetRegion.o \
XSetScreenSaver.o \
XSetSelectionOwner.o \
XSetSizeHints.o \
XSetStandardColormap.o \
XSetStandardProperties.o \
XSetState.o \
XSetStipple.o \
XSetSubwindowMode.o \
XSetTSOrigin.o \
XSetTextProperty.o \
XSetTile.o \
XSetTransientForHint.o \
XSetWMClientMachine.o \
XSetWMColormapWindows.o \
XSetWMHints.o \
XSetWMIconName.o \
XSetWMName.o \
XSetWMNormalHints.o \
XSetWMProperties.o \
XSetWMProtocols.o \
XSetWMSizeHints.o \
XSetWindowBackground.o \
XSetWindowBackgroundPixmap.o \
XSetWindowBorder.o \
XSetWindowBorderPixmap.o \
XSetWindowBorderWidth.o \
XSetWindowColormap.o \
XSetZoomHints.o \
XShrinkRegion.o \
XStoreBuffer.o \
XStoreBytes.o \
XStoreColor.o \
XStoreColors.o \
XStoreName.o \
XStoreNamedColor.o \
XStringListToTextProperty.o \
XStringToKeysym.o \
XSubImage.o \
XSubtractRegion.o \
XSupportsLocale.o \
XSync.o \
XTextExtents.o \
XTextExtents16.o \
XTextPropertyToStringList.o \
XTextWidth.o \
XTextWidth16.o \
XTranslateCoordinates.o \
XUndefineCursor.o \
XUngrabButton.o \
XUngrabKey.o \
XUngrabKeyboard.o \
XUngrabPointer.o \
XUngrabServer.o \
XUninstallColormap.o \
XUnionRectWithRegion.o \
XUnionRegion.o \
XUnloadFont.o \
XUnlockDisplay.o \
XUnmapSubwindows.o \
XUnmapWindow.o \
XUnregisterIMInstantiateCallback.o \
XUnsetICFocus.o \
XVendorRelease.o \
XVisualIDFromVisual.o \
XWMGeometry.o \
XWarpPointer.o \
XWhitePixel.o \
XWhitePixelOfScreen.o \
XWidthMMOfScreen.o \
XWidthOfScreen.o \
XWindowEvent.o \
XWithdrawWindow.o \
XWriteBitmapFile.o \
XXorRegion.o \
XauDisposeAuth.o \
XauFileName.o \
XauGetBestAuthByAddr.o \
XauReadAuth.o \
XcmsAddColorSpace.o \
XcmsAddFunctionSet.o \
XcmsAllocColor.o \
XcmsAllocNamedColor.o \
XcmsCCCOfColormap.o \
XcmsCIELabClipL.o \
XcmsCIELabClipLab.o \
XcmsCIELabClipab.o \
XcmsCIELabQueryMaxC.o \
XcmsCIELabQueryMaxL.o \
XcmsCIELabQueryMaxLC.o \
XcmsCIELabQueryMinL.o \
XcmsCIELabToCIEXYZ.o \
XcmsCIELabWhiteShiftColors.o \
XcmsCIELuvClipL.o \
XcmsCIELuvClipLuv.o \
XcmsCIELuvClipuv.o \
XcmsCIELuvQueryMaxC.o \
XcmsCIELuvQueryMaxL.o \
XcmsCIELuvQueryMaxLC.o \
XcmsCIELuvQueryMinL.o \
XcmsCIELuvToCIEuvY.o \
XcmsCIELuvWhiteShiftColors.o \
XcmsCIEXYZToCIELab.o \
XcmsCIEXYZToCIEuvY.o \
XcmsCIEXYZToCIExyY.o \
XcmsCIEXYZToRGBi.o \
XcmsCIEuvYToCIELuv.o \
XcmsCIEuvYToCIEXYZ.o \
XcmsCIEuvYToTekHVC.o \
XcmsCIExyYToCIEXYZ.o \
XcmsClientWhitePointOfCCC.o \
XcmsConvertColors.o \
XcmsCreateCCC.o \
XcmsDefaultCCC.o \
XcmsDisplayOfCCC.o \
XcmsFormatOfPrefix.o \
XcmsFreeCCC.o \
XcmsLookupColor.o \
XcmsPrefixOfFormat.o \
XcmsQueryBlack.o \
XcmsQueryBlue.o \
XcmsQueryColor.o \
XcmsQueryColors.o \
XcmsQueryGreen.o \
XcmsQueryRed.o \
XcmsQueryWhite.o \
XcmsRGBToRGBi.o \
XcmsRGBiToCIEXYZ.o \
XcmsRGBiToRGB.o \
XcmsScreenNumberOfCCC.o \
XcmsScreenWhitePointOfCCC.o \
XcmsSetCCCOfColormap.o \
XcmsSetCompressionProc.o \
XcmsSetWhiteAdjustProc.o \
XcmsSetWhitePoint.o \
XcmsStoreColor.o \
XcmsStoreColors.o \
XcmsTekHVCClipC.o \
XcmsTekHVCClipV.o \
XcmsTekHVCClipVC.o \
XcmsTekHVCQueryMaxC.o \
XcmsTekHVCQueryMaxV.o \
XcmsTekHVCQueryMaxVC.o \
XcmsTekHVCQueryMaxVSamples.o \
XcmsTekHVCQueryMinV.o \
XcmsTekHVCToCIEuvY.o \
XcmsTekHVCWhiteShiftColors.o \
XcmsVisualOfCCC.o \
XkbAllocClientMap.o \
XkbAllocCompatMap.o \
XkbAllocControls.o \
XkbAllocIndicatorMaps.o \
XkbAllocKeyboard.o \
XkbAllocNames.o \
XkbAllocServerMap.o \
XkbApplyCompatMapToKey.o \
XkbBell.o \
XkbBellEvent.o \
XkbChangeEnabledControls.o \
XkbChangeMap.o \
XkbChangeNames.o \
XkbChangeTypesOfKey.o \
XkbComputeEffectiveMap.o \
XkbCopyKeyType.o \
XkbCopyKeyTypes.o \
XkbForceBell.o \
XkbFreeClientMap.o \
XkbFreeCompatMap.o \
XkbFreeComponentList.o \
XkbFreeControls.o \
XkbFreeIndicatorMaps.o \
XkbFreeKeyboard.o \
XkbFreeNames.o \
XkbFreeServerMap.o \
XkbGetAutoRepeatRate.o \
XkbGetCompatMap.o \
XkbGetControls.o \
XkbGetIndicatorMap.o \
XkbGetIndicatorState.o \
XkbGetKeyActions.o \
XkbGetKeyBehaviors.o \
XkbGetKeyExplicitComponents.o \
XkbGetKeyModifierMap.o \
XkbGetKeySyms.o \
XkbGetKeyTypes.o \
XkbGetKeyboard.o \
XkbGetKeyboardByName.o \
XkbGetMap.o \
XkbGetMapChanges.o \
XkbGetNamedIndicator.o \
XkbGetNames.o \
XkbGetState.o \
XkbGetUpdatedMap.o \
XkbGetVirtualMods.o \
XkbGetXlibControls.o \
XkbIgnoreExtension.o \
XkbInitCanonicalKeyTypes.o \
XkbKeyTypesForCoreSymbols.o \
XkbKeycodeToKeysym.o \
XkbKeysymToModifiers.o \
XkbLatchGroup.o \
XkbLatchModifiers.o \
XkbLibraryVersion.o \
XkbListComponents.o \
XkbLockGroup.o \
XkbLockModifiers.o \
XkbLookupKeyBinding.o \
XkbLookupKeySym.o \
XkbNoteControlsChanges.o \
XkbNoteMapChanges.o \
XkbNoteNameChanges.o \
XkbOpenDisplay.o \
XkbQueryExtension.o \
XkbRefreshKeyboardMapping.o \
XkbResizeKeyActions.o \
XkbResizeKeySyms.o \
XkbResizeKeyType.o \
XkbSelectEventDetails.o \
XkbSelectEvents.o \
XkbSetAtomFuncs.o \
XkbSetAutoRepeatRate.o \
XkbSetAutoResetControls.o \
XkbSetCompatMap.o \
XkbSetControls.o \
XkbSetDebuggingFlags.o \
XkbSetDetectableAutoRepeat.o \
XkbSetIgnoreLockMods.o \
XkbSetIndicatorMap.o \
XkbSetMap.o \
XkbSetNamedIndicator.o \
XkbSetNames.o \
XkbSetServerInternalMods.o \
XkbSetXlibControls.o \
XkbToControl.o \
XkbTranslateKeyCode.o \
XkbTranslateKeySym.o \
XkbUpdateMapFromCore.o \
XkbUseExtension.o \
XkbVirtualModsToReal.o \
XmbDrawImageString.o \
XmbDrawString.o \
XmbDrawText.o \
XmbLookupString.o \
XmbResetIC.o \
XmbSetWMProperties.o \
XmbTextEscapement.o \
XmbTextExtents.o \
XmbTextListToTextProperty.o \
XmbTextPerCharExtents.o \
XmbTextPropertyToTextList.o \
XrmCombineDatabase.o \
XrmCombineFileDatabase.o \
XrmDestroyDatabase.o \
XrmEnumerateDatabase.o \
XrmGetDatabase.o \
XrmGetFileDatabase.o \
XrmGetResource.o \
XrmGetStringDatabase.o \
XrmInitialize.o \
XrmLocaleOfDatabase.o \
XrmMergeDatabases.o \
XrmParseCommand.o \
XrmPermStringToQuark.o \
XrmPutFileDatabase.o \
XrmPutLineResource.o \
XrmPutResource.o \
XrmPutStringResource.o \
XrmQGetResource.o \
XrmQGetSearchList.o \
XrmQGetSearchResource.o \
XrmQPutResource.o \
XrmQPutStringResource.o \
XrmQuarkToString.o \
XrmSetDatabase.o \
XrmStringToBindingQuarkList.o \
XrmStringToQuark.o \
XrmStringToQuarkList.o \
XrmUniqueQuark.o \
Xutf8TextListToTextProperty.o \
Xutf8TextPropertyToTextList.o \
XwcDrawImageString.o \
XwcDrawString.o \
XwcDrawText.o \
XwcFreeStringList.o \
XwcLookupString.o \
XwcResetIC.o \
XwcTextEscapement.o \
XwcTextExtents.o \
XwcTextListToTextProperty.o \
XwcTextPerCharExtents.o \
XwcTextPropertyToTextList.o 