GEN_FUNCS = \
XActivateScreenSaver.o \
XAddConnectionWatch.o \
XAddExtension.o \
XAddHost.o \
XAddHosts.o \
XAddPixel.o \
XAddToExtensionList.o \
XAddToSaveSet.o \
XAllPlanes.o \
XAllocClassHint.o \
XAllocColor.o \
XAllocColorCells.o \
XAllocColorPlanes.o \
XAllocIconSize.o \
XAllocNamedColor.o \
XAllocSizeHints.o \
XAllocStandardColormap.o \
XAllocWMHints.o \
XAllowEvents.o \
XAutoRepeatOff.o \
XAutoRepeatOn.o \
XBaseFontNameListOfFontSet.o \
XBell.o \
XBitmapBitOrder.o \
XBitmapPad.o \
XBitmapUnit.o \
XBlackPixel.o \
XBlackPixelOfScreen.o \
XCellsOfScreen.o \
XChangeActivePointerGrab.o \
XChangeGC.o \
XChangeKeyboardControl.o \
XChangeKeyboardMapping.o \
XChangePointerControl.o \
XChangeProperty.o \
XChangeSaveSet.o \
XChangeWindowAttributes.o \
XCheckIfEvent.o \
XCheckMaskEvent.o \
XCheckTypedEvent.o \
XCheckTypedWindowEvent.o \
XCheckWindowEvent.o \
XCirculateSubwindows.o \
XCirculateSubwindowsDown.o \
XCirculateSubwindowsUp.o \
XClearArea.o \
XClearWindow.o \
XClipBox.o \
XCloseDisplay.o \
XCloseIM.o \
XCloseOM.o \
XConfigureWindow.o \
XConnectionNumber.o \
XContextDependentDrawing.o \
XContextualDrawing.o \
XConvertCase.o \
XConvertSelection.o \
XCopyArea.o \
XCopyColormapAndFree.o \
XCopyGC.o \
XCopyPlane.o \
XCreateBitmapFromData.o \
XCreateColormap.o \
XCreateFontCursor.o \
XCreateFontSet.o \
XCreateGC.o \
XCreateGlyphCursor.o \
XCreateImage.o \
XCreatePixmap.o \
XCreatePixmapCursor.o \
XCreatePixmapFromBitmapData.o \
XCreateRegion.o \
XCreateSimpleWindow.o \
XCreateWindow.o \
XDefaultColormap.o \
XDefaultColormapOfScreen.o \
XDefaultDepth.o \
XDefaultDepthOfScreen.o \
XDefaultGC.o \
XDefaultGCOfScreen.o \
XDefaultRootWindow.o \
XDefaultScreen.o \
XDefaultScreenOfDisplay.o \
XDefaultString.o \
XDefaultVisual.o \
XDefaultVisualOfScreen.o \
XDefineCursor.o \
XDeleteContext.o \
XDeleteModifiermapEntry.o \
XDeleteProperty.o \
XDestroyIC.o \
XDestroyImage.o \
XDestroyOC.o \
XDestroyRegion.o \
XDestroySubwindows.o \
XDestroyWindow.o \
XDirectionalDependentDrawing.o \
XDisableAccessControl.o \
XDisplayCells.o \
XDisplayHeight.o \
XDisplayHeightMM.o \
XDisplayKeycodes.o \
XDisplayMotionBufferSize.o \
XDisplayName.o \
XDisplayOfIM.o \
XDisplayOfOM.o \
XDisplayOfScreen.o \
XDisplayPlanes.o \
XDisplayString.o \
XDisplayWidth.o \
XDisplayWidthMM.o \
XDoesBackingStore.o \
XDoesSaveUnders.o \
XDrawArc.o \
XDrawArcs.o \
XDrawImageString.o \
XDrawImageString16.o \
XDrawLine.o \
XDrawLines.o \
XDrawPoint.o \
XDrawPoints.o \
XDrawRectangle.o \
XDrawRectangles.o \
XDrawSegments.o \
XDrawString.o \
XDrawString16.o \
XDrawText.o \
XDrawText16.o \
XEHeadOfExtensionList.o \
XESetBeforeFlush.o \
XESetCloseDisplay.o \
XESetCopyGC.o \
XESetCreateFont.o \
XESetCreateGC.o \
XESetError.o \
XESetErrorString.o \
XESetEventToWire.o \
XESetFlushGC.o \
XESetFreeFont.o \
XESetFreeGC.o \
XESetPrintErrorValues.o \
XESetWireToError.o \
XESetWireToEvent.o \
XEmptyRegion.o \
XEnableAccessControl.o \
XEqualRegion.o \
XEventMaskOfScreen.o \
XEventsQueued.o \
XExtendedMaxRequestSize.o \
XExtentsOfFontSet.o \
XFetchBuffer.o \
XFetchBytes.o \
XFetchName.o \
XFillArc.o \
XFillArcs.o \
XFillPolygon.o \
XFillRectangle.o \
XFillRectangles.o \
XFilterEvent.o \
XFindContext.o \
XFindOnExtensionList.o \
XFlush.o \
XFlushGC.o \
XFontsOfFontSet.o \
XForceScreenSaver.o \
XFree.o \
XFreeColormap.o \
XFreeColors.o \
XFreeCursor.o \
XFreeExtensionList.o \
XFreeFont.o \
XFreeFontInfo.o \
XFreeFontNames.o \
XFreeFontPath.o \
XFreeFontSet.o \
XFreeGC.o \
XFreeModifiermap.o \
XFreePixmap.o \
XFreeStringList.o \
XGContextFromGC.o \
XGeometry.o \
XGetAtomName.o \
XGetAtomNames.o \
XGetClassHint.o \
XGetCommand.o \
XGetDefault.o \
XGetErrorDatabaseText.o \
XGetErrorText.o \
XGetFontPath.o \
XGetFontProperty.o \
XGetGCValues.o \
XGetGeometry.o \
XGetIconName.o \
XGetIconSizes.o \
XGetImage.o \
XGetInputFocus.o \
XGetKeyboardControl.o \
XGetKeyboardMapping.o \
XGetModifierMapping.o \
XGetMotionEvents.o \
XGetNormalHints.o \
XGetPixel.o \
XGetPointerControl.o \
XGetPointerMapping.o \
XGetRGBColormaps.o \
XGetScreenSaver.o \
XGetSelectionOwner.o \
XGetSizeHints.o \
XGetStandardColormap.o \
XGetSubImage.o \
XGetTextProperty.o \
XGetTransientForHint.o \
XGetVisualInfo.o \
XGetWMClientMachine.o \
XGetWMColormapWindows.o \
XGetWMHints.o \
XGetWMIconName.o \
XGetWMName.o \
XGetWMNormalHints.o \
XGetWMProtocols.o \
XGetWMSizeHints.o \
XGetWindowAttributes.o \
XGetWindowProperty.o \
XGetZoomHints.o \
XGrabButton.o \
XGrabKey.o \
XGrabKeyboard.o \
XGrabPointer.o \
XGrabServer.o \
XHeightMMOfScreen.o \
XHeightOfScreen.o \
XIMOfIC.o \
XIconifyWindow.o \
XIfEvent.o \
XImageByteOrder.o \
XInitExtension.o \
XInitImage.o \
XInitThreads.o \
XInsertModifiermapEntry.o \
XInstallColormap.o \
XInternAtom.o \
XInternAtoms.o \
XInternalConnectionNumbers.o \
XIntersectRegion.o \
XKeycodeToKeysym.o \
XKeysymToKeycode.o \
XKeysymToString.o \
XKillClient.o \
XLastKnownRequestProcessed.o \
XListDepths.o \
XListExtensions.o \
XListFonts.o \
XListFontsWithInfo.o \
XListHosts.o \
XListInstalledColormaps.o \
XListPixmapFormats.o \
XListProperties.o \
XLoadFont.o \
XLoadQueryFont.o \
XLocaleOfFontSet.o \
XLocaleOfIM.o \
XLocaleOfOM.o \
XLockDisplay.o \
XLookupColor.o \
XLookupKeysym.o \
XLookupString.o \
XLowerWindow.o \
XMapRaised.o \
XMapSubwindows.o \
XMapWindow.o \
XMaskEvent.o \
XMatchVisualInfo.o \
XMaxCmapsOfScreen.o \
XMaxRequestSize.o \
XMinCmapsOfScreen.o \
XMoveResizeWindow.o \
XMoveWindow.o \
XNewModifiermap.o \
XNextEvent.o \
XNextRequest.o \
XNoOp.o \
XOMOfOC.o \
XOffsetRegion.o \
XOpenDisplay.o \
XOpenIM.o \
XOpenOM.o \
XParseColor.o \
XParseGeometry.o \
XPeekEvent.o \
XPeekIfEvent.o \
XPending.o \
XPlanesOfScreen.o \
XPointInRegion.o \
XPolygonRegion.o \
XProcessInternalConnection.o \
XProtocolRevision.o \
XProtocolVersion.o \
XPutBackEvent.o \
XPutImage.o \
XPutPixel.o \
XQLength.o \
XQueryBestCursor.o \
XQueryBestSize.o \
XQueryBestStipple.o \
XQueryBestTile.o \
XQueryColor.o \
XQueryColors.o \
XQueryExtension.o \
XQueryFont.o \
XQueryKeymap.o \
XQueryPointer.o \
XQueryTextExtents.o \
XQueryTextExtents16.o \
XQueryTree.o \
XRaiseWindow.o \
XReadBitmapFile.o \
XReadBitmapFileData.o \
XRebindKeysym.o \
XRecolorCursor.o \
XReconfigureWMWindow.o \
XRectInRegion.o \
XRefreshKeyboardMapping.o \
XRegisterIMInstantiateCallback.o \
XRemoveConnectionWatch.o \
XRemoveFromSaveSet.o \
XRemoveHost.o \
XRemoveHosts.o \
XReparentWindow.o \
XResetScreenSaver.o \
XResizeWindow.o \
XResourceManagerString.o \
XRestackWindows.o \
XRootWindow.o \
XRootWindowOfScreen.o \
XRotateBuffers.o \
XRotateWindowProperties.o \
XSaveContext.o \
XScreenCount.o \
XScreenNumberOfScreen.o \
XScreenOfDisplay.o \
XScreenResourceString.o \
XSelectInput.o \
XSendEvent.o \
XServerVendor.o \
XSetAccessControl.o \
XSetArcMode.o \
XSetAuthorization.o \
XSetBackground.o \
XSetClassHint.o \
XSetClipMask.o \
XSetClipOrigin.o \
XSetClipRectangles.o \
XSetCloseDownMode.o \
XSetCommand.o \
XSetDashes.o \
XSetErrorHandler.o \
XSetFillRule.o \
XSetFillStyle.o \
XSetFont.o \
XSetFontPath.o \
XSetForeground.o \
XSetFunction.o \
XSetGraphicsExposures.o \
XSetICFocus.o \
XSetIOErrorHandler.o \
XSetIconName.o \
XSetIconSizes.o \
XSetInputFocus.o \
XSetLineAttributes.o \
XSetLocaleModifiers.o \
XSetModifierMapping.o \
XSetNormalHints.o \
XSetPlaneMask.o \
XSetPointerMapping.o \
XSetRGBColormaps.o \
XSetRegion.o \
XSetScreenSaver.o \
XSetSelectionOwner.o \
XSetSizeHints.o \
XSetStandardColormap.o \
XSetStandardProperties.o \
XSetState.o \
XSetStipple.o \
XSetSubwindowMode.o \
XSetTSOrigin.o \
XSetTextProperty.o \
XSetTile.o \
XSetTransientForHint.o \
XSetWMClientMachine.o \
XSetWMColormapWindows.o \
XSetWMHints.o \
XSetWMIconName.o \
XSetWMName.o \
XSetWMNormalHints.o \
XSetWMProperties.o \
XSetWMProtocols.o \
XSetWMSizeHints.o \
XSetWindowBackground.o \
XSetWindowBackgroundPixmap.o \
XSetWindowBorder.o \
XSetWindowBorderPixmap.o \
XSetWindowBorderWidth.o \
XSetWindowColormap.o \
XSetZoomHints.o 