// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
#include <X11/X.h>
#undef XAllocColorCells
static int(*funcptr) (Display * , Colormap , int , unsigned long * , unsigned int , unsigned long * , unsigned int ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
int XAllocColorCells (Display * arg0 , Colormap arg1 , int arg2 , unsigned long * arg3 , unsigned int arg4 , unsigned long * arg5 , unsigned int arg6 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XAllocColorCells");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XAllocColorCells()");
	validate_Rdaddress( arg0, "XAllocColorCells - arg0");
		validate_NULL_TYPETYPE(  arg0, "XAllocColorCells - arg0");
		validate_NULL_TYPETYPE(  arg1, "XAllocColorCells - arg1");
		validate_NULL_TYPETYPE(  arg2, "XAllocColorCells - arg2");
	validate_Rdaddress( arg3, "XAllocColorCells - arg3");
		validate_NULL_TYPETYPE(  arg3, "XAllocColorCells - arg3");
		validate_NULL_TYPETYPE(  arg4, "XAllocColorCells - arg4");
	validate_Rdaddress( arg5, "XAllocColorCells - arg5");
		validate_NULL_TYPETYPE(  arg5, "XAllocColorCells - arg5");
		validate_NULL_TYPETYPE(  arg6, "XAllocColorCells - arg6");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
	__lsb_check_params = reset_flag;
	return ret_value;
}

