// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <X11/Xlib.h>
#include <X11/X.h>
#undef XChangeKeyboardMapping
static int(*funcptr) (Display * , int , int , KeySym * , int ) = 0;

extern int __lsb_check_params;
int XChangeKeyboardMapping (Display * arg0 , int arg1 , int arg2 , KeySym * arg3 , int arg4 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlsym(RTLD_NEXT, "XChangeKeyboardMapping");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XChangeKeyboardMapping()");
		validate_RWaddress( arg0, "XChangeKeyboardMapping - arg0");
		validate_NULL_TYPETYPE(  arg0, "XChangeKeyboardMapping - arg0");
		validate_NULL_TYPETYPE(  arg1, "XChangeKeyboardMapping - arg1");
		validate_NULL_TYPETYPE(  arg2, "XChangeKeyboardMapping - arg2");
		validate_RWaddress( arg3, "XChangeKeyboardMapping - arg3");
		validate_NULL_TYPETYPE(  arg3, "XChangeKeyboardMapping - arg3");
		validate_NULL_TYPETYPE(  arg4, "XChangeKeyboardMapping - arg4");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
	return ret_value;
}

