// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/X.h>
#undef XChangeKeyboardMapping
static int(*funcptr) (Display * , int , int , KeySym * , int ) = 0;

extern int __lsb_check_params;
int XChangeKeyboardMapping (Display * arg0 , int arg1 , int arg2 , KeySym * arg3 , int arg4 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for XChangeKeyboardMapping()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XChangeKeyboardMapping");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XChangeKeyboardMapping. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XChangeKeyboardMapping() - validating");
		validate_RWaddress( arg0, "XChangeKeyboardMapping - arg0");
		validate_NULL_TYPETYPE(  arg0, "XChangeKeyboardMapping - arg0");
		validate_NULL_TYPETYPE(  arg1, "XChangeKeyboardMapping - arg1");
		validate_NULL_TYPETYPE(  arg2, "XChangeKeyboardMapping - arg2");
		validate_RWaddress( arg3, "XChangeKeyboardMapping - arg3");
		validate_NULL_TYPETYPE(  arg3, "XChangeKeyboardMapping - arg3");
		validate_NULL_TYPETYPE(  arg4, "XChangeKeyboardMapping - arg4");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
	return ret_value;
}

