// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, Window) = 0;

int XCirculateSubwindowsDown(Display * arg0, Window arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XCirculateSubwindowsDown");
	validate_NULL_TYPETYPE(arg0, "XCirculateSubwindowsDown");
	validate_NULL_TYPETYPE(arg1, "XCirculateSubwindowsDown");
	return funcptr(arg0, arg1);
}

int lsb_XCirculateSubwindowsDown(Display * arg0, Window arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XCirculateSubwindowsDown");
	return funcptr(arg0, arg1);
}

