// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xcms.h>
#undef XcmsCIELuvToCIEuvY
static int(*funcptr) (XcmsCCC , XcmsColor * , XcmsColor * , unsigned int ) = 0;

extern int __lsb_check_params;
int XcmsCIELuvToCIEuvY (XcmsCCC arg0 , XcmsColor * arg1 , XcmsColor * arg2 , unsigned int arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for XcmsCIELuvToCIEuvY()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XcmsCIELuvToCIEuvY");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XcmsCIELuvToCIEuvY. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XcmsCIELuvToCIEuvY() - validating");
		validate_NULL_TYPETYPE(  arg0, "XcmsCIELuvToCIEuvY - arg0");
		validate_RWaddress( arg1, "XcmsCIELuvToCIEuvY - arg1");
		validate_NULL_TYPETYPE(  arg1, "XcmsCIELuvToCIEuvY - arg1");
		validate_RWaddress( arg2, "XcmsCIELuvToCIEuvY - arg2");
		validate_NULL_TYPETYPE(  arg2, "XcmsCIELuvToCIEuvY - arg2");
		validate_NULL_TYPETYPE(  arg3, "XcmsCIELuvToCIEuvY - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

