// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Xcms.h>
#include <X11/Xcms.h>
static int(*funcptr)(XcmsCCC, XcmsFloat, XcmsColor *) = 0;

int XcmsTekHVCQueryMaxVC(XcmsCCC arg0, XcmsFloat arg1, XcmsColor * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XcmsTekHVCQueryMaxVC");
	validate_NULL_TYPETYPE(arg0, "XcmsTekHVCQueryMaxVC");
	validate_NULL_TYPETYPE(arg1, "XcmsTekHVCQueryMaxVC");
	validate_NULL_TYPETYPE(arg2, "XcmsTekHVCQueryMaxVC");
	return funcptr(arg0, arg1, arg2);
}

int lsb_XcmsTekHVCQueryMaxVC(XcmsCCC arg0, XcmsFloat arg1, XcmsColor * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XcmsTekHVCQueryMaxVC");
	return funcptr(arg0, arg1, arg2);
}

