// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, Drawable, char *, unsigned int, unsigned int) = 0;

Pixmap XCreateBitmapFromData(Display * arg0, Drawable arg1, char * arg2, unsigned int arg3, unsigned int arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XCreateBitmapFromData");
	validate_NULL_TYPETYPE(arg0, "XCreateBitmapFromData");
	validate_NULL_TYPETYPE(arg1, "XCreateBitmapFromData");
	validate_NULL_TYPETYPE(arg2, "XCreateBitmapFromData");
	validate_NULL_TYPETYPE(arg3, "XCreateBitmapFromData");
	validate_NULL_TYPETYPE(arg4, "XCreateBitmapFromData");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

Pixmap __lsb_XCreateBitmapFromData(Display * arg0, Drawable arg1, char * arg2, unsigned int arg3, unsigned int arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XCreateBitmapFromData");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

