// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <X11/Xlib.h>
#undef XCreateFontSet
static XFontSet(*funcptr) (Display * , const char * , char * * * , int * , char * * ) = 0;

extern int __lsb_check_params;
XFontSet XCreateFontSet (Display * arg0 , const char * arg1 , char * * * arg2 , int * arg3 , char * * arg4 )
{
	int reset_flag = __lsb_check_params;
	XFontSet ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlsym(RTLD_NEXT, "XCreateFontSet");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XCreateFontSet()");
		validate_RWaddress( arg0, "XCreateFontSet - arg0");
		validate_NULL_TYPETYPE(  arg0, "XCreateFontSet - arg0");
		validate_Rdaddress( arg1, "XCreateFontSet - arg1");
		validate_NULL_TYPETYPE(  arg1, "XCreateFontSet - arg1");
		validate_RWaddress( arg2, "XCreateFontSet - arg2");
		validate_NULL_TYPETYPE(  arg2, "XCreateFontSet - arg2");
		validate_RWaddress( arg3, "XCreateFontSet - arg3");
		validate_NULL_TYPETYPE(  arg3, "XCreateFontSet - arg3");
		validate_RWaddress( arg4, "XCreateFontSet - arg4");
		validate_NULL_TYPETYPE(  arg4, "XCreateFontSet - arg4");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
	return ret_value;
}

