// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
#include <X11/Xutil.h>
static int(*funcptr)(Display *, XID, XContext) = 0;

int XDeleteContext(Display * arg0, XID arg1, XContext arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XDeleteContext");
	validate_NULL_TYPETYPE(arg0, "XDeleteContext");
	validate_NULL_TYPETYPE(arg1, "XDeleteContext");
	validate_NULL_TYPETYPE(arg2, "XDeleteContext");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_XDeleteContext(Display * arg0, XID arg1, XContext arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XDeleteContext");
	return funcptr(arg0, arg1, arg2);
}

