// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)() = 0;

int XESetEventToWire()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XESetEventToWire");
	return funcptr();
}

int lsb_XESetEventToWire()
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XESetEventToWire");
	return funcptr();
}

