// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
#include <X11/X.h>
#undef XFillArc
static int(*funcptr) (Display * , Drawable , GC , int , int , unsigned int , unsigned int , int , int ) = 0;

extern int __lsb_check_params;
int XFillArc (Display * arg0 , Drawable arg1 , GC arg2 , int arg3 , int arg4 , unsigned int arg5 , unsigned int arg6 , int arg7 , int arg8 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " XFillArc ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "XFillArc()");
		validate_RWaddress( arg0, "XFillArc - arg0");
		validate_NULL_TYPETYPE(  arg0, "XFillArc - arg0");
		validate_NULL_TYPETYPE(  arg1, "XFillArc - arg1");
		validate_NULL_TYPETYPE(  arg2, "XFillArc - arg2");
		validate_NULL_TYPETYPE(  arg3, "XFillArc - arg3");
		validate_NULL_TYPETYPE(  arg4, "XFillArc - arg4");
		validate_NULL_TYPETYPE(  arg5, "XFillArc - arg5");
		validate_NULL_TYPETYPE(  arg6, "XFillArc - arg6");
		validate_NULL_TYPETYPE(  arg7, "XFillArc - arg7");
		validate_NULL_TYPETYPE(  arg8, "XFillArc - arg8");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
	__lsb_check_params = reset_flag;
	return ret_value;
}

