// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
#include <X11/X.h>
#undef XGetWMColormapWindows
static int(*funcptr) (Display * , Window , Window * * , int * ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
int XGetWMColormapWindows (Display * arg0 , Window arg1 , Window * * arg2 , int * arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XGetWMColormapWindows");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XGetWMColormapWindows()");
	validate_RWaddress( arg0, "XGetWMColormapWindows - arg0");
		validate_NULL_TYPETYPE(  arg0, "XGetWMColormapWindows - arg0");
		validate_NULL_TYPETYPE(  arg1, "XGetWMColormapWindows - arg1");
	validate_RWaddress( arg2, "XGetWMColormapWindows - arg2");
		validate_NULL_TYPETYPE(  arg2, "XGetWMColormapWindows - arg2");
	validate_RWaddress( arg3, "XGetWMColormapWindows - arg3");
		validate_NULL_TYPETYPE(  arg3, "XGetWMColormapWindows - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

