// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, Window, XSizeHints *) = 0;

int XGetZoomHints(Display * arg0, Window arg1, XSizeHints * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XGetZoomHints");
	validate_NULL_TYPETYPE(arg0, "XGetZoomHints");
	validate_NULL_TYPETYPE(arg1, "XGetZoomHints");
	validate_NULL_TYPETYPE(arg2, "XGetZoomHints");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_XGetZoomHints(Display * arg0, Window arg1, XSizeHints * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XGetZoomHints");
	return funcptr(arg0, arg1, arg2);
}

