// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(Display *, unsigned long, XkbDescPtr) = 0;

int XkbGetIndicatorMap(Display * arg0, unsigned long arg1, XkbDescPtr arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XkbGetIndicatorMap");
	validate_NULL_TYPETYPE(arg0, "XkbGetIndicatorMap");
	validate_NULL_TYPETYPE(arg1, "XkbGetIndicatorMap");
	validate_NULL_TYPETYPE(arg2, "XkbGetIndicatorMap");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_XkbGetIndicatorMap(Display * arg0, unsigned long arg1, XkbDescPtr arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XkbGetIndicatorMap");
	return funcptr(arg0, arg1, arg2);
}

