// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(Display *, unsigned int, unsigned int *, unsigned int *) = 0;

int XkbSetAutoResetControls(Display * arg0, unsigned int arg1, unsigned int * arg2, unsigned int * arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XkbSetAutoResetControls");
	validate_NULL_TYPETYPE(arg0, "XkbSetAutoResetControls");
	validate_NULL_TYPETYPE(arg1, "XkbSetAutoResetControls");
	validate_NULL_TYPETYPE(arg2, "XkbSetAutoResetControls");
	validate_NULL_TYPETYPE(arg3, "XkbSetAutoResetControls");
	return funcptr(arg0, arg1, arg2, arg3);
}

int __lsb_XkbSetAutoResetControls(Display * arg0, unsigned int arg1, unsigned int * arg2, unsigned int * arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XkbSetAutoResetControls");
	return funcptr(arg0, arg1, arg2, arg3);
}

