// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "../../misc/lsb_dlsym.h"
#include <X11/X.h>
#include <X11/Xlib.h>
#undef XQueryPointer
static int(*funcptr) (Display * , Window , Window * , Window * , int * , int * , int * , int * , unsigned int * ) = 0;

extern int __lsb_check_params;
int XQueryPointer (Display * arg0 , Window arg1 , Window * arg2 , Window * arg3 , int * arg4 , int * arg5 , int * arg6 , int * arg7 , unsigned int * arg8 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = lsb_dlsym(RTLD_NEXT, "XQueryPointer");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XQueryPointer()");
		validate_RWaddress( arg0, "XQueryPointer - arg0");
		validate_NULL_TYPETYPE(  arg0, "XQueryPointer - arg0");
		validate_NULL_TYPETYPE(  arg1, "XQueryPointer - arg1");
		validate_RWaddress( arg2, "XQueryPointer - arg2");
		validate_NULL_TYPETYPE(  arg2, "XQueryPointer - arg2");
		validate_RWaddress( arg3, "XQueryPointer - arg3");
		validate_NULL_TYPETYPE(  arg3, "XQueryPointer - arg3");
		validate_RWaddress( arg4, "XQueryPointer - arg4");
		validate_NULL_TYPETYPE(  arg4, "XQueryPointer - arg4");
		validate_RWaddress( arg5, "XQueryPointer - arg5");
		validate_NULL_TYPETYPE(  arg5, "XQueryPointer - arg5");
		validate_RWaddress( arg6, "XQueryPointer - arg6");
		validate_NULL_TYPETYPE(  arg6, "XQueryPointer - arg6");
		validate_RWaddress( arg7, "XQueryPointer - arg7");
		validate_NULL_TYPETYPE(  arg7, "XQueryPointer - arg7");
		validate_RWaddress( arg8, "XQueryPointer - arg8");
		validate_NULL_TYPETYPE(  arg8, "XQueryPointer - arg8");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
	__lsb_check_params = reset_flag;
	return ret_value;
}

