// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Xresource.h>
#undef XrmCombineDatabase
static void(*funcptr) (XrmDatabase , XrmDatabase * , int ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
void XrmCombineDatabase (XrmDatabase arg0 , XrmDatabase * arg1 , int arg2 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XrmCombineDatabase");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XrmCombineDatabase()");
		validate_NULL_TYPETYPE(  arg0, "XrmCombineDatabase - arg0");
	validate_RWaddress( arg1, "XrmCombineDatabase - arg1");
		validate_NULL_TYPETYPE(  arg1, "XrmCombineDatabase - arg1");
		validate_NULL_TYPETYPE(  arg2, "XrmCombineDatabase - arg2");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

