// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Xresource.h>
static int(*funcptr)(XrmQuark) = 0;

XrmString XrmQuarkToString(XrmQuark arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XrmQuarkToString");
	validate_NULL_TYPETYPE(arg0, "XrmQuarkToString");
	return funcptr(arg0);
}

XrmString lsb_XrmQuarkToString(XrmQuark arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XrmQuarkToString");
	return funcptr(arg0);
}

