// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <X11/Xresource.h>
#undef XrmStringToBindingQuarkList
static void(*funcptr) (const char * , XrmBindingList , XrmQuarkList ) = 0;

extern int __lsb_check_params;
void XrmStringToBindingQuarkList (const char * arg0 , XrmBindingList arg1 , XrmQuarkList arg2 )
{
	int reset_flag = __lsb_check_params;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " XrmStringToBindingQuarkList ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "XrmStringToBindingQuarkList()");
		validate_Rdaddress( arg0, "XrmStringToBindingQuarkList - arg0");
		validate_NULL_TYPETYPE(  arg0, "XrmStringToBindingQuarkList - arg0");
		validate_NULL_TYPETYPE(  arg1, "XrmStringToBindingQuarkList - arg1");
		validate_NULL_TYPETYPE(  arg2, "XrmStringToBindingQuarkList - arg2");
	}
	funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
}

