// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(Display *, int) = 0;

int XRotateBuffers(Display * arg0, int arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XRotateBuffers");
	validate_NULL_TYPETYPE(arg0, "XRotateBuffers");
	validate_NULL_TYPETYPE(arg1, "XRotateBuffers");
	return funcptr(arg0, arg1);
}

int __lsb_XRotateBuffers(Display * arg0, int arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XRotateBuffers");
	return funcptr(arg0, arg1);
}

