// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
#include <X11/Xutil.h>
static int(*funcptr)(Display *, XID, XContext, char *) = 0;

int XSaveContext(Display * arg0, XID arg1, XContext arg2, char * arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSaveContext");
	validate_NULL_TYPETYPE(arg0, "XSaveContext");
	validate_NULL_TYPETYPE(arg1, "XSaveContext");
	validate_NULL_TYPETYPE(arg2, "XSaveContext");
	validate_NULL_TYPETYPE(arg3, "XSaveContext");
	return funcptr(arg0, arg1, arg2, arg3);
}

int lsb_XSaveContext(Display * arg0, XID arg1, XContext arg2, char * arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSaveContext");
	return funcptr(arg0, arg1, arg2, arg3);
}

