// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
static int(*funcptr)(Display *, GC, int) = 0;

int XSetFillRule(Display * arg0, GC arg1, int arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetFillRule");
	validate_NULL_TYPETYPE(arg0, "XSetFillRule");
	validate_NULL_TYPETYPE(arg1, "XSetFillRule");
	validate_NULL_TYPETYPE(arg2, "XSetFillRule");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_XSetFillRule(Display * arg0, GC arg1, int arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetFillRule");
	return funcptr(arg0, arg1, arg2);
}

