// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
static int(*funcptr)(Display *, GC, int, int) = 0;

int XSetClipOrigin(Display * arg0, GC arg1, int arg2, int arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetClipOrigin");
	validate_NULL_TYPETYPE(arg0, "XSetClipOrigin");
	validate_NULL_TYPETYPE(arg1, "XSetClipOrigin");
	validate_NULL_TYPETYPE(arg2, "XSetClipOrigin");
	validate_NULL_TYPETYPE(arg3, "XSetClipOrigin");
	return funcptr(arg0, arg1, arg2, arg3);
}

int __lsb_XSetClipOrigin(Display * arg0, GC arg1, int arg2, int arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetClipOrigin");
	return funcptr(arg0, arg1, arg2, arg3);
}

