// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, Window, XWMHints *) = 0;

int XSetWMHints(Display * arg0, Window arg1, XWMHints * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetWMHints");
	validate_NULL_TYPETYPE(arg0, "XSetWMHints");
	validate_NULL_TYPETYPE(arg1, "XSetWMHints");
	validate_NULL_TYPETYPE(arg2, "XSetWMHints");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_XSetWMHints(Display * arg0, Window arg1, XWMHints * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetWMHints");
	return funcptr(arg0, arg1, arg2);
}

