// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
#undef XSetClipOrigin
static int(*funcptr) (Display * , GC , int , int ) = 0;

extern int __lsb_check_params;
int XSetClipOrigin (Display * arg0 , GC arg1 , int arg2 , int arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, " XSetClipOrigin ");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(5-reset_flag, "XSetClipOrigin()");
		validate_RWaddress( arg0, "XSetClipOrigin - arg0");
		validate_NULL_TYPETYPE(  arg0, "XSetClipOrigin - arg0");
		validate_NULL_TYPETYPE(  arg1, "XSetClipOrigin - arg1");
		validate_NULL_TYPETYPE(  arg2, "XSetClipOrigin - arg2");
		validate_NULL_TYPETYPE(  arg3, "XSetClipOrigin - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

