// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, Colormap, XColor *) = 0;

int XStoreColor(Display * arg0, Colormap arg1, XColor * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XStoreColor");
	validate_NULL_TYPETYPE(arg0, "XStoreColor");
	validate_NULL_TYPETYPE(arg1, "XStoreColor");
	validate_NULL_TYPETYPE(arg2, "XStoreColor");
	return funcptr(arg0, arg1, arg2);
}

int __lsb_XStoreColor(Display * arg0, Colormap arg1, XColor * arg2)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XStoreColor");
	return funcptr(arg0, arg1, arg2);
}

