// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
static int(*funcptr)(Display *, char *, int, int) = 0;

int XStoreBuffer(Display * arg0, char * arg1, int arg2, int arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XStoreBuffer");
	validate_NULL_TYPETYPE(arg0, "XStoreBuffer");
	validate_NULL_TYPETYPE(arg1, "XStoreBuffer");
	validate_NULL_TYPETYPE(arg2, "XStoreBuffer");
	validate_NULL_TYPETYPE(arg3, "XStoreBuffer");
	return funcptr(arg0, arg1, arg2, arg3);
}

int __lsb_XStoreBuffer(Display * arg0, char * arg1, int arg2, int arg3)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XStoreBuffer");
	return funcptr(arg0, arg1, arg2, arg3);
}

