// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/X.h>
static int(*funcptr)(Display *, Window) = 0;

int XUndefineCursor(Display * arg0, Window arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XUndefineCursor");
	validate_NULL_TYPETYPE(arg0, "XUndefineCursor");
	validate_NULL_TYPETYPE(arg1, "XUndefineCursor");
	return funcptr(arg0, arg1);
}

int __lsb_XUndefineCursor(Display * arg0, Window arg1)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XUndefineCursor");
	return funcptr(arg0, arg1);
}

