// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
#include <X11/X.h>
#undef XUngrabKey
static int(*funcptr) (Display * , int , unsigned int , Window ) = 0;

extern int __lsb_check_params;
extern int __lsb_output(int, char*, ...);
int XUngrabKey (Display * arg0 , int arg1 , unsigned int arg2 , Window arg3 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XUngrabKey");
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
	__lsb_output(5-__lsb_check_params, "XUngrabKey()");
	validate_Rdaddress( arg0, "XUngrabKey - arg0");
		validate_NULL_TYPETYPE(  arg0, "XUngrabKey - arg0");
		validate_NULL_TYPETYPE(  arg1, "XUngrabKey - arg1");
		validate_NULL_TYPETYPE(  arg2, "XUngrabKey - arg2");
		validate_NULL_TYPETYPE(  arg3, "XUngrabKey - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

