// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/Xlib.h>
static int(*funcptr)(XFontSet, wchar_t *, int, XRectangle *, XRectangle *) = 0;

int XwcTextExtents(XFontSet arg0, wchar_t * arg1, int arg2, XRectangle * arg3, XRectangle * arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XwcTextExtents");
	validate_NULL_TYPETYPE(arg0, "XwcTextExtents");
	validate_NULL_TYPETYPE(arg1, "XwcTextExtents");
	validate_NULL_TYPETYPE(arg2, "XwcTextExtents");
	validate_NULL_TYPETYPE(arg3, "XwcTextExtents");
	validate_NULL_TYPETYPE(arg4, "XwcTextExtents");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

int __lsb_XwcTextExtents(XFontSet arg0, wchar_t * arg1, int arg2, XRectangle * arg3, XRectangle * arg4)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XwcTextExtents");
	return funcptr(arg0, arg1, arg2, arg3, arg4);
}

