// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <gtk-3.0/gdk/gdk.h>
#include <glib-2.0/glib.h>
#undef gdk_device_get_key
static gboolean(*funcptr) (GdkDevice * , guint , guint * , GdkModifierType * ) = 0;

extern int __lsb_check_params;
gboolean gdk_device_get_key (GdkDevice * arg0 , guint arg1 , guint * arg2 , GdkModifierType * arg3 )
{
	int reset_flag = __lsb_check_params;
	gboolean ret_value  ;
	__lsb_output(4, "Invoking wrapper for gdk_device_get_key()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "gdk_device_get_key");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load gdk_device_get_key. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "gdk_device_get_key() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "gdk_device_get_key - arg0 (device)");
		}
		validate_NULL_TYPETYPE(  arg0, "gdk_device_get_key - arg0 (device)");
		validate_NULL_TYPETYPE(  arg1, "gdk_device_get_key - arg1");
		if( arg2 ) {
		validate_RWaddress( arg2, "gdk_device_get_key - arg2");
		}
		validate_NULL_TYPETYPE(  arg2, "gdk_device_get_key - arg2");
		if( arg3 ) {
		validate_RWaddress( arg3, "gdk_device_get_key - arg3");
		}
		validate_NULL_TYPETYPE(  arg3, "gdk_device_get_key - arg3");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
	return ret_value;
}

