GEN_FUNCS = \
gdk_add_option_entries_libgtk_only.o \
gdk_app_launch_context_get_type.o \
gdk_app_launch_context_new.o \
gdk_app_launch_context_set_desktop.o \
gdk_app_launch_context_set_display.o \
gdk_app_launch_context_set_icon.o \
gdk_app_launch_context_set_icon_name.o \
gdk_app_launch_context_set_screen.o \
gdk_app_launch_context_set_timestamp.o \
gdk_broadway_cursor_get_type.o \
gdk_broadway_display_manager_get_type.o \
gdk_broadway_get_last_seen_time.o \
gdk_broadway_visual_get_type.o \
gdk_broadway_window_get_type.o \
gdk_cairo_get_clip_rectangle.o \
gdk_cairo_region_create_from_surface.o \
gdk_cairo_set_source_rgba.o \
gdk_cairo_set_source_window.o \
gdk_color_to_string.o \
gdk_cursor_get_cursor_type.o \
gdk_device_get_associated_device.o \
gdk_device_get_axis_use.o \
gdk_device_get_axis_value.o \
gdk_device_get_device_type.o \
gdk_device_get_display.o \
gdk_device_get_has_cursor.o \
gdk_device_get_key.o \
gdk_device_get_mode.o \
gdk_device_get_n_axes.o \
gdk_device_get_n_keys.o \
gdk_device_get_name.o \
gdk_device_get_position.o \
gdk_device_get_source.o \
gdk_device_get_window_at_position.o \
gdk_device_grab.o \
gdk_device_grab_info_libgtk_only.o \
gdk_device_list_axes.o \
gdk_device_list_slave_devices.o \
gdk_device_manager_get_client_pointer.o \
gdk_device_manager_get_display.o \
gdk_device_manager_get_type.o \
gdk_device_manager_list_devices.o \
gdk_device_type_get_type.o \
gdk_device_ungrab.o \
gdk_device_warp.o \
gdk_disable_multidevice.o \
gdk_display_device_is_grabbed.o \
gdk_display_get_app_launch_context.o \
gdk_display_get_device_manager.o \
gdk_display_has_pending.o \
gdk_display_is_closed.o \
gdk_display_manager_open_display.o \
gdk_display_notify_startup_complete.o \
gdk_display_open_default_libgtk_only.o \
gdk_display_supports_composite.o \
gdk_drag_begin_for_device.o \
gdk_drag_context_get_actions.o \
gdk_drag_context_get_dest_window.o \
gdk_drag_context_get_device.o \
gdk_drag_context_get_protocol.o \
gdk_drag_context_get_selected_action.o \
gdk_drag_context_get_source_window.o \
gdk_drag_context_get_suggested_action.o \
gdk_drag_context_list_targets.o \
gdk_drag_context_set_device.o \
gdk_error_trap_pop_ignored.o \
gdk_event_get_button.o \
gdk_event_get_click_count.o \
gdk_event_get_device.o \
gdk_event_get_event_sequence.o \
gdk_event_get_keycode.o \
gdk_event_get_keyval.o \
gdk_event_get_scroll_deltas.o \
gdk_event_get_scroll_direction.o \
gdk_event_get_source_device.o \
gdk_event_request_motions.o \
gdk_event_set_device.o \
gdk_event_set_source_device.o \
gdk_event_triggers_context_menu.o \
gdk_events_get_angle.o \
gdk_events_get_center.o \
gdk_events_get_distance.o \
gdk_grab_ownership_get_type.o \
gdk_keymap_add_virtual_modifiers.o \
gdk_keymap_get_caps_lock_state.o \
gdk_keymap_get_modifier_mask.o \
gdk_keymap_get_modifier_state.o \
gdk_keymap_get_num_lock_state.o \
gdk_keymap_have_bidi_layouts.o \
gdk_keymap_map_virtual_modifiers.o \
gdk_modifier_intent_get_type.o \
gdk_notify_startup_complete_with_id.o \
gdk_offscreen_window_get_embedder.o \
gdk_offscreen_window_get_surface.o \
gdk_offscreen_window_set_embedder.o \
gdk_pixbuf_get_from_surface.o \
gdk_pixbuf_get_from_window.o \
gdk_pre_parse_libgtk_only.o \
gdk_rgba_copy.o \
gdk_rgba_equal.o \
gdk_rgba_free.o \
gdk_rgba_get_type.o \
gdk_rgba_hash.o \
gdk_rgba_parse.o \
gdk_rgba_to_string.o \
gdk_screen_get_monitor_height_mm.o \
gdk_screen_get_monitor_plug_name.o \
gdk_screen_get_monitor_width_mm.o \
gdk_screen_get_monitor_workarea.o \
gdk_screen_get_primary_monitor.o \
gdk_test_render_sync.o \
gdk_test_simulate_button.o \
gdk_test_simulate_key.o \
gdk_threads_add_idle.o \
gdk_threads_add_idle_full.o \
gdk_threads_add_timeout.o \
gdk_threads_add_timeout_full.o \
gdk_threads_add_timeout_seconds.o \
gdk_threads_add_timeout_seconds_full.o \
gdk_visual_get_bits_per_rgb.o \
gdk_visual_get_blue_pixel_details.o \
gdk_visual_get_byte_order.o \
gdk_visual_get_colormap_size.o \
gdk_visual_get_depth.o \
gdk_visual_get_green_pixel_details.o \
gdk_visual_get_red_pixel_details.o \
gdk_visual_get_visual_type.o \
gdk_window_beep.o \
gdk_window_begin_move_drag_for_device.o \
gdk_window_begin_resize_drag_for_device.o \
gdk_window_coords_from_parent.o \
gdk_window_coords_to_parent.o \
gdk_window_create_similar_surface.o \
gdk_window_ensure_native.o \
gdk_window_flush.o \
gdk_window_freeze_toplevel_updates_libgtk_only.o \
gdk_window_geometry_changed.o \
gdk_window_get_accept_focus.o \
gdk_window_get_background_pattern.o \
gdk_window_get_clip_region.o \
gdk_window_get_composited.o \
gdk_window_get_cursor.o \
gdk_window_get_device_cursor.o \
gdk_window_get_device_events.o \
gdk_window_get_device_position.o \
gdk_window_get_display.o \
gdk_window_get_drag_protocol.o \
gdk_window_get_effective_parent.o \
gdk_window_get_effective_toplevel.o \
gdk_window_get_focus_on_map.o \
gdk_window_get_height.o \
gdk_window_get_modal_hint.o \
gdk_window_get_root_coords.o \
gdk_window_get_screen.o \
gdk_window_get_source_events.o \
gdk_window_get_support_multidevice.o \
gdk_window_get_type.o \
gdk_window_get_visible_region.o \
gdk_window_get_visual.o \
gdk_window_get_width.o \
gdk_window_has_native.o \
gdk_window_is_destroyed.o \
gdk_window_is_input_only.o \
gdk_window_is_shaped.o \
gdk_window_restack.o \
gdk_window_set_background_pattern.o \
gdk_window_set_background_rgba.o \
gdk_window_set_composited.o \
gdk_window_set_device_cursor.o \
gdk_window_set_device_events.o \
gdk_window_set_opacity.o \
gdk_window_set_source_events.o \
gdk_window_set_startup_id.o \
gdk_window_set_support_multidevice.o \
gdk_window_thaw_toplevel_updates_libgtk_only.o \
gdk_window_window_class_get_type.o \
gdk_x11_app_launch_context_get_type.o \
gdk_x11_cursor_get_type.o \
gdk_x11_device_core_get_type.o \
gdk_x11_device_get_id.o \
gdk_x11_device_manager_core_get_type.o \
gdk_x11_device_manager_lookup.o \
gdk_x11_device_manager_xi2_get_type.o \
gdk_x11_device_xi2_get_type.o \
gdk_x11_display_error_trap_pop.o \
gdk_x11_display_error_trap_pop_ignored.o \
gdk_x11_display_error_trap_push.o \
gdk_x11_display_get_startup_notification_id.o \
gdk_x11_display_get_type.o \
gdk_x11_display_manager_get_type.o \
gdk_x11_display_set_startup_notification_id.o \
gdk_x11_display_string_to_compound_text.o \
gdk_x11_display_text_property_to_text_list.o \
gdk_x11_display_utf8_to_compound_text.o \
gdk_x11_drag_context_get_type.o \
gdk_x11_free_compound_text.o \
gdk_x11_free_text_list.o \
gdk_x11_keymap_get_group_for_state.o \
gdk_x11_keymap_get_type.o \
gdk_x11_keymap_key_is_modifier.o \
gdk_x11_screen_get_monitor_output.o \
gdk_x11_screen_get_type.o \
gdk_x11_set_sm_client_id.o \
gdk_x11_visual_get_type.o \
gdk_x11_window_foreign_new_for_display.o \
gdk_x11_window_get_type.o \
gdk_x11_window_get_xid.o \
gdk_x11_window_lookup_for_display.o \
gdk_x11_window_set_hide_titlebar_when_maximized.o \
gdk_x11_window_set_theme_variant.o \
gdk_x11_window_set_utf8_property.o 