GEN_FUNCS = \
XftCharExists.o \
XftCharFontSpecRender.o \
XftCharIndex.o \
XftCharSpecRender.o \
XftColorAllocName.o \
XftColorAllocValue.o \
XftColorFree.o \
XftDefaultHasRender.o \
XftDefaultSet.o \
XftDefaultSubstitute.o \
XftDrawChange.o \
XftDrawCharFontSpec.o \
XftDrawCharSpec.o \
XftDrawColormap.o \
XftDrawCreate.o \
XftDrawCreateAlpha.o \
XftDrawCreateBitmap.o \
XftDrawDestroy.o \
XftDrawDisplay.o \
XftDrawDrawable.o \
XftDrawGlyphFontSpec.o \
XftDrawGlyphSpec.o \
XftDrawGlyphs.o \
XftDrawPicture.o \
XftDrawRect.o \
XftDrawSetClip.o \
XftDrawSetClipRectangles.o \
XftDrawSetSubwindowMode.o \
XftDrawSrcPicture.o \
XftDrawString16.o \
XftDrawString32.o \
XftDrawString8.o \
XftDrawStringUtf16.o \
XftDrawStringUtf8.o \
XftDrawVisual.o \
XftFontCheckGlyph.o \
XftFontClose.o \
XftFontCopy.o \
XftFontInfoCreate.o \
XftFontInfoDestroy.o \
XftFontInfoEqual.o \
XftFontInfoHash.o \
XftFontLoadGlyphs.o \
XftFontMatch.o \
XftFontOpenInfo.o \
XftFontOpenName.o \
XftFontOpenPattern.o \
XftFontOpenXlfd.o \
XftFontUnloadGlyphs.o \
XftGetVersion.o \
XftGlyphExtents.o \
XftGlyphFontSpecRender.o \
XftGlyphRender.o \
XftGlyphSpecRender.o \
XftInit.o \
XftInitFtLibrary.o \
XftLockFace.o \
XftNameParse.o \
XftTextExtents16.o \
XftTextExtents32.o \
XftTextExtents8.o \
XftTextExtentsUtf16.o \
XftTextExtentsUtf8.o \
XftTextRender16.o \
XftTextRender16BE.o \
XftTextRender16LE.o \
XftTextRender32.o \
XftTextRender32BE.o \
XftTextRender32LE.o \
XftTextRender8.o \
XftTextRenderUtf16.o \
XftTextRenderUtf8.o \
XftUnlockFace.o \
XftXlfdParse.o 