// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <pango-1.0/pango/pangoxft.h>
#include <X11/X.h>
#include <X11/Xft/Xft.h>
#undef XftDrawChange
static void(*funcptr) (XftDraw * , Drawable ) = 0;

extern int __lsb_check_params;
void XftDrawChange (XftDraw * arg0 , Drawable arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for XftDrawChange()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XftDrawChange");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XftDrawChange. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XftDrawChange() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "XftDrawChange - arg0");
		}
		validate_NULL_TYPETYPE(  arg0, "XftDrawChange - arg0");
		validate_NULL_TYPETYPE(  arg1, "XftDrawChange - arg1");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

