/* Generated file - Do Not Edit */

#include "rpmchk.h"
#include "tagfuncs.h"

RpmIdxTagFuncRec SigTags[] = {
{HDRTAG_HDRIMAGE,	"HDRTAG_HDRIMAGE",	BIN,	checkRpmIdxHDRIMAGE,	Required,	NotSeen},
{HDRTAG_HDRSIGNATURES,	"HDRTAG_HDRSIGNATURES",	BIN,	checkRpmIdxHDRSIGNATURES,	Required,	NotSeen},
{HDRTAG_HDRIMMUTABLE,	"HDRTAG_HDRIMMUTABLE",	BIN,	checkRpmIdxHDRIMMUTABLE,	Required,	NotSeen},
{HDRTAG_HDRREGIONS,	"HDRTAG_HDRREGIONS",	BIN,	checkRpmIdxHDRREGIONS,	Required,	NotSeen},
{HDRTAG_HDRI18NTABLE,	"HDRTAG_HDRI18NTABLE",	STRING_ARRAY,	checkRpmIdxHDRI18NTABLE,	Required,	NotSeen},
{SIGTAG_SHA1HEADER,	"SIGTAG_SHA1HEADER",	STRING,	checkRpmIdxSHA1HEADER,	Required,	NotSeen},
{SIGTAG_SIZE,	"SIGTAG_SIZE",	INT32,	checkRpmIdxSIZE,	Required,	NotSeen},
{SIGTAG_MD5,	"SIGTAG_MD5",	BIN,	checkRpmIdxMD5,	Required,	NotSeen},
{SIGTAG_PGP,	"SIGTAG_PGP",	BIN,	checkRpmIdxPGP,	Required,	NotSeen},
	};


int numSigIdxTags = sizeof(SigTags)/sizeof(RpmIdxTagFuncRec);

RpmIdxTagFuncRec HdrTags[] = {
{HDRTAG_HDRIMAGE,	"HDRTAG_HDRIMAGE",	BIN,	checkRpmIdxHDRIMAGE,	Required,	NotSeen},
{HDRTAG_HDRSIGNATURES,	"HDRTAG_HDRSIGNATURES",	BIN,	checkRpmIdxHDRSIGNATURES,	Required,	NotSeen},
{HDRTAG_HDRIMMUTABLE,	"HDRTAG_HDRIMMUTABLE",	BIN,	checkRpmIdxHDRIMMUTABLE,	Required,	NotSeen},
{HDRTAG_HDRREGIONS,	"HDRTAG_HDRREGIONS",	BIN,	checkRpmIdxHDRREGIONS,	Required,	NotSeen},
{HDRTAG_HDRI18NTABLE,	"HDRTAG_HDRI18NTABLE",	STRING_ARRAY,	checkRpmIdxHDRI18NTABLE,	Required,	NotSeen},
{RPMTAG_NAME,	"RPMTAG_NAME",	STRING,	checkRpmIdxNAME,	Required,	NotSeen},
{RPMTAG_VERSION,	"RPMTAG_VERSION",	STRING,	checkRpmIdxVERSION,	Required,	NotSeen},
{RPMTAG_RELEASE,	"RPMTAG_RELEASE",	STRING,	checkRpmIdxRELEASE,	Required,	NotSeen},
{RPMTAG_SUMMARY,	"RPMTAG_SUMMARY",	I18NSTRING,	checkRpmIdxSUMMARY,	Required,	NotSeen},
{RPMTAG_DESCRIPTION,	"RPMTAG_DESCRIPTION",	I18NSTRING,	checkRpmIdxDESCRIPTION,	Required,	NotSeen},
{RPMTAG_OS,	"RPMTAG_OS",	STRING,	checkRpmIdxOS,	Required,	NotSeen},
{RPMTAG_ARCH,	"RPMTAG_ARCH",	STRING,	checkRpmIdxARCH,	Required,	NotSeen},
{RPMTAG_PROVIDENAME,	"RPMTAG_PROVIDENAME",	STRING_ARRAY,	checkRpmIdxPROVIDENAME,	Required,	NotSeen},
{RPMTAG_REQUIREFLAGS,	"RPMTAG_REQUIREFLAGS",	INT32,	checkRpmIdxREQUIREFLAGS,	Required,	NotSeen},
{RPMTAG_REQUIRENAME,	"RPMTAG_REQUIRENAME",	STRING_ARRAY,	checkRpmIdxREQUIRENAME,	Required,	NotSeen},
{RPMTAG_REQUIREVERSION,	"RPMTAG_REQUIREVERSION",	STRING_ARRAY,	checkRpmIdxREQUIREVERSION,	Required,	NotSeen},
{RPMTAG_PAYLOADFORMAT,	"RPMTAG_PAYLOADFORMAT",	STRING,	checkRpmIdxPAYLOADFORMAT,	Required,	NotSeen},
{RPMTAG_PAYLOADCOMPRESSOR,	"RPMTAG_PAYLOADCOMPRESSOR",	STRING,	checkRpmIdxPAYLOADCOMPRESSOR,	Required,	NotSeen},
	};

int numHdrIdxTags = sizeof(HdrTags)/sizeof(RpmIdxTagFuncRec);
