GEN_FUNCS = \
SmFreeProperty.o \
SmFreeReasons.o \
SmcClientID.o \
SmcCloseConnection.o \
SmcDeleteProperties.o \
SmcGetIceConnection.o \
SmcGetProperties.o \
SmcInteractDone.o \
SmcInteractRequest.o \
SmcModifyCallbacks.o \
SmcOpenConnection.o \
SmcProtocolRevision.o \
SmcProtocolVersion.o \
SmcRelease.o \
SmcRequestSaveYourself.o \
SmcRequestSaveYourselfPhase2.o \
SmcSaveYourselfDone.o \
SmcSetErrorHandler.o \
SmcSetProperties.o \
SmcVendor.o \
SmsCleanUp.o \
SmsClientHostName.o \
SmsClientID.o \
SmsDie.o \
SmsGenerateClientID.o \
SmsGetIceConnection.o \
SmsInitialize.o \
SmsInteract.o \
SmsProtocolRevision.o \
SmsProtocolVersion.o \
SmsRegisterClientReply.o \
SmsReturnProperties.o \
SmsSaveComplete.o \
SmsSaveYourself.o \
SmsSaveYourselfPhase2.o \
SmsSetErrorHandler.o \
SmsShutdownCancelled.o 