// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/SM/SMlib.h>
static int(*funcptr)(SmcConn) = 0;

int SmcProtocolRevision(SmcConn arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "SmcProtocolRevision");
	validate_NULL_TYPETYPE(arg0, "SmcProtocolRevision");
	return funcptr(arg0);
}

int __lsb_SmcProtocolRevision(SmcConn arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "SmcProtocolRevision");
	return funcptr(arg0);
}

