// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/SM/SMlib.h>
static int(*funcptr)(SmsConn) = 0;

char * SmsClientID(SmsConn arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "SmsClientID");
	validate_NULL_TYPETYPE(arg0, "SmsClientID");
	return funcptr(arg0);
}

char * lsb_SmsClientID(SmsConn arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "SmsClientID");
	return funcptr(arg0);
}

