// Generated by gen_lib.pl

#include "type_tests.h"
#include <dlfcn.h>
#include <X11/SM/SMlib.h>
static int(*funcptr)(SmsConn) = 0;

char * SmsGenerateClientID(SmsConn arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "SmsGenerateClientID");
	validate_NULL_TYPETYPE(arg0, "SmsGenerateClientID");
	return funcptr(arg0);
}

char * __lsb_SmsGenerateClientID(SmsConn arg0)
{
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "SmsGenerateClientID");
	return funcptr(arg0);
}

