.TH lsbarchk "1" "" "lsbarchk (LSB)" LSB
.SH NAME
lsbarchk \- check LSB conformance of static archive
.SH SYNOPSIS
.B lsbarchk
.RB [ \-o
.IR outputfile ]
.RB [ \-A ]
.RB [ \-M
.IR modulename ]
.RB [ \-L
.IR pathtolib "] ..."
.I libname
.SH DESCRIPTION
.PP
Measure a static archive's suitability for inclusion in an LSB
conforming binary.  Checks if any unresolved external references
are to interfaces which are not part of the LSB specification.
Since some unresolved external references may be intentional,
.I lsbarchk
can be instructed to look at additional libraries for such references.
.TP
\fB\-o \fIoutputfile\fR
Write the journal file (see below) to \fIoutputfile\fR
instead of to the default filename in the current directory.
.TP
\fB\-A
Check the symbols found in all modules.
.TP
\fB\-M \fImodulename\fR
Check only the symbols found in module \fImodulename\fR.
.TP
\fB\-L \fInameoflib\fR
Specify the full pathname of a library which will be part of the application.
This option can be specified as many times as needed, and will prevent 
.I lsbarchk
from complaining about symbols which are provided in those libraries.
The order of libraries specified this way is significant.
Note that by using -L, you are predicting libraries which will be
specified at link time; if 
.I lsbarchk
is thus convinced not to report on certain issues,
and then the libraries are NOT used at link time,
IR lsbarchk 's
answers are not very useful!
.PP
A journal file is created named 
.BI journal.archk. libname ,
where 
.I libname
is the library specified on the command line. It contains a record of
the test results in a format that can be processed by the same tools
used for LSB Certification (e.g. 
.IR tjreport ).
You must have write access to the current working directory
in order to run 
.I lsbarchk
successfully, or use the \fI-o\fR option to
specify an alternate location for the journal.
.SH "NOTES"
.I lsbarchk 
is a predictive tool.  It can identify some problems which are
certain to be issues, but depending on how the final binary is
constructed, may miss others. 
.I lsbappchk
should always be run on the final binary.
.SH "AUTHORS"
The contributors to the Linux Standard Base.
.SH "REPORTING BUGS"
If you obtained this checker from the LSB ftp site,
report bugs at http://bugs.linuxbase.org or email to
<lsb-test@freestandards.org>.  If you obtained this
from your distribution, report bugs back to the
distribution in the normal way.
.SH "SEE ALSO"
Linux Standard Base specification and other documents at
http://www.linuxbase.org/
