.TH lsbappchk "1" "" "lsbappchk (LSB)" LSB
.SH NAME
lsbappchk \- check LSB conformance of application
.SH SYNOPSIS
.B lsbappchk
.RB [ \-L
.IR pathtolib ]...
.IR appname ...
.SH DESCRIPTION
.PP
Measure an application executable's conformance to the Linux Standard
Base (LSB) specification. The object format of the application is
checked, as is the list of shared libraries used by the application,
and the list of functions and global data used by the
application. Warnings are produced for anything that is used, but not
contained in the LSB specification.
.TP
\fB\-L \fIpathtolib\fR
Specify libraries which are part of the application.  This option can
be specified as many times as needed, and will prevent lsbappchk from
complaining about symbols which are provided in those shared
libraries.
.PP
A journal file named journal.appchk.<appname> where appname is the
first binary specified is created. It contains a record of the test
results. You must have write access to the current working directory
in order to run lsbappchk successfully.
.PP
The lsbappchk program cannot detect all conformance problems.  In particular, itis a static test and does not actually run the application.  Lsbappchk
will not find any behaviors which show themselves only at run\-time
(for example, anything involving the File Hierarchy Standard, or
constants and other such items which are found in header files).
.SH "AUTHORS"
The contributors to the Linux Standard Base.
.SH "REPORTING BUGS"
Report bugs to <lsb-test@linuxbase.org>.
.SH "BUGS"
Should be able to specify where to write the journal file.
.SH "SEE ALSO"
Linux Standard Base specification and other documents at
http://www.linuxbase.org/
