.TH lsbdynchk "1" "" "lsbdynchk (LSB)" LSB
.SH NAME
lsbdynchk \- check LSB conformance of application
.SH SYNOPSIS
.B lsbdynchk
.IR appname ...
.SH DESCRIPTION
.PP
Measure an application's runtime conformance to the Linux Standard
Base (LSB) specification. The parameters passed to LSB interfaces are
checked as the application is executed. 
.PP
The lsbdynchk program should be used in conjuntion with the lsbappchk program.
.SH "AUTHORS"
The contributors to the Linux Standard Base.
.SH "REPORTING BUGS"
If you obtained this checker from the LSB ftp site,
report bugs at http://bugs.linuxbase.org or email to
<lsb-discuss@linux-foundation.org>.  If you obtained this
from your distribution, report bugs back to the
distribution in the normal way.
.SH "BUGS"
Should produce a journal file.
.SH "SEE ALSO"
Linux Standard Base specification and other documents at
http://www.linux-foundation.org/
