.TH lsbdynchk "1" "" "lsbdynchk (LSB)" LSB
.SH NAME
lsbdynchk \- check LSB conformance of application
.SH SYNOPSIS
.B lsbdynchk
.IR appname ...
.SH DESCRIPTION
.PP
Measure an application's runtime conformance to the Linux Standard
Base (LSB) specification. The parameters passed to LSB interfaces are
checked as the application is executed. 
.PP
The lsbdynchk program should be used in conjuntion with the lsbappchk program.
.SH "AUTHORS"
The contributors to the Linux Standard Base.
.SH "REPORTING BUGS"
Report bugs to <lsb-test@linuxbase.org>.
.SH "BUGS"
Should produce a journal file.
.SH "SEE ALSO"
Linux Standard Base specification and other documents at
http://www.linuxbase.org/
