// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/gio/giotypes.h>
#include <glib-2.0/gio/gioenums.h>
#include <glib-2.0/glib.h>
#include <glib-2.0/gio/gdbusconnection.h>
#undef g_dbus_connection_send_message_with_reply_sync
static GDBusMessage *(*funcptr) (GDBusConnection * , GDBusMessage * , GDBusSendMessageFlags , gint , unsigned int volatile  * , GCancellable * , GError * * ) = 0;

extern int __lsb_check_params;
GDBusMessage * g_dbus_connection_send_message_with_reply_sync (GDBusConnection * arg0 , GDBusMessage * arg1 , GDBusSendMessageFlags arg2 , gint arg3 , unsigned int volatile  * arg4 , GCancellable * arg5 , GError * * arg6 )
{
	int reset_flag = __lsb_check_params;
	GDBusMessage * ret_value  ;
	__lsb_output(4, "Invoking wrapper for g_dbus_connection_send_message_with_reply_sync()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_dbus_connection_send_message_with_reply_sync");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_dbus_connection_send_message_with_reply_sync. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_dbus_connection_send_message_with_reply_sync() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "g_dbus_connection_send_message_with_reply_sync - arg0 (connection)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_dbus_connection_send_message_with_reply_sync - arg0 (connection)");
		if( arg1 ) {
		validate_RWaddress( arg1, "g_dbus_connection_send_message_with_reply_sync - arg1 (message)");
		}
		validate_NULL_TYPETYPE(  arg1, "g_dbus_connection_send_message_with_reply_sync - arg1 (message)");
		validate_NULL_TYPETYPE(  arg2, "g_dbus_connection_send_message_with_reply_sync - arg2 (flags)");
		validate_NULL_TYPETYPE(  arg3, "g_dbus_connection_send_message_with_reply_sync - arg3 (timeout_msec)");
		if( arg4 ) {
		validate_RWaddress( arg4, "g_dbus_connection_send_message_with_reply_sync - arg4 (out_serial)");
		}
		validate_NULL_TYPETYPE(  arg4, "g_dbus_connection_send_message_with_reply_sync - arg4 (out_serial)");
		if( arg5 ) {
		validate_RWaddress( arg5, "g_dbus_connection_send_message_with_reply_sync - arg5 (cancellable)");
		}
		validate_NULL_TYPETYPE(  arg5, "g_dbus_connection_send_message_with_reply_sync - arg5 (cancellable)");
		if( arg6 ) {
		validate_RWaddress( arg6, "g_dbus_connection_send_message_with_reply_sync - arg6 (error)");
		}
		validate_NULL_TYPETYPE(  arg6, "g_dbus_connection_send_message_with_reply_sync - arg6 (error)");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
	__lsb_check_params = reset_flag;
	return ret_value;
}

