// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#include <glib-2.0/gio/gnetworkaddress.h>
#undef g_network_address_parse_uri
static GSocketConnectable *(*funcptr) (const gchar * , guint16 , GError * * ) = 0;

extern int __lsb_check_params;
GSocketConnectable * g_network_address_parse_uri (const gchar * arg0 , guint16 arg1 , GError * * arg2 )
{
	int reset_flag = __lsb_check_params;
	GSocketConnectable * ret_value  ;
	__lsb_output(4, "Invoking wrapper for g_network_address_parse_uri()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_network_address_parse_uri");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_network_address_parse_uri. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_network_address_parse_uri() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "g_network_address_parse_uri - arg0 (uri)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_network_address_parse_uri - arg0 (uri)");
		validate_NULL_TYPETYPE(  arg1, "g_network_address_parse_uri - arg1 (default_port)");
		if( arg2 ) {
		validate_RWaddress( arg2, "g_network_address_parse_uri - arg2 (error)");
		}
		validate_NULL_TYPETYPE(  arg2, "g_network_address_parse_uri - arg2 (error)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

