// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#include <glib-2.0/gio/gsimpleaction.h>
#undef g_simple_action_new_stateful
static GSimpleAction *(*funcptr) (const gchar * , , GVariant * ) = 0;

extern int __lsb_check_params;
GSimpleAction * g_simple_action_new_stateful (const gchar * arg0 ,  arg1, GVariant * arg2 )
{
	int reset_flag = __lsb_check_params;
	GSimpleAction * ret_value  ;
	__lsb_output(4, "Invoking wrapper for g_simple_action_new_stateful()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_simple_action_new_stateful");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_simple_action_new_stateful. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_simple_action_new_stateful() - validating");
		if( arg0 ) {
		validate_Rdaddress( arg0, "g_simple_action_new_stateful - arg0 (name)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_simple_action_new_stateful - arg0 (name)");
		validate_UNSET_TYPETYPE(  arg1, "g_simple_action_new_stateful - arg1 (parameter_type)");
		if( arg2 ) {
		validate_RWaddress( arg2, "g_simple_action_new_stateful - arg2 (state)");
		}
		validate_NULL_TYPETYPE(  arg2, "g_simple_action_new_stateful - arg2 (state)");
	}
	ret_value = funcptr(arg0, arg1, arg2);
	__lsb_check_params = reset_flag;
	return ret_value;
}

