// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/gio/giotypes.h>
#include <glib-2.0/gio/gsocketservice.h>
#undef g_socket_service_is_active
static gboolean(*funcptr) (GSocketService * ) = 0;

extern int __lsb_check_params;
gboolean g_socket_service_is_active (GSocketService * arg0 )
{
	int reset_flag = __lsb_check_params;
	gboolean ret_value  ;
	__lsb_output(4, "Invoking wrapper for g_socket_service_is_active()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_socket_service_is_active");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_socket_service_is_active. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_socket_service_is_active() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "g_socket_service_is_active - arg0 (service)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_socket_service_is_active - arg0 (service)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

