// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/gio/giotypes.h>
#include <glib-2.0/gio/gioenums.h>
#include <glib-2.0/gio/gsocketclient.h>
#undef g_socket_client_set_family
static void(*funcptr) (GSocketClient * , GSocketFamily ) = 0;

extern int __lsb_check_params;
void g_socket_client_set_family (GSocketClient * arg0 , GSocketFamily arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for g_socket_client_set_family()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "g_socket_client_set_family");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load g_socket_client_set_family. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "g_socket_client_set_family() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "g_socket_client_set_family - arg0 (client)");
		}
		validate_NULL_TYPETYPE(  arg0, "g_socket_client_set_family - arg0 (client)");
		validate_NULL_TYPETYPE(  arg1, "g_socket_client_set_family - arg1 (family)");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

