GEN_FUNCS = \
pango_alignment_get_type.o \
pango_attr_background_new.o \
pango_attr_fallback_new.o \
pango_attr_family_new.o \
pango_attr_font_desc_new.o \
pango_attr_foreground_new.o \
pango_attr_gravity_hint_new.o \
pango_attr_gravity_new.o \
pango_attr_iterator_copy.o \
pango_attr_iterator_destroy.o \
pango_attr_iterator_get.o \
pango_attr_iterator_get_attrs.o \
pango_attr_iterator_get_font.o \
pango_attr_iterator_next.o \
pango_attr_iterator_range.o \
pango_attr_language_new.o \
pango_attr_letter_spacing_new.o \
pango_attr_list_change.o \
pango_attr_list_copy.o \
pango_attr_list_filter.o \
pango_attr_list_get_iterator.o \
pango_attr_list_get_type.o \
pango_attr_list_insert.o \
pango_attr_list_insert_before.o \
pango_attr_list_new.o \
pango_attr_list_ref.o \
pango_attr_list_splice.o \
pango_attr_list_unref.o \
pango_attr_rise_new.o \
pango_attr_scale_new.o \
pango_attr_shape_new.o \
pango_attr_shape_new_with_data.o \
pango_attr_size_new.o \
pango_attr_size_new_absolute.o \
pango_attr_stretch_new.o \
pango_attr_strikethrough_color_new.o \
pango_attr_strikethrough_new.o \
pango_attr_style_new.o \
pango_attr_type_get_name.o \
pango_attr_type_get_type.o \
pango_attr_type_register.o \
pango_attr_underline_color_new.o \
pango_attr_underline_new.o \
pango_attr_variant_new.o \
pango_attr_weight_new.o \
pango_attribute_copy.o \
pango_attribute_destroy.o \
pango_attribute_equal.o \
pango_attribute_init.o \
pango_bidi_type_for_unichar.o \
pango_bidi_type_get_type.o \
pango_break.o \
pango_color_copy.o \
pango_color_free.o \
pango_color_get_type.o \
pango_color_parse.o \
pango_color_to_string.o \
pango_context_get_base_dir.o \
pango_context_get_base_gravity.o \
pango_context_get_font_description.o \
pango_context_get_font_map.o \
pango_context_get_gravity.o \
pango_context_get_gravity_hint.o \
pango_context_get_language.o \
pango_context_get_matrix.o \
pango_context_get_metrics.o \
pango_context_get_type.o \
pango_context_list_families.o \
pango_context_load_font.o \
pango_context_load_fontset.o \
pango_context_new.o \
pango_context_set_base_dir.o \
pango_context_set_base_gravity.o \
pango_context_set_font_description.o \
pango_context_set_font_map.o \
pango_context_set_gravity_hint.o \
pango_context_set_language.o \
pango_context_set_matrix.o \
pango_coverage_copy.o \
pango_coverage_from_bytes.o \
pango_coverage_get.o \
pango_coverage_level_get_type.o \
pango_coverage_max.o \
pango_coverage_new.o \
pango_coverage_ref.o \
pango_coverage_set.o \
pango_coverage_to_bytes.o \
pango_coverage_unref.o \
pango_direction_get_type.o \
pango_ellipsize_mode_get_type.o \
pango_extents_to_pixels.o \
pango_find_base_dir.o \
pango_find_paragraph_boundary.o \
pango_font_describe.o \
pango_font_describe_with_absolute_size.o \
pango_font_description_better_match.o \
pango_font_description_copy.o \
pango_font_description_copy_static.o \
pango_font_description_equal.o \
pango_font_description_free.o \
pango_font_description_from_string.o \
pango_font_description_get_family.o \
pango_font_description_get_gravity.o \
pango_font_description_get_set_fields.o \
pango_font_description_get_size.o \
pango_font_description_get_size_is_absolute.o \
pango_font_description_get_stretch.o \
pango_font_description_get_style.o \
pango_font_description_get_type.o \
pango_font_description_get_variant.o \
pango_font_description_get_weight.o \
pango_font_description_hash.o \
pango_font_description_merge.o \
pango_font_description_merge_static.o \
pango_font_description_new.o \
pango_font_description_set_absolute_size.o \
pango_font_description_set_family.o \
pango_font_description_set_family_static.o \
pango_font_description_set_gravity.o \
pango_font_description_set_size.o \
pango_font_description_set_stretch.o \
pango_font_description_set_style.o \
pango_font_description_set_variant.o \
pango_font_description_set_weight.o \
pango_font_description_to_filename.o \
pango_font_description_to_string.o \
pango_font_description_unset_fields.o \
pango_font_descriptions_free.o \
pango_font_face_describe.o \
pango_font_face_get_face_name.o \
pango_font_face_get_type.o \
pango_font_face_is_synthesized.o \
pango_font_face_list_sizes.o \
pango_font_family_get_name.o \
pango_font_family_get_type.o \
pango_font_family_is_monospace.o \
pango_font_family_list_faces.o \
pango_font_find_shaper.o \
pango_font_get_coverage.o \
pango_font_get_font_map.o \
pango_font_get_glyph_extents.o \
pango_font_get_metrics.o \
pango_font_get_type.o \
pango_font_map_create_context.o \
pango_font_map_get_type.o \
pango_font_map_list_families.o \
pango_font_map_load_font.o \
pango_font_map_load_fontset.o \
pango_font_mask_get_type.o \
pango_font_metrics_get_approximate_char_width.o \
pango_font_metrics_get_approximate_digit_width.o \
pango_font_metrics_get_ascent.o \
pango_font_metrics_get_descent.o \
pango_font_metrics_get_strikethrough_position.o \
pango_font_metrics_get_strikethrough_thickness.o \
pango_font_metrics_get_type.o \
pango_font_metrics_get_underline_position.o \
pango_font_metrics_get_underline_thickness.o \
pango_font_metrics_ref.o \
pango_font_metrics_unref.o \
pango_fontset_foreach.o \
pango_fontset_get_font.o \
pango_fontset_get_metrics.o \
pango_fontset_get_type.o \
pango_get_log_attrs.o \
pango_glyph_item_apply_attrs.o \
pango_glyph_item_copy.o \
pango_glyph_item_free.o \
pango_glyph_item_get_logical_widths.o \
pango_glyph_item_get_type.o \
pango_glyph_item_iter_copy.o \
pango_glyph_item_iter_free.o \
pango_glyph_item_iter_get_type.o \
pango_glyph_item_iter_init_end.o \
pango_glyph_item_iter_init_start.o \
pango_glyph_item_iter_next_cluster.o \
pango_glyph_item_iter_prev_cluster.o \
pango_glyph_item_letter_space.o \
pango_glyph_item_split.o \
pango_glyph_string_copy.o \
pango_glyph_string_extents.o \
pango_glyph_string_extents_range.o \
pango_glyph_string_free.o \
pango_glyph_string_get_logical_widths.o \
pango_glyph_string_get_type.o \
pango_glyph_string_get_width.o \
pango_glyph_string_index_to_x.o \
pango_glyph_string_new.o \
pango_glyph_string_set_size.o \
pango_glyph_string_x_to_index.o \
pango_gravity_get_for_matrix.o \
pango_gravity_get_for_script.o \
pango_gravity_get_for_script_and_width.o \
pango_gravity_get_type.o \
pango_gravity_hint_get_type.o \
pango_gravity_to_rotation.o \
pango_is_zero_width.o \
pango_item_copy.o \
pango_item_free.o \
pango_item_get_type.o \
pango_item_new.o \
pango_item_split.o \
pango_itemize.o \
pango_itemize_with_base_dir.o \
pango_language_from_string.o \
pango_language_get_default.o \
pango_language_get_sample_string.o \
pango_language_get_scripts.o \
pango_language_get_type.o \
pango_language_includes_script.o \
pango_language_matches.o \
pango_language_to_string.o \
pango_layout_context_changed.o \
pango_layout_copy.o \
pango_layout_get_alignment.o \
pango_layout_get_attributes.o \
pango_layout_get_auto_dir.o \
pango_layout_get_baseline.o \
pango_layout_get_character_count.o \
pango_layout_get_context.o \
pango_layout_get_cursor_pos.o \
pango_layout_get_ellipsize.o \
pango_layout_get_extents.o \
pango_layout_get_font_description.o \
pango_layout_get_height.o \
pango_layout_get_indent.o \
pango_layout_get_iter.o \
pango_layout_get_justify.o \
pango_layout_get_line.o \
pango_layout_get_line_count.o \
pango_layout_get_line_readonly.o \
pango_layout_get_lines.o \
pango_layout_get_lines_readonly.o \
pango_layout_get_log_attrs.o \
pango_layout_get_log_attrs_readonly.o \
pango_layout_get_pixel_extents.o \
pango_layout_get_pixel_size.o \
pango_layout_get_single_paragraph_mode.o \
pango_layout_get_size.o \
pango_layout_get_spacing.o \
pango_layout_get_tabs.o \
pango_layout_get_text.o \
pango_layout_get_type.o \
pango_layout_get_unknown_glyphs_count.o \
pango_layout_get_width.o \
pango_layout_get_wrap.o \
pango_layout_index_to_line_x.o \
pango_layout_index_to_pos.o \
pango_layout_is_ellipsized.o \
pango_layout_is_wrapped.o \
pango_layout_iter_at_last_line.o \
pango_layout_iter_copy.o \
pango_layout_iter_free.o \
pango_layout_iter_get_baseline.o \
pango_layout_iter_get_char_extents.o \
pango_layout_iter_get_cluster_extents.o \
pango_layout_iter_get_index.o \
pango_layout_iter_get_layout.o \
pango_layout_iter_get_layout_extents.o \
pango_layout_iter_get_line.o \
pango_layout_iter_get_line_extents.o \
pango_layout_iter_get_line_readonly.o \
pango_layout_iter_get_line_yrange.o \
pango_layout_iter_get_run.o \
pango_layout_iter_get_run_extents.o \
pango_layout_iter_get_run_readonly.o \
pango_layout_iter_get_type.o \
pango_layout_iter_next_char.o \
pango_layout_iter_next_cluster.o \
pango_layout_iter_next_line.o \
pango_layout_iter_next_run.o \
pango_layout_line_get_extents.o \
pango_layout_line_get_pixel_extents.o \
pango_layout_line_get_type.o \
pango_layout_line_get_x_ranges.o \
pango_layout_line_index_to_x.o \
pango_layout_line_ref.o \
pango_layout_line_unref.o \
pango_layout_line_x_to_index.o \
pango_layout_move_cursor_visually.o \
pango_layout_new.o \
pango_layout_set_alignment.o \
pango_layout_set_attributes.o \
pango_layout_set_auto_dir.o \
pango_layout_set_ellipsize.o \
pango_layout_set_font_description.o \
pango_layout_set_height.o \
pango_layout_set_indent.o \
pango_layout_set_justify.o \
pango_layout_set_markup.o \
pango_layout_set_markup_with_accel.o \
pango_layout_set_single_paragraph_mode.o \
pango_layout_set_spacing.o \
pango_layout_set_tabs.o \
pango_layout_set_text.o \
pango_layout_set_width.o \
pango_layout_set_wrap.o \
pango_layout_xy_to_index.o \
pango_log2vis_get_embedding_levels.o \
pango_matrix_concat.o \
pango_matrix_copy.o \
pango_matrix_free.o \
pango_matrix_get_font_scale_factor.o \
pango_matrix_get_type.o \
pango_matrix_rotate.o \
pango_matrix_scale.o \
pango_matrix_transform_distance.o \
pango_matrix_transform_pixel_rectangle.o \
pango_matrix_transform_point.o \
pango_matrix_transform_rectangle.o \
pango_matrix_translate.o \
pango_parse_enum.o \
pango_parse_markup.o \
pango_parse_stretch.o \
pango_parse_style.o \
pango_parse_variant.o \
pango_parse_weight.o \
pango_quantize_line_geometry.o \
pango_read_line.o \
pango_render_part_get_type.o \
pango_renderer_activate.o \
pango_renderer_deactivate.o \
pango_renderer_draw_error_underline.o \
pango_renderer_draw_glyph.o \
pango_renderer_draw_glyph_item.o \
pango_renderer_draw_glyphs.o \
pango_renderer_draw_layout.o \
pango_renderer_draw_layout_line.o \
pango_renderer_draw_rectangle.o \
pango_renderer_draw_trapezoid.o \
pango_renderer_get_color.o \
pango_renderer_get_layout.o \
pango_renderer_get_layout_line.o \
pango_renderer_get_matrix.o \
pango_renderer_get_type.o \
pango_renderer_part_changed.o \
pango_renderer_set_color.o \
pango_renderer_set_matrix.o \
pango_reorder_items.o \
pango_scan_int.o \
pango_scan_string.o \
pango_scan_word.o \
pango_script_for_unichar.o \
pango_script_get_sample_language.o \
pango_script_get_type.o \
pango_script_iter_free.o \
pango_script_iter_get_range.o \
pango_script_iter_new.o \
pango_script_iter_next.o \
pango_shape.o \
pango_skip_space.o \
pango_split_file_list.o \
pango_stretch_get_type.o \
pango_style_get_type.o \
pango_tab_align_get_type.o \
pango_tab_array_copy.o \
pango_tab_array_free.o \
pango_tab_array_get_positions_in_pixels.o \
pango_tab_array_get_size.o \
pango_tab_array_get_tab.o \
pango_tab_array_get_tabs.o \
pango_tab_array_get_type.o \
pango_tab_array_new.o \
pango_tab_array_resize.o \
pango_tab_array_set_tab.o \
pango_trim_string.o \
pango_underline_get_type.o \
pango_unichar_direction.o \
pango_units_from_double.o \
pango_units_to_double.o \
pango_variant_get_type.o \
pango_version.o \
pango_version_check.o \
pango_version_string.o \
pango_weight_get_type.o \
pango_wrap_mode_get_type.o 