// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <glib-2.0/glib.h>
#include <pango-1.0/pango/pango.h>
#undef pango_find_paragraph_boundary
static void(*funcptr) (const gchar * , gint , gint * , gint * ) = 0;

extern int __lsb_check_params;
void pango_find_paragraph_boundary (const gchar * arg0 , gint arg1 , gint * arg2 , gint * arg3 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for pango_find_paragraph_boundary()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pango_find_paragraph_boundary");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load pango_find_paragraph_boundary. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "pango_find_paragraph_boundary() - validating");
		validate_Rdaddress( arg0, "pango_find_paragraph_boundary - arg0 (text)");
		validate_NULL_TYPETYPE(  arg0, "pango_find_paragraph_boundary - arg0 (text)");
		validate_NULL_TYPETYPE(  arg1, "pango_find_paragraph_boundary - arg1 (length)");
		validate_RWaddress( arg2, "pango_find_paragraph_boundary - arg2 (paragraph_delimiter_index)");
		validate_NULL_TYPETYPE(  arg2, "pango_find_paragraph_boundary - arg2 (paragraph_delimiter_index)");
		validate_RWaddress( arg3, "pango_find_paragraph_boundary - arg3 (next_paragraph_start)");
		validate_NULL_TYPETYPE(  arg3, "pango_find_paragraph_boundary - arg3 (next_paragraph_start)");
	}
	funcptr(arg0, arg1, arg2, arg3);
	__lsb_check_params = reset_flag;
}

