// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <pango-1.0/pango/pango.h>
#undef pango_color_copy
static PangoColor *(*funcptr) (const PangoColor * ) = 0;

extern int __lsb_check_params;
PangoColor * pango_color_copy (const PangoColor * arg0 )
{
	int reset_flag = __lsb_check_params;
	PangoColor * ret_value  ;
	__lsb_output(4, "Invoking wrapper for pango_color_copy()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "pango_color_copy");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load pango_color_copy. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "pango_color_copy() - validating");
		validate_Rdaddress( arg0, "pango_color_copy - arg0 (src)");
		validate_NULL_TYPETYPE(  arg0, "pango_color_copy - arg0 (src)");
	}
	ret_value = funcptr(arg0);
	__lsb_check_params = reset_flag;
	return ret_value;
}

