GEN_FUNCS = \
XAllowDeviceEvents.o \
XChangeDeviceControl.o \
XChangeDeviceDontPropagateList.o \
XChangeDeviceKeyMapping.o \
XChangeFeedbackControl.o \
XChangeKeyboardDevice.o \
XChangePointerDevice.o \
XCloseDevice.o \
XDeviceBell.o \
XFreeDeviceControl.o \
XFreeDeviceList.o \
XFreeDeviceMotionEvents.o \
XFreeDeviceState.o \
XFreeFeedbackList.o \
XGetDeviceButtonMapping.o \
XGetDeviceControl.o \
XGetDeviceDontPropagateList.o \
XGetDeviceFocus.o \
XGetDeviceKeyMapping.o \
XGetDeviceModifierMapping.o \
XGetDeviceMotionEvents.o \
XGetExtensionVersion.o \
XGetFeedbackControl.o \
XGetSelectedExtensionEvents.o \
XGrabDevice.o \
XGrabDeviceButton.o \
XGrabDeviceKey.o \
XListInputDevices.o \
XOpenDevice.o \
XQueryDeviceState.o \
XSelectExtensionEvent.o \
XSendExtensionEvent.o \
XSetDeviceButtonMapping.o \
XSetDeviceFocus.o \
XSetDeviceMode.o \
XSetDeviceModifierMapping.o \
XSetDeviceValuators.o \
XUngrabDevice.o \
XUngrabDeviceButton.o \
XUngrabDeviceKey.o 