// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <X11/Xlib.h>
#include <X11/extensions/XInput.h>
#include <X11/X.h>
#undef XSetDeviceFocus
static int(*funcptr) (Display * , XDevice * , Window , int , Time ) = 0;

extern int __lsb_check_params;
int XSetDeviceFocus (Display * arg0 , XDevice * arg1 , Window arg2 , int arg3 , Time arg4 )
{
	int reset_flag = __lsb_check_params;
	int ret_value  ;
	__lsb_output(4, "Invoking wrapper for XSetDeviceFocus()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "XSetDeviceFocus");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load XSetDeviceFocus. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "XSetDeviceFocus() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "XSetDeviceFocus - arg0");
		}
		validate_NULL_TYPETYPE(  arg0, "XSetDeviceFocus - arg0");
		if( arg1 ) {
		validate_RWaddress( arg1, "XSetDeviceFocus - arg1");
		}
		validate_NULL_TYPETYPE(  arg1, "XSetDeviceFocus - arg1");
		validate_NULL_TYPETYPE(  arg2, "XSetDeviceFocus - arg2");
		validate_NULL_TYPETYPE(  arg3, "XSetDeviceFocus - arg3");
		validate_NULL_TYPETYPE(  arg4, "XSetDeviceFocus - arg4");
	}
	ret_value = funcptr(arg0, arg1, arg2, arg3, arg4);
	__lsb_check_params = reset_flag;
	return ret_value;
}

