// Generated by gen_lib.pl

#include "../../tests/type_tests.h"
#include "../../misc/lsb_output.h"
#include "stdlib.h"
#include <cairo/cairo-script-interpreter.h>
#undef cairo_script_interpreter_install_hooks
static void(*funcptr) (cairo_script_interpreter_t * , const cairo_script_interpreter_hooks_t * ) = 0;

extern int __lsb_check_params;
void cairo_script_interpreter_install_hooks (cairo_script_interpreter_t * arg0 , const cairo_script_interpreter_hooks_t * arg1 )
{
	int reset_flag = __lsb_check_params;
	__lsb_output(4, "Invoking wrapper for cairo_script_interpreter_install_hooks()");
	if(!funcptr)
		funcptr = dlsym(RTLD_NEXT, "cairo_script_interpreter_install_hooks");
	if(!funcptr) {
		__lsb_output(-1, "Failed to load cairo_script_interpreter_install_hooks. Probably the library was loaded using dlopen, we don't support this at the moment.");
		exit(1);
	}
	if(__lsb_check_params)
	{
		__lsb_check_params=0;
		__lsb_output(4, "cairo_script_interpreter_install_hooks() - validating");
		if( arg0 ) {
		validate_RWaddress( arg0, "cairo_script_interpreter_install_hooks - arg0 (ctx)");
		}
		validate_NULL_TYPETYPE(  arg0, "cairo_script_interpreter_install_hooks - arg0 (ctx)");
		if( arg1 ) {
		validate_Rdaddress( arg1, "cairo_script_interpreter_install_hooks - arg1 (hooks)");
		}
		validate_NULL_TYPETYPE(  arg1, "cairo_script_interpreter_install_hooks - arg1 (hooks)");
	}
	funcptr(arg0, arg1);
	__lsb_check_params = reset_flag;
}

