GEN_FUNCS = \
g_array_get_type.o \
g_binding_flags_get_type.o \
g_binding_get_flags.o \
g_binding_get_source.o \
g_binding_get_source_property.o \
g_binding_get_target.o \
g_binding_get_target_property.o \
g_binding_get_type.o \
g_boxed_copy.o \
g_boxed_free.o \
g_boxed_type_register_static.o \
g_byte_array_get_type.o \
g_bytes_get_type.o \
g_cclosure_marshal_BOOLEAN__FLAGS.o \
g_cclosure_marshal_STRING__OBJECT_POINTER.o \
g_cclosure_marshal_VOID__BOOLEAN.o \
g_cclosure_marshal_VOID__BOOLEANv.o \
g_cclosure_marshal_VOID__BOXED.o \
g_cclosure_marshal_VOID__BOXEDv.o \
g_cclosure_marshal_VOID__CHAR.o \
g_cclosure_marshal_VOID__CHARv.o \
g_cclosure_marshal_VOID__DOUBLE.o \
g_cclosure_marshal_VOID__DOUBLEv.o \
g_cclosure_marshal_VOID__ENUM.o \
g_cclosure_marshal_VOID__ENUMv.o \
g_cclosure_marshal_VOID__FLAGS.o \
g_cclosure_marshal_VOID__FLAGSv.o \
g_cclosure_marshal_VOID__FLOAT.o \
g_cclosure_marshal_VOID__FLOATv.o \
g_cclosure_marshal_VOID__INT.o \
g_cclosure_marshal_VOID__INTv.o \
g_cclosure_marshal_VOID__LONG.o \
g_cclosure_marshal_VOID__LONGv.o \
g_cclosure_marshal_VOID__OBJECT.o \
g_cclosure_marshal_VOID__OBJECTv.o \
g_cclosure_marshal_VOID__PARAM.o \
g_cclosure_marshal_VOID__PARAMv.o \
g_cclosure_marshal_VOID__POINTER.o \
g_cclosure_marshal_VOID__POINTERv.o \
g_cclosure_marshal_VOID__STRING.o \
g_cclosure_marshal_VOID__STRINGv.o \
g_cclosure_marshal_VOID__UCHAR.o \
g_cclosure_marshal_VOID__UCHARv.o \
g_cclosure_marshal_VOID__UINT.o \
g_cclosure_marshal_VOID__UINT_POINTER.o \
g_cclosure_marshal_VOID__UINT_POINTERv.o \
g_cclosure_marshal_VOID__UINTv.o \
g_cclosure_marshal_VOID__ULONG.o \
g_cclosure_marshal_VOID__ULONGv.o \
g_cclosure_marshal_VOID__VARIANT.o \
g_cclosure_marshal_VOID__VARIANTv.o \
g_cclosure_marshal_VOID__VOID.o \
g_cclosure_marshal_VOID__VOIDv.o \
g_cclosure_marshal_generic.o \
g_cclosure_marshal_generic_va.o \
g_cclosure_new.o \
g_cclosure_new_object.o \
g_cclosure_new_object_swap.o \
g_cclosure_new_swap.o \
g_clear_object.o \
g_closure_add_finalize_notifier.o \
g_closure_add_invalidate_notifier.o \
g_closure_add_marshal_guards.o \
g_closure_get_type.o \
g_closure_invalidate.o \
g_closure_invoke.o \
g_closure_new_object.o \
g_closure_new_simple.o \
g_closure_ref.o \
g_closure_remove_finalize_notifier.o \
g_closure_remove_invalidate_notifier.o \
g_closure_set_marshal.o \
g_closure_set_meta_marshal.o \
g_closure_sink.o \
g_closure_unref.o \
g_date_get_type.o \
g_date_time_get_type.o \
g_enum_complete_type_info.o \
g_enum_get_value.o \
g_enum_get_value_by_name.o \
g_enum_get_value_by_nick.o \
g_enum_register_static.o \
g_error_get_type.o \
g_flags_complete_type_info.o \
g_flags_get_first_value.o \
g_flags_get_value_by_name.o \
g_flags_get_value_by_nick.o \
g_flags_register_static.o \
g_gstring_get_type.o \
g_gtype_get_type.o \
g_hash_table_get_type.o \
g_initially_unowned_get_type.o \
g_io_channel_get_type.o \
g_io_condition_get_type.o \
g_key_file_get_type.o \
g_main_context_get_type.o \
g_main_loop_get_type.o \
g_match_info_get_type.o \
g_object_add_toggle_ref.o \
g_object_add_weak_pointer.o \
g_object_bind_property.o \
g_object_bind_property_full.o \
g_object_bind_property_with_closures.o \
g_object_class_find_property.o \
g_object_class_install_properties.o \
g_object_class_install_property.o \
g_object_class_list_properties.o \
g_object_class_override_property.o \
g_object_compat_control.o \
g_object_force_floating.o \
g_object_freeze_notify.o \
g_object_get_data.o \
g_object_get_property.o \
g_object_get_qdata.o \
g_object_get_type.o \
g_object_get_valist.o \
g_object_interface_find_property.o \
g_object_interface_install_property.o \
g_object_interface_list_properties.o \
g_object_is_floating.o \
g_object_new_valist.o \
g_object_newv.o \
g_object_notify.o \
g_object_notify_by_pspec.o \
g_object_ref.o \
g_object_ref_sink.o \
g_object_remove_toggle_ref.o \
g_object_remove_weak_pointer.o \
g_object_run_dispose.o \
g_object_set_data.o \
g_object_set_data_full.o \
g_object_set_property.o \
g_object_set_qdata.o \
g_object_set_qdata_full.o \
g_object_set_valist.o \
g_object_steal_data.o \
g_object_steal_qdata.o \
g_object_thaw_notify.o \
g_object_unref.o \
g_object_watch_closure.o \
g_object_weak_ref.o \
g_object_weak_unref.o \
g_param_spec_boolean.o \
g_param_spec_boxed.o \
g_param_spec_char.o \
g_param_spec_double.o \
g_param_spec_enum.o \
g_param_spec_flags.o \
g_param_spec_float.o \
g_param_spec_get_blurb.o \
g_param_spec_get_name.o \
g_param_spec_get_nick.o \
g_param_spec_get_qdata.o \
g_param_spec_get_redirect_target.o \
g_param_spec_gtype.o \
g_param_spec_int.o \
g_param_spec_int64.o \
g_param_spec_internal.o \
g_param_spec_long.o \
g_param_spec_object.o \
g_param_spec_override.o \
g_param_spec_param.o \
g_param_spec_pointer.o \
g_param_spec_pool_insert.o \
g_param_spec_pool_list.o \
g_param_spec_pool_list_owned.o \
g_param_spec_pool_lookup.o \
g_param_spec_pool_new.o \
g_param_spec_pool_remove.o \
g_param_spec_ref.o \
g_param_spec_ref_sink.o \
g_param_spec_set_qdata.o \
g_param_spec_set_qdata_full.o \
g_param_spec_sink.o \
g_param_spec_steal_qdata.o \
g_param_spec_string.o \
g_param_spec_uchar.o \
g_param_spec_uint.o \
g_param_spec_uint64.o \
g_param_spec_ulong.o \
g_param_spec_unichar.o \
g_param_spec_unref.o \
g_param_spec_value_array.o \
g_param_spec_variant.o \
g_param_type_register_static.o \
g_param_value_convert.o \
g_param_value_defaults.o \
g_param_value_set_default.o \
g_param_value_validate.o \
g_param_values_cmp.o \
g_pointer_type_register_static.o \
g_ptr_array_get_type.o \
g_regex_get_type.o \
g_signal_accumulator_first_wins.o \
g_signal_accumulator_true_handled.o \
g_signal_add_emission_hook.o \
g_signal_chain_from_overridden.o \
g_signal_connect_closure.o \
g_signal_connect_closure_by_id.o \
g_signal_connect_data.o \
g_signal_connect_object.o \
g_signal_emit_valist.o \
g_signal_emitv.o \
g_signal_get_invocation_hint.o \
g_signal_handler_block.o \
g_signal_handler_disconnect.o \
g_signal_handler_find.o \
g_signal_handler_is_connected.o \
g_signal_handler_unblock.o \
g_signal_handlers_block_matched.o \
g_signal_handlers_disconnect_matched.o \
g_signal_handlers_unblock_matched.o \
g_signal_has_handler_pending.o \
g_signal_list_ids.o \
g_signal_lookup.o \
g_signal_name.o \
g_signal_new_valist.o \
g_signal_newv.o \
g_signal_override_class_closure.o \
g_signal_override_class_handler.o \
g_signal_parse_name.o \
g_signal_query.o \
g_signal_remove_emission_hook.o \
g_signal_set_va_marshaller.o \
g_signal_stop_emission.o \
g_signal_stop_emission_by_name.o \
g_signal_type_cclosure_new.o \
g_source_get_type.o \
g_source_set_closure.o \
g_source_set_dummy_callback.o \
g_strdup_value_contents.o \
g_strv_get_type.o \
g_type_add_class_cache_func.o \
g_type_add_class_private.o \
g_type_add_interface_check.o \
g_type_add_interface_dynamic.o \
g_type_add_interface_static.o \
g_type_check_class_cast.o \
g_type_check_class_is_a.o \
g_type_check_instance.o \
g_type_check_instance_cast.o \
g_type_check_instance_is_a.o \
g_type_check_is_value_type.o \
g_type_check_value.o \
g_type_check_value_holds.o \
g_type_children.o \
g_type_class_add_private.o \
g_type_class_get_private.o \
g_type_class_peek.o \
g_type_class_peek_parent.o \
g_type_class_peek_static.o \
g_type_class_ref.o \
g_type_class_unref.o \
g_type_class_unref_uncached.o \
g_type_create_instance.o \
g_type_default_interface_peek.o \
g_type_default_interface_ref.o \
g_type_default_interface_unref.o \
g_type_depth.o \
g_type_free_instance.o \
g_type_from_name.o \
g_type_fundamental.o \
g_type_fundamental_next.o \
g_type_get_plugin.o \
g_type_get_qdata.o \
g_type_init.o \
g_type_init_with_debug_flags.o \
g_type_instance_get_private.o \
g_type_interface_add_prerequisite.o \
g_type_interface_get_plugin.o \
g_type_interface_peek.o \
g_type_interface_peek_parent.o \
g_type_interface_prerequisites.o \
g_type_interfaces.o \
g_type_is_a.o \
g_type_module_add_interface.o \
g_type_module_get_type.o \
g_type_module_register_enum.o \
g_type_module_register_flags.o \
g_type_module_register_type.o \
g_type_module_set_name.o \
g_type_module_unuse.o \
g_type_module_use.o \
g_type_name.o \
g_type_name_from_class.o \
g_type_name_from_instance.o \
g_type_next_base.o \
g_type_parent.o \
g_type_plugin_complete_interface_info.o \
g_type_plugin_complete_type_info.o \
g_type_plugin_get_type.o \
g_type_plugin_unuse.o \
g_type_plugin_use.o \
g_type_qname.o \
g_type_query.o \
g_type_register_dynamic.o \
g_type_register_fundamental.o \
g_type_register_static.o \
g_type_register_static_simple.o \
g_type_remove_class_cache_func.o \
g_type_remove_interface_check.o \
g_type_set_qdata.o \
g_type_test_flags.o \
g_type_value_table_peek.o \
g_value_array_append.o \
g_value_array_copy.o \
g_value_array_free.o \
g_value_array_get_nth.o \
g_value_array_get_type.o \
g_value_array_insert.o \
g_value_array_new.o \
g_value_array_prepend.o \
g_value_array_remove.o \
g_value_array_sort.o \
g_value_array_sort_with_data.o \
g_value_copy.o \
g_value_dup_boxed.o \
g_value_dup_object.o \
g_value_dup_param.o \
g_value_dup_string.o \
g_value_dup_variant.o \
g_value_fits_pointer.o \
g_value_get_boolean.o \
g_value_get_boxed.o \
g_value_get_char.o \
g_value_get_double.o \
g_value_get_enum.o \
g_value_get_flags.o \
g_value_get_float.o \
g_value_get_gtype.o \
g_value_get_int.o \
g_value_get_int64.o \
g_value_get_long.o \
g_value_get_object.o \
g_value_get_param.o \
g_value_get_pointer.o \
g_value_get_schar.o \
g_value_get_string.o \
g_value_get_type.o \
g_value_get_uchar.o \
g_value_get_uint.o \
g_value_get_uint64.o \
g_value_get_ulong.o \
g_value_get_variant.o \
g_value_init.o \
g_value_peek_pointer.o \
g_value_register_transform_func.o \
g_value_reset.o \
g_value_set_boolean.o \
g_value_set_boxed.o \
g_value_set_boxed_take_ownership.o \
g_value_set_char.o \
g_value_set_double.o \
g_value_set_enum.o \
g_value_set_flags.o \
g_value_set_float.o \
g_value_set_gtype.o \
g_value_set_instance.o \
g_value_set_int.o \
g_value_set_int64.o \
g_value_set_long.o \
g_value_set_object.o \
g_value_set_object_take_ownership.o \
g_value_set_param.o \
g_value_set_param_take_ownership.o \
g_value_set_pointer.o \
g_value_set_schar.o \
g_value_set_static_boxed.o \
g_value_set_static_string.o \
g_value_set_string.o \
g_value_set_string_take_ownership.o \
g_value_set_uchar.o \
g_value_set_uint.o \
g_value_set_uint64.o \
g_value_set_ulong.o \
g_value_set_variant.o \
g_value_take_boxed.o \
g_value_take_object.o \
g_value_take_param.o \
g_value_take_string.o \
g_value_take_variant.o \
g_value_transform.o \
g_value_type_compatible.o \
g_value_type_transformable.o \
g_value_unset.o \
g_variant_builder_get_type.o \
g_variant_get_gtype.o \
g_variant_type_get_gtype.o \
g_weak_ref_clear.o \
g_weak_ref_get.o \
g_weak_ref_init.o \
g_weak_ref_set.o 