#include <stdlib.h>
#include "elfchk.h"
struct versym libcups_so_2[] = {
	{"cupsAddDest","",0,LSB_Printing,0,1},
	{"cupsAddOption","",0,LSB_Printing,0,1},
	{"cupsCancelJob","",0,LSB_Printing,0,1},
	{"cupsEncryption","",0,LSB_Printing,4,1},
	{"cupsFreeDests","",0,LSB_Printing,0,1},
	{"cupsFreeJobs","",0,LSB_Printing,0,1},
	{"cupsFreeOptions","",0,LSB_Printing,0,1},
	{"cupsGetDefault","",0,LSB_Printing,0,1},
	{"cupsGetDest","",0,LSB_Printing,0,1},
	{"cupsGetDests","",0,LSB_Printing,0,1},
	{"cupsGetJobs","",0,LSB_Printing,0,1},
	{"cupsGetOption","",0,LSB_Printing,0,1},
	{"cupsGetPPD","",0,LSB_Printing,0,1},
	{"cupsGetPassword","",0,LSB_Printing,0,1},
	{"cupsLangEncoding","",0,LSB_Printing,0,1},
	{"cupsLangFlush","",0,LSB_Printing,0,1},
	{"cupsLangFree","",0,LSB_Printing,0,1},
	{"cupsLangGet","",0,LSB_Printing,0,1},
	{"cupsLastError","",0,LSB_Printing,4,1},
	{"cupsMarkOptions","",0,LSB_Printing,0,1},
	{"cupsParseOptions","",0,LSB_Printing,0,1},
	{"cupsPrintFile","",0,LSB_Printing,0,1},
	{"cupsPrintFiles","",0,LSB_Printing,0,1},
	{"cupsServer","",0,LSB_Printing,0,1},
	{"cupsSetDests","",0,LSB_Printing,0,1},
	{"cupsSetEncryption","",0,LSB_Printing,0,1},
	{"cupsSetPasswordCB","",0,LSB_Printing,0,1},
	{"cupsSetServer","",0,LSB_Printing,0,1},
	{"cupsSetUser","",0,LSB_Printing,0,1},
	{"cupsTempFd","",0,LSB_Printing,0,1},
	{"cupsUser","",0,LSB_Printing,0,1},
	{"ppdClose","",0,LSB_Printing,0,1},
	{"ppdCollect","",0,LSB_Printing,0,1},
	{"ppdConflicts","",0,LSB_Printing,0,1},
	{"ppdEmit","",0,LSB_Printing,0,1},
	{"ppdEmitFd","",0,LSB_Printing,0,1},
	{"ppdEmitJCL","",0,LSB_Printing,0,1},
	{"ppdErrorString","",0,LSB_Printing,0,1},
	{"ppdFindAttr","",0,LSB_Printing,0,1},
	{"ppdFindChoice","",0,LSB_Printing,0,1},
	{"ppdFindMarkedChoice","",0,LSB_Printing,0,1},
	{"ppdFindNextAttr","",0,LSB_Printing,0,1},
	{"ppdFindOption","",0,LSB_Printing,0,1},
	{"ppdIsMarked","",0,LSB_Printing,0,1},
	{"ppdLastError","",0,LSB_Printing,4,1},
	{"ppdMarkDefaults","",0,LSB_Printing,0,1},
	{"ppdMarkOption","",0,LSB_Printing,0,1},
	{"ppdOpen","",0,LSB_Printing,0,1},
	{"ppdOpenFd","",0,LSB_Printing,0,1},
	{"ppdOpenFile","",0,LSB_Printing,0,1},
	{"ppdPageLength","",0,LSB_Printing,0,1},
	{"ppdPageSize","",0,LSB_Printing,0,1},
	{"ppdPageWidth","",0,LSB_Printing,0,1},
	{"ppdSetConformance","",0,LSB_Printing,0,1},
	{0,0}};

struct classinfo *libcups_so_2_classinfo[] = {

	NULL	};
