#include <stdlib.h>
#include "elfchk.h"
struct versym libGLU_so_1[] = {
	{"gluBeginCurve","",0,LSB_Graphics,0,1},
	{"gluBeginPolygon","",0,LSB_Graphics,0,1},
	{"gluBeginSurface","",0,LSB_Graphics,0,1},
	{"gluBeginTrim","",0,LSB_Graphics,0,1},
	{"gluBuild1DMipmapLevels","",0,LSB_Graphics,0,1},
	{"gluBuild1DMipmaps","",0,LSB_Graphics,0,1},
	{"gluBuild2DMipmapLevels","",0,LSB_Graphics,0,1},
	{"gluBuild2DMipmaps","",0,LSB_Graphics,0,1},
	{"gluBuild3DMipmapLevels","",0,LSB_Graphics,0,1},
	{"gluBuild3DMipmaps","",0,LSB_Graphics,0,1},
	{"gluCheckExtension","",0,LSB_Graphics,0,1},
	{"gluCylinder","",0,LSB_Graphics,0,1},
	{"gluDeleteNurbsRenderer","",0,LSB_Graphics,0,1},
	{"gluDeleteQuadric","",0,LSB_Graphics,0,1},
	{"gluDeleteTess","",0,LSB_Graphics,0,1},
	{"gluDisk","",0,LSB_Graphics,0,1},
	{"gluEndCurve","",0,LSB_Graphics,0,1},
	{"gluEndPolygon","",0,LSB_Graphics,0,1},
	{"gluEndSurface","",0,LSB_Graphics,0,1},
	{"gluEndTrim","",0,LSB_Graphics,0,1},
	{"gluErrorString","",0,LSB_Graphics,0,1},
	{"gluGetNurbsProperty","",0,LSB_Graphics,0,1},
	{"gluGetString","",0,LSB_Graphics,0,1},
	{"gluGetTessProperty","",0,LSB_Graphics,0,1},
	{"gluLoadSamplingMatrices","",0,LSB_Graphics,0,1},
	{"gluLookAt","",0,LSB_Graphics,0,1},
	{"gluNewNurbsRenderer","",0,LSB_Graphics,0,1},
	{"gluNewQuadric","",0,LSB_Graphics,0,1},
	{"gluNewTess","",0,LSB_Graphics,0,1},
	{"gluNextContour","",0,LSB_Graphics,0,1},
	{"gluNurbsCallback","",0,LSB_Graphics,0,1},
	{"gluNurbsCallbackData","",0,LSB_Graphics,0,1},
	{"gluNurbsCallbackDataEXT","",0,LSB_Graphics,0,1},
	{"gluNurbsCurve","",0,LSB_Graphics,0,1},
	{"gluNurbsProperty","",0,LSB_Graphics,0,1},
	{"gluNurbsSurface","",0,LSB_Graphics,0,1},
	{"gluOrtho2D","",0,LSB_Graphics,0,1},
	{"gluPartialDisk","",0,LSB_Graphics,0,1},
	{"gluPerspective","",0,LSB_Graphics,0,1},
	{"gluPickMatrix","",0,LSB_Graphics,0,1},
	{"gluProject","",0,LSB_Graphics,0,1},
	{"gluPwlCurve","",0,LSB_Graphics,0,1},
	{"gluQuadricCallback","",0,LSB_Graphics,0,1},
	{"gluQuadricDrawStyle","",0,LSB_Graphics,0,1},
	{"gluQuadricNormals","",0,LSB_Graphics,0,1},
	{"gluQuadricOrientation","",0,LSB_Graphics,0,1},
	{"gluQuadricTexture","",0,LSB_Graphics,0,1},
	{"gluScaleImage","",0,LSB_Graphics,0,1},
	{"gluSphere","",0,LSB_Graphics,0,1},
	{"gluTessBeginContour","",0,LSB_Graphics,0,1},
	{"gluTessBeginPolygon","",0,LSB_Graphics,0,1},
	{"gluTessCallback","",0,LSB_Graphics,0,1},
	{"gluTessEndContour","",0,LSB_Graphics,0,1},
	{"gluTessEndPolygon","",0,LSB_Graphics,0,1},
	{"gluTessNormal","",0,LSB_Graphics,0,1},
	{"gluTessProperty","",0,LSB_Graphics,0,1},
	{"gluTessVertex","",0,LSB_Graphics,0,1},
	{"gluUnProject","",0,LSB_Graphics,0,1},
	{"gluUnProject4","",0,LSB_Graphics,0,1},
	{0,0}};

struct classinfo *libGLU_so_1_classinfo[] = {

	NULL	};
