#include <stdlib.h>
#include "elfchk.h"
struct versym libICE_so_6[] = {
	{"IceAcceptConnection","",0,"",0,1},
	{"IceAddConnectionWatch","",0,"",0,1},
	{"IceAllocScratch","",0,"",0,1},
	{"IceAppLockConn","",0,"",0,1},
	{"IceAppUnlockConn","",0,"",0,1},
	{"IceAuthFileName","",0,"",0,1},
	{"IceCheckShutdownNegotiation","",0,"",0,1},
	{"IceCloseConnection","",0,"",0,1},
	{"IceComposeNetworkIdList","",0,"",0,1},
	{"IceConnectionNumber","",0,"",0,1},
	{"IceConnectionStatus","",0,"",0,1},
	{"IceConnectionString","",0,"",0,1},
	{"IceFlush","",0,"",0,1},
	{"IceFreeAuthFileEntry","",0,"",0,1},
	{"IceFreeListenObjs","",0,"",0,1},
	{"IceGenerateMagicCookie","",0,"",0,1},
	{"IceGetAuthFileEntry","",0,"",0,1},
	{"IceGetConnectionContext","",0,"",0,1},
	{"IceGetInBufSize","",0,"",0,1},
	{"IceGetListenConnectionNumber","",0,"",0,1},
	{"IceGetListenConnectionString","",0,"",0,1},
	{"IceGetOutBufSize","",0,"",0,1},
	{"IceInitThreads","",0,"",0,1},
	{"IceLastReceivedSequenceNumber","",0,"",0,1},
	{"IceLastSentSequenceNumber","",0,"",0,1},
	{"IceListenForConnections","",0,"",0,1},
	{"IceListenForWellKnownConnections","",0,"",0,1},
	{"IceLockAuthFile","",0,"",0,1},
	{"IceOpenConnection","",0,"",0,1},
	{"IcePing","",0,"",0,1},
	{"IceProcessMessages","",0,"",0,1},
	{"IceProtocolRevision","",0,"",0,1},
	{"IceProtocolSetup","",0,"",0,1},
	{"IceProtocolShutdown","",0,"",0,1},
	{"IceProtocolVersion","",0,"",0,1},
	{"IceReadAuthFileEntry","",0,"",0,1},
	{"IceRegisterForProtocolReply","",0,"",0,1},
	{"IceRegisterForProtocolSetup","",0,"",0,1},
	{"IceRelease","",0,"",0,1},
	{"IceRemoveConnectionWatch","",0,"",0,1},
	{"IceSetErrorHandler","",0,"",0,1},
	{"IceSetHostBasedAuthProc","",0,"",0,1},
	{"IceSetIOErrorHandler","",0,"",0,1},
	{"IceSetPaAuthData","",0,"",0,1},
	{"IceSetShutdownNegotiation","",0,"",0,1},
	{"IceSwapping","",0,"",0,1},
	{"IceUnlockAuthFile","",0,"",0,1},
	{"IceVendor","",0,"",0,1},
	{"IceWriteAuthFileEntry","",0,"",0,1},
	{0,0}};

struct classinfo *libICE_so_6_classinfo[] = {

	NULL	};
