#include <stdlib.h>
#include "elfchk.h"
struct versym libICE_so_6[] = {
	{"IceAcceptConnection","",0,LSB_Graphics,8,1},
	{"IceAddConnectionWatch","",0,LSB_Graphics,0,1},
	{"IceAllocScratch","",0,LSB_Graphics,0,1},
	{"IceAppLockConn","",0,LSB_Graphics,0,1},
	{"IceAppUnlockConn","",0,LSB_Graphics,0,1},
	{"IceAuthFileName","",0,LSB_Graphics,0,1},
	{"IceCheckShutdownNegotiation","",0,LSB_Graphics,0,1},
	{"IceCloseConnection","",0,LSB_Graphics,4,1},
	{"IceComposeNetworkIdList","",0,LSB_Graphics,0,1},
	{"IceConnectionNumber","",0,LSB_Graphics,0,1},
	{"IceConnectionStatus","",0,LSB_Graphics,4,1},
	{"IceConnectionString","",0,LSB_Graphics,0,1},
	{"IceFlush","",0,LSB_Graphics,0,1},
	{"IceFreeAuthFileEntry","",0,LSB_Graphics,0,1},
	{"IceFreeListenObjs","",0,LSB_Graphics,0,1},
	{"IceGenerateMagicCookie","",0,LSB_Graphics,0,1},
	{"IceGetAuthFileEntry","",0,LSB_Graphics,0,1},
	{"IceGetConnectionContext","",0,LSB_Graphics,8,1},
	{"IceGetInBufSize","",0,LSB_Graphics,0,1},
	{"IceGetListenConnectionNumber","",0,LSB_Graphics,0,1},
	{"IceGetListenConnectionString","",0,LSB_Graphics,0,1},
	{"IceGetOutBufSize","",0,LSB_Graphics,0,1},
	{"IceInitThreads","",0,LSB_Graphics,0,1},
	{"IceLastReceivedSequenceNumber","",0,LSB_Graphics,0,1},
	{"IceLastSentSequenceNumber","",0,LSB_Graphics,0,1},
	{"IceListenForConnections","",0,LSB_Graphics,0,1},
	{"IceListenForWellKnownConnections","",0,LSB_Graphics,0,1},
	{"IceLockAuthFile","",0,LSB_Graphics,0,1},
	{"IceOpenConnection","",0,LSB_Graphics,8,1},
	{"IcePing","",0,LSB_Graphics,0,1},
	{"IceProcessMessages","",0,LSB_Graphics,4,1},
	{"IceProtocolRevision","",0,LSB_Graphics,0,1},
	{"IceProtocolSetup","",0,LSB_Graphics,4,1},
	{"IceProtocolShutdown","",0,LSB_Graphics,0,1},
	{"IceProtocolVersion","",0,LSB_Graphics,0,1},
	{"IceReadAuthFileEntry","",0,LSB_Graphics,0,1},
	{"IceRegisterForProtocolReply","",0,LSB_Graphics,0,1},
	{"IceRegisterForProtocolSetup","",0,LSB_Graphics,0,1},
	{"IceRelease","",0,LSB_Graphics,0,1},
	{"IceRemoveConnectionWatch","",0,LSB_Graphics,0,1},
	{"IceSetErrorHandler","",0,LSB_Graphics,8,1},
	{"IceSetHostBasedAuthProc","",0,LSB_Graphics,0,1},
	{"IceSetIOErrorHandler","",0,LSB_Graphics,8,1},
	{"IceSetPaAuthData","",0,LSB_Graphics,0,1},
	{"IceSetShutdownNegotiation","",0,LSB_Graphics,0,1},
	{"IceSwapping","",0,LSB_Graphics,0,1},
	{"IceUnlockAuthFile","",0,LSB_Graphics,0,1},
	{"IceVendor","",0,LSB_Graphics,0,1},
	{"IceWriteAuthFileEntry","",0,LSB_Graphics,0,1},
	{"_IceRead","",0,LSB_Graphics,0,1},
	{"_IceReadSkip","",0,LSB_Graphics,0,1},
	{"_IceWrite","",0,LSB_Graphics,0,1},
	{0,0}};

struct classinfo *libICE_so_6_classinfo[] = {

	NULL	};
