/* Generated file, do not edit */
#include <stdlib.h>
#include "elfchk.h"
struct versym libjpeg_so_62[] = {
	{"jpeg_CreateCompress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_CreateDecompress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_abort","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_abort_compress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_abort_decompress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_add_quant_table","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_alloc_huff_table","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_alloc_quant_table","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_calc_output_dimensions","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_consume_input","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_copy_critical_parameters","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_default_colorspace","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_destroy","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_destroy_compress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_destroy_decompress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_finish_compress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_finish_decompress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_finish_output","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_has_multiple_scans","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_input_complete","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_new_colormap","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_quality_scaling","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_coefficients","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_header","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_raw_data","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_scanlines","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_resync_to_restart","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_save_markers","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_colorspace","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_defaults","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_linear_quality","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_marker_processor","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_quality","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_simple_progression","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_start_compress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_start_decompress","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_start_output","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_std_error","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_stdio_dest","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_stdio_src","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_suppress_tables","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_coefficients","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_m_byte","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_m_header","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_marker","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_raw_data","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_scanlines","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_tables","LIBJPEG_6.2",0,LSB_Graphics_Ext,0,1},
	{0,0}};

struct classinfo *libjpeg_so_62_classinfo[] = {

	NULL	};
