#include <stdlib.h>
#include "elfchk.h"
struct versym libjpeg_so_62[] = {
	{"jpeg_CreateCompress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_CreateDecompress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_abort","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_abort_compress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_abort_decompress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_add_quant_table","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_alloc_huff_table","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_alloc_quant_table","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_calc_output_dimensions","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_consume_input","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_copy_critical_parameters","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_default_colorspace","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_destroy","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_destroy_compress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_destroy_decompress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_finish_compress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_finish_decompress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_finish_output","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_has_multiple_scans","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_input_complete","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_new_colormap","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_quality_scaling","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_coefficients","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_header","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_raw_data","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_read_scanlines","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_resync_to_restart","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_save_markers","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_colorspace","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_defaults","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_linear_quality","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_marker_processor","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_set_quality","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_simple_progression","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_start_compress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_start_decompress","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_start_output","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_std_error","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_stdio_dest","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_stdio_src","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_suppress_tables","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_coefficients","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_m_byte","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_m_header","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_marker","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_raw_data","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_scanlines","",0,LSB_Graphics_Ext,0,1},
	{"jpeg_write_tables","",0,LSB_Graphics_Ext,0,1},
	{0,0}};

struct classinfo *libjpeg_so_62_classinfo[] = {

	NULL	};
