#include "elfchk.h"
struct versym librt_so_1[] = {
	{"aio_cancel","GLIBC_2.1"},
	{"aio_cancel64","GLIBC_2.1"},
	{"aio_error","GLIBC_2.1"},
	{"aio_error64","GLIBC_2.1"},
	{"aio_fsync","GLIBC_2.1"},
	{"aio_fsync64","GLIBC_2.1"},
	{"aio_init","GLIBC_2.1"},
	{"aio_read","GLIBC_2.1"},
	{"aio_read64","GLIBC_2.1"},
	{"aio_return","GLIBC_2.1"},
	{"aio_return64","GLIBC_2.1"},
	{"aio_suspend","GLIBC_2.1"},
	{"aio_suspend64","GLIBC_2.1"},
	{"aio_write","GLIBC_2.1"},
	{"aio_write64","GLIBC_2.1"},
	{"clock_getcpuclockid",""},
	{"clock_getres",""},
	{"clock_gettime",""},
	{"clock_nanosleep",""},
	{"clock_settime",""},
	{"lio_listio","GLIBC_2.1"},
	{"lio_listio64","GLIBC_2.1"},
	{"shm_open",""},
	{"shm_unlink",""},
	{0,0}};
