#include <stdlib.h>
#include "elfchk.h"
struct versym libSM_so_6[] = {
	{"SmFreeProperty","",0,"",0,1},
	{"SmFreeReasons","",0,"",0,1},
	{"SmcClientID","",0,"",0,1},
	{"SmcCloseConnection","",0,"",0,1},
	{"SmcDeleteProperties","",0,"",0,1},
	{"SmcGetIceConnection","",0,"",0,1},
	{"SmcGetProperties","",0,"",0,1},
	{"SmcInteractDone","",0,"",0,1},
	{"SmcInteractRequest","",0,"",0,1},
	{"SmcModifyCallbacks","",0,"",0,1},
	{"SmcOpenConnection","",0,"",0,1},
	{"SmcProtocolRevision","",0,"",0,1},
	{"SmcProtocolVersion","",0,"",0,1},
	{"SmcRelease","",0,"",0,1},
	{"SmcRequestSaveYourself","",0,"",0,1},
	{"SmcRequestSaveYourselfPhase2","",0,"",0,1},
	{"SmcSaveYourselfDone","",0,"",0,1},
	{"SmcSetErrorHandler","",0,"",0,1},
	{"SmcSetProperties","",0,"",0,1},
	{"SmcVendor","",0,"",0,1},
	{"SmsCleanUp","",0,"",0,1},
	{"SmsClientHostName","",0,"",0,1},
	{"SmsClientID","",0,"",0,1},
	{"SmsDie","",0,"",0,1},
	{"SmsGenerateClientID","",0,"",0,1},
	{"SmsGetIceConnection","",0,"",0,1},
	{"SmsInitialize","",0,"",0,1},
	{"SmsInteract","",0,"",0,1},
	{"SmsProtocolRevision","",0,"",0,1},
	{"SmsProtocolVersion","",0,"",0,1},
	{"SmsRegisterClientReply","",0,"",0,1},
	{"SmsReturnProperties","",0,"",0,1},
	{"SmsSaveComplete","",0,"",0,1},
	{"SmsSaveYourself","",0,"",0,1},
	{"SmsSaveYourselfPhase2","",0,"",0,1},
	{"SmsSetErrorHandler","",0,"",0,1},
	{"SmsShutdownCancelled","",0,"",0,1},
	{0,0}};

struct classinfo *libSM_so_6_classinfo[] = {

	NULL	};
