# Generated file, do not edit
LIBOBJS = \
	ld_lsb_ia64_so_3.o \
	ld_lsb_ppc32_so_3.o \
	ld_lsb_s390_so_3.o \
	ld_lsb_so_3.o \
	ld_lsb_ppc64_so_3.o \
	ld_lsb_s390x_so_3.o \
	ld_lsb_x86_64_so_3.o \
	libasound_so_2.o \
	libatk_1_0_so_0.o \
	libc_so_6.o \
	libc_so_6_1.o \
	libcairo_so_2.o \
	libcrypt_so_1.o \
	libcups_so_2.o \
	libcupsimage_so_2.o \
	libdl_so_2.o \
	libfontconfig_so_1.o \
	libfreetype_so_6.o \
	libgcc_s_so_1.o \
	libgdk_x11_2_0_so_0.o \
	libgdk_pixbuf_2_0_so_0.o \
	libgdk_pixbuf_xlib_2_0_so_0.o \
	libGL_so_1.o \
	libglib_2_0_so_0.o \
	libGLU_so_1.o \
	libgmodule_2_0_so_0.o \
	libgobject_2_0_so_0.o \
	libgthread_2_0_so_0.o \
	libgtk_x11_2_0_so_0.o \
	libICE_so_6.o \
	libjpeg_so_62.o \
	libm_so_6.o \
	libm_so_6_1.o \
	libncurses_so_5.o \
	libnspr4_so.o \
	libnss3_so.o \
	libpam_so_0.o \
	libpango_1_0_so_0.o \
	libpangocairo_1_0_so_0.o \
	libpangoft2_1_0_so_0.o \
	libpangoxft_1_0_so_0.o \
	libpng12_so_0.o \
	libpthread_so_0.o \
	libQtCore_so_4.o \
	libQtGui_so_4.o \
	libQtNetwork_so_4.o \
	libQtOpenGL_so_4.o \
	libQtSql_so_4.o \
	libQtSvg_so_4.o \
	libQtXml_so_4.o \
	librt_so_1.o \
	libsane_so_1.o \
	libSM_so_6.o \
	libssl3_so.o \
	libstdcxx_so_6.o \
	libutil_so_1.o \
	libX11_so_6.o \
	libXext_so_6.o \
	libXft_so_2.o \
	libXi_so_6.o \
	libxml2_so_2.o \
	libXrender_so_1.o \
	libxslt_so_1.o \
	libXt_so_6.o \
	libXtst_so_6.o \
	libz_so_1.o \


LIBSRCS = \
	ld_lsb_ia64_so_3.c \
	ld_lsb_ppc32_so_3.c \
	ld_lsb_s390_so_3.c \
	ld_lsb_so_3.c \
	ld_lsb_ppc64_so_3.c \
	ld_lsb_s390x_so_3.c \
	ld_lsb_x86_64_so_3.c \
	libasound_so_2.c \
	libatk_1_0_so_0.c \
	libc_so_6.c \
	libc_so_6_1.c \
	libcairo_so_2.c \
	libcrypt_so_1.c \
	libcups_so_2.c \
	libcupsimage_so_2.c \
	libdl_so_2.c \
	libfontconfig_so_1.c \
	libfreetype_so_6.c \
	libgcc_s_so_1.c \
	libgdk_x11_2_0_so_0.c \
	libgdk_pixbuf_2_0_so_0.c \
	libgdk_pixbuf_xlib_2_0_so_0.c \
	libGL_so_1.c \
	libglib_2_0_so_0.c \
	libGLU_so_1.c \
	libgmodule_2_0_so_0.c \
	libgobject_2_0_so_0.c \
	libgthread_2_0_so_0.c \
	libgtk_x11_2_0_so_0.c \
	libICE_so_6.c \
	libjpeg_so_62.c \
	libm_so_6.c \
	libm_so_6_1.c \
	libncurses_so_5.c \
	libnspr4_so.c \
	libnss3_so.c \
	libpam_so_0.c \
	libpango_1_0_so_0.c \
	libpangocairo_1_0_so_0.c \
	libpangoft2_1_0_so_0.c \
	libpangoxft_1_0_so_0.c \
	libpng12_so_0.c \
	libpthread_so_0.c \
	libQtCore_so_4.c \
	libQtGui_so_4.c \
	libQtNetwork_so_4.c \
	libQtOpenGL_so_4.c \
	libQtSql_so_4.c \
	libQtSvg_so_4.c \
	libQtXml_so_4.c \
	librt_so_1.c \
	libsane_so_1.c \
	libSM_so_6.c \
	libssl3_so.c \
	libstdcxx_so_6.c \
	libutil_so_1.c \
	libX11_so_6.c \
	libXext_so_6.c \
	libXft_so_2.c \
	libXi_so_6.c \
	libxml2_so_2.c \
	libXrender_so_1.c \
	libxslt_so_1.c \
	libXt_so_6.c \
	libXtst_so_6.c \
	libz_so_1.c \


LSBLIBRARIES= -lasound -latk-1.0 -lc -lcairo -lcrypt -lcups -lcupsimage -ldl -lfontconfig -lfreetype -lgcc_s -lgdk-x11-2.0 -lgdk_pixbuf-2.0 -lgdk_pixbuf_xlib-2.0 -lGL -lglib-2.0 -lGLU -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lgtk-x11-2.0 -lICE -ljpeg -lm -lncurses -lnspr4 -lnss3 -lpam -lpango-1.0 -lpangocairo-1.0 -lpangoft2-1.0 -lpangoxft-1.0 -lpng12 -lpthread -lQtCore -lQtGui -lQtNetwork -lQtOpenGL -lQtSql -lQtSvg -lQtXml -lrt -lsane -lSM -lssl3 -lstdc++ -lutil -lX11 -lXext -lXft -lXi -lxslt -lxml2 -lXrender -lXt -lXtst -lz
