#include <stdlib.h>
#include "elfchk.h"
struct versym libssl_so[] = {
	{"NSS_CmpCertChainWCANames","NSS_3.2",0,LSB_Security,0,1},
	{"NSS_FindCertKEAType","NSS_3.2",0,LSB_Security,0,1},
	{"NSS_GetClientAuthData","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_AuthCertificate","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_AuthCertificateHook","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_BadCertHook","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_CipherPolicyGet","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_CipherPolicySet","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_CipherPrefGet","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_CipherPrefGetDefault","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_CipherPrefSet","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_CipherPrefSetDefault","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ClearSessionCache","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ConfigMPServerSIDCache","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ConfigSecureServer","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ConfigServerSessionIDCache","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_DataPending","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ForceHandshake","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_GetClientAuthDataHook","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_GetSessionID","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_HandshakeCallback","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ImportFD","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_InheritMPServerSIDCache","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_InvalidateSession","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_OptionGet","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_OptionGetDefault","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_OptionSet","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_OptionSetDefault","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_PeerCertificate","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ReHandshake","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_ResetHandshake","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_RevealPinArg","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_RevealURL","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_SecurityStatus","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_SetPKCS11PinArg","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_SetSockPeerID","NSS_3.2",0,LSB_Security,0,1},
	{"SSL_SetURL","NSS_3.2",0,LSB_Security,0,1},
	{0,0}};

struct classinfo *libssl_so_classinfo[] = {

	NULL	};
