#include <stdlib.h>
#include "elfchk.h"
struct versym libXrender_so_1[] = {
	{"XRenderAddGlyphs","",0,LSB_Graphics,0,1},
	{"XRenderAddTraps","",0,LSB_Graphics,0,1},
	{"XRenderChangePicture","",0,LSB_Graphics,0,1},
	{"XRenderComposite","",0,LSB_Graphics,0,1},
	{"XRenderCompositeDoublePoly","",0,LSB_Graphics,0,1},
	{"XRenderCompositeString16","",0,LSB_Graphics,0,1},
	{"XRenderCompositeString32","",0,LSB_Graphics,0,1},
	{"XRenderCompositeString8","",0,LSB_Graphics,0,1},
	{"XRenderCompositeText16","",0,LSB_Graphics,0,1},
	{"XRenderCompositeText32","",0,LSB_Graphics,0,1},
	{"XRenderCompositeText8","",0,LSB_Graphics,0,1},
	{"XRenderCompositeTrapezoids","",0,LSB_Graphics,0,1},
	{"XRenderCompositeTriFan","",0,LSB_Graphics,0,1},
	{"XRenderCompositeTriStrip","",0,LSB_Graphics,0,1},
	{"XRenderCompositeTriangles","",0,LSB_Graphics,0,1},
	{"XRenderCreateAnimCursor","",0,LSB_Graphics,0,1},
	{"XRenderCreateConicalGradient","",0,LSB_Graphics,0,1},
	{"XRenderCreateCursor","",0,LSB_Graphics,0,1},
	{"XRenderCreateGlyphSet","",0,LSB_Graphics,0,1},
	{"XRenderCreateLinearGradient","",0,LSB_Graphics,0,1},
	{"XRenderCreatePicture","",0,LSB_Graphics,0,1},
	{"XRenderCreateRadialGradient","",0,LSB_Graphics,0,1},
	{"XRenderCreateSolidFill","",0,LSB_Graphics,0,1},
	{"XRenderFillRectangle","",0,LSB_Graphics,0,1},
	{"XRenderFillRectangles","",0,LSB_Graphics,0,1},
	{"XRenderFindFormat","",0,LSB_Graphics,4,1},
	{"XRenderFindStandardFormat","",0,LSB_Graphics,4,1},
	{"XRenderFindVisualFormat","",0,LSB_Graphics,4,1},
	{"XRenderFreeGlyphSet","",0,LSB_Graphics,0,1},
	{"XRenderFreeGlyphs","",0,LSB_Graphics,0,1},
	{"XRenderFreePicture","",0,LSB_Graphics,0,1},
	{"XRenderParseColor","",0,LSB_Graphics,0,1},
	{"XRenderQueryExtension","",0,LSB_Graphics,0,1},
	{"XRenderQueryFilters","",0,LSB_Graphics,4,1},
	{"XRenderQueryFormats","",0,LSB_Graphics,0,1},
	{"XRenderQueryPictIndexValues","",0,LSB_Graphics,4,1},
	{"XRenderQuerySubpixelOrder","",0,LSB_Graphics,0,1},
	{"XRenderQueryVersion","",0,LSB_Graphics,0,1},
	{"XRenderReferenceGlyphSet","",0,LSB_Graphics,0,1},
	{"XRenderSetPictureClipRectangles","",0,LSB_Graphics,0,1},
	{"XRenderSetPictureClipRegion","",0,LSB_Graphics,0,1},
	{"XRenderSetPictureFilter","",0,LSB_Graphics,0,1},
	{"XRenderSetPictureTransform","",0,LSB_Graphics,0,1},
	{"XRenderSetSubpixelOrder","",0,LSB_Graphics,0,1},
	{0,0}};

struct classinfo *libXrender_so_1_classinfo[] = {

	NULL	};
