#include <stdlib.h>
#include "elfchk.h"
struct versym libXi_so_6[] = {
	{"XAllowDeviceEvents","",0,LSB_Graphics,0,1},
	{"XChangeDeviceControl","",0,LSB_Graphics,0,1},
	{"XChangeDeviceDontPropagateList","",0,LSB_Graphics,0,1},
	{"XChangeDeviceKeyMapping","",0,LSB_Graphics,0,1},
	{"XChangeFeedbackControl","",0,LSB_Graphics,0,1},
	{"XChangeKeyboardDevice","",0,LSB_Graphics,0,1},
	{"XChangePointerDevice","",0,LSB_Graphics,0,1},
	{"XCloseDevice","",0,LSB_Graphics,0,1},
	{"XDeviceBell","",0,LSB_Graphics,0,1},
	{"XFreeDeviceControl","",0,LSB_Graphics,0,1},
	{"XFreeDeviceList","",0,LSB_Graphics,0,1},
	{"XFreeDeviceMotionEvents","",0,LSB_Graphics,0,1},
	{"XFreeDeviceState","",0,LSB_Graphics,0,1},
	{"XFreeFeedbackList","",0,LSB_Graphics,0,1},
	{"XGetDeviceButtonMapping","",0,LSB_Graphics,0,1},
	{"XGetDeviceControl","",0,LSB_Graphics,0,1},
	{"XGetDeviceDontPropagateList","",0,LSB_Graphics,0,1},
	{"XGetDeviceFocus","",0,LSB_Graphics,0,1},
	{"XGetDeviceKeyMapping","",0,LSB_Graphics,0,1},
	{"XGetDeviceModifierMapping","",0,LSB_Graphics,0,1},
	{"XGetDeviceMotionEvents","",0,LSB_Graphics,0,1},
	{"XGetExtensionVersion","",0,LSB_Graphics,0,1},
	{"XGetFeedbackControl","",0,LSB_Graphics,0,1},
	{"XGetSelectedExtensionEvents","",0,LSB_Graphics,0,1},
	{"XGrabDevice","",0,LSB_Graphics,0,1},
	{"XGrabDeviceButton","",0,LSB_Graphics,0,1},
	{"XGrabDeviceKey","",0,LSB_Graphics,0,1},
	{"XListInputDevices","",0,LSB_Graphics,0,1},
	{"XOpenDevice","",0,LSB_Graphics,0,1},
	{"XQueryDeviceState","",0,LSB_Graphics,0,1},
	{"XSelectExtensionEvent","",0,LSB_Graphics,0,1},
	{"XSendExtensionEvent","",0,LSB_Graphics,0,1},
	{"XSetDeviceButtonMapping","",0,LSB_Graphics,0,1},
	{"XSetDeviceFocus","",0,LSB_Graphics,0,1},
	{"XSetDeviceMode","",0,LSB_Graphics,0,1},
	{"XSetDeviceModifierMapping","",0,LSB_Graphics,0,1},
	{"XSetDeviceValuators","",0,LSB_Graphics,0,1},
	{"XUngrabDevice","",0,LSB_Graphics,0,1},
	{"XUngrabDeviceButton","",0,LSB_Graphics,0,1},
	{"XUngrabDeviceKey","",0,LSB_Graphics,0,1},
	{0,0}};

struct classinfo *libXi_so_6_classinfo[] = {

	NULL	};
