#!/bin/sh

SELF=$0;

if [ -h $SELF ]; then
		SELF=`readlink -f $SELF`
fi

START_FROM_DIR=`dirname $SELF`

# Get list of libraries
ldd $START_FROM_DIR/dummy_link | sed -e 's/[[:space:]]\+/ /g'  -e 's/^ //' -e 's/=> //' | cut -f1,2 -d' ' | sed -e 's/ /\
/' > /tmp/lsblibchk.$$
                                                                                   

$START_FROM_DIR/libchk /tmp/lsblibchk.$$

rm /tmp/lsblibchk.$$
