#!/bin/sh

SELF=$0;

if [ -h $SELF ]; then
		SELF=`readlink -f $SELF`
fi

START_FROM_DIR=`dirname $SELF`

# Get list of libraries
# We could choose particular dummy_link corresponding to target LSB version, but it is much more easier
# just to run ldd against all of them
ldd $START_FROM_DIR/dummy_link* | sort -u | sed -e 's/[[:space:]]\+/ /g'  -e 's/^ //' -e 's/=> //' | cut -f1,2 -d' ' | sed -e 's/ /\
/' > /tmp/lsblibchk.$$
                                                                                   

$START_FROM_DIR/libchk $* /tmp/lsblibchk.$$

rm /tmp/lsblibchk.$$
