#!/bin/sh

# This is $Revision: 1.1 $

PATH=$PATH:"."

echo "Compiling test program"
LSBVERSION=1.0 make > run_tests.log 2>&1

if [ $? -ne 0 ]; then
  echo "Failed to compile test. Aborting\n"
fi

echo "Running tests"
./libchk > report 2>> run_tests.log

echo >> report
echo  '----------------------------------------------------------------------' >> report
echo >> report

machine_info >> report 2>> run_tests.log

echo "Finished."
echo "A report has been created in a file named report"
echo "A log of the test output has been placed in run_tests.log"
echo 
