/*
 * Test of X11/Xlib.h
 */
#include "hdrchk.h"
#include "sys/types.h"
#include <X11/Xdefs.h>
#include <X11/Xlibint.h>
#include <X11/Xutil.h>
#include "X11/Xlib.h"



int X11_Xlib_h()
{
int cnt=0;
CheckTypeSize(XConnectionWatchProc,4)
CheckTypeSize(XIMHotKeyState,4)
CheckTypeSize(XIMValuesList,8)
CheckTypeSize(XIOErrorHandler,4)
CheckTypeSize(XErrorHandler,4)
CheckTypeSize(XIMHotKeyTriggers,8)
CheckTypeSize(XIMStatusDrawCallbackStruct,8)
CheckTypeSize(struct _XIMHotKeyTrigger,0)
CheckOffset(struct _XIMHotKeyTrigger,keysym,0)
CheckOffset(struct _XIMHotKeyTrigger,modifier,4)
CheckOffset(struct _XIMHotKeyTrigger,modifier_mask,8)
CheckTypeSize(struct _XIMStatusDrawCallbackStruct,0)
CheckOffset(struct _XIMStatusDrawCallbackStruct,type,0)
CheckTypeSize(struct _XIMHotKeyTriggers,0)
CheckOffset(struct _XIMHotKeyTriggers,num_hot_key,0)
CheckOffset(struct _XIMHotKeyTriggers,key,4)
CheckTypeSize(XIMHotKeyTrigger,12)
CheckTypeSize(XIMStatusDataType,4)
CheckTypeSize(XIMPreeditCaretCallbackStruct,12)
CheckTypeSize(XIMCaretStyle,4)
CheckTypeSize(XIMPreeditDrawCallbackStruct,16)
CheckTypeSize(struct _XIMPreeditDrawCallbackStruct,0)
CheckOffset(struct _XIMPreeditDrawCallbackStruct,caret,0)
CheckOffset(struct _XIMPreeditDrawCallbackStruct,chg_first,4)
CheckOffset(struct _XIMPreeditDrawCallbackStruct,chg_length,8)
CheckOffset(struct _XIMPreeditDrawCallbackStruct,text,12)
CheckTypeSize(XIMStringConversionCallbackStruct,16)
CheckTypeSize(struct _XIMStringConversionCallbackStruct,0)
CheckOffset(struct _XIMStringConversionCallbackStruct,position,0)
CheckOffset(struct _XIMStringConversionCallbackStruct,direction,4)
CheckOffset(struct _XIMStringConversionCallbackStruct,operation,8)
CheckOffset(struct _XIMStringConversionCallbackStruct,factor,10)
CheckOffset(struct _XIMStringConversionCallbackStruct,text,12)
CheckTypeSize(XIMStringConversionPosition,2)
CheckTypeSize(struct _XIMPreeditCaretCallbackStruct,0)
CheckOffset(struct _XIMPreeditCaretCallbackStruct,position,0)
CheckOffset(struct _XIMPreeditCaretCallbackStruct,direction,4)
CheckOffset(struct _XIMPreeditCaretCallbackStruct,style,8)
CheckTypeSize(XIMCaretDirection,4)
CheckTypeSize(XIMStringConversionText,16)
CheckTypeSize(XIMStringConversionOperation,2)
CheckTypeSize(XIMStringConversionType,2)
CheckTypeSize(XIMStringConversionFeedback,4)
CheckTypeSize(struct _XIMStringConversionText,0)
CheckOffset(struct _XIMStringConversionText,length,0)
CheckOffset(struct _XIMStringConversionText,feedback,4)
CheckOffset(struct _XIMStringConversionText,encoding_is_wchar,8)
CheckTypeSize(XIMResetState,4)
CheckTypeSize(XIMPreeditStateNotifyCallbackStruct,4)
CheckTypeSize(struct _XIMPreeditStateNotifyCallbackStruct,0)
CheckOffset(struct _XIMPreeditStateNotifyCallbackStruct,state,8)
CheckTypeSize(XIMText,16)
CheckTypeSize(XIMPreeditState,4)
CheckTypeSize(XIMFeedback,4)
CheckTypeSize(struct _XIMText,0)
CheckOffset(struct _XIMText,length,0)
CheckOffset(struct _XIMText,feedback,4)
CheckOffset(struct _XIMText,encoding_is_wchar,8)
CheckTypeSize(XICCallback,8)
CheckTypeSize(XIMCallback,8)
CheckTypeSize(XVaNestedList,4)
CheckTypeSize(XIMStyles,8)
CheckTypeSize(XIMStyle,4)
CheckTypeSize(XIDProc,4)
CheckTypeSize(XICProc,4)
CheckTypeSize(XIMProc,4)
CheckTypeSize(XIM,4)
CheckTypeSize(XIC,4)
CheckTypeSize(XOMFontInfo,12)
CheckTypeSize(XOMOrientation,8)
CheckTypeSize(XOrientation,4)
CheckTypeSize(XOMCharSetList,8)
CheckTypeSize(XwcTextItem,16)
CheckTypeSize(XmbTextItem,16)
CheckTypeSize(XFontSet,4)
CheckTypeSize(XOM,4)
CheckTypeSize(XOC,4)
CheckTypeSize(XFontSetExtents,16)
CheckTypeSize(XEDataObject,4)
CheckTypeSize(XTextItem16,16)
CheckTypeSize(XChar2b,2)
CheckTypeSize(XTextItem,16)
CheckTypeSize(XFontStruct,80)
CheckTypeSize(XFontProp,8)
CheckTypeSize(XCharStruct,12)
CheckTypeSize(XEvent,96)
CheckTypeSize(XClientMessageEvent,48)
CheckTypeSize(union _XEvent,0)
CheckOffset(union _XEvent,type,0)
CheckOffset(union _XEvent,xany,0)
CheckOffset(union _XEvent,xkey,0)
CheckOffset(union _XEvent,xbutton,0)
CheckOffset(union _XEvent,xmotion,0)
CheckOffset(union _XEvent,xcrossing,0)
CheckOffset(union _XEvent,xfocus,0)
CheckOffset(union _XEvent,xexpose,0)
CheckOffset(union _XEvent,xgraphicsexpose,0)
CheckOffset(union _XEvent,xnoexpose,0)
CheckOffset(union _XEvent,xvisibility,0)
CheckOffset(union _XEvent,xcreatewindow,0)
CheckOffset(union _XEvent,xdestroywindow,0)
CheckOffset(union _XEvent,xunmap,0)
CheckOffset(union _XEvent,xmap,0)
CheckOffset(union _XEvent,xmaprequest,0)
CheckOffset(union _XEvent,xreparent,0)
CheckOffset(union _XEvent,xconfigure,0)
CheckOffset(union _XEvent,xgravity,0)
CheckOffset(union _XEvent,xresizerequest,0)
CheckOffset(union _XEvent,xconfigurerequest,0)
CheckOffset(union _XEvent,xcirculate,0)
CheckOffset(union _XEvent,xcirculaterequest,0)
CheckOffset(union _XEvent,xproperty,0)
CheckOffset(union _XEvent,xselectionclear,0)
CheckOffset(union _XEvent,xselectionrequest,0)
CheckOffset(union _XEvent,xselection,0)
CheckOffset(union _XEvent,xcolormap,0)
CheckOffset(union _XEvent,xclient,0)
CheckOffset(union _XEvent,xmapping,0)
CheckOffset(union _XEvent,xerror,0)
CheckOffset(union _XEvent,xkeymap,0)
CheckOffset(union _XEvent,pad,49)
CheckTypeSize(XAnyEvent,20)
CheckTypeSize(XErrorEvent,20)
CheckTypeSize(XMappingEvent,32)
CheckTypeSize(XColormapEvent,32)
CheckTypeSize(XSelectionEvent,36)
CheckTypeSize(XSelectionRequestEvent,40)
CheckTypeSize(XConfigureRequestEvent,56)
CheckTypeSize(XSelectionClearEvent,28)
CheckTypeSize(XPropertyEvent,32)
CheckTypeSize(XCirculateRequestEvent,28)
CheckTypeSize(XResizeRequestEvent,28)
CheckTypeSize(XCirculateEvent,28)
CheckTypeSize(XGravityEvent,32)
CheckTypeSize(XConfigureEvent,52)
CheckTypeSize(XReparentEvent,40)
CheckTypeSize(XMapRequestEvent,24)
CheckTypeSize(XMapEvent,28)
CheckTypeSize(XUnmapEvent,28)
CheckTypeSize(XDestroyWindowEvent,24)
CheckTypeSize(XCreateWindowEvent,48)
CheckTypeSize(XVisibilityEvent,24)
CheckTypeSize(XNoExposeEvent,28)
CheckTypeSize(XGraphicsExposeEvent,48)
CheckTypeSize(XExposeEvent,40)
CheckTypeSize(XKeymapEvent,52)
CheckTypeSize(XFocusOutEvent,28)
CheckTypeSize(XFocusChangeEvent,28)
CheckTypeSize(XEnterWindowEvent,68)
CheckTypeSize(XLeaveWindowEvent,68)
CheckTypeSize(XFocusInEvent,28)
CheckTypeSize(XCrossingEvent,68)
CheckTypeSize(XMotionEvent,60)
CheckTypeSize(XPointerMovedEvent,60)
CheckTypeSize(XButtonReleasedEvent,60)
CheckTypeSize(XButtonEvent,60)
CheckTypeSize(XButtonPressedEvent,60)
CheckTypeSize(XKeyReleasedEvent,60)
CheckTypeSize(XKeyPressedEvent,60)
CheckTypeSize(XKeyEvent,60)
CheckTypeSize(_XPrivDisplay,4)
CheckTypeSize(Display,1336)
CheckTypeSize(XModifierKeymap,8)
CheckTypeSize(XTimeCoord,8)
CheckTypeSize(XKeyboardState,56)
CheckTypeSize(XKeyboardControl,32)
CheckTypeSize(XArc,12)
CheckTypeSize(XRectangle,8)
CheckTypeSize(XPoint,4)
CheckTypeSize(XSegment,8)
CheckTypeSize(XColor,12)
CheckTypeSize(XWindowChanges,28)
CheckTypeSize(XImage,88)
CheckTypeSize(struct funcs,0)
CheckOffset(struct funcs,create_image,0)
CheckOffset(struct funcs,destroy_image,4)
CheckOffset(struct funcs,get_pixel,8)
CheckOffset(struct funcs,put_pixel,12)
CheckOffset(struct funcs,sub_image,16)
CheckOffset(struct funcs,add_pixel,20)
CheckTypeSize(struct _XImage,0)
CheckOffset(struct _XImage,width,0)
CheckOffset(struct _XImage,height,4)
CheckOffset(struct _XImage,xoffset,8)
CheckOffset(struct _XImage,format,12)
CheckOffset(struct _XImage,data,4)
CheckOffset(struct _XImage,byte_order,20)
CheckOffset(struct _XImage,bitmap_unit,24)
CheckOffset(struct _XImage,bitmap_bit_order,28)
CheckOffset(struct _XImage,bitmap_pad,32)
CheckOffset(struct _XImage,depth,36)
CheckOffset(struct _XImage,bytes_per_line,40)
CheckOffset(struct _XImage,bits_per_pixel,44)
CheckOffset(struct _XImage,red_mask,48)
CheckOffset(struct _XImage,green_mask,52)
CheckOffset(struct _XImage,blue_mask,56)
CheckOffset(struct _XImage,obdata,60)
CheckTypeSize(XHostAddress,12)
CheckTypeSize(XWindowAttributes,92)
CheckTypeSize(XSetWindowAttributes,60)
CheckTypeSize(ScreenFormat,16)
CheckTypeSize(Screen,80)
CheckTypeSize(Depth,12)
CheckTypeSize(Visual,32)
CheckTypeSize(GC,4)
CheckTypeSize(XGCValues,92)
CheckTypeSize(XPixmapFormatValues,12)
CheckTypeSize(XExtCodes,16)
CheckTypeSize(XExtData,16)
CheckTypeSize(struct _XExtData,0)
CheckOffset(struct _XExtData,number,0)
CheckOffset(struct _XExtData,next,4)
CheckOffset(struct _XExtData,free_private,8)
CheckOffset(struct _XExtData,private_data,12)
CheckTypeSize(XPointer,4)
printf("%d tests in X11/Xlib.h\n",cnt);
return cnt;
}
